import type { Metadata } from "next";
import { PageHeader } from "@/components/layout/page-header";
import { FilterGrid, type GridItem } from "@/components/learn/filter-grid";
import { Badge } from "@/components/ui/badge";
import { Callout } from "@/components/learn/blocks";
import { listeningTasks } from "@/content";

export const metadata: Metadata = {
  title: "Listening",
  description:
    "German listening practice with variable playback speed, transcripts, vocabulary support and exam-style questions.",
};

export default function ListeningPage() {
  const items: GridItem[] = listeningTasks.map((task) => ({
    id: task.slug,
    title: task.title,
    subtitle: task.titleEn,
    description: task.scenario,
    href: `/listening/${task.slug}`,
    level: task.level,
    meta: `${task.seconds}s · ${task.questions.length} questions · ${task.transcript.length} turns`,
    keywords: task.transcript.map((line) => line.de).join(" "),
  }));

  return (
    <>
      <PageHeader
        title="Listening"
        description="Dialogues, announcements, phone calls, radio features and lectures. Start at 0.75× and work up to full speed."
        breadcrumbs={[{ label: "Home", href: "/dashboard" }, { label: "Listening" }]}
        eyebrow={<Badge variant="secondary">{listeningTasks.length} tasks</Badge>}
      />
      <Callout variant="tip" title="How the audio works">
        <p>
          Audio is generated by your browser&apos;s German speech engine, so it works offline and you can slow it
          down without distortion. For the most natural voice, pick a de-DE voice in Settings.
        </p>
      </Callout>
      <div className="mt-5">
        <FilterGrid items={items} searchPlaceholder="Search listening tasks…" columns={2} />
      </div>
    </>
  );
}
