import Link from "next/link";
import type { Metadata } from "next";
import { Download } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge, LevelBadge } from "@/components/ui/badge";
import { verbs } from "@/content";
import { conjugate, verbSlug } from "@/lib/conjugate";

export const metadata: Metadata = {
  title: "Verb conjugation",
  description:
    "Complete German verb tables: Präsens, Präteritum, Perfekt, Plusquamperfekt, Futur I and II, Konjunktiv I and II, imperative and passive — for regular, irregular, modal, separable and reflexive verbs.",
};

export default function VerbsPage() {
  const grouped = ["auxiliary", "modal", "irregular", "separable", "reflexive", "mixed", "regular"] as const;

  return (
    <>
      <PageHeader
        title="Verb conjugation"
        description="Pick a verb to see every tense generated by the conjugation engine, including the passive and the sentence-bracket behaviour of separable verbs."
        breadcrumbs={[{ label: "Home", href: "/dashboard" }, { label: "Verbs" }]}
        eyebrow={<Badge variant="secondary">{verbs.length} verbs</Badge>}
        actions={
          <Button variant="outline" asChild>
            <a href="/api/pdf/verbs/all" target="_blank" rel="noopener noreferrer">
              <Download /> Verb tables PDF
            </a>
          </Button>
        }
      />

      <Card className="mb-6">
        <CardContent className="pt-5 sm:pt-6">
          <p className="mb-3 font-semibold">Stammformen — the three forms to memorise</p>
          <div className="scroll-slim overflow-x-auto">
            <table className="de-table">
              <thead>
                <tr>
                  <th>Infinitiv</th>
                  <th>Präsens (er/sie/es)</th>
                  <th>Präteritum</th>
                  <th>Partizip II</th>
                  <th>Hilfsverb</th>
                  <th>Typ</th>
                </tr>
              </thead>
              <tbody>
                {verbs.map((verb) => {
                  const table = conjugate(verb);
                  return (
                    <tr key={verb.infinitive}>
                      <td className="font-medium">
                        <Link href={`/verbs/${verbSlug(verb)}`} className="text-primary hover:underline">
                          {verb.infinitive}
                        </Link>
                        <span className="ml-2 text-xs text-muted-foreground">{verb.en}</span>
                      </td>
                      <td>{table.tables[0].forms[2]}</td>
                      <td>{table.tables[1].forms[0]}</td>
                      <td className="font-medium">{verb.partizip2}</td>
                      <td>{verb.auxiliary}</td>
                      <td>
                        <Badge variant="secondary" className="capitalize">
                          {verb.kind}
                        </Badge>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      <div className="space-y-6">
        {grouped.map((kind) => {
          const list = verbs.filter((verb) => verb.kind === kind);
          if (!list.length) return null;
          return (
            <div key={kind}>
              <h2 className="mb-3 font-display text-lg font-semibold capitalize">{kind} verbs</h2>
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {list.map((verb) => (
                  <Card key={verb.infinitive} interactive>
                    <Link href={`/verbs/${verbSlug(verb)}`}>
                      <CardContent className="pt-5 sm:pt-6">
                        <div className="mb-2 flex items-center justify-between">
                          <p className="font-display text-lg font-semibold">{verb.infinitive}</p>
                          <LevelBadge level={verb.level} />
                        </div>
                        <p className="text-sm text-muted-foreground">{verb.en}</p>
                        <p className="mt-2 font-mono text-xs text-muted-foreground">
                          {verb.preteriteStem} · {verb.partizip2} · {verb.auxiliary}
                        </p>
                      </CardContent>
                    </Link>
                  </Card>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </>
  );
}
