import type { VocabDeck } from "@/lib/types";

export const a1Decks: VocabDeck[] = [
  {
    id: "a1-greetings",
    slug: "begruessung-vorstellung",
    title: "Greetings & introductions",
    titleDe: "Begrüßung und Vorstellung",
    level: "A1",
    topic: "Social basics",
    icon: "Handshake",
    description: "The first 10 phrases and words you need in any German conversation.",
    words: [
      {
        id: "a1-g-1", de: "Guten Tag", en: "hello / good day", ipa: "ˈɡuːtn̩ ˈtaːk", pos: "phrase", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Guten Tag, mein Name ist Ayoub.", en: "Hello, my name is Ayoub." },
        synonyms: ["Hallo", "Grüß Gott (Süddeutschland)"],
        expressions: [{ de: "Guten Morgen / Guten Abend", en: "good morning / good evening" }],
        memoryTip: "Literally 'good day' — safe in every formal situation.",
      },
      {
        id: "a1-g-2", de: "Name", article: "der", plural: "die Namen", en: "name", ipa: "ˈnaːmə", pos: "noun", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Wie ist Ihr Name, bitte?", en: "What is your name, please?" },
        expressions: [{ de: "Mein Name ist …", en: "My name is …" }],
        memoryTip: "Almost identical to English 'name'.",
      },
      {
        id: "a1-g-3", de: "heißen", en: "to be called", ipa: "ˈhaɪsn̩", pos: "verb", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Ich heiße Lena. Wie heißt du?", en: "My name is Lena. What's your name?" },
        synonyms: ["sich nennen"],
        memoryTip: "Think of 'hail' — how someone is hailed.",
      },
      {
        id: "a1-g-4", de: "kommen aus", en: "to come from", ipa: "ˈkɔmən aʊs", pos: "phrase", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Ich komme aus Marokko.", en: "I come from Morocco." },
        expressions: [{ de: "Woher kommen Sie?", en: "Where are you from?" }],
        memoryTip: "aus = out of; you come out of a country.",
      },
      {
        id: "a1-g-5", de: "wohnen", en: "to live / reside", ipa: "ˈvoːnən", pos: "verb", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Ich wohne in Berlin, im Stadtzentrum.", en: "I live in Berlin, in the city centre." },
        synonyms: ["leben"],
        memoryTip: "Related to English 'wone/won' — to dwell.",
      },
      {
        id: "a1-g-6", de: "Freund", article: "der", plural: "die Freunde", en: "friend", ipa: "fʁɔɪnt", pos: "noun", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Das ist mein Freund Karim.", en: "This is my friend Karim." },
        opposites: ["der Feind"],
        expressions: [{ de: "ein guter Freund", en: "a good friend" }],
        memoryTip: "Feminine form: die Freundin.",
      },
      {
        id: "a1-g-7", de: "danke", en: "thank you", ipa: "ˈdaŋkə", pos: "phrase", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Danke schön! — Bitte schön.", en: "Thank you very much! — You're welcome." },
        synonyms: ["vielen Dank", "danke sehr"],
        expressions: [{ de: "Nein, danke.", en: "No, thank you." }],
        memoryTip: "danke ↔ bitte is the most useful pair in German.",
      },
      {
        id: "a1-g-8", de: "Entschuldigung", article: "die", plural: "die Entschuldigungen", en: "excuse me / apology", ipa: "ɛntˈʃʊldɪɡʊŋ", pos: "noun", level: "A1", topic: "greetings", difficulty: 2,
        example: { de: "Entschuldigung, wo ist der Bahnhof?", en: "Excuse me, where is the station?" },
        synonyms: ["Verzeihung"],
        expressions: [{ de: "Entschuldigen Sie bitte!", en: "Excuse me, please!" }],
        memoryTip: "Use it to start any question to a stranger.",
      },
      {
        id: "a1-g-9", de: "Auf Wiedersehen", en: "goodbye", ipa: "aʊf ˈviːdɐˌzeːən", pos: "phrase", level: "A1", topic: "greetings", difficulty: 1,
        example: { de: "Auf Wiedersehen und einen schönen Tag!", en: "Goodbye and have a nice day!" },
        synonyms: ["Tschüss (informell)", "Bis bald"],
        memoryTip: "wieder + sehen = 'see again'.",
      },
      {
        id: "a1-g-10", de: "sprechen", en: "to speak", ipa: "ˈʃpʁɛçn̩", pos: "verb", level: "A1", topic: "greetings", difficulty: 2,
        example: { de: "Sprechen Sie Englisch? — Ich spreche ein bisschen Deutsch.", en: "Do you speak English? — I speak a little German." },
        expressions: [{ de: "Sprechen Sie bitte langsamer.", en: "Please speak more slowly." }],
        memoryTip: "Stem change e → i: du sprichst, er spricht.",
      },
    ],
  },
  {
    id: "a1-family",
    slug: "familie-personen",
    title: "Family & people",
    titleDe: "Familie und Personen",
    level: "A1",
    topic: "People",
    icon: "Users",
    description: "Talk about your family, describe people and their relationships.",
    words: [
      {
        id: "a1-f-1", de: "Familie", article: "die", plural: "die Familien", en: "family", ipa: "faˈmiːli̯ə", pos: "noun", level: "A1", topic: "family", difficulty: 1,
        example: { de: "Meine Familie wohnt in Casablanca.", en: "My family lives in Casablanca." },
        expressions: [{ de: "eine große Familie", en: "a big family" }],
        memoryTip: "Stress on the second syllable: fa-MI-lie.",
      },
      {
        id: "a1-f-2", de: "Eltern", article: "die", plural: "die Eltern", en: "parents", ipa: "ˈɛltɐn", pos: "noun", level: "A1", topic: "family", difficulty: 1,
        example: { de: "Ich wohne noch bei meinen Eltern.", en: "I still live with my parents." },
        memoryTip: "Plural only — there is no singular 'ein Eltern'.",
      },
      {
        id: "a1-f-3", de: "Mutter", article: "die", plural: "die Mütter", en: "mother", ipa: "ˈmʊtɐ", pos: "noun", level: "A1", topic: "family", difficulty: 1,
        example: { de: "Meine Mutter kocht sehr gut.", en: "My mother cooks very well." },
        opposites: ["der Vater"],
        expressions: [{ de: "Mutti (liebevoll)", en: "mum" }],
        memoryTip: "Plural adds an Umlaut: Mütter.",
      },
      {
        id: "a1-f-4", de: "Vater", article: "der", plural: "die Väter", en: "father", ipa: "ˈfaːtɐ", pos: "noun", level: "A1", topic: "family", difficulty: 1,
        example: { de: "Mein Vater arbeitet als Elektriker.", en: "My father works as an electrician." },
        opposites: ["die Mutter"],
        memoryTip: "Vater ↔ father: v is pronounced [f].",
      },
      {
        id: "a1-f-5", de: "Bruder", article: "der", plural: "die Brüder", en: "brother", ipa: "ˈbʁuːdɐ", pos: "noun", level: "A1", topic: "family", difficulty: 1,
        example: { de: "Ich habe zwei Brüder und eine Schwester.", en: "I have two brothers and one sister." },
        opposites: ["die Schwester"],
        memoryTip: "Umlaut in the plural: Brüder.",
      },
      {
        id: "a1-f-6", de: "Schwester", article: "die", plural: "die Schwestern", en: "sister", ipa: "ˈʃvɛstɐ", pos: "noun", level: "A1", topic: "family", difficulty: 1,
        example: { de: "Meine Schwester studiert Medizin.", en: "My sister studies medicine." },
        opposites: ["der Bruder"],
        expressions: [{ de: "die Krankenschwester", en: "nurse" }],
        memoryTip: "Krankenschwester literally = 'sick sister'.",
      },
      {
        id: "a1-f-7", de: "Kind", article: "das", plural: "die Kinder", en: "child", ipa: "kɪnt", pos: "noun", level: "A1", topic: "family", difficulty: 1,
        example: { de: "Wir haben drei Kinder.", en: "We have three children." },
        expressions: [{ de: "als Kind", en: "as a child" }],
        memoryTip: "Kinder → English 'kindergarten'.",
      },
      {
        id: "a1-f-8", de: "verheiratet", en: "married", ipa: "fɛɐ̯ˈhaɪʁaːtət", pos: "adjective", level: "A1", topic: "family", difficulty: 2,
        example: { de: "Ich bin verheiratet und habe ein Kind.", en: "I'm married and have one child." },
        opposites: ["ledig", "geschieden"],
        memoryTip: "From heiraten (to marry).",
      },
      {
        id: "a1-f-9", de: "ledig", en: "single (unmarried)", ipa: "ˈleːdɪç", pos: "adjective", level: "A1", topic: "family", difficulty: 2,
        example: { de: "Familienstand: ledig.", en: "Marital status: single." },
        opposites: ["verheiratet"],
        memoryTip: "Appears on every German form under Familienstand.",
      },
      {
        id: "a1-f-10", de: "Geschwister", article: "die", plural: "die Geschwister", en: "siblings", ipa: "ɡəˈʃvɪstɐ", pos: "noun", level: "A1", topic: "family", difficulty: 2,
        example: { de: "Hast du Geschwister? — Ja, einen Bruder.", en: "Do you have siblings? — Yes, one brother." },
        memoryTip: "Ge- + Schwister: a collective noun, plural only.",
      },
    ],
  },
  {
    id: "a1-time",
    slug: "zahlen-zeit-datum",
    title: "Numbers, time & date",
    titleDe: "Zahlen, Uhrzeit und Datum",
    level: "A1",
    topic: "Numbers & time",
    icon: "Clock",
    description: "Tell the time, make appointments and understand dates.",
    words: [
      {
        id: "a1-t-1", de: "Uhr", article: "die", plural: "die Uhren", en: "clock / o'clock", ipa: "uːɐ̯", pos: "noun", level: "A1", topic: "time", difficulty: 1,
        example: { de: "Es ist zehn Uhr dreißig.", en: "It's ten thirty." },
        expressions: [{ de: "Wie viel Uhr ist es?", en: "What time is it?" }],
        memoryTip: "Uhr = both the clock and 'o'clock'.",
      },
      {
        id: "a1-t-2", de: "halb", en: "half", ipa: "halp", pos: "adjective", level: "A1", topic: "time", difficulty: 2,
        example: { de: "Wir treffen uns um halb acht.", en: "We're meeting at half past seven." },
        memoryTip: "Careful: halb acht = 7:30, not 8:30 — German counts towards the next hour.",
      },
      {
        id: "a1-t-3", de: "Viertel", article: "das", plural: "die Viertel", en: "quarter", ipa: "ˈfɪʁtl̩", pos: "noun", level: "A1", topic: "time", difficulty: 2,
        example: { de: "Es ist Viertel vor neun.", en: "It's a quarter to nine." },
        expressions: [{ de: "Viertel nach / vor", en: "quarter past / to" }],
        memoryTip: "vier (four) → Viertel (a fourth).",
      },
      {
        id: "a1-t-4", de: "Montag", article: "der", plural: "die Montage", en: "Monday", ipa: "ˈmoːntaːk", pos: "noun", level: "A1", topic: "time", difficulty: 1,
        example: { de: "Am Montag habe ich einen Termin.", en: "On Monday I have an appointment." },
        expressions: [{ de: "am Montag", en: "on Monday" }],
        memoryTip: "Mond (moon) + Tag = Monday.",
      },
      {
        id: "a1-t-5", de: "Woche", article: "die", plural: "die Wochen", en: "week", ipa: "ˈvɔxə", pos: "noun", level: "A1", topic: "time", difficulty: 1,
        example: { de: "Nächste Woche fange ich den Kurs an.", en: "Next week I start the course." },
        expressions: [{ de: "am Wochenende", en: "at the weekend" }],
        memoryTip: "Wochenende = 'week end'.",
      },
      {
        id: "a1-t-6", de: "Monat", article: "der", plural: "die Monate", en: "month", ipa: "ˈmoːnat", pos: "noun", level: "A1", topic: "time", difficulty: 1,
        example: { de: "Im Januar beginnt das neue Semester.", en: "The new semester begins in January." },
        expressions: [{ de: "im Monat", en: "per month" }],
        memoryTip: "Again from Mond (moon).",
      },
      {
        id: "a1-t-7", de: "Jahr", article: "das", plural: "die Jahre", en: "year", ipa: "jaːɐ̯", pos: "noun", level: "A1", topic: "time", difficulty: 1,
        example: { de: "Ich lerne seit einem Jahr Deutsch.", en: "I've been learning German for a year." },
        expressions: [{ de: "Ich bin 24 Jahre alt.", en: "I am 24 years old." }],
        memoryTip: "Jahr ↔ year: J is pronounced [j] like English 'y'.",
      },
      {
        id: "a1-t-8", de: "Termin", article: "der", plural: "die Termine", en: "appointment", ipa: "tɛɐ̯ˈmiːn", pos: "noun", level: "A1", topic: "time", difficulty: 2,
        example: { de: "Ich möchte einen Termin beim Arzt vereinbaren.", en: "I'd like to make a doctor's appointment." },
        expressions: [{ de: "einen Termin absagen", en: "to cancel an appointment" }],
        memoryTip: "Essential for German bureaucracy: Termin first, everything else later.",
      },
      {
        id: "a1-t-9", de: "früh", en: "early", ipa: "fʁyː", pos: "adjective", level: "A1", topic: "time", difficulty: 1,
        example: { de: "Ich stehe jeden Tag früh auf.", en: "I get up early every day." },
        opposites: ["spät"],
        memoryTip: "Rhymes with the German ü sound — round your lips.",
      },
      {
        id: "a1-t-10", de: "pünktlich", en: "punctual, on time", ipa: "ˈpʏŋktlɪç", pos: "adjective", level: "A1", topic: "time", difficulty: 2,
        example: { de: "Bitte seien Sie pünktlich!", en: "Please be on time!" },
        opposites: ["unpünktlich", "zu spät"],
        expressions: [{ de: "auf die Minute pünktlich", en: "punctual to the minute" }],
        memoryTip: "From Punkt (point): exactly on the dot.",
      },
    ],
  },
  {
    id: "a1-food",
    slug: "essen-trinken",
    title: "Food & drink",
    titleDe: "Essen und Trinken",
    level: "A1",
    topic: "Everyday life",
    icon: "UtensilsCrossed",
    description: "Order in a café, shop for groceries and talk about meals.",
    words: [
      {
        id: "a1-e-1", de: "Brot", article: "das", plural: "die Brote", en: "bread", ipa: "bʁoːt", pos: "noun", level: "A1", topic: "food", difficulty: 1,
        example: { de: "Ich kaufe jeden Morgen frisches Brot.", en: "I buy fresh bread every morning." },
        expressions: [{ de: "das Brötchen", en: "bread roll" }],
        memoryTip: "Germany has over 300 kinds of Brot.",
      },
      {
        id: "a1-e-2", de: "Wasser", article: "das", plural: "die Wässer", en: "water", ipa: "ˈvasɐ", pos: "noun", level: "A1", topic: "food", difficulty: 1,
        example: { de: "Ein Glas Wasser, bitte.", en: "A glass of water, please." },
        expressions: [{ de: "Wasser mit / ohne Kohlensäure", en: "sparkling / still water" }],
        memoryTip: "Wasser ↔ water: w is pronounced [v].",
      },
      {
        id: "a1-e-3", de: "Kaffee", article: "der", plural: "die Kaffees", en: "coffee", ipa: "ˈkafe", pos: "noun", level: "A1", topic: "food", difficulty: 1,
        example: { de: "Ich trinke morgens einen Kaffee mit Milch.", en: "In the morning I drink a coffee with milk." },
        expressions: [{ de: "Kaffee und Kuchen", en: "coffee and cake (a German ritual)" }],
        memoryTip: "Stress the first syllable in Germany: KA-ffee.",
      },
      {
        id: "a1-e-4", de: "Gemüse", article: "das", plural: "—", en: "vegetables", ipa: "ɡəˈmyːzə", pos: "noun", level: "A1", topic: "food", difficulty: 2,
        example: { de: "Ich esse jeden Tag Obst und Gemüse.", en: "I eat fruit and vegetables every day." },
        memoryTip: "Ge- nouns are usually neuter and often collective.",
      },
      {
        id: "a1-e-5", de: "Obst", article: "das", plural: "—", en: "fruit", ipa: "oːpst", pos: "noun", level: "A1", topic: "food", difficulty: 2,
        example: { de: "Obst ist im Sommer billiger.", en: "Fruit is cheaper in summer." },
        memoryTip: "Uncountable, like English 'fruit' in general.",
      },
      {
        id: "a1-e-6", de: "essen", en: "to eat", ipa: "ˈɛsn̩", pos: "verb", level: "A1", topic: "food", difficulty: 1,
        example: { de: "Was isst du zum Frühstück?", en: "What do you eat for breakfast?" },
        expressions: [{ de: "essen gehen", en: "to eat out" }],
        memoryTip: "Stem change e → i: du isst, er isst.",
      },
      {
        id: "a1-e-7", de: "trinken", en: "to drink", ipa: "ˈtʁɪŋkən", pos: "verb", level: "A1", topic: "food", difficulty: 1,
        example: { de: "Was möchten Sie trinken?", en: "What would you like to drink?" },
        memoryTip: "Perfekt: hat getrunken.",
      },
      {
        id: "a1-e-8", de: "Rechnung", article: "die", plural: "die Rechnungen", en: "bill / invoice", ipa: "ˈʁɛçnʊŋ", pos: "noun", level: "A1", topic: "food", difficulty: 2,
        example: { de: "Die Rechnung, bitte! Zusammen oder getrennt?", en: "The bill, please! Together or separately?" },
        expressions: [{ de: "eine Rechnung bezahlen", en: "to pay a bill" }],
        memoryTip: "From rechnen (to calculate). -ung → feminine.",
      },
      {
        id: "a1-e-9", de: "lecker", en: "tasty, delicious", ipa: "ˈlɛkɐ", pos: "adjective", level: "A1", topic: "food", difficulty: 1,
        example: { de: "Das Essen war sehr lecker, danke!", en: "The food was very tasty, thank you!" },
        synonyms: ["köstlich", "gut"],
        memoryTip: "The one compliment every German cook wants to hear.",
      },
      {
        id: "a1-e-10", de: "Frühstück", article: "das", plural: "die Frühstücke", en: "breakfast", ipa: "ˈfʁyːʃtʏk", pos: "noun", level: "A1", topic: "food", difficulty: 2,
        example: { de: "Zum Frühstück esse ich ein Brötchen mit Käse.", en: "For breakfast I eat a roll with cheese." },
        expressions: [{ de: "frühstücken", en: "to have breakfast" }],
        memoryTip: "früh (early) + Stück (piece) = the early bite.",
      },
    ],
  },
  {
    id: "a1-home",
    slug: "wohnen-moebel",
    title: "Home & furniture",
    titleDe: "Wohnen und Möbel",
    level: "A1",
    topic: "Everyday life",
    icon: "Home",
    description: "Describe your flat, read housing adverts and name furniture.",
    words: [
      {
        id: "a1-h-1", de: "Wohnung", article: "die", plural: "die Wohnungen", en: "flat, apartment", ipa: "ˈvoːnʊŋ", pos: "noun", level: "A1", topic: "home", difficulty: 1,
        example: { de: "Ich suche eine Wohnung mit zwei Zimmern.", en: "I'm looking for a two-room flat." },
        expressions: [{ de: "eine Wohnung mieten", en: "to rent a flat" }],
        memoryTip: "From wohnen; -ung is always feminine.",
      },
      {
        id: "a1-h-2", de: "Zimmer", article: "das", plural: "die Zimmer", en: "room", ipa: "ˈtsɪmɐ", pos: "noun", level: "A1", topic: "home", difficulty: 1,
        example: { de: "Das Zimmer ist hell und ruhig.", en: "The room is bright and quiet." },
        expressions: [{ de: "das Wohnzimmer / Schlafzimmer", en: "living room / bedroom" }],
        memoryTip: "Same form in singular and plural.",
      },
      {
        id: "a1-h-3", de: "Küche", article: "die", plural: "die Küchen", en: "kitchen", ipa: "ˈkʏçə", pos: "noun", level: "A1", topic: "home", difficulty: 1,
        example: { de: "Die Küche ist klein, aber praktisch.", en: "The kitchen is small but practical." },
        memoryTip: "Küche ↔ kitchen; the ü needs rounded lips.",
      },
      {
        id: "a1-h-4", de: "Miete", article: "die", plural: "die Mieten", en: "rent", ipa: "ˈmiːtə", pos: "noun", level: "A1", topic: "home", difficulty: 2,
        example: { de: "Die Miete beträgt 650 Euro warm.", en: "The rent is 650 euros including bills." },
        expressions: [{ de: "warm / kalt", en: "with / without heating costs" }],
        memoryTip: "Warmmiete includes Nebenkosten — always check.",
      },
      {
        id: "a1-h-5", de: "Tisch", article: "der", plural: "die Tische", en: "table", ipa: "tɪʃ", pos: "noun", level: "A1", topic: "home", difficulty: 1,
        example: { de: "Der Tisch steht in der Mitte des Zimmers.", en: "The table is in the middle of the room." },
        memoryTip: "Plural adds -e: Tische.",
      },
      {
        id: "a1-h-6", de: "Stuhl", article: "der", plural: "die Stühle", en: "chair", ipa: "ʃtuːl", pos: "noun", level: "A1", topic: "home", difficulty: 1,
        example: { de: "Wir brauchen noch vier Stühle.", en: "We still need four chairs." },
        memoryTip: "Umlaut plural: Stühle.",
      },
      {
        id: "a1-h-7", de: "Bett", article: "das", plural: "die Betten", en: "bed", ipa: "bɛt", pos: "noun", level: "A1", topic: "home", difficulty: 1,
        example: { de: "Ich gehe um elf Uhr ins Bett.", en: "I go to bed at eleven." },
        expressions: [{ de: "ins Bett gehen", en: "to go to bed" }],
        memoryTip: "Bett ↔ bed, double t.",
      },
      {
        id: "a1-h-8", de: "hell", en: "bright", ipa: "hɛl", pos: "adjective", level: "A1", topic: "home", difficulty: 1,
        example: { de: "Das Wohnzimmer ist sehr hell.", en: "The living room is very bright." },
        opposites: ["dunkel"],
        memoryTip: "Key word in every flat advert.",
      },
      {
        id: "a1-h-9", de: "günstig", en: "cheap, good value", ipa: "ˈɡʏnstɪç", pos: "adjective", level: "A1", topic: "home", difficulty: 2,
        example: { de: "Die Wohnung ist zentral und günstig.", en: "The flat is central and good value." },
        opposites: ["teuer"],
        synonyms: ["billig (negative Nuance)"],
        memoryTip: "günstig sounds positive; billig can sound cheap.",
      },
      {
        id: "a1-h-10", de: "Nebenkosten", article: "die", plural: "die Nebenkosten", en: "utility / additional costs", ipa: "ˈneːbn̩ˌkɔstn̩", pos: "noun", level: "A1", topic: "home", difficulty: 3,
        example: { de: "Die Nebenkosten sind in der Miete enthalten.", en: "The utilities are included in the rent." },
        memoryTip: "neben (next to) + Kosten (costs) = the extras.",
      },
    ],
  },
  {
    id: "a1-city",
    slug: "stadt-verkehr",
    title: "City & transport",
    titleDe: "Stadt und Verkehr",
    level: "A1",
    topic: "Orientation",
    icon: "Train",
    description: "Ask for directions, buy tickets and get around a German city.",
    words: [
      {
        id: "a1-c-1", de: "Bahnhof", article: "der", plural: "die Bahnhöfe", en: "train station", ipa: "ˈbaːnhoːf", pos: "noun", level: "A1", topic: "city", difficulty: 1,
        example: { de: "Wie komme ich zum Bahnhof?", en: "How do I get to the station?" },
        expressions: [{ de: "der Hauptbahnhof (Hbf)", en: "main station" }],
        memoryTip: "Bahn (railway) + Hof (yard).",
      },
      {
        id: "a1-c-2", de: "Straße", article: "die", plural: "die Straßen", en: "street", ipa: "ˈʃtʁaːsə", pos: "noun", level: "A1", topic: "city", difficulty: 1,
        example: { de: "Ich wohne in der Goethestraße 12.", en: "I live at 12 Goethe Street." },
        expressions: [{ de: "die Straße überqueren", en: "to cross the street" }],
        memoryTip: "Written Str. in addresses.",
      },
      {
        id: "a1-c-3", de: "links", en: "left", ipa: "lɪŋks", pos: "adverb", level: "A1", topic: "city", difficulty: 1,
        example: { de: "Gehen Sie an der Ampel links.", en: "Turn left at the traffic light." },
        opposites: ["rechts"],
        expressions: [{ de: "nach links", en: "to the left" }],
        memoryTip: "links – rechts: learn as a pair with hand gestures.",
      },
      {
        id: "a1-c-4", de: "geradeaus", en: "straight ahead", ipa: "ɡəˈʁaːdəˌʔaʊs", pos: "adverb", level: "A1", topic: "city", difficulty: 2,
        example: { de: "Gehen Sie hundert Meter geradeaus.", en: "Go straight ahead for a hundred metres." },
        memoryTip: "gerade (straight) + aus (out).",
      },
      {
        id: "a1-c-5", de: "Fahrkarte", article: "die", plural: "die Fahrkarten", en: "ticket", ipa: "ˈfaːɐ̯ˌkaʁtə", pos: "noun", level: "A1", topic: "city", difficulty: 2,
        example: { de: "Eine Fahrkarte nach Köln, bitte.", en: "A ticket to Cologne, please." },
        synonyms: ["das Ticket"],
        memoryTip: "fahren + Karte = travel card.",
      },
      {
        id: "a1-c-6", de: "umsteigen", en: "to change (trains)", ipa: "ˈʊmʃtaɪɡn̩", pos: "verb", level: "A1", topic: "city", difficulty: 2,
        example: { de: "In Frankfurt müssen Sie umsteigen.", en: "You have to change in Frankfurt." },
        memoryTip: "Separable: Ich steige in Köln um.",
      },
      {
        id: "a1-c-7", de: "Verspätung", article: "die", plural: "die Verspätungen", en: "delay", ipa: "fɛɐ̯ˈʃpɛːtʊŋ", pos: "noun", level: "A1", topic: "city", difficulty: 2,
        example: { de: "Der Zug hat zehn Minuten Verspätung.", en: "The train is ten minutes late." },
        expressions: [{ de: "Verspätung haben", en: "to be delayed" }],
        memoryTip: "From spät (late).",
      },
      {
        id: "a1-c-8", de: "Apotheke", article: "die", plural: "die Apotheken", en: "pharmacy", ipa: "apoˈteːkə", pos: "noun", level: "A1", topic: "city", difficulty: 2,
        example: { de: "Gibt es hier in der Nähe eine Apotheke?", en: "Is there a pharmacy nearby?" },
        memoryTip: "Not the same as Drogerie, which sells cosmetics.",
      },
      {
        id: "a1-c-9", de: "in der Nähe", en: "nearby", ipa: "ɪn deːɐ̯ ˈnɛːə", pos: "phrase", level: "A1", topic: "city", difficulty: 2,
        example: { de: "Der Supermarkt ist in der Nähe.", en: "The supermarket is nearby." },
        opposites: ["weit weg"],
        memoryTip: "nah (near) → die Nähe (the vicinity).",
      },
      {
        id: "a1-c-10", de: "Ampel", article: "die", plural: "die Ampeln", en: "traffic light", ipa: "ˈampl̩", pos: "noun", level: "A1", topic: "city", difficulty: 2,
        example: { de: "Warten Sie bitte an der Ampel.", en: "Please wait at the traffic light." },
        memoryTip: "In Germany people really do wait for the green Ampel.",
      },
    ],
  },
];
