import type { VocabDeck } from "@/lib/types";

export const a2Decks: VocabDeck[] = [
  {
    id: "a2-work",
    slug: "arbeit-berufe",
    title: "Work & professions",
    titleDe: "Arbeit und Berufe",
    level: "A2",
    topic: "Work",
    icon: "Briefcase",
    description: "Job titles, contracts and the words you meet on your first day at work.",
    words: [
      {
        id: "a2-w-1", de: "Beruf", article: "der", plural: "die Berufe", en: "profession, job", ipa: "bəˈʁuːf", pos: "noun", level: "A2", topic: "work", difficulty: 1,
        example: { de: "Was sind Sie von Beruf? — Ich bin Elektriker.", en: "What's your profession? — I'm an electrician." },
        expressions: [{ de: "von Beruf sein", en: "to be … by profession" }],
        memoryTip: "From rufen (to call) — your calling.",
      },
      {
        id: "a2-w-2", de: "Stelle", article: "die", plural: "die Stellen", en: "position, job vacancy", ipa: "ˈʃtɛlə", pos: "noun", level: "A2", topic: "work", difficulty: 2,
        example: { de: "Ich habe eine Stelle als Pflegehelfer gefunden.", en: "I found a job as a care assistant." },
        synonyms: ["der Arbeitsplatz", "der Job"],
        expressions: [{ de: "sich auf eine Stelle bewerben", en: "to apply for a position" }],
        memoryTip: "Stellenangebot = job advert.",
      },
      {
        id: "a2-w-3", de: "Ausbildung", article: "die", plural: "die Ausbildungen", en: "vocational training", ipa: "ˈaʊsˌbɪldʊŋ", pos: "noun", level: "A2", topic: "work", difficulty: 2,
        example: { de: "Ich mache eine Ausbildung als Kfz-Mechatroniker.", en: "I'm doing training as a car mechatronics technician." },
        expressions: [{ de: "eine Ausbildung machen", en: "to do vocational training" }],
        memoryTip: "The German dual system: school + company at the same time.",
      },
      {
        id: "a2-w-4", de: "Gehalt", article: "das", plural: "die Gehälter", en: "salary", ipa: "ɡəˈhalt", pos: "noun", level: "A2", topic: "work", difficulty: 2,
        example: { de: "Das Gehalt wird monatlich überwiesen.", en: "The salary is transferred monthly." },
        synonyms: ["der Lohn"],
        memoryTip: "Gehalt = monthly salary, Lohn = hourly wage.",
      },
      {
        id: "a2-w-5", de: "Kollege", article: "der", plural: "die Kollegen", en: "colleague", ipa: "kɔˈleːɡə", pos: "noun", level: "A2", topic: "work", difficulty: 1,
        example: { de: "Meine Kollegen sind sehr hilfsbereit.", en: "My colleagues are very helpful." },
        expressions: [{ de: "die Kollegin", en: "female colleague" }],
        memoryTip: "N-declension: den Kollegen, dem Kollegen.",
      },
      {
        id: "a2-w-6", de: "Feierabend", article: "der", plural: "die Feierabende", en: "end of the working day", ipa: "ˈfaɪɐˌʔaːbn̩t", pos: "noun", level: "A2", topic: "work", difficulty: 3,
        example: { de: "Um 17 Uhr habe ich Feierabend.", en: "I finish work at 5 pm." },
        expressions: [{ de: "Schönen Feierabend!", en: "Have a nice evening (after work)!" }],
        memoryTip: "feiern (celebrate) + Abend — the work day is over.",
      },
      {
        id: "a2-w-7", de: "Überstunden", article: "die", plural: "die Überstunden", en: "overtime", ipa: "ˈyːbɐˌʃtʊndn̩", pos: "noun", level: "A2", topic: "work", difficulty: 2,
        example: { de: "Diese Woche muss ich Überstunden machen.", en: "This week I have to work overtime." },
        memoryTip: "über (over) + Stunden (hours).",
      },
      {
        id: "a2-w-8", de: "kündigen", en: "to resign / to give notice", ipa: "ˈkʏndɪɡn̩", pos: "verb", level: "A2", topic: "work", difficulty: 3,
        example: { de: "Er hat zum 31. März gekündigt.", en: "He gave notice effective 31 March." },
        opposites: ["einstellen"],
        expressions: [{ de: "die Kündigung", en: "notice, termination" }],
        memoryTip: "Both employer and employee can kündigen.",
      },
      {
        id: "a2-w-9", de: "Vorstellungsgespräch", article: "das", plural: "die Vorstellungsgespräche", en: "job interview", ipa: "ˈfoːɐ̯ʃtɛlʊŋsɡəˌʃpʁɛːç", pos: "noun", level: "A2", topic: "work", difficulty: 3,
        example: { de: "Ich habe morgen ein Vorstellungsgespräch.", en: "I have a job interview tomorrow." },
        memoryTip: "sich vorstellen (introduce oneself) + Gespräch (conversation).",
      },
      {
        id: "a2-w-10", de: "Erfahrung", article: "die", plural: "die Erfahrungen", en: "experience", ipa: "ɛɐ̯ˈfaːʁʊŋ", pos: "noun", level: "A2", topic: "work", difficulty: 2,
        example: { de: "Ich habe zwei Jahre Erfahrung in der Gastronomie.", en: "I have two years of experience in catering." },
        expressions: [{ de: "Berufserfahrung", en: "professional experience" }],
        memoryTip: "erfahren = to find out / experienced.",
      },
    ],
  },
  {
    id: "a2-health",
    slug: "gesundheit-koerper",
    title: "Health & body",
    titleDe: "Gesundheit und Körper",
    level: "A2",
    topic: "Health",
    icon: "HeartPulse",
    description: "Describe symptoms, talk to a doctor and understand a prescription.",
    words: [
      {
        id: "a2-h-1", de: "Arzt", article: "der", plural: "die Ärzte", en: "doctor", ipa: "aːɐ̯t͡st", pos: "noun", level: "A2", topic: "health", difficulty: 1,
        example: { de: "Ich muss dringend zum Arzt gehen.", en: "I urgently need to see a doctor." },
        expressions: [{ de: "die Ärztin", en: "female doctor" }, { de: "der Hausarzt", en: "GP" }],
        memoryTip: "zum Arzt gehen — always with zu + Dativ.",
      },
      {
        id: "a2-h-2", de: "Schmerz", article: "der", plural: "die Schmerzen", en: "pain", ipa: "ʃmɛɐ̯t͡s", pos: "noun", level: "A2", topic: "health", difficulty: 2,
        example: { de: "Ich habe seit drei Tagen Kopfschmerzen.", en: "I've had a headache for three days." },
        expressions: [{ de: "Bauchschmerzen, Rückenschmerzen", en: "stomach ache, back pain" }],
        memoryTip: "Usually used in the plural: Schmerzen.",
      },
      {
        id: "a2-h-3", de: "Krankenkasse", article: "die", plural: "die Krankenkassen", en: "health insurance fund", ipa: "ˈkʁaŋkn̩ˌkasə", pos: "noun", level: "A2", topic: "health", difficulty: 3,
        example: { de: "Welche Krankenkasse haben Sie?", en: "Which health insurance do you have?" },
        memoryTip: "krank (ill) + Kasse (fund) — obligatory in Germany.",
      },
      {
        id: "a2-h-4", de: "Rezept", article: "das", plural: "die Rezepte", en: "prescription / recipe", ipa: "ʁeˈt͡sɛpt", pos: "noun", level: "A2", topic: "health", difficulty: 2,
        example: { de: "Der Arzt hat mir ein Rezept gegeben.", en: "The doctor gave me a prescription." },
        memoryTip: "Same word for a cooking recipe — context decides.",
      },
      {
        id: "a2-h-5", de: "sich erkälten", en: "to catch a cold", ipa: "zɪç ɛɐ̯ˈkɛltn̩", pos: "verb", level: "A2", topic: "health", difficulty: 2,
        example: { de: "Ich habe mich am Wochenende erkältet.", en: "I caught a cold at the weekend." },
        expressions: [{ de: "die Erkältung", en: "a cold" }],
        memoryTip: "From kalt (cold) — reflexive verb.",
      },
      {
        id: "a2-h-6", de: "Kopf", article: "der", plural: "die Köpfe", en: "head", ipa: "kɔpf", pos: "noun", level: "A2", topic: "health", difficulty: 1,
        example: { de: "Mein Kopf tut weh.", en: "My head hurts." },
        expressions: [{ de: "weh tun", en: "to hurt" }],
        memoryTip: "Kopfschmerzen = head + pains.",
      },
      {
        id: "a2-h-7", de: "gesund", en: "healthy", ipa: "ɡəˈzʊnt", pos: "adjective", level: "A2", topic: "health", difficulty: 1,
        example: { de: "Obst und Gemüse sind gesund.", en: "Fruit and vegetables are healthy." },
        opposites: ["krank", "ungesund"],
        expressions: [{ de: "Gesundheit!", en: "Bless you! (after a sneeze)" }],
        memoryTip: "die Gesundheit = health.",
      },
      {
        id: "a2-h-8", de: "Krankmeldung", article: "die", plural: "die Krankmeldungen", en: "sick note", ipa: "ˈkʁaŋkˌmɛldʊŋ", pos: "noun", level: "A2", topic: "health", difficulty: 3,
        example: { de: "Bitte schicken Sie die Krankmeldung an die Personalabteilung.", en: "Please send the sick note to HR." },
        synonyms: ["die Arbeitsunfähigkeitsbescheinigung (AU)"],
        memoryTip: "You must report sick on day one in Germany.",
      },
      {
        id: "a2-h-9", de: "Notaufnahme", article: "die", plural: "die Notaufnahmen", en: "emergency department", ipa: "ˈnoːtʔaʊfˌnaːmə", pos: "noun", level: "A2", topic: "health", difficulty: 3,
        example: { de: "Wir sind sofort in die Notaufnahme gefahren.", en: "We drove straight to A&E." },
        memoryTip: "Not (emergency) + Aufnahme (admission). Emergency number: 112.",
      },
      {
        id: "a2-h-10", de: "sich ausruhen", en: "to rest", ipa: "zɪç ˈaʊsˌʁuːən", pos: "verb", level: "A2", topic: "health", difficulty: 2,
        example: { de: "Sie sollten sich ein paar Tage ausruhen.", en: "You should rest for a few days." },
        synonyms: ["sich erholen"],
        memoryTip: "Separable and reflexive: Ich ruhe mich aus.",
      },
    ],
  },
  {
    id: "a2-shopping",
    slug: "einkaufen-kleidung",
    title: "Shopping & clothes",
    titleDe: "Einkaufen und Kleidung",
    level: "A2",
    topic: "Everyday life",
    icon: "ShoppingBag",
    description: "Sizes, prices, returns and complaints in German shops.",
    words: [
      {
        id: "a2-s-1", de: "Größe", article: "die", plural: "die Größen", en: "size", ipa: "ˈɡʁøːsə", pos: "noun", level: "A2", topic: "shopping", difficulty: 2,
        example: { de: "Haben Sie das auch in Größe 42?", en: "Do you have this in size 42 as well?" },
        memoryTip: "From groß (big).",
      },
      {
        id: "a2-s-2", de: "anprobieren", en: "to try on", ipa: "ˈanpʁoˌbiːʁən", pos: "verb", level: "A2", topic: "shopping", difficulty: 2,
        example: { de: "Kann ich die Jacke anprobieren?", en: "Can I try the jacket on?" },
        memoryTip: "Separable: Ich probiere sie an.",
      },
      {
        id: "a2-s-3", de: "umtauschen", en: "to exchange", ipa: "ˈʊmˌtaʊʃn̩", pos: "verb", level: "A2", topic: "shopping", difficulty: 2,
        example: { de: "Kann ich das Hemd umtauschen? Hier ist der Kassenzettel.", en: "Can I exchange the shirt? Here's the receipt." },
        expressions: [{ de: "der Kassenzettel", en: "receipt" }],
        memoryTip: "um- often means 'change': umsteigen, umziehen, umtauschen.",
      },
      {
        id: "a2-s-4", de: "Angebot", article: "das", plural: "die Angebote", en: "special offer", ipa: "ˈanɡəˌboːt", pos: "noun", level: "A2", topic: "shopping", difficulty: 2,
        example: { de: "Die Schuhe sind im Angebot: 30 % Rabatt.", en: "The shoes are on offer: 30 % off." },
        expressions: [{ de: "im Angebot", en: "on offer" }],
        memoryTip: "anbieten → das Angebot.",
      },
      {
        id: "a2-s-5", de: "Kasse", article: "die", plural: "die Kassen", en: "till, checkout", ipa: "ˈkasə", pos: "noun", level: "A2", topic: "shopping", difficulty: 1,
        example: { de: "Bitte bezahlen Sie an der Kasse 3.", en: "Please pay at till 3." },
        expressions: [{ de: "Zahlen Sie bar oder mit Karte?", en: "Are you paying cash or by card?" }],
        memoryTip: "Cash is still king in many German shops.",
      },
      {
        id: "a2-s-6", de: "Hose", article: "die", plural: "die Hosen", en: "trousers", ipa: "ˈhoːzə", pos: "noun", level: "A2", topic: "shopping", difficulty: 1,
        example: { de: "Die Hose ist mir zu eng.", en: "The trousers are too tight for me." },
        memoryTip: "Singular in German, plural in English.",
      },
      {
        id: "a2-s-7", de: "Schuhe", article: "die", plural: "die Schuhe", en: "shoes", ipa: "ˈʃuːə", pos: "noun", level: "A2", topic: "shopping", difficulty: 1,
        example: { de: "Ich brauche neue Schuhe für die Arbeit.", en: "I need new shoes for work." },
        memoryTip: "Singular: der Schuh.",
      },
      {
        id: "a2-s-8", de: "preiswert", en: "reasonably priced", ipa: "ˈpʁaɪsˌveːɐ̯t", pos: "adjective", level: "A2", topic: "shopping", difficulty: 3,
        example: { de: "Das Angebot ist wirklich preiswert.", en: "The offer is really good value." },
        synonyms: ["günstig"],
        opposites: ["teuer"],
        memoryTip: "Literally 'worth the price'.",
      },
    ],
  },
  {
    id: "a2-travel",
    slug: "reisen-urlaub",
    title: "Travel & holidays",
    titleDe: "Reisen und Urlaub",
    level: "A2",
    topic: "Travel",
    icon: "Plane",
    description: "Book a room, describe a trip and deal with problems while travelling.",
    words: [
      {
        id: "a2-r-1", de: "Urlaub", article: "der", plural: "die Urlaube", en: "holiday, vacation", ipa: "ˈuːɐ̯laʊp", pos: "noun", level: "A2", topic: "travel", difficulty: 1,
        example: { de: "Im August fahren wir in den Urlaub.", en: "In August we're going on holiday." },
        expressions: [{ de: "Urlaub beantragen", en: "to request holiday leave" }],
        memoryTip: "Urlaub = time off work; Ferien = school holidays.",
      },
      {
        id: "a2-r-2", de: "buchen", en: "to book", ipa: "ˈbuːxn̩", pos: "verb", level: "A2", topic: "travel", difficulty: 1,
        example: { de: "Ich habe ein Doppelzimmer für zwei Nächte gebucht.", en: "I booked a double room for two nights." },
        memoryTip: "Regular verb: hat gebucht.",
      },
      {
        id: "a2-r-3", de: "Unterkunft", article: "die", plural: "die Unterkünfte", en: "accommodation", ipa: "ˈʊntɐˌkʊnft", pos: "noun", level: "A2", topic: "travel", difficulty: 3,
        example: { de: "Die Unterkunft war sauber und zentral.", en: "The accommodation was clean and central." },
        memoryTip: "unter + kommen → where you 'come under' a roof.",
      },
      {
        id: "a2-r-4", de: "Sehenswürdigkeit", article: "die", plural: "die Sehenswürdigkeiten", en: "sight, attraction", ipa: "ˈzeːənsˌvʏʁdɪçkaɪt", pos: "noun", level: "A2", topic: "travel", difficulty: 3,
        example: { de: "Der Kölner Dom ist die bekannteste Sehenswürdigkeit der Stadt.", en: "Cologne Cathedral is the city's most famous sight." },
        memoryTip: "sehen + würdig = 'worth seeing'.",
      },
      {
        id: "a2-r-5", de: "Gepäck", article: "das", plural: "—", en: "luggage", ipa: "ɡəˈpɛk", pos: "noun", level: "A2", topic: "travel", difficulty: 2,
        example: { de: "Mein Gepäck ist noch am Flughafen.", en: "My luggage is still at the airport." },
        memoryTip: "Uncountable, like English 'luggage'.",
      },
      {
        id: "a2-r-6", de: "sich beschweren", en: "to complain", ipa: "zɪç bəˈʃveːʁən", pos: "verb", level: "A2", topic: "travel", difficulty: 3,
        example: { de: "Ich möchte mich über den Lärm beschweren.", en: "I'd like to complain about the noise." },
        expressions: [{ de: "die Beschwerde", en: "complaint" }],
        memoryTip: "Reflexive + über + Akkusativ.",
      },
      {
        id: "a2-r-7", de: "Ausflug", article: "der", plural: "die Ausflüge", en: "excursion, day trip", ipa: "ˈaʊsfluːk", pos: "noun", level: "A2", topic: "travel", difficulty: 2,
        example: { de: "Am Sonntag machen wir einen Ausflug an den See.", en: "On Sunday we're taking a trip to the lake." },
        expressions: [{ de: "einen Ausflug machen", en: "to go on an excursion" }],
        memoryTip: "aus + Flug — a flight out of your routine.",
      },
      {
        id: "a2-r-8", de: "inklusive", en: "included", ipa: "ɪnkluˈziːvə", pos: "adjective", level: "A2", topic: "travel", difficulty: 2,
        example: { de: "Das Frühstück ist inklusive.", en: "Breakfast is included." },
        opposites: ["exklusive", "extra"],
        memoryTip: "Often abbreviated inkl. in adverts.",
      },
    ],
  },
  {
    id: "a2-routine",
    slug: "alltag-freizeit",
    title: "Daily routine & free time",
    titleDe: "Alltag und Freizeit",
    level: "A2",
    topic: "Everyday life",
    icon: "Sun",
    description: "Describe your day, your habits and your hobbies.",
    words: [
      {
        id: "a2-a-1", de: "aufwachen", en: "to wake up", ipa: "ˈaʊfˌvaxn̩", pos: "verb", level: "A2", topic: "routine", difficulty: 1,
        example: { de: "Ich wache jeden Tag um sechs Uhr auf.", en: "I wake up at six every day." },
        opposites: ["einschlafen"],
        memoryTip: "Separable, Perfekt with sein: ist aufgewacht.",
      },
      {
        id: "a2-a-2", de: "sich duschen", en: "to shower", ipa: "zɪç ˈduːʃn̩", pos: "verb", level: "A2", topic: "routine", difficulty: 1,
        example: { de: "Nach dem Sport dusche ich mich.", en: "After sport I take a shower." },
        memoryTip: "Reflexive in German, not in English.",
      },
      {
        id: "a2-a-3", de: "Haushalt", article: "der", plural: "die Haushalte", en: "household, housework", ipa: "ˈhaʊsˌhalt", pos: "noun", level: "A2", topic: "routine", difficulty: 2,
        example: { de: "Wir teilen uns die Arbeit im Haushalt.", en: "We share the housework." },
        expressions: [{ de: "den Haushalt machen", en: "to do the housework" }],
        memoryTip: "Haus + halten = keeping the house.",
      },
      {
        id: "a2-a-4", de: "Freizeit", article: "die", plural: "—", en: "free time", ipa: "ˈfʁaɪˌt͡saɪt", pos: "noun", level: "A2", topic: "routine", difficulty: 1,
        example: { de: "In meiner Freizeit spiele ich Fußball.", en: "In my free time I play football." },
        memoryTip: "frei + Zeit.",
      },
      {
        id: "a2-a-5", de: "Verein", article: "der", plural: "die Vereine", en: "club, association", ipa: "fɛɐ̯ˈʔaɪn", pos: "noun", level: "A2", topic: "routine", difficulty: 3,
        example: { de: "Ich bin in einem Sportverein angemeldet.", en: "I'm registered with a sports club." },
        memoryTip: "Germans love Vereine — a great way to make friends.",
      },
      {
        id: "a2-a-6", de: "sich treffen", en: "to meet", ipa: "zɪç ˈtʁɛfn̩", pos: "verb", level: "A2", topic: "routine", difficulty: 1,
        example: { de: "Wir treffen uns um acht vor dem Kino.", en: "We're meeting at eight in front of the cinema." },
        memoryTip: "sich treffen mit + Dativ.",
      },
      {
        id: "a2-a-7", de: "müde", en: "tired", ipa: "ˈmyːdə", pos: "adjective", level: "A2", topic: "routine", difficulty: 1,
        example: { de: "Nach der Arbeit bin ich immer müde.", en: "After work I'm always tired." },
        opposites: ["wach", "fit"],
        memoryTip: "ü sound: lips rounded, tongue forward.",
      },
      {
        id: "a2-a-8", de: "normalerweise", en: "usually", ipa: "nɔʁˈmaːlɐˌvaɪzə", pos: "adverb", level: "A2", topic: "routine", difficulty: 2,
        example: { de: "Normalerweise fahre ich mit dem Rad zur Arbeit.", en: "I usually cycle to work." },
        synonyms: ["meistens", "gewöhnlich"],
        memoryTip: "-weise turns adjectives into adverbs.",
      },
    ],
  },
];
