import type { ListeningTask } from "@/lib/types";

/**
 * Listening material is rendered by the browser speech engine (de-DE) so the
 * platform needs no audio files and every task supports variable playback speed.
 */
export const listeningTasks: ListeningTask[] = [
  {
    slug: "im-cafe-bestellen",
    level: "A1",
    title: "Im Café bestellen",
    titleEn: "Ordering in a café",
    scenario: "Nour orders breakfast in a café in Leipzig. Listen for what she orders and what she pays.",
    seconds: 55,
    transcript: [
      { speaker: "Kellner", de: "Guten Morgen! Was darf ich Ihnen bringen?", en: "Good morning! What can I get you?" },
      { speaker: "Nour", de: "Guten Morgen. Ich möchte einen Kaffee mit Milch, bitte.", en: "Good morning. I'd like a coffee with milk, please." },
      { speaker: "Kellner", de: "Gern. Möchten Sie auch etwas essen?", en: "Certainly. Would you like something to eat as well?" },
      { speaker: "Nour", de: "Ja, ein Brötchen mit Käse, bitte. Und ein Glas Wasser.", en: "Yes, a roll with cheese, please. And a glass of water." },
      { speaker: "Kellner", de: "Also ein Kaffee, ein Brötchen mit Käse und ein Wasser. Das macht sechs Euro achtzig.", en: "So one coffee, a cheese roll and a water. That's six euros eighty." },
      { speaker: "Nour", de: "Hier sind sieben Euro. Stimmt so, danke.", en: "Here's seven euros. Keep the change, thanks." },
      { speaker: "Kellner", de: "Vielen Dank! Einen schönen Tag noch.", en: "Thank you very much! Have a nice day." },
    ],
    vocabulary: [
      { de: "Was darf ich Ihnen bringen?", en: "What can I bring you?" },
      { de: "Gern.", en: "With pleasure / certainly." },
      { de: "Das macht …", en: "That comes to …" },
      { de: "Stimmt so.", en: "Keep the change." },
    ],
    tips: [
      "Listen for numbers first — prices are almost always tested.",
      "Bestellen phrases repeat: Ich möchte …, bitte / Ich nehme …",
    ],
    questions: [
      {
        id: "l-a1-1-q1",
        type: "multiple-choice",
        prompt: "Was trinkt Nour?",
        options: ["Tee mit Zitrone", "Kaffee mit Milch", "Orangensaft", "Nur Wasser"],
        answerIndex: 1,
        explanation: "„Ich möchte einen Kaffee mit Milch, bitte.“",
        skill: "listening",
      },
      {
        id: "l-a1-1-q2",
        type: "multiple-choice",
        prompt: "Wie viel kostet das Frühstück?",
        options: ["6,08 €", "6,80 €", "7,00 €", "8,60 €"],
        answerIndex: 1,
        explanation: "„Das macht sechs Euro achtzig.“",
        skill: "listening",
      },
      {
        id: "l-a1-1-q3",
        type: "dictation",
        prompt: "Schreiben Sie den Satz, den Sie hören.",
        audioText: "Ich möchte einen Kaffee mit Milch, bitte.",
        answers: ["Ich möchte einen Kaffee mit Milch, bitte.", "Ich möchte einen Kaffee mit Milch bitte"],
        explanation: "Akkusativ: einen Kaffee.",
        skill: "listening",
      },
    ],
  },
  {
    slug: "ansage-bahnhof",
    level: "A1",
    title: "Ansagen am Bahnhof",
    titleEn: "Station announcements",
    scenario: "Three short announcements. Note platform numbers, delays and destinations.",
    seconds: 60,
    transcript: [
      { speaker: "Ansage 1", de: "Achtung an Gleis vier: Der Regionalexpress nach Dresden, Abfahrt zehn Uhr zwanzig, hat heute etwa fünfzehn Minuten Verspätung." },
      { speaker: "Ansage 2", de: "Der Intercity nach München, Abfahrt zehn Uhr fünfundvierzig, fährt heute von Gleis neun, nicht von Gleis sieben. Wir bitten um Ihr Verständnis." },
      { speaker: "Ansage 3", de: "Nächster Halt: Leipzig Hauptbahnhof. Bitte alle aussteigen. Der Zug endet hier." },
    ],
    vocabulary: [
      { de: "das Gleis", en: "platform / track" },
      { de: "die Abfahrt", en: "departure" },
      { de: "die Verspätung", en: "delay" },
      { de: "aussteigen", en: "to get off" },
      { de: "Wir bitten um Ihr Verständnis.", en: "We ask for your understanding." },
    ],
    tips: [
      "Announcements always follow the same order: place, train, time, problem.",
      "Practise numbers 1–60 until you recognise them at full speed.",
    ],
    questions: [
      {
        id: "l-a1-2-q1",
        type: "multiple-choice",
        prompt: "Wie viel Verspätung hat der Zug nach Dresden?",
        options: ["5 Minuten", "10 Minuten", "15 Minuten", "20 Minuten"],
        answerIndex: 2,
        explanation: "„etwa fünfzehn Minuten Verspätung“.",
        skill: "listening",
      },
      {
        id: "l-a1-2-q2",
        type: "multiple-choice",
        prompt: "Von welchem Gleis fährt der Intercity nach München?",
        options: ["Gleis 4", "Gleis 7", "Gleis 9", "Gleis 10"],
        answerIndex: 2,
        explanation: "„fährt heute von Gleis neun, nicht von Gleis sieben“.",
        skill: "listening",
      },
      {
        id: "l-a1-2-q3",
        type: "true-false",
        prompt: "Der Zug in Ansage 3 fährt nach dem Hauptbahnhof weiter.",
        answer: false,
        explanation: "„Der Zug endet hier.“",
        skill: "listening",
      },
    ],
  },
  {
    slug: "termin-beim-arzt",
    level: "A2",
    title: "Termin beim Arzt vereinbaren",
    titleEn: "Making a doctor's appointment",
    scenario: "A phone call with a medical practice. Note the date, time and what to bring.",
    seconds: 75,
    transcript: [
      { speaker: "Praxis", de: "Praxis Dr. Hoffmann, Schneider am Telefon, guten Tag." },
      { speaker: "Karim", de: "Guten Tag, mein Name ist Karim Aziz. Ich würde gern einen Termin vereinbaren." },
      { speaker: "Praxis", de: "Sind Sie schon Patient bei uns?" },
      { speaker: "Karim", de: "Nein, ich bin neu hier. Ich habe seit einer Woche starke Rückenschmerzen." },
      { speaker: "Praxis", de: "Verstehe. Wir hätten am Donnerstag um zehn Uhr dreißig etwas frei, oder am Freitag um sechzehn Uhr." },
      { speaker: "Karim", de: "Donnerstag passt mir besser. Am Freitag muss ich arbeiten." },
      { speaker: "Praxis", de: "Gut, dann notiere ich Donnerstag, den achtzehnten, um zehn Uhr dreißig. Bringen Sie bitte Ihre Versichertenkarte und, wenn möglich, alte Befunde mit." },
      { speaker: "Karim", de: "Alles klar. Muss ich früher da sein?" },
      { speaker: "Praxis", de: "Kommen Sie bitte zehn Minuten vorher, dann füllen Sie noch einen Bogen aus." },
      { speaker: "Karim", de: "Vielen Dank. Auf Wiederhören." },
    ],
    vocabulary: [
      { de: "einen Termin vereinbaren", en: "to arrange an appointment" },
      { de: "die Versichertenkarte", en: "health insurance card" },
      { de: "der Befund", en: "medical report/finding" },
      { de: "der Bogen (Formular)", en: "form" },
      { de: "Das passt mir.", en: "That suits me." },
    ],
    tips: [
      "Note the two options offered and which one is chosen — a classic trap.",
      "Formal phone German: Auf Wiederhören, not Auf Wiedersehen.",
    ],
    questions: [
      {
        id: "l-a2-1-q1",
        type: "multiple-choice",
        prompt: "Wann ist der Termin?",
        options: ["Donnerstag 10:30", "Freitag 16:00", "Donnerstag 16:00", "Freitag 10:30"],
        answerIndex: 0,
        explanation: "Karim wählt Donnerstag, weil er am Freitag arbeitet.",
        skill: "listening",
      },
      {
        id: "l-a2-1-q2",
        type: "multiple-choice",
        prompt: "Was soll Karim mitbringen?",
        options: [
          "Nur Geld",
          "Versichertenkarte und alte Befunde",
          "Einen Ausweis und ein Foto",
          "Ein Rezept",
        ],
        answerIndex: 1,
        explanation: "„Bringen Sie bitte Ihre Versichertenkarte und … alte Befunde mit.“",
        skill: "listening",
      },
      {
        id: "l-a2-1-q3",
        type: "fill-blank",
        prompt: "Ergänzen Sie die höfliche Formulierung.",
        sentence: "Ich ___ gern einen Termin ___.",
        answers: [["würde"], ["vereinbaren"]],
        explanation: "Konjunktiv II für höfliche Wünsche.",
        skill: "listening",
      },
    ],
  },
  {
    slug: "wegbeschreibung-kollege",
    level: "A2",
    title: "Wegbeschreibung zum Betrieb",
    titleEn: "Directions to the company",
    scenario: "A colleague explains how to get to the workshop on the first day.",
    seconds: 70,
    transcript: [
      { speaker: "Frau Vogt", de: "Sie kommen mit der Straßenbahn, richtig? Dann steigen Sie an der Haltestelle Industriestraße aus." },
      { speaker: "Karim", de: "Ja, Linie zwölf. Und dann?" },
      { speaker: "Frau Vogt", de: "Gehen Sie geradeaus bis zur Ampel, dann rechts in die Hafenstraße. Nach etwa zweihundert Metern sehen Sie links ein großes graues Gebäude." },
      { speaker: "Karim", de: "Ist das schon die Werkstatt?" },
      { speaker: "Frau Vogt", de: "Nein, das ist das Lager. Die Werkstatt ist direkt dahinter, im Hof. Der Eingang ist neben dem blauen Tor." },
      { speaker: "Karim", de: "Und wo finde ich Sie?" },
      { speaker: "Frau Vogt", de: "Im ersten Stock, Zimmer einhundertzwölf. Kommen Sie bitte um sieben Uhr fünfzehn, damit wir vor der Besprechung noch Zeit haben." },
    ],
    vocabulary: [
      { de: "die Haltestelle", en: "stop (bus/tram)" },
      { de: "das Lager", en: "warehouse" },
      { de: "der Hof", en: "yard, courtyard" },
      { de: "das Tor", en: "gate" },
      { de: "die Besprechung", en: "meeting" },
    ],
    tips: [
      "Directions use accusative for movement: in die Hafenstraße.",
      "Listen for negations: „Nein, das ist das Lager“ changes the answer.",
    ],
    questions: [
      {
        id: "l-a2-2-q1",
        type: "multiple-choice",
        prompt: "Wo ist die Werkstatt?",
        options: [
          "Im grauen Gebäude an der Straße",
          "Im Hof hinter dem Lager",
          "Im ersten Stock",
          "Neben der Haltestelle",
        ],
        answerIndex: 1,
        explanation: "„Die Werkstatt ist direkt dahinter, im Hof.“",
        skill: "listening",
      },
      {
        id: "l-a2-2-q2",
        type: "multiple-choice",
        prompt: "Wann soll Karim kommen?",
        options: ["7:00", "7:15", "7:50", "8:15"],
        answerIndex: 1,
        explanation: "„um sieben Uhr fünfzehn“.",
        skill: "listening",
      },
      {
        id: "l-a2-2-q3",
        type: "order",
        prompt: "Bringen Sie die Wegbeschreibung in die richtige Reihenfolge.",
        tokens: ["Haltestelle Industriestraße", "geradeaus bis zur Ampel", "rechts in die Hafenstraße", "200 Meter", "Hof hinter dem Lager"],
        answer: "Haltestelle Industriestraße geradeaus bis zur Ampel rechts in die Hafenstraße 200 Meter Hof hinter dem Lager",
        explanation: "Die Reihenfolge folgt dem Gespräch.",
        skill: "listening",
      },
    ],
  },
  {
    slug: "radiobeitrag-wohnen",
    level: "B1",
    title: "Radiobeitrag: Wohnungssuche in Großstädten",
    titleEn: "Radio feature: looking for a flat in big cities",
    scenario: "A short radio feature with an interview. Listen for causes, figures and advice.",
    seconds: 110,
    transcript: [
      { speaker: "Moderatorin", de: "Wohnungssuche in deutschen Großstädten – für viele ein Vollzeitjob. Unsere Reporterin hat mit einer Beraterin des Mietervereins gesprochen." },
      { speaker: "Beraterin", de: "Das größte Problem ist nicht der Preis allein, sondern die Konkurrenz. Auf eine Wohnung kommen in München oder Frankfurt oft mehr als hundert Bewerbungen." },
      { speaker: "Reporterin", de: "Was empfehlen Sie den Suchenden?" },
      { speaker: "Beraterin", de: "Erstens: Unterlagen vorbereiten. Gehaltsnachweise, Schufa-Auskunft und eine Mietschuldenfreiheitsbescheinigung sollten Sie als PDF bereithalten. Zweitens: schnell reagieren, am besten innerhalb einer Stunde." },
      { speaker: "Reporterin", de: "Und wenn man neu in Deutschland ist?" },
      { speaker: "Beraterin", de: "Dann ist ein Bürge hilfreich, oder eine Bestätigung vom Arbeitgeber. Viele Vermieter akzeptieren auch eine Kaution über drei Monatsmieten statt weiterer Nachweise." },
      { speaker: "Moderatorin", de: "Ein letzter Tipp?" },
      { speaker: "Beraterin", de: "Suchen Sie auch am Stadtrand. Mit guter Bahnverbindung sind zwanzig Minuten mehr Fahrzeit oft zweihundert Euro weniger Miete." },
    ],
    vocabulary: [
      { de: "die Konkurrenz", en: "competition" },
      { de: "der Gehaltsnachweis", en: "proof of income" },
      { de: "die Schufa-Auskunft", en: "credit report" },
      { de: "der Bürge", en: "guarantor" },
      { de: "die Kaution", en: "deposit" },
      { de: "der Stadtrand", en: "outskirts" },
    ],
    tips: [
      "In B1 listening, note enumerations: Erstens … Zweitens …",
      "Numbers often appear as comparisons: 20 Minuten mehr = 200 Euro weniger.",
    ],
    questions: [
      {
        id: "l-b1-1-q1",
        type: "multiple-choice",
        prompt: "Was ist laut Beraterin das größte Problem?",
        options: ["Der Preis", "Die Konkurrenz", "Die Lage", "Die Vermieter"],
        answerIndex: 1,
        explanation: "„nicht der Preis allein, sondern die Konkurrenz“.",
        skill: "listening",
      },
      {
        id: "l-b1-1-q2",
        type: "multiple-choice",
        prompt: "Wie schnell soll man auf eine Anzeige reagieren?",
        options: ["Innerhalb eines Tages", "Innerhalb einer Stunde", "Innerhalb einer Woche", "Am Wochenende"],
        answerIndex: 1,
        explanation: "„am besten innerhalb einer Stunde“.",
        skill: "listening",
      },
      {
        id: "l-b1-1-q3",
        type: "multiple-choice",
        prompt: "Welchen Vorteil hat der Stadtrand?",
        options: [
          "Bessere Schulen",
          "Weniger Miete bei guter Bahnverbindung",
          "Mehr Konkurrenz",
          "Keine Kaution",
        ],
        answerIndex: 1,
        explanation: "Letzter Beitrag der Beraterin.",
        skill: "listening",
      },
      {
        id: "l-b1-1-q4",
        type: "dictation",
        prompt: "Schreiben Sie den Tipp, den Sie hören.",
        audioText: "Suchen Sie auch am Stadtrand.",
        answers: ["Suchen Sie auch am Stadtrand.", "Suchen Sie auch am Stadtrand"],
        explanation: "Imperativ mit Sie.",
        skill: "listening",
      },
    ],
  },
  {
    slug: "telefonat-krankmeldung",
    level: "B1",
    title: "Telefonat: Krankmeldung im Betrieb",
    titleEn: "Phone call: reporting sick at work",
    scenario: "Reporting sick correctly is a real-life skill. Listen for the rules mentioned.",
    seconds: 80,
    transcript: [
      { speaker: "Karim", de: "Guten Morgen, Frau Vogt, hier ist Karim Aziz. Leider muss ich mich krankmelden." },
      { speaker: "Frau Vogt", de: "Guten Morgen, Herr Aziz. Was fehlt Ihnen denn?" },
      { speaker: "Karim", de: "Ich habe Fieber und starke Halsschmerzen. Ich gehe heute zum Arzt." },
      { speaker: "Frau Vogt", de: "Gute Besserung. Denken Sie daran: Ab dem vierten Tag brauchen wir eine Bescheinigung vom Arzt, bei uns im Betrieb aber bitte schon ab dem ersten Tag." },
      { speaker: "Karim", de: "Verstanden. Soll ich die Bescheinigung per E-Mail schicken?" },
      { speaker: "Frau Vogt", de: "Ja, an die Personalabteilung, und mich setzen Sie bitte in cc. Falls Sie länger ausfallen, melden Sie sich am Freitag noch einmal." },
      { speaker: "Karim", de: "Mache ich. Vielen Dank für Ihr Verständnis." },
    ],
    vocabulary: [
      { de: "sich krankmelden", en: "to report sick" },
      { de: "Was fehlt Ihnen?", en: "What's wrong with you?" },
      { de: "die Bescheinigung", en: "certificate, note" },
      { de: "ausfallen", en: "to be absent, to be off" },
      { de: "Gute Besserung!", en: "Get well soon!" },
    ],
    tips: [
      "Report sick before your shift starts, by phone if possible.",
      "Note the difference between the legal rule and the company rule.",
    ],
    questions: [
      {
        id: "l-b1-2-q1",
        type: "multiple-choice",
        prompt: "Ab wann verlangt dieser Betrieb eine Bescheinigung?",
        options: ["Ab dem 1. Tag", "Ab dem 3. Tag", "Ab dem 4. Tag", "Nie"],
        answerIndex: 0,
        explanation: "Gesetzlich ab dem 4. Tag, im Betrieb schon ab dem 1. Tag.",
        skill: "listening",
      },
      {
        id: "l-b1-2-q2",
        type: "multiple-choice",
        prompt: "Wohin schickt Karim die Bescheinigung?",
        options: ["An Frau Vogt allein", "An die Personalabteilung, Frau Vogt in cc", "An den Betriebsrat", "An die Krankenkasse"],
        answerIndex: 1,
        explanation: "„an die Personalabteilung, und mich setzen Sie bitte in cc“.",
        skill: "listening",
      },
      {
        id: "l-b1-2-q3",
        type: "speaking",
        prompt: "Melden Sie sich selbst krank. Sprechen Sie den Anruf.",
        target: "Guten Morgen, hier ist Karim Aziz. Leider muss ich mich heute krankmelden, ich habe Fieber.",
        translation: "Good morning, this is Karim Aziz. Unfortunately I have to report sick today, I have a fever.",
        tips: ["Name zuerst", "Grund kurz nennen", "Arztbesuch ankündigen"],
        skill: "speaking",
      },
    ],
  },
  {
    slug: "vortrag-digitalisierung",
    level: "B2",
    title: "Vortrag: Digitalisierung im Handwerk",
    titleEn: "Lecture: digitalisation in the trades",
    scenario: "A short lecture excerpt with argumentation, statistics and a concluding recommendation.",
    seconds: 130,
    transcript: [
      { speaker: "Referent", de: "Meine Damen und Herren, ich möchte heute drei Thesen zur Digitalisierung im Handwerk vorstellen." },
      { speaker: "Referent", de: "Erste These: Die Digitalisierung ersetzt keine Handwerker, sie verändert deren Aufgaben. Wer heute eine Heizungsanlage installiert, konfiguriert zugleich eine Software und erklärt sie dem Kunden." },
      { speaker: "Referent", de: "Zweite These: Der größte Engpass ist nicht die Technik, sondern die Qualifizierung. Nach unserer Erhebung geben rund sechzig Prozent der Betriebe an, dass ihnen Zeit für Weiterbildung fehle." },
      { speaker: "Referent", de: "Dritte These: Kleine Betriebe profitieren überproportional, sofern sie kooperieren. Gemeinsame Einkaufsplattformen und geteilte Software senken die Kosten erheblich." },
      { speaker: "Referent", de: "Daraus ergibt sich eine klare Empfehlung: Investieren Sie zuerst in Menschen, dann in Geräte. Ein digitales Werkzeug, das niemand bedienen kann, ist teurer als gar kein Werkzeug." },
    ],
    vocabulary: [
      { de: "die These", en: "thesis, claim" },
      { de: "der Engpass", en: "bottleneck" },
      { de: "die Erhebung", en: "survey" },
      { de: "überproportional", en: "disproportionately" },
      { de: "sofern", en: "provided that" },
      { de: "bedienen", en: "to operate (a machine)" },
    ],
    tips: [
      "Structure markers (Erste These, Daraus ergibt sich) tell you what comes next.",
      "Reported speech with Konjunktiv I (fehle) signals someone else's statement.",
    ],
    questions: [
      {
        id: "l-b2-1-q1",
        type: "multiple-choice",
        prompt: "Was sagt die erste These?",
        options: [
          "Handwerker werden ersetzt.",
          "Die Aufgaben der Handwerker verändern sich.",
          "Software ist unnötig.",
          "Kunden brauchen keine Erklärung.",
        ],
        answerIndex: 1,
        explanation: "„ersetzt keine Handwerker, sie verändert deren Aufgaben“.",
        skill: "listening",
      },
      {
        id: "l-b2-1-q2",
        type: "multiple-choice",
        prompt: "Wie viele Betriebe nennen fehlende Zeit für Weiterbildung?",
        options: ["16 %", "40 %", "60 %", "76 %"],
        answerIndex: 2,
        explanation: "„rund sechzig Prozent“.",
        skill: "listening",
      },
      {
        id: "l-b2-1-q3",
        type: "multiple-choice",
        prompt: "Welche Empfehlung gibt der Referent?",
        options: [
          "Erst Geräte, dann Personal",
          "Erst in Menschen investieren, dann in Geräte",
          "Keine Investitionen",
          "Nur große Betriebe sollen investieren",
        ],
        answerIndex: 1,
        explanation: "Letzter Satz.",
        skill: "listening",
      },
      {
        id: "l-b2-1-q4",
        type: "writing",
        prompt: "Fassen Sie den Vortrag in drei Sätzen zusammen.",
        minWords: 45,
        checklist: ["alle drei Thesen", "eine Zahl korrekt", "die Empfehlung"],
        sampleAnswer:
          "Der Referent argumentiert, die Digitalisierung ersetze Handwerker nicht, sondern verändere ihre Aufgaben. Als größten Engpass nennt er die Qualifizierung, denn etwa sechzig Prozent der Betriebe hätten keine Zeit für Weiterbildung. Kleine Betriebe könnten besonders profitieren, wenn sie kooperieren; deshalb empfiehlt er, zuerst in Menschen und erst danach in Geräte zu investieren.",
        skill: "writing",
      },
    ],
  },
  {
    slug: "diskussion-arbeitszeit",
    level: "B2",
    title: "Diskussion: Vier-Tage-Woche",
    titleEn: "Discussion: the four-day week",
    scenario: "Three speakers discuss a shorter working week. Identify each position and the arguments.",
    seconds: 120,
    transcript: [
      { speaker: "Moderator", de: "Vier Tage arbeiten, fünf Tage bezahlt bekommen – realistisch oder Wunschdenken? Frau Kaya, Sie sind dafür." },
      { speaker: "Frau Kaya", de: "Ganz klar. Pilotprojekte zeigen, dass die Produktivität kaum sinkt, die Krankheitstage aber deutlich zurückgehen. Wer erholt ist, arbeitet konzentrierter." },
      { speaker: "Herr Brandt", de: "Für Büroberufe mag das gelten. In der Pflege oder in der Produktion lässt sich Arbeit nicht einfach verdichten. Dort bedeutet ein Tag weniger schlicht: weniger Versorgung oder mehr Personal, das wir nicht haben." },
      { speaker: "Frau Kaya", de: "Deshalb plädiere ich für branchenspezifische Modelle, nicht für eine Regel für alle." },
      { speaker: "Herr Brandt", de: "Damit könnte ich leben, sofern die Finanzierung geklärt ist." },
      { speaker: "Moderator", de: "Frau Ott, Sie forschen dazu. Was sagen die Daten?" },
      { speaker: "Frau Ott", de: "Die Ergebnisse sind ermutigend, aber die Studien sind meist kurz und freiwillig. Man sollte daraus keine allgemeinen Schlüsse ziehen, ohne die Branche zu berücksichtigen." },
    ],
    vocabulary: [
      { de: "das Wunschdenken", en: "wishful thinking" },
      { de: "verdichten", en: "to condense, compress" },
      { de: "plädieren für", en: "to argue in favour of" },
      { de: "ermutigend", en: "encouraging" },
      { de: "Schlüsse ziehen", en: "to draw conclusions" },
    ],
    tips: [
      "Match speaker to position before listening for details.",
      "Hedging language (mag gelten, sollte man nicht) marks a cautious position.",
    ],
    questions: [
      {
        id: "l-b2-2-q1",
        type: "match",
        prompt: "Ordnen Sie die Positionen zu.",
        pairs: [
          { left: "Frau Kaya", right: "dafür, aber branchenspezifisch" },
          { left: "Herr Brandt", right: "skeptisch wegen Pflege und Produktion" },
          { left: "Frau Ott", right: "vorsichtig: Datenlage begrenzt" },
        ],
        explanation: "Jede Person nennt ihre Position explizit.",
        skill: "listening",
      },
      {
        id: "l-b2-2-q2",
        type: "multiple-choice",
        prompt: "Welches Argument nennt Frau Kaya zuerst?",
        options: [
          "Höhere Löhne",
          "Produktivität sinkt kaum, Krankheitstage gehen zurück",
          "Mehr Freizeit für Familien",
          "Weniger Personalkosten",
        ],
        answerIndex: 1,
        explanation: "Erste Wortmeldung von Frau Kaya.",
        skill: "listening",
      },
      {
        id: "l-b2-2-q3",
        type: "speaking",
        prompt: "Nehmen Sie Stellung: Sind Sie für oder gegen die Vier-Tage-Woche? Begründen Sie mit zwei Argumenten.",
        target:
          "Ich bin grundsätzlich dafür, allerdings nur branchenspezifisch, weil sich Arbeit in der Pflege nicht verdichten lässt.",
        tips: ["Position klar nennen", "zwei Argumente", "ein Gegenargument einräumen"],
        skill: "speaking",
      },
    ],
  },
];
