import type { ReadingText } from "@/lib/types";

export const readingTexts: ReadingText[] = [
  {
    slug: "steckbrief-nour",
    level: "A1",
    title: "Das bin ich: Nour aus Rabat",
    titleEn: "This is me: Nour from Rabat",
    genre: "Profile",
    minutes: 4,
    intro: "A short self-introduction, the classic first reading text at A1.",
    paragraphs: [
      "Hallo! Ich heiße Nour Benali und ich komme aus Rabat in Marokko. Ich bin 23 Jahre alt und ich bin ledig. Seit acht Monaten wohne ich in Leipzig, in einer kleinen Wohnung im Stadtzentrum. Die Wohnung hat zwei Zimmer, eine Küche und ein Bad. Die Miete ist nicht sehr hoch: 480 Euro warm.",
      "Ich lerne Deutsch, denn ich möchte eine Ausbildung als Pflegefachkraft machen. Mein Kurs beginnt um neun Uhr und endet um halb eins. Am Nachmittag arbeite ich in einem Café. Die Arbeit ist nicht schwer, aber ich stehe viel.",
      "Meine Familie wohnt noch in Marokko. Ich habe zwei Brüder und eine Schwester. Am Sonntag telefoniere ich immer mit meinen Eltern. Ich vermisse sie sehr, aber ich habe hier auch Freunde. Meine Freundin Lena kommt aus Leipzig. Wir gehen oft zusammen ins Kino oder wir kochen zu Hause.",
      "Am Wochenende habe ich frei. Dann lerne ich Vokabeln, ich mache Sport und ich schlafe lange. Ich bin sehr müde, aber ich bin auch glücklich. In zwei Jahren spreche ich sehr gut Deutsch — das ist mein Ziel.",
    ],
    glossary: [
      { de: "ledig", en: "single, unmarried" },
      { de: "die Miete", en: "the rent" },
      { de: "warm (Miete)", en: "including heating/utilities" },
      { de: "die Pflegefachkraft", en: "qualified nurse / carer" },
      { de: "vermissen", en: "to miss (someone)" },
      { de: "das Ziel", en: "the goal" },
    ],
    grammarHighlights: [
      { label: "Präsens", note: "All verbs are in the present tense: heiße, komme, wohne, lerne.", grammar: "praesens-regelmaessig" },
      { label: "seit + Dativ", note: "seit acht Monaten — duration with the dative.", grammar: "dativ" },
      { label: "Wortstellung", note: "Am Sonntag telefoniere ich … — the verb stays in position 2.", grammar: "wortstellung-fragen" },
    ],
    questions: [
      {
        id: "r-a1-1-q1",
        type: "multiple-choice",
        prompt: "Woher kommt Nour?",
        options: ["Aus Leipzig", "Aus Rabat", "Aus Berlin", "Aus Tunis"],
        answerIndex: 1,
        explanation: "Im ersten Satz: „ich komme aus Rabat in Marokko“.",
        skill: "reading",
      },
      {
        id: "r-a1-1-q2",
        type: "true-false",
        prompt: "Nour ist verheiratet.",
        answer: false,
        explanation: "Sie schreibt: „ich bin ledig“.",
        skill: "reading",
      },
      {
        id: "r-a1-1-q3",
        type: "multiple-choice",
        prompt: "Warum lernt Nour Deutsch?",
        options: [
          "Sie möchte in Marokko studieren.",
          "Sie möchte eine Ausbildung als Pflegefachkraft machen.",
          "Sie möchte in einem Café arbeiten.",
          "Sie möchte ihre Freundin verstehen.",
        ],
        answerIndex: 1,
        explanation: "„denn ich möchte eine Ausbildung als Pflegefachkraft machen“.",
        skill: "reading",
      },
      {
        id: "r-a1-1-q4",
        type: "fill-blank",
        prompt: "Ergänzen Sie aus dem Text.",
        sentence: "Die Miete kostet ___ Euro warm und der Kurs beginnt um ___ Uhr.",
        answers: [["480"], ["neun", "9"]],
        explanation: "480 Euro warm, Kursbeginn 9 Uhr.",
        skill: "reading",
      },
    ],
  },
  {
    slug: "wohnungsanzeigen",
    level: "A1",
    title: "Vier Wohnungsanzeigen",
    titleEn: "Four flat adverts",
    genre: "Adverts",
    minutes: 5,
    intro: "Scanning short adverts for specific information — a typical Goethe A1 reading task.",
    paragraphs: [
      "A) 2-Zimmer-Wohnung in Leipzig-Süd, 52 m², Balkon, 3. Stock ohne Aufzug. Miete: 520 € kalt + 130 € Nebenkosten. Frei ab 1. September. Keine Haustiere. Kontakt: Hausverwaltung Meyer, Tel. 0341 55 21 90.",
      "B) Möbliertes Zimmer in einer WG (3 Personen), 18 m², Internet inklusive. 350 € warm. Zentral, 5 Minuten zur Universität. Nur für Studentinnen. E-Mail: wg-plagwitz@mail.de",
      "C) Kleine Wohnung im Erdgeschoss, 40 m², Küche neu, Waschmaschine vorhanden. 610 € warm. Haustiere erlaubt. Besichtigung am Samstag um 14 Uhr. Bitte anrufen: 0176 33 44 55 6.",
      "D) 3-Zimmer-Wohnung mit Garten, 78 m², ruhige Lage am Stadtrand, Bus 74 direkt vor dem Haus. 890 € warm, Kaution: 2 Monatsmieten. Frei ab sofort. Nichtraucher bevorzugt.",
    ],
    glossary: [
      { de: "kalt / warm", en: "rent without / with utilities" },
      { de: "die Nebenkosten", en: "utility costs" },
      { de: "der Aufzug", en: "lift, elevator" },
      { de: "möbliert", en: "furnished" },
      { de: "die WG (Wohngemeinschaft)", en: "shared flat" },
      { de: "die Kaution", en: "deposit" },
      { de: "die Besichtigung", en: "viewing" },
    ],
    grammarHighlights: [
      { label: "Nominalstil", note: "Adverts drop verbs: „Frei ab sofort“ instead of „Die Wohnung ist ab sofort frei“." },
      { label: "Präpositionen", note: "im Erdgeschoss, am Stadtrand, zur Universität — dative for position.", grammar: "wechselpraepositionen" },
    ],
    questions: [
      {
        id: "r-a1-2-q1",
        type: "multiple-choice",
        prompt: "Sie haben eine Katze. Welche Wohnung passt?",
        options: ["A", "B", "C", "D"],
        answerIndex: 2,
        explanation: "Nur in Anzeige C steht: „Haustiere erlaubt“.",
        skill: "reading",
      },
      {
        id: "r-a1-2-q2",
        type: "multiple-choice",
        prompt: "Welche Wohnung ist am günstigsten?",
        options: ["A", "B", "C", "D"],
        answerIndex: 1,
        explanation: "Das WG-Zimmer kostet 350 € warm.",
        skill: "reading",
      },
      {
        id: "r-a1-2-q3",
        type: "true-false",
        prompt: "In Wohnung A gibt es einen Aufzug.",
        answer: false,
        explanation: "„3. Stock ohne Aufzug“.",
        skill: "reading",
      },
      {
        id: "r-a1-2-q4",
        type: "multiple-choice",
        prompt: "Sie brauchen eine Wohnung für eine Familie mit zwei Kindern und einem Garten. Welche Anzeige?",
        options: ["A", "B", "C", "D"],
        answerIndex: 3,
        explanation: "D: 3 Zimmer, 78 m², mit Garten.",
        skill: "reading",
      },
    ],
  },
  {
    slug: "erster-arbeitstag",
    level: "A2",
    title: "Mein erster Arbeitstag",
    titleEn: "My first day at work",
    genre: "Blog post",
    minutes: 6,
    intro: "A short blog entry in the Perfekt — ideal for A2 reading and for talking about the past.",
    paragraphs: [
      "Gestern hatte ich meinen ersten Arbeitstag in der Bäckerei Sommer. Ich bin um Viertel vor fünf aufgewacht, weil ich schon um halb sechs anfangen musste. Draußen war es noch dunkel und sehr kalt. Ich bin mit dem Fahrrad zur Arbeit gefahren, denn die Straßenbahn fährt so früh nur alle 20 Minuten.",
      "Meine Chefin, Frau Sommer, hat mich freundlich begrüßt und mir alles gezeigt: den Ofen, die Kasse, das Lager und den Pausenraum. Danach habe ich eine weiße Schürze und eine Mütze bekommen. Am Anfang habe ich nur zugeschaut, später durfte ich schon Brötchen verkaufen.",
      "Ein Kunde hat sehr schnell gesprochen und ich habe ihn zuerst nicht verstanden. Ich habe gesagt: „Entschuldigung, können Sie das bitte wiederholen?“ Er hat gelächelt und langsamer gesprochen. Das war eine wichtige Erfahrung: Man darf ruhig nachfragen.",
      "Um halb eins war Feierabend. Ich war müde, aber sehr zufrieden. Frau Sommer hat gesagt, dass ich schnell lerne. Nächste Woche arbeite ich vier Tage. Ich freue mich darauf, weil ich dort viel Deutsch spreche und weil die Kollegen nett sind.",
    ],
    glossary: [
      { de: "die Schürze", en: "apron" },
      { de: "das Lager", en: "storeroom" },
      { de: "zuschauen", en: "to watch" },
      { de: "nachfragen", en: "to ask again, follow up" },
      { de: "der Feierabend", en: "end of the working day" },
      { de: "zufrieden", en: "satisfied" },
    ],
    grammarHighlights: [
      { label: "Perfekt", note: "bin aufgewacht, habe bekommen, hat gesprochen — sein for movement, haben for the rest.", grammar: "perfekt" },
      { label: "Nebensätze", note: "…, weil ich schon um halb sechs anfangen musste — verb at the end.", grammar: "nebensaetze-a2" },
      { label: "Präteritum", note: "hatte, war, durfte — these verbs prefer the Präteritum even in speech.", grammar: "praeteritum" },
    ],
    questions: [
      {
        id: "r-a2-1-q1",
        type: "multiple-choice",
        prompt: "Wann hat die Arbeit angefangen?",
        options: ["Um 4:45", "Um 5:30", "Um 6:00", "Um 12:30"],
        answerIndex: 1,
        explanation: "„weil ich schon um halb sechs anfangen musste“ = 5:30.",
        skill: "reading",
      },
      {
        id: "r-a2-1-q2",
        type: "multiple-choice",
        prompt: "Warum ist er mit dem Fahrrad gefahren?",
        options: [
          "Das Fahrrad ist schneller als das Auto.",
          "Die Straßenbahn fährt so früh selten.",
          "Er hat keine Fahrkarte.",
          "Die Bäckerei ist sehr weit weg.",
        ],
        answerIndex: 1,
        explanation: "„denn die Straßenbahn fährt so früh nur alle 20 Minuten“.",
        skill: "reading",
      },
      {
        id: "r-a2-1-q3",
        type: "true-false",
        prompt: "Er hat den Kunden sofort verstanden.",
        answer: false,
        explanation: "„habe ich ihn zuerst nicht verstanden“.",
        skill: "reading",
      },
      {
        id: "r-a2-1-q4",
        type: "fill-blank",
        prompt: "Wie fragt man höflich nach?",
        sentence: "Entschuldigung, können Sie das bitte ___?",
        answers: [["wiederholen"]],
        explanation: "Eine der wichtigsten Redewendungen für den Alltag.",
        skill: "reading",
      },
    ],
  },
  {
    slug: "mietwohnung-hausordnung",
    level: "A2",
    title: "Die Hausordnung",
    titleEn: "House rules",
    genre: "Official notice",
    minutes: 5,
    intro: "Authentic-style house rules: modal verbs, passive-like instructions and everyday bureaucracy.",
    paragraphs: [
      "Sehr geehrte Mieterinnen und Mieter, bitte beachten Sie die folgenden Regeln, damit alle Bewohner sich im Haus wohlfühlen.",
      "1. Ruhezeiten: Von 22:00 bis 6:00 Uhr sowie sonntags und an Feiertagen ganztägig muss es im Haus ruhig sein. In dieser Zeit dürfen Sie keine Waschmaschine benutzen und nicht laut Musik hören.",
      "2. Müll: Der Müll muss getrennt werden. Papier gehört in die blaue Tonne, Verpackungen in den gelben Sack, Bioabfall in die braune Tonne. Glas bringen Sie bitte zum Container an der Ecke.",
      "3. Treppenhaus: Das Treppenhaus wird jede Woche von einer Firma gereinigt. Fahrräder und Kinderwagen dürfen nicht im Treppenhaus stehen, weil es ein Fluchtweg ist.",
      "4. Reparaturen: Bei Schäden informieren Sie bitte sofort die Hausverwaltung (Tel. 0341 55 21 90). Reparaturen dürfen Sie nicht selbst beauftragen.",
      "Vielen Dank für Ihr Verständnis. Ihre Hausverwaltung Meyer",
    ],
    glossary: [
      { de: "die Ruhezeit", en: "quiet hours" },
      { de: "der Feiertag", en: "public holiday" },
      { de: "trennen", en: "to separate" },
      { de: "die Verpackung", en: "packaging" },
      { de: "der Fluchtweg", en: "escape route" },
      { de: "die Hausverwaltung", en: "property management" },
      { de: "beauftragen", en: "to commission, order" },
    ],
    grammarHighlights: [
      { label: "Modalverben", note: "muss ruhig sein, dürfen nicht benutzen — obligation and prohibition.", grammar: "modalverben" },
      { label: "Passiv", note: "Der Müll muss getrennt werden. Das Treppenhaus wird gereinigt.", grammar: "passiv" },
    ],
    questions: [
      {
        id: "r-a2-2-q1",
        type: "multiple-choice",
        prompt: "Wann darf man nicht waschen?",
        options: ["Samstags", "Zwischen 22 und 6 Uhr", "Morgens vor 8 Uhr", "Immer erlaubt"],
        answerIndex: 1,
        explanation: "Ruhezeit von 22:00 bis 6:00 und sonntags.",
        skill: "reading",
      },
      {
        id: "r-a2-2-q2",
        type: "multiple-choice",
        prompt: "Wohin kommt Papier?",
        options: ["In den gelben Sack", "In die braune Tonne", "In die blaue Tonne", "Zum Container"],
        answerIndex: 2,
        explanation: "„Papier gehört in die blaue Tonne“.",
        skill: "reading",
      },
      {
        id: "r-a2-2-q3",
        type: "true-false",
        prompt: "Man darf Fahrräder im Treppenhaus parken.",
        answer: false,
        explanation: "Das Treppenhaus ist ein Fluchtweg.",
        skill: "reading",
      },
      {
        id: "r-a2-2-q4",
        type: "multiple-choice",
        prompt: "Was machen Sie, wenn die Heizung kaputt ist?",
        options: [
          "Selbst einen Handwerker rufen",
          "Die Hausverwaltung informieren",
          "Die Nachbarn fragen",
          "Nichts machen",
        ],
        answerIndex: 1,
        explanation: "„Bei Schäden informieren Sie bitte sofort die Hausverwaltung“.",
        skill: "reading",
      },
    ],
  },
  {
    slug: "ausbildung-in-deutschland",
    level: "B1",
    title: "Ausbildung in Deutschland: das duale System",
    titleEn: "Vocational training in Germany: the dual system",
    genre: "Informational article",
    minutes: 8,
    intro: "A B1 article about the German dual training system — vocabulary you need for the Ausbildung path.",
    paragraphs: [
      "Wer in Deutschland einen Beruf lernen möchte, entscheidet sich häufig für eine duale Ausbildung. „Dual“ bedeutet, dass die Ausbildung an zwei Orten stattfindet: im Betrieb und in der Berufsschule. Drei oder vier Tage pro Woche arbeiten die Auszubildenden – kurz „Azubis“ – im Unternehmen, an den anderen Tagen besuchen sie die Schule, wo sie theoretisches Wissen erwerben.",
      "Ein großer Vorteil ist die Bezahlung. Anders als Studierende bekommen Azubis von Anfang an ein monatliches Gehalt, die sogenannte Ausbildungsvergütung. Sie steigt in jedem Ausbildungsjahr und liegt je nach Branche zwischen etwa 700 und 1.200 Euro. Gleichzeitig sind die Azubis sozialversichert.",
      "Die Ausbildung dauert normalerweise zwei bis dreieinhalb Jahre und endet mit einer Abschlussprüfung vor der Industrie- und Handelskammer oder der Handwerkskammer. Wer die Prüfung besteht, erhält einen Berufsabschluss, der in ganz Deutschland und in vielen anderen Ländern anerkannt wird.",
      "Für internationale Bewerber sind vor allem zwei Dinge wichtig: ausreichende Sprachkenntnisse und die Anerkennung der Schulzeugnisse. Die meisten Betriebe verlangen Deutsch auf dem Niveau B1, im Bereich Pflege und Gesundheit oft B2. Es lohnt sich also, früh mit dem Sprachkurs zu beginnen und schon vor der Bewerbung Fachvokabular zu lernen.",
      "Besonders gesucht werden Fachkräfte in der Pflege, im Handwerk, in der Gastronomie, in der Logistik und in technischen Berufen. Da in vielen Regionen Bewerber fehlen, unterstützen manche Unternehmen ihre neuen Azubis sogar bei der Wohnungssuche und bei Behördengängen. Wer sich früh informiert und die Bewerbung sorgfältig vorbereitet, hat sehr gute Chancen.",
    ],
    glossary: [
      { de: "der Betrieb", en: "company, firm" },
      { de: "der Auszubildende / Azubi", en: "apprentice, trainee" },
      { de: "die Ausbildungsvergütung", en: "training salary" },
      { de: "sozialversichert", en: "covered by social insurance" },
      { de: "die Abschlussprüfung", en: "final examination" },
      { de: "anerkennen", en: "to recognise officially" },
      { de: "der Behördengang", en: "trip to the authorities" },
      { de: "sorgfältig", en: "careful(ly)" },
    ],
    grammarHighlights: [
      { label: "Relativsätze", note: "…, der in ganz Deutschland anerkannt wird — relative pronoun + passive.", grammar: "relativsaetze" },
      { label: "Passiv", note: "Besonders gesucht werden Fachkräfte … — passive with a fronted element.", grammar: "passiv" },
      { label: "Infinitiv mit zu", note: "Es lohnt sich, früh mit dem Sprachkurs zu beginnen.", grammar: "indirekte-fragen" },
    ],
    questions: [
      {
        id: "r-b1-1-q1",
        type: "multiple-choice",
        prompt: "Was bedeutet „dual“ in diesem Text?",
        options: [
          "Die Ausbildung dauert doppelt so lange.",
          "Die Ausbildung findet im Betrieb und in der Berufsschule statt.",
          "Man lernt zwei Berufe gleichzeitig.",
          "Man muss zwei Prüfungen bezahlen.",
        ],
        answerIndex: 1,
        explanation: "„dass die Ausbildung an zwei Orten stattfindet: im Betrieb und in der Berufsschule“.",
        skill: "reading",
      },
      {
        id: "r-b1-1-q2",
        type: "multiple-choice",
        prompt: "Welches Sprachniveau verlangen die meisten Betriebe?",
        options: ["A2", "B1, in der Pflege oft B2", "C1", "Kein Niveau nötig"],
        answerIndex: 1,
        explanation: "„verlangen Deutsch auf dem Niveau B1, im Bereich Pflege und Gesundheit oft B2“.",
        skill: "reading",
      },
      {
        id: "r-b1-1-q3",
        type: "true-false",
        prompt: "Azubis verdienen während der Ausbildung kein Geld.",
        answer: false,
        explanation: "Sie erhalten eine Ausbildungsvergütung von ca. 700–1.200 €.",
        skill: "reading",
      },
      {
        id: "r-b1-1-q4",
        type: "multiple-choice",
        prompt: "Warum helfen manche Firmen bei der Wohnungssuche?",
        options: [
          "Weil es ein Gesetz gibt.",
          "Weil Bewerber in vielen Regionen fehlen.",
          "Weil Wohnungen billig sind.",
          "Weil Azubis kein Geld verdienen.",
        ],
        answerIndex: 1,
        explanation: "„Da in vielen Regionen Bewerber fehlen, unterstützen manche Unternehmen …“.",
        skill: "reading",
      },
      {
        id: "r-b1-1-q5",
        type: "fill-blank",
        prompt: "Ergänzen Sie.",
        sentence: "Die Ausbildung endet mit einer ___ vor der Industrie- und Handelskammer.",
        answers: [["Abschlussprüfung"]],
        explanation: "Siehe Absatz 3.",
        skill: "reading",
      },
    ],
  },
  {
    slug: "leben-in-der-stadt-oder-auf-dem-land",
    level: "B1",
    title: "Stadt oder Land? Zwei Meinungen",
    titleEn: "City or countryside? Two opinions",
    genre: "Forum discussion",
    minutes: 7,
    intro: "Two forum posts with opposing arguments — the perfect model for a B1 opinion essay.",
    paragraphs: [
      "Sabine, 34, Hamburg: Ich könnte mir ein Leben auf dem Land nicht vorstellen. In der Stadt habe ich alles in der Nähe: Arbeit, Ärzte, Kitas, Kino, Restaurants. Ich brauche kein Auto, weil die öffentlichen Verkehrsmittel rund um die Uhr fahren. Natürlich ist die Miete hoch – wir zahlen für 70 Quadratmeter fast 1.300 Euro warm. Aber dafür verliere ich keine Zeit im Stau, und meine Tochter kann zu Fuß zur Schule gehen. Was mich stört, ist der Lärm. Nachts hört man die Straße, und im Sommer ist es in der Wohnung sehr heiß.",
      "Markus, 41, bei Rostock: Wir sind vor fünf Jahren aus der Stadt weggezogen und haben es nicht bereut. Für das Geld, das wir früher für eine Dreizimmerwohnung bezahlt haben, haben wir hier ein Haus mit Garten. Die Kinder spielen draußen, die Luft ist besser und die Nachbarn kennen sich. Allerdings muss ich ehrlich sagen: ohne Auto geht es nicht. Der Bus fährt dreimal am Tag, der nächste Supermarkt ist sechs Kilometer entfernt, und wenn ein Facharzt nötig ist, fahren wir eine Stunde. Wer viel Kultur braucht, wird das Land schnell langweilig finden.",
      "Beide Beiträge zeigen: Es gibt nicht die eine richtige Antwort. Entscheidend ist, welche Nachteile man akzeptieren kann. Wer Ruhe und Platz sucht, ist auf dem Land besser aufgehoben; wer kurze Wege und ein großes Angebot an Freizeitmöglichkeiten schätzt, bleibt lieber in der Stadt.",
    ],
    glossary: [
      { de: "sich etwas vorstellen", en: "to imagine something" },
      { de: "rund um die Uhr", en: "around the clock" },
      { de: "der Stau", en: "traffic jam" },
      { de: "bereuen", en: "to regret" },
      { de: "allerdings", en: "however" },
      { de: "der Facharzt", en: "specialist doctor" },
      { de: "gut aufgehoben sein", en: "to be in good hands / well off" },
    ],
    grammarHighlights: [
      { label: "Konjunktiv II", note: "Ich könnte mir ein Leben auf dem Land nicht vorstellen.", grammar: "konjunktiv-2" },
      { label: "Konnektoren", note: "Natürlich …, aber dafür …; Allerdings … — typical concessive structures.", grammar: "zweiteilige-konnektoren" },
      { label: "Relativsätze", note: "Für das Geld, das wir früher bezahlt haben, …", grammar: "relativsaetze" },
    ],
    questions: [
      {
        id: "r-b1-2-q1",
        type: "multiple-choice",
        prompt: "Was ist für Sabine der größte Nachteil der Stadt?",
        options: ["Die Miete", "Der Lärm", "Die Verkehrsmittel", "Die Schule"],
        answerIndex: 1,
        explanation: "„Was mich stört, ist der Lärm.“",
        skill: "reading",
      },
      {
        id: "r-b1-2-q2",
        type: "multiple-choice",
        prompt: "Welchen Nachteil nennt Markus?",
        options: [
          "Die Nachbarn sind unfreundlich.",
          "Man ist auf ein Auto angewiesen.",
          "Die Häuser sind zu teuer.",
          "Die Luft ist schlecht.",
        ],
        answerIndex: 1,
        explanation: "„ohne Auto geht es nicht“.",
        skill: "reading",
      },
      {
        id: "r-b1-2-q3",
        type: "true-false",
        prompt: "Markus bereut den Umzug aufs Land.",
        answer: false,
        explanation: "„haben es nicht bereut“.",
        skill: "reading",
      },
      {
        id: "r-b1-2-q4",
        type: "writing",
        prompt: "Und Sie? Schreiben Sie Ihre Meinung (Stadt oder Land) mit zwei Argumenten und einem Gegenargument.",
        minWords: 60,
        checklist: [
          "Meinung klar formuliert (Meiner Meinung nach …)",
          "zwei Argumente mit weil oder denn",
          "ein Gegenargument mit obwohl / allerdings",
          "Schluss mit einem Fazit",
        ],
        sampleAnswer:
          "Meiner Meinung nach ist das Leben in der Stadt für junge Menschen besser. Erstens findet man dort leichter eine Arbeit oder einen Ausbildungsplatz, weil es viele Betriebe gibt. Zweitens braucht man kein Auto, denn Busse und Bahnen fahren sehr oft. Allerdings muss man akzeptieren, dass die Mieten hoch sind und dass es abends laut sein kann. Insgesamt finde ich die Vorteile größer als die Nachteile, deshalb möchte ich in einer Stadt wohnen.",
        skill: "writing",
      },
    ],
  },
  {
    slug: "homeoffice-debatte",
    level: "B2",
    title: "Homeoffice: Freiheit oder Falle?",
    titleEn: "Working from home: freedom or trap?",
    genre: "Opinion piece",
    minutes: 9,
    intro: "A B2 opinion article with nominal style, participial attributes and hedged claims.",
    paragraphs: [
      "Kaum ein Thema hat die Arbeitswelt in den letzten Jahren so verändert wie das Homeoffice. Was zunächst als Notlösung eingeführt wurde, gilt heute in vielen Branchen als selbstverständlicher Bestandteil des Arbeitsvertrags. Doch die Begeisterung ist nicht ungeteilt: Während die eine Seite von mehr Autonomie spricht, warnt die andere vor einer schleichenden Entgrenzung von Arbeit und Privatleben.",
      "Für die Beschäftigten liegen die Vorteile auf der Hand. Der Wegfall des täglichen Arbeitswegs spart Zeit und Geld, die Arbeitszeit lässt sich flexibler an familiäre Verpflichtungen anpassen, und wer konzentriert arbeiten möchte, wird zu Hause seltener unterbrochen als in einem Großraumbüro. Untersuchungen deuten darauf hin, dass die Produktivität bei klar definierten Aufgaben sogar steigt.",
      "Kritischer sieht es bei der Zusammenarbeit aus. Informelle Gespräche in der Kaffeeküche, die für den Austausch von Wissen und für das Gefühl der Zugehörigkeit erhebliche Bedeutung haben, fallen weg. Neu eingestellte Kolleginnen und Kollegen, die ihr Team nur über den Bildschirm kennen, brauchen deutlich länger, bis sie sich zugehörig fühlen. Führungskräfte klagen zudem darüber, dass Konflikte in Videokonferenzen später erkannt werden.",
      "Hinzu kommt ein Aspekt, der lange unterschätzt wurde: die ständige Erreichbarkeit. Wer den Laptop im Wohnzimmer stehen lässt, arbeitet abends „nur noch schnell“ weiter. Fachleute empfehlen deshalb klare Regeln – feste Kernarbeitszeiten, ein abgetrennter Arbeitsplatz und das konsequente Abschalten von Benachrichtigungen nach Feierabend.",
      "Man wird also kaum von einem eindeutigen Gewinn oder Verlust sprechen können. Entscheidend dürfte die Mischung sein: Hybride Modelle, bei denen zwei bis drei Präsenztage pro Woche vereinbart werden, verbinden die Konzentration des Homeoffice mit dem sozialen Kapital des Büros. Voraussetzung ist allerdings, dass Unternehmen die dafür nötige Infrastruktur schaffen und dass Beschäftigte lernen, ihre Grenzen selbst zu ziehen.",
    ],
    glossary: [
      { de: "die Notlösung", en: "stopgap solution" },
      { de: "selbstverständlich", en: "taken for granted" },
      { de: "die Entgrenzung", en: "blurring of boundaries" },
      { de: "der Wegfall", en: "elimination, absence" },
      { de: "die Zugehörigkeit", en: "sense of belonging" },
      { de: "die Führungskraft", en: "manager" },
      { de: "die Erreichbarkeit", en: "availability, reachability" },
      { de: "hybride Modelle", en: "hybrid models" },
    ],
    grammarHighlights: [
      { label: "Partizipialattribute", note: "Neu eingestellte Kolleginnen …; die dafür nötige Infrastruktur.", grammar: "partizipialattribute" },
      { label: "Nominalstil", note: "Der Wegfall des täglichen Arbeitswegs spart Zeit — instead of Weil der Arbeitsweg wegfällt …", grammar: "nominalisierung" },
      { label: "Vermutungen", note: "Entscheidend dürfte die Mischung sein — subjective modal.", grammar: "subjektive-modalverben" },
      { label: "Passiversatz", note: "Die Arbeitszeit lässt sich flexibler anpassen.", grammar: "passiversatzformen" },
    ],
    questions: [
      {
        id: "r-b2-1-q1",
        type: "multiple-choice",
        prompt: "Welche Haltung nimmt der Text insgesamt ein?",
        options: [
          "Homeoffice ist eindeutig besser als Büroarbeit.",
          "Homeoffice sollte abgeschafft werden.",
          "Eine Mischform ist am sinnvollsten.",
          "Homeoffice funktioniert nur für Führungskräfte.",
        ],
        answerIndex: 2,
        explanation: "Der letzte Absatz empfiehlt hybride Modelle.",
        skill: "reading",
      },
      {
        id: "r-b2-1-q2",
        type: "multiple-choice",
        prompt: "Was wird als Nachteil für neue Mitarbeitende genannt?",
        options: [
          "Sie verdienen weniger.",
          "Sie brauchen länger, bis sie sich zugehörig fühlen.",
          "Sie bekommen keine Technik.",
          "Sie müssen mehr reisen.",
        ],
        answerIndex: 1,
        explanation: "Absatz 3.",
        skill: "reading",
      },
      {
        id: "r-b2-1-q3",
        type: "multiple-choice",
        prompt: "Was bedeutet „Entgrenzung von Arbeit und Privatleben“?",
        options: [
          "Arbeit und Privatleben werden strikt getrennt.",
          "Die Grenze zwischen beiden verschwimmt.",
          "Man arbeitet im Ausland.",
          "Der Arbeitsvertrag wird gekündigt.",
        ],
        answerIndex: 1,
        explanation: "Grenze + ent- = die Grenze löst sich auf.",
        skill: "reading",
      },
      {
        id: "r-b2-1-q4",
        type: "transform",
        prompt: "Formulieren Sie verbal (Verbalstil).",
        input: "Der Wegfall des täglichen Arbeitswegs spart Zeit.",
        answers: [
          "Weil der tägliche Arbeitsweg wegfällt, spart man Zeit.",
          "Wenn der tägliche Arbeitsweg wegfällt, spart man Zeit.",
        ],
        explanation: "Nominalstil → Nebensatz mit weil/wenn.",
        skill: "grammar",
        grammar: "nominalisierung",
      },
    ],
  },
  {
    slug: "fachkraeftemangel",
    level: "B2",
    title: "Fachkräftemangel: Wer hält das System am Laufen?",
    titleEn: "Skilled labour shortage: who keeps the system running?",
    genre: "Report",
    minutes: 9,
    intro: "A statistics-based report with reported speech and formal connectors.",
    paragraphs: [
      "Nach Angaben des Instituts für Arbeitsmarktforschung fehlen in Deutschland derzeit mehrere Hunderttausend qualifizierte Arbeitskräfte. Besonders betroffen sind die Pflege, das Handwerk, der Bereich Erziehung sowie Berufe in Elektro- und Anlagentechnik. Die Bundesagentur für Arbeit teilte mit, in einigen Regionen bleibe jede zweite Ausbildungsstelle im Handwerk unbesetzt.",
      "Die Ursachen sind vielschichtig. Zum einen gehen die geburtenstarken Jahrgänge in den Ruhestand, zum anderen entscheiden sich immer mehr Schulabgänger für ein Studium statt für eine berufliche Ausbildung. Hinzu kommt, dass das Ansehen mancher Berufe – trotz guter Verdienstmöglichkeiten – als niedrig empfunden wird.",
      "Politik und Wirtschaft setzen daher auf drei Strategien. Erstens soll die Erwerbsbeteiligung im Inland erhöht werden, etwa durch bessere Kinderbetreuung und durch flexible Modelle für ältere Beschäftigte. Zweitens werden Ausbildungswege attraktiver gestaltet: Wer eine Ausbildung abschließt, kann sich anschließend zum Meister oder zum Techniker weiterqualifizieren. Drittens wird gezielt im Ausland angeworben, wobei die Anerkennung ausländischer Abschlüsse beschleunigt werden soll.",
      "Kritiker weisen darauf hin, dass Anwerbung allein nicht ausreiche. Wer nach Deutschland komme, brauche Sprachkurse, Wohnraum und eine Perspektive für die Familie; andernfalls verlasse ein Teil der Zugewanderten das Land nach wenigen Jahren wieder. Untersuchungen zeigen, dass die Bleibewahrscheinlichkeit deutlich steigt, wenn im ersten Jahr eine intensive Sprachförderung und eine betriebliche Begleitung angeboten werden.",
      "Für Bewerberinnen und Bewerber aus dem Ausland ergibt sich daraus eine klare Empfehlung: Sprachkenntnisse frühzeitig aufbauen, Unterlagen vollständig und beglaubigt vorbereiten und den Kontakt zu Kammern und Betrieben aktiv suchen. Wer B2 erreicht, hat auf dem deutschen Arbeitsmarkt derzeit ausgesprochen gute Aussichten.",
    ],
    glossary: [
      { de: "der Fachkräftemangel", en: "shortage of skilled workers" },
      { de: "unbesetzt bleiben", en: "to remain unfilled" },
      { de: "der Ruhestand", en: "retirement" },
      { de: "das Ansehen", en: "reputation, prestige" },
      { de: "die Erwerbsbeteiligung", en: "labour force participation" },
      { de: "anwerben", en: "to recruit" },
      { de: "beglaubigt", en: "certified (document)" },
      { de: "die Aussichten", en: "prospects" },
    ],
    grammarHighlights: [
      { label: "Indirekte Rede", note: "…, in einigen Regionen bleibe jede zweite Stelle unbesetzt; Wer komme, brauche …", grammar: "konjunktiv-1-indirekte-rede" },
      { label: "Passiv", note: "wird gezielt im Ausland angeworben; soll beschleunigt werden.", grammar: "passiv" },
      { label: "Nominalstil", note: "Nach Angaben des Instituts …; trotz guter Verdienstmöglichkeiten.", grammar: "nominalisierung" },
    ],
    questions: [
      {
        id: "r-b2-2-q1",
        type: "multiple-choice",
        prompt: "Welche drei Strategien nennt der Text?",
        options: [
          "Löhne senken, Studium fördern, Werbung schalten",
          "Erwerbsbeteiligung erhöhen, Ausbildung attraktiver machen, im Ausland anwerben",
          "Arbeitszeit verlängern, Steuern erhöhen, Renten kürzen",
          "Schulen schließen, Kammern abschaffen, Anerkennung stoppen",
        ],
        answerIndex: 1,
        explanation: "Absatz 3: Erstens … Zweitens … Drittens …",
        skill: "reading",
      },
      {
        id: "r-b2-2-q2",
        type: "multiple-choice",
        prompt: "Was steigert laut Untersuchungen die Bleibewahrscheinlichkeit?",
        options: [
          "Höhere Löhne im ersten Jahr",
          "Sprachförderung und betriebliche Begleitung im ersten Jahr",
          "Ein kostenloses Auto",
          "Kürzere Arbeitszeiten",
        ],
        answerIndex: 1,
        explanation: "Absatz 4, letzter Satz.",
        skill: "reading",
      },
      {
        id: "r-b2-2-q3",
        type: "transform",
        prompt: "Geben Sie die Aussage in direkter Rede wieder.",
        input: "Die Bundesagentur teilte mit, in einigen Regionen bleibe jede zweite Ausbildungsstelle unbesetzt.",
        answers: [
          "Die Bundesagentur sagte: „In einigen Regionen bleibt jede zweite Ausbildungsstelle unbesetzt.“",
        ],
        explanation: "Konjunktiv I → Indikativ in direkter Rede.",
        skill: "grammar",
        grammar: "konjunktiv-1-indirekte-rede",
      },
      {
        id: "r-b2-2-q4",
        type: "writing",
        prompt: "Schreiben Sie eine Stellungnahme (ca. 100 Wörter): Was sollte Deutschland tun, um Fachkräfte zu gewinnen und zu halten?",
        minWords: 90,
        checklist: [
          "Einleitung mit Bezug auf den Text",
          "mindestens zwei begründete Vorschläge",
          "ein Konzessivsatz (obwohl / zwar … aber)",
          "Nominalstil-Ausdruck (aufgrund, trotz, im Hinblick auf)",
          "Fazit",
        ],
        sampleAnswer:
          "Der Text zeigt, dass Deutschland nicht nur Fachkräfte anwerben, sondern sie auch halten muss. Aufgrund der demografischen Entwicklung wird der Bedarf weiter steigen. Meiner Ansicht nach sind zwei Maßnahmen entscheidend. Erstens sollte die Anerkennung ausländischer Abschlüsse deutlich schneller erfolgen, denn wer monatelang auf einen Bescheid wartet, verliert Motivation und Einkommen. Zweitens müssten Betriebe im ersten Jahr eine feste Ansprechperson und begleitende Sprachkurse anbieten. Zwar entstehen dadurch Kosten, aber die Fluktuation sinkt und die Einarbeitung gelingt schneller. Insgesamt halte ich eine Kombination aus schnelleren Verfahren und betrieblicher Begleitung für den wirksamsten Weg.",
        skill: "writing",
      },
    ],
  },
];
