import type { SpeakingTask } from "@/lib/types";

export const speakingTasks: SpeakingTask[] = [
  {
    slug: "sich-vorstellen",
    level: "A1",
    title: "Sich vorstellen",
    kind: "monologue",
    minutes: 8,
    scenario: "First day in a language course. You introduce yourself to the group.",
    goal: "Speak about yourself for 60 seconds using 6 pieces of information.",
    prompts: [
      { question: "Wie heißen Sie?", hint: "Ich heiße … / Mein Name ist …", sample: "Ich heiße Nour Benali." },
      { question: "Woher kommen Sie?", hint: "aus + Land", sample: "Ich komme aus Marokko, aus Rabat." },
      { question: "Wo wohnen Sie jetzt?", hint: "in + Dativ", sample: "Jetzt wohne ich in Leipzig." },
      { question: "Was machen Sie?", hint: "Beruf oder Kurs", sample: "Ich lerne Deutsch und arbeite in einem Café." },
      { question: "Warum lernen Sie Deutsch?", hint: "weil …", sample: "Ich lerne Deutsch, weil ich eine Ausbildung machen möchte." },
      { question: "Was machen Sie gern?", hint: "gern + Verb", sample: "Ich koche gern und ich spiele Fußball." },
    ],
    usefulPhrases: [
      { de: "Darf ich mich vorstellen?", en: "May I introduce myself?" },
      { de: "Ich bin seit … Monaten hier.", en: "I've been here for … months." },
      { de: "Ich spreche Arabisch, Französisch und ein bisschen Deutsch.", en: "I speak Arabic, French and a little German." },
      { de: "Freut mich!", en: "Nice to meet you!" },
    ],
    targets: [
      { de: "Ich heiße Nour und ich komme aus Marokko.", en: "My name is Nour and I come from Morocco." },
      { de: "Ich wohne seit acht Monaten in Leipzig.", en: "I've been living in Leipzig for eight months." },
      { de: "Ich lerne Deutsch, weil ich hier arbeiten möchte.", en: "I'm learning German because I want to work here." },
    ],
  },
  {
    slug: "im-geschaeft-einkaufen",
    level: "A1",
    title: "Rollenspiel: im Geschäft",
    kind: "roleplay",
    minutes: 10,
    scenario: "You are in a bakery. A partner (or the app) plays the salesperson.",
    goal: "Order, ask for the price and pay politely.",
    prompts: [
      { question: "Bestellen Sie zwei Brötchen und einen Kaffee.", sample: "Guten Tag, ich möchte zwei Brötchen und einen Kaffee, bitte." },
      { question: "Fragen Sie nach dem Preis.", sample: "Was kostet das zusammen?" },
      { question: "Sie haben nur eine Karte. Fragen Sie.", sample: "Kann ich mit Karte bezahlen?" },
      { question: "Bedanken und verabschieden Sie sich.", sample: "Vielen Dank, auf Wiedersehen!" },
    ],
    usefulPhrases: [
      { de: "Ich möchte … , bitte.", en: "I would like …, please." },
      { de: "Was kostet das?", en: "How much is that?" },
      { de: "Zusammen oder getrennt?", en: "Together or separately?" },
      { de: "Stimmt so.", en: "Keep the change." },
    ],
    targets: [
      { de: "Ich möchte zwei Brötchen und einen Kaffee, bitte.", en: "I'd like two rolls and a coffee, please." },
      { de: "Kann ich mit Karte bezahlen?", en: "Can I pay by card?" },
    ],
  },
  {
    slug: "termin-vereinbaren-rollenspiel",
    level: "A2",
    title: "Rollenspiel: Termin vereinbaren",
    kind: "roleplay",
    minutes: 10,
    scenario: "You phone a doctor's practice to arrange an appointment and change it later.",
    goal: "Manage a phone call: greeting, request, negotiating a time, confirmation.",
    prompts: [
      { question: "Melden Sie sich am Telefon und nennen Sie Ihren Wunsch.", sample: "Guten Tag, mein Name ist Karim Aziz. Ich würde gern einen Termin vereinbaren." },
      { question: "Die Praxis bietet Freitag 16 Uhr an. Sie arbeiten dann.", sample: "Freitag passt mir leider nicht, da arbeite ich. Hätten Sie etwas am Donnerstagvormittag?" },
      { question: "Fragen Sie, was Sie mitbringen sollen.", sample: "Was soll ich mitbringen?" },
      { question: "Bestätigen Sie den Termin und verabschieden Sie sich.", sample: "Also Donnerstag um halb elf. Vielen Dank, auf Wiederhören." },
    ],
    usefulPhrases: [
      { de: "Ich würde gern einen Termin vereinbaren.", en: "I'd like to make an appointment." },
      { de: "Hätten Sie etwas am Vormittag?", en: "Would you have something in the morning?" },
      { de: "Das passt mir leider nicht.", en: "Unfortunately that doesn't suit me." },
      { de: "Könnten Sie den Termin verschieben?", en: "Could you postpone the appointment?" },
    ],
    targets: [
      { de: "Ich würde gern einen Termin vereinbaren.", en: "I'd like to make an appointment." },
      { de: "Hätten Sie vielleicht etwas am Donnerstagvormittag?", en: "Would you perhaps have something on Thursday morning?" },
    ],
  },
  {
    slug: "ueber-den-alltag-sprechen",
    level: "A2",
    title: "Über den Alltag und die Vergangenheit sprechen",
    kind: "conversation",
    minutes: 12,
    scenario: "Talk about yesterday and about your normal week.",
    goal: "Use the Perfekt and time expressions fluently for 90 seconds.",
    prompts: [
      { question: "Was haben Sie gestern gemacht?", hint: "Perfekt", sample: "Gestern bin ich früh aufgestanden und habe bis 14 Uhr gearbeitet." },
      { question: "Wie sieht eine normale Woche bei Ihnen aus?", sample: "Von Montag bis Freitag habe ich Kurs, am Wochenende arbeite ich." },
      { question: "Was machen Sie am Wochenende am liebsten?", sample: "Am liebsten koche ich mit Freunden." },
      { question: "Was möchten Sie nächstes Jahr machen?", sample: "Nächstes Jahr möchte ich eine Ausbildung anfangen." },
    ],
    usefulPhrases: [
      { de: "zuerst … dann … danach … am Ende", en: "first … then … after that … in the end" },
      { de: "normalerweise / meistens / manchmal / selten", en: "usually / mostly / sometimes / rarely" },
      { de: "Das hat mir gut gefallen.", en: "I liked that." },
    ],
    targets: [
      { de: "Gestern bin ich um sechs Uhr aufgestanden und habe im Café gearbeitet.", en: "Yesterday I got up at six and worked in the café." },
      { de: "Normalerweise fahre ich mit dem Rad zum Kurs.", en: "I usually cycle to the course." },
    ],
  },
  {
    slug: "bewerbungsgespraech",
    level: "B1",
    title: "Vorstellungsgespräch für eine Ausbildung",
    kind: "interview",
    minutes: 15,
    scenario: "A simulated interview for an Ausbildung place. The app asks, you answer aloud.",
    goal: "Answer six standard interview questions with structure and concrete examples.",
    prompts: [
      {
        question: "Erzählen Sie etwas über sich.",
        hint: "60 Sekunden: Herkunft, Ausbildung, Motivation, Ziel",
        sample:
          "Ich bin Karim Aziz, 23 Jahre alt, und komme aus Marokko. Ich habe das Abitur gemacht und zwei Jahre in einer Werkstatt gearbeitet. Seit einem Jahr lerne ich Deutsch und habe jetzt das Niveau B1. Mein Ziel ist eine Ausbildung als Anlagenmechaniker.",
      },
      {
        question: "Warum haben Sie sich bei uns beworben?",
        hint: "Bezug zum Betrieb",
        sample:
          "Ihr Betrieb arbeitet viel mit Heizungs- und Solartechnik, und genau dieser Bereich interessiert mich. Außerdem habe ich gelesen, dass Sie Auszubildende intensiv begleiten.",
      },
      {
        question: "Was sind Ihre Stärken und Schwächen?",
        hint: "Schwäche + Lösung",
        sample:
          "Ich bin zuverlässig und arbeite gern im Team. Eine Schwäche ist, dass ich am Telefon noch unsicher bin; deshalb übe ich jede Woche Telefongespräche mit meinem Sprachpartner.",
      },
      {
        question: "Wie gehen Sie mit Kritik um?",
        sample:
          "Ich frage nach, was genau ich verbessern soll, und schreibe es mir auf. Kritik hilft mir, schneller besser zu werden.",
      },
      { question: "Haben Sie Fragen an uns?", sample: "Ja, wie sieht der erste Monat in der Ausbildung konkret aus? Und wer wäre mein Ansprechpartner im Betrieb?" },
      { question: "Wann könnten Sie anfangen?", sample: "Ich könnte ab dem 1. September anfangen." },
    ],
    usefulPhrases: [
      { de: "Ich interessiere mich besonders für …", en: "I'm particularly interested in …" },
      { de: "Ich habe bereits Erfahrung in …", en: "I already have experience in …" },
      { de: "Daran arbeite ich gerade.", en: "I'm working on that at the moment." },
      { de: "Vielen Dank für das Gespräch.", en: "Thank you for the interview." },
    ],
    targets: [
      { de: "Ich habe mich beworben, weil mich Heizungs- und Solartechnik besonders interessiert.", en: "I applied because heating and solar technology particularly interest me." },
      { de: "Ich bin zuverlässig, pünktlich und arbeite gern im Team.", en: "I'm reliable, punctual and enjoy working in a team." },
    ],
  },
  {
    slug: "problem-loesen-am-telefon",
    level: "B1",
    title: "Ein Problem am Telefon lösen",
    kind: "roleplay",
    minutes: 12,
    scenario: "Your delivery has not arrived. You call the company and negotiate a solution.",
    goal: "Complain politely, insist and agree on a concrete next step.",
    prompts: [
      { question: "Beschreiben Sie das Problem.", sample: "Guten Tag, ich habe am Montag eine Lieferung bestellt, aber sie ist bis heute nicht angekommen." },
      { question: "Der Mitarbeiter sagt, es dauert noch eine Woche. Reagieren Sie.", sample: "Eine Woche ist für mich zu lang. Ich brauche das Gerät für die Arbeit. Gibt es eine schnellere Lösung?" },
      { question: "Fragen Sie nach einer Bestätigung.", sample: "Könnten Sie mir das bitte schriftlich per E-Mail bestätigen?" },
      { question: "Fassen Sie die Vereinbarung zusammen.", sample: "Also: Sie schicken das Gerät morgen per Express und ich bekomme eine Bestätigung per E-Mail. Richtig?" },
    ],
    usefulPhrases: [
      { de: "Ich möchte mich über … beschweren.", en: "I'd like to complain about …" },
      { de: "Das ist für mich leider nicht akzeptabel.", en: "Unfortunately that isn't acceptable for me." },
      { de: "Könnten Sie mir entgegenkommen?", en: "Could you meet me halfway?" },
      { de: "Ich fasse noch einmal zusammen: …", en: "Let me summarise: …" },
    ],
    targets: [
      { de: "Ich möchte mich über die verspätete Lieferung beschweren.", en: "I'd like to complain about the late delivery." },
      { de: "Könnten Sie mir das bitte schriftlich bestätigen?", en: "Could you confirm that to me in writing, please?" },
    ],
  },
  {
    slug: "praesentation-halten",
    level: "B2",
    title: "Eine Präsentation halten",
    kind: "monologue",
    minutes: 18,
    scenario: "Goethe/TELC B2 speaking part 1: a structured short presentation on a topic.",
    goal: "Give a 4-minute presentation with introduction, arguments, example and conclusion.",
    prompts: [
      { question: "Einleitung: Thema nennen und Struktur ankündigen.", sample: "Ich möchte heute über Homeoffice sprechen. Zuerst nenne ich Vorteile, dann Nachteile, und am Ende gebe ich meine persönliche Einschätzung." },
      { question: "Argument 1 mit Beispiel.", sample: "Ein klarer Vorteil ist die Zeitersparnis. In meinem Fall sind das täglich fast neunzig Minuten, die ich sonst im Bus verbringe." },
      { question: "Argument 2 (Gegenseite).", sample: "Andererseits leidet der informelle Austausch. Gerade neue Kollegen brauchen deutlich länger, bis sie sich im Team zurechtfinden." },
      { question: "Situation im Heimatland vergleichen.", sample: "In Marokko ist Homeoffice noch weniger verbreitet, weil viele Betriebe Präsenz erwarten." },
      { question: "Fazit und Empfehlung.", sample: "Zusammenfassend halte ich hybride Modelle für den besten Kompromiss: zwei Tage im Büro, drei Tage zu Hause." },
    ],
    usefulPhrases: [
      { de: "Ich möchte kurz auf … eingehen.", en: "I'd like to briefly address …" },
      { de: "Einerseits … andererseits …", en: "On the one hand … on the other …" },
      { de: "Das lässt sich gut daran erkennen, dass …", en: "This can clearly be seen from the fact that …" },
      { de: "Zusammenfassend lässt sich sagen, dass …", en: "In summary, it can be said that …" },
    ],
    targets: [
      { de: "Zusammenfassend lässt sich sagen, dass hybride Modelle die Vorteile beider Seiten verbinden.", en: "In summary, hybrid models combine the advantages of both sides." },
      { de: "Ich möchte kurz auf die Nachteile der ständigen Erreichbarkeit eingehen.", en: "I'd like to briefly address the disadvantages of constant availability." },
    ],
  },
  {
    slug: "diskussion-fuehren",
    level: "B2",
    title: "Diskussion führen und moderieren",
    kind: "challenge",
    minutes: 15,
    scenario: "Goethe/TELC B2 speaking part 2: discuss a proposal with a partner and reach an agreement.",
    goal: "React to arguments, disagree politely, make compromises, summarise the outcome.",
    prompts: [
      { question: "Vorschlag: Der Betrieb soll einen Deutschkurs für alle Azubis anbieten. Nehmen Sie Stellung.", sample: "Grundsätzlich halte ich den Vorschlag für sinnvoll, allerdings sollte der Kurs während der Arbeitszeit stattfinden." },
      { question: "Ihr Partner ist dagegen, weil es zu teuer sei. Reagieren Sie.", sample: "Das Argument verstehe ich, dennoch würde ich es anders sehen: Die Kosten amortisieren sich, wenn weniger Fehler durch Missverständnisse entstehen." },
      { question: "Machen Sie einen Kompromissvorschlag.", sample: "Wie wäre es mit einem Kurs alle zwei Wochen, den der Betrieb zur Hälfte finanziert?" },
      { question: "Fassen Sie das Ergebnis zusammen.", sample: "Wir sind uns also einig: ein Kurs alle zwei Wochen, hälftig finanziert, mit Prüfung nach sechs Monaten." },
    ],
    usefulPhrases: [
      { de: "Da bin ich ganz Ihrer Meinung.", en: "I completely agree with you." },
      { de: "Das sehe ich etwas anders, weil …", en: "I see that a little differently because …" },
      { de: "Darf ich kurz einhaken?", en: "May I interject briefly?" },
      { de: "Können wir uns darauf einigen, dass …?", en: "Can we agree that …?" },
    ],
    targets: [
      { de: "Das sehe ich etwas anders, weil die Kosten sich langfristig amortisieren.", en: "I see it a bit differently, because the costs pay off in the long run." },
      { de: "Können wir uns darauf einigen, dass der Kurs während der Arbeitszeit stattfindet?", en: "Can we agree that the course takes place during working hours?" },
    ],
  },
  {
    slug: "aussprache-training-taeglich",
    level: "A1",
    title: "Täglicher Aussprache-Sprint",
    kind: "pronunciation",
    minutes: 6,
    scenario: "Five sentences a day with the sounds that are hardest for learners of German.",
    goal: "Record yourself, compare with the model and score above 80 % recognition.",
    prompts: [
      { question: "ü / u", sample: "Über fünf Brücken müssen wir früh fahren." },
      { question: "ö / o", sample: "Können Sie die Tür öffnen? Es ist schön hier." },
      { question: "ch (ich-Laut)", sample: "Ich möchte nicht wirklich richtig sprechen üben." },
      { question: "ch (ach-Laut)", sample: "Nach acht Wochen macht die Nachbarin Kuchen." },
      { question: "r + Endung -er", sample: "Der Lehrer aus Hamburg trinkt Wasser mit Zucker." },
    ],
    usefulPhrases: [
      { de: "Noch einmal, bitte langsamer.", en: "Again, more slowly please." },
      { de: "Wie spricht man das aus?", en: "How do you pronounce that?" },
    ],
    targets: [
      { de: "Über fünf Brücken müssen wir früh fahren.", en: "We have to drive over five bridges early." },
      { de: "Ich möchte richtig sprechen üben.", en: "I want to practise speaking correctly." },
      { de: "Nach acht Wochen macht die Nachbarin Kuchen.", en: "After eight weeks the neighbour bakes a cake." },
    ],
  },
];
