import type { WritingTask } from "@/lib/types";

export const writingTasks: WritingTask[] = [
  {
    slug: "kurze-nachricht-freundin",
    level: "A1",
    title: "Kurze Nachricht: Termin absagen",
    kind: "message",
    minutes: 15,
    scenario:
      "Sie sind mit Ihrer Freundin Lena um 18 Uhr im Kino verabredet. Sie müssen länger arbeiten. Schreiben Sie eine kurze Nachricht (WhatsApp).",
    bullets: ["Grund nennen", "sich entschuldigen", "einen neuen Termin vorschlagen"],
    minWords: 30,
    maxWords: 50,
    structure: [
      { part: "Anrede", detail: "Hallo Lena, / Liebe Lena," },
      { part: "Grund", detail: "Ich muss heute länger arbeiten." },
      { part: "Entschuldigung", detail: "Es tut mir wirklich leid." },
      { part: "Vorschlag", detail: "Können wir morgen um 18 Uhr gehen?" },
      { part: "Gruß", detail: "Liebe Grüße, Nour" },
    ],
    usefulPhrases: [
      { de: "Es tut mir leid, aber …", en: "I'm sorry, but …" },
      { de: "Ich kann heute leider nicht kommen.", en: "Unfortunately I can't come today." },
      { de: "Hast du morgen Zeit?", en: "Do you have time tomorrow?" },
      { de: "Liebe Grüße", en: "Best wishes (informal)" },
    ],
    checklist: [
      "Anrede und Gruß vorhanden",
      "alle drei Punkte bearbeitet",
      "du-Form durchgehend",
      "Verb an Position 2",
      "30–50 Wörter",
    ],
    sampleAnswer:
      "Hallo Lena,\n\nes tut mir wirklich leid, aber ich kann heute nicht ins Kino kommen. Ich muss bis 19 Uhr arbeiten. Hast du morgen Abend Zeit? Wir können um 18 Uhr gehen, der Film läuft auch morgen.\n\nLiebe Grüße\nNour",
    nativeVersion:
      "Hey Lena, tut mir leid – ich muss heute länger arbeiten und schaffe das Kino nicht. Morgen um 18 Uhr statt heute? Der Film läuft auch dann noch. LG Nour",
  },
  {
    slug: "formular-anmeldung",
    level: "A1",
    title: "Formular: Anmeldung im Sprachkurs",
    kind: "email",
    minutes: 12,
    scenario:
      "Sie möchten sich für einen Deutschkurs anmelden. Schreiben Sie eine kurze E-Mail an die Sprachschule.",
    bullets: ["Kurs nennen (A1, abends)", "nach dem Preis fragen", "nach dem Beginn fragen"],
    minWords: 35,
    maxWords: 60,
    structure: [
      { part: "Anrede", detail: "Sehr geehrte Damen und Herren," },
      { part: "Anlass", detail: "ich möchte einen Deutschkurs besuchen." },
      { part: "Fragen", detail: "Was kostet der Kurs? Wann beginnt er?" },
      { part: "Schluss", detail: "Vielen Dank für Ihre Antwort." },
      { part: "Gruß", detail: "Mit freundlichen Grüßen, Nour Benali" },
    ],
    usefulPhrases: [
      { de: "Sehr geehrte Damen und Herren,", en: "Dear Sir or Madam," },
      { de: "Ich interessiere mich für …", en: "I'm interested in …" },
      { de: "Können Sie mir bitte sagen, …?", en: "Could you please tell me …?" },
      { de: "Mit freundlichen Grüßen", en: "Kind regards" },
    ],
    checklist: [
      "formelle Anrede und Grußformel",
      "Sie-Form",
      "zwei Fragen gestellt",
      "kleine Buchstaben nach der Anrede (ich möchte …)",
    ],
    sampleAnswer:
      "Sehr geehrte Damen und Herren,\n\nich interessiere mich für einen Deutschkurs auf dem Niveau A1 am Abend. Können Sie mir bitte sagen, was der Kurs kostet und wann der nächste Kurs beginnt? Ich arbeite bis 17 Uhr und kann erst danach kommen.\n\nVielen Dank für Ihre Antwort.\n\nMit freundlichen Grüßen\nNour Benali",
  },
  {
    slug: "email-entschuldigung-kurs",
    level: "A2",
    title: "E-Mail: Entschuldigung an die Kursleiterin",
    kind: "email",
    minutes: 20,
    scenario:
      "Sie waren zwei Tage krank und haben den Unterricht verpasst. Schreiben Sie an Ihre Kursleiterin, Frau Berger.",
    bullets: [
      "Grund für die Abwesenheit nennen",
      "nach den Hausaufgaben fragen",
      "einen Termin für ein Gespräch vorschlagen",
    ],
    minWords: 50,
    maxWords: 80,
    structure: [
      { part: "Anrede", detail: "Sehr geehrte Frau Berger," },
      { part: "Grund", detail: "ich war am Montag und Dienstag krank." },
      { part: "Nachweis", detail: "Die Bescheinigung vom Arzt bringe ich morgen mit." },
      { part: "Bitte", detail: "Könnten Sie mir sagen, welche Hausaufgaben ich nachholen muss?" },
      { part: "Vorschlag", detail: "Hätten Sie am Donnerstag nach dem Kurs kurz Zeit?" },
      { part: "Gruß", detail: "Mit freundlichen Grüßen, Karim Aziz" },
    ],
    usefulPhrases: [
      { de: "Leider konnte ich nicht am Unterricht teilnehmen.", en: "Unfortunately I couldn't attend the lesson." },
      { de: "Ich hoffe auf Ihr Verständnis.", en: "I hope for your understanding." },
      { de: "Könnten Sie mir bitte mitteilen, …", en: "Could you please let me know …" },
      { de: "Vielen Dank im Voraus.", en: "Thank you in advance." },
    ],
    checklist: [
      "formelle Anrede mit Namen",
      "Perfekt für die Vergangenheit korrekt",
      "höfliche Bitte mit Konjunktiv II (könnten)",
      "alle drei Punkte behandelt",
      "50–80 Wörter",
    ],
    sampleAnswer:
      "Sehr geehrte Frau Berger,\n\nleider konnte ich am Montag und Dienstag nicht am Unterricht teilnehmen, weil ich krank war. Ich hatte Fieber und war beim Arzt. Die Bescheinigung bringe ich morgen mit.\n\nKönnten Sie mir bitte mitteilen, welche Hausaufgaben ich nachholen muss? Außerdem hätte ich eine Frage zum Perfekt. Hätten Sie am Donnerstag nach dem Kurs zehn Minuten Zeit?\n\nVielen Dank im Voraus und viele Grüße\nKarim Aziz",
    nativeVersion:
      "Sehr geehrte Frau Berger, ich war Montag und Dienstag krankgeschrieben und konnte deshalb nicht am Unterricht teilnehmen; die AU-Bescheinigung reiche ich morgen nach. Könnten Sie mir bitte kurz mitteilen, welche Aufgaben ich nacharbeiten sollte? Für eine Rückfrage zum Perfekt wäre ich Ihnen dankbar, wenn Sie Donnerstag nach dem Kurs zehn Minuten Zeit hätten. Mit freundlichen Grüßen, Karim Aziz",
  },
  {
    slug: "brief-wohnungsanfrage",
    level: "A2",
    title: "Anfrage zu einer Wohnung",
    kind: "letter",
    minutes: 20,
    scenario:
      "Sie haben eine Wohnungsanzeige gelesen (2 Zimmer, 520 € kalt). Schreiben Sie an die Hausverwaltung.",
    bullets: [
      "sich vorstellen (Beruf, Einkommen)",
      "nach Nebenkosten und Kaution fragen",
      "einen Besichtigungstermin erfragen",
    ],
    minWords: 60,
    maxWords: 90,
    structure: [
      { part: "Betreff", detail: "Anfrage zur 2-Zimmer-Wohnung in der Hafenstraße" },
      { part: "Anrede", detail: "Sehr geehrte Damen und Herren," },
      { part: "Bezug", detail: "ich habe Ihre Anzeige auf … gelesen." },
      { part: "Vorstellung", detail: "Ich arbeite seit einem Jahr als … und verdiene …" },
      { part: "Fragen", detail: "Wie hoch sind die Nebenkosten? Wie viele Monatsmieten Kaution?" },
      { part: "Termin", detail: "Wann könnte ich die Wohnung besichtigen?" },
      { part: "Gruß", detail: "Mit freundlichen Grüßen" },
    ],
    usefulPhrases: [
      { de: "Ich habe Ihre Anzeige mit großem Interesse gelesen.", en: "I read your advert with great interest." },
      { de: "Die Wohnung würde mir sehr gut passen.", en: "The flat would suit me very well." },
      { de: "Über eine Besichtigung würde ich mich freuen.", en: "I would be glad to view the flat." },
      { de: "Für Rückfragen erreichen Sie mich unter …", en: "You can reach me for questions at …" },
    ],
    checklist: [
      "Betreffzeile vorhanden",
      "formeller Stil durchgehend",
      "drei Inhaltspunkte klar getrennt",
      "Kontaktangabe am Ende",
    ],
    sampleAnswer:
      "Betreff: Anfrage zur 2-Zimmer-Wohnung in der Hafenstraße\n\nSehr geehrte Damen und Herren,\n\nich habe Ihre Anzeige mit großem Interesse gelesen und möchte mich für die Wohnung bewerben. Ich bin 24 Jahre alt, arbeite seit einem Jahr als Pflegehelfer in der Klinik St. Georg und verdiene netto 1.900 Euro monatlich. Ich bin Nichtraucher und habe keine Haustiere.\n\nKönnten Sie mir bitte mitteilen, wie hoch die Nebenkosten sind und wie viele Monatsmieten als Kaution verlangt werden? Außerdem würde ich die Wohnung gern besichtigen. Wann wäre das möglich?\n\nFür Rückfragen erreichen Sie mich unter 0176 33 44 55 6.\n\nMit freundlichen Grüßen\nKarim Aziz",
  },
  {
    slug: "forumsbeitrag-meinung",
    level: "B1",
    title: "Forumsbeitrag: Meinung äußern",
    kind: "essay",
    minutes: 30,
    scenario:
      "In einem Online-Forum wird diskutiert: „Sollten Handys in der Berufsschule verboten werden?“ Schreiben Sie Ihren Beitrag.",
    bullets: [
      "eigene Meinung klar formulieren",
      "zwei Argumente mit Beispiel",
      "ein Gegenargument einräumen",
      "Fazit",
    ],
    minWords: 80,
    maxWords: 120,
    structure: [
      { part: "Einleitung", detail: "Bezug zum Thema + eigene Position" },
      { part: "Argument 1", detail: "weil / denn + Beispiel aus Erfahrung" },
      { part: "Argument 2", detail: "Außerdem … / Ein weiterer Punkt ist, dass …" },
      { part: "Gegenargument", detail: "Natürlich / Zwar … aber …" },
      { part: "Fazit", detail: "Insgesamt / Zusammenfassend …" },
    ],
    usefulPhrases: [
      { de: "Meiner Meinung nach …", en: "In my opinion …" },
      { de: "Ich bin der Ansicht, dass …", en: "I take the view that …" },
      { de: "Zwar …, aber …", en: "Admittedly …, but …" },
      { de: "Aus meiner Erfahrung …", en: "From my experience …" },
      { de: "Zusammenfassend würde ich sagen, dass …", en: "In summary I would say that …" },
    ],
    checklist: [
      "Position in der Einleitung erkennbar",
      "mindestens zwei begründete Argumente",
      "ein Konzessivsatz (zwar … aber / obwohl)",
      "Konnektoren korrekt (weil, deshalb, außerdem)",
      "Fazit am Ende",
    ],
    sampleAnswer:
      "Meiner Meinung nach ist ein komplettes Handyverbot in der Berufsschule nicht sinnvoll. Erstens brauchen wir das Handy im Unterricht selbst: Ich benutze es täglich für Wörterbücher und für Notizen, weil ich Deutsch noch lerne. Zweitens gehören digitale Geräte längst zum Beruf; in der Werkstatt lesen wir technische Anleitungen auf dem Tablet.\n\nZwar stört es, wenn während des Unterrichts ständig Nachrichten ankommen, aber dafür gibt es einfache Regeln: Handy auf dem Tisch, stumm, und nur nach Aufforderung benutzen.\n\nZusammenfassend würde ich sagen, dass klare Regeln besser funktionieren als ein Verbot, weil wir so lernen, verantwortungsvoll mit dem Gerät umzugehen.",
    nativeVersion:
      "Ein pauschales Handyverbot halte ich für den falschen Weg. Zum einen ist das Smartphone im Unterricht ein Arbeitsmittel – Wörterbuch, Notizblock, Übersetzungshilfe –, zum anderen arbeiten wir auch im Betrieb längst mit digitalen Anleitungen. Dass Benachrichtigungen ablenken, ist unbestritten; genau deshalb braucht es verbindliche Regeln statt eines Verbots: lautlos, sichtbar auf dem Tisch, Nutzung nur auf Aufforderung. So lernen Auszubildende einen verantwortungsvollen Umgang, der ihnen im Beruf ohnehin abverlangt wird.",
  },
  {
    slug: "beschwerde-brief",
    level: "B1",
    title: "Beschwerdebrief",
    kind: "letter",
    minutes: 30,
    scenario:
      "Sie haben einen Sprachkurs bezahlt, aber der Unterricht fiel dreimal aus und der Raum war zu klein. Schreiben Sie eine Beschwerde an die Schulleitung.",
    bullets: [
      "Sachverhalt sachlich schildern",
      "konkrete Kritikpunkte nennen",
      "eine Forderung stellen (Ersatzstunden oder Teilrückzahlung)",
      "Frist setzen",
    ],
    minWords: 90,
    maxWords: 130,
    structure: [
      { part: "Betreff", detail: "Beschwerde: Kurs A2.2, Kursnummer 2418" },
      { part: "Anrede", detail: "Sehr geehrte Frau Dr. Lange," },
      { part: "Sachverhalt", detail: "Fakten mit Datum" },
      { part: "Kritik", detail: "Erstens … Zweitens …" },
      { part: "Forderung", detail: "Ich bitte Sie daher, …" },
      { part: "Frist", detail: "bis zum 30. April" },
      { part: "Gruß", detail: "Mit freundlichen Grüßen" },
    ],
    usefulPhrases: [
      { de: "Leider muss ich Sie auf folgendes Problem hinweisen.", en: "Unfortunately I must point out the following problem." },
      { de: "Ich bitte Sie daher, … zu prüfen.", en: "I therefore ask you to examine …" },
      { de: "Ich erwarte eine Antwort bis zum …", en: "I expect a reply by …" },
      { de: "Andernfalls sehe ich mich gezwungen, …", en: "Otherwise I will be forced to …" },
    ],
    checklist: [
      "sachlicher, höflicher Ton (keine Beleidigungen)",
      "Daten und Fakten konkret",
      "klare Forderung",
      "Frist genannt",
      "formelle Grußformel",
    ],
    sampleAnswer:
      "Betreff: Beschwerde zum Kurs A2.2 (Kursnummer 2418)\n\nSehr geehrte Frau Dr. Lange,\n\nleider muss ich Sie auf mehrere Probleme in meinem Kurs hinweisen. Der Unterricht ist am 8., 15. und 22. März ohne Ersatz ausgefallen, sodass insgesamt zwölf Unterrichtsstunden fehlen. Außerdem findet der Kurs seit vier Wochen in Raum 3 statt, der für 18 Teilnehmende deutlich zu klein ist; mehrere Personen müssen stehen.\n\nIch habe für den Kurs 390 Euro bezahlt und erwarte dafür die vereinbarte Stundenzahl. Ich bitte Sie daher, entweder Ersatzstunden anzubieten oder einen Teil der Kursgebühr zurückzuerstatten.\n\nÜber eine Antwort bis zum 30. April würde ich mich freuen.\n\nMit freundlichen Grüßen\nKarim Aziz",
  },
  {
    slug: "eroerterung-b2",
    level: "B2",
    title: "Erörterung: Sollten Unternehmen Sprachkurse bezahlen?",
    kind: "essay",
    minutes: 45,
    scenario:
      "Schreiben Sie einen argumentativen Text: „Sollten Unternehmen für ihre internationalen Mitarbeitenden Deutschkurse während der Arbeitszeit finanzieren?“",
    bullets: [
      "Einleitung mit Problemaufriss",
      "Pro-Argumente (mindestens zwei, mit Beispiel oder Zahl)",
      "Contra-Argumente (mindestens zwei)",
      "eigene begründete Position",
      "Ausblick",
    ],
    minWords: 180,
    maxWords: 250,
    structure: [
      { part: "Einleitung", detail: "Relevanz, Fragestellung, Aufbau ankündigen" },
      { part: "Hauptteil 1", detail: "Argumente dafür: Produktivität, Bindung, Sicherheit" },
      { part: "Hauptteil 2", detail: "Argumente dagegen: Kosten, Ausfallzeit, Eigenverantwortung" },
      { part: "Abwägung", detail: "Gegenüberstellung, Gewichtung" },
      { part: "Schluss", detail: "eigene Position + Empfehlung" },
    ],
    usefulPhrases: [
      { de: "Zunächst ist festzuhalten, dass …", en: "First of all it should be noted that …" },
      { de: "Ein wesentliches Argument dafür ist, dass …", en: "A key argument in favour is that …" },
      { de: "Dem lässt sich entgegenhalten, dass …", en: "It can be countered that …" },
      { de: "Abwägend komme ich zu dem Ergebnis, dass …", en: "Weighing this up, I conclude that …" },
      { de: "Voraussetzung dafür wäre allerdings, dass …", en: "A prerequisite, however, would be that …" },
    ],
    checklist: [
      "klare Gliederung (Einleitung, Pro, Contra, Fazit)",
      "mindestens vier Argumente mit Begründung",
      "Konnektoren variiert (zunächst, darüber hinaus, dagegen, folglich)",
      "Passiv oder Passiversatz verwendet",
      "Nominalstil an mindestens zwei Stellen",
      "180–250 Wörter",
    ],
    sampleAnswer:
      "Angesichts des Fachkräftemangels stellt sich für viele Betriebe die Frage, ob sie Deutschkurse für internationale Mitarbeitende selbst finanzieren sollten. Im Folgenden werden zunächst die wichtigsten Argumente beider Seiten dargestellt und anschließend abgewogen.\n\nFür eine betriebliche Finanzierung spricht vor allem die Produktivität. Missverständnisse in der Kommunikation führen zu Fehlern, die im Handwerk und in der Pflege erhebliche Kosten und im schlimmsten Fall Sicherheitsrisiken verursachen. Darüber hinaus erhöht ein solches Angebot die Bindung an das Unternehmen: Wer betrieblich gefördert wird, wechselt seltener den Arbeitgeber. Schließlich lässt sich die Einarbeitung neuer Kolleginnen und Kollegen deutlich beschleunigen, wenn die sprachlichen Voraussetzungen früh geschaffen werden.\n\nDem lässt sich entgegenhalten, dass Kurse während der Arbeitszeit Produktionsausfall bedeuten und gerade kleine Betriebe finanziell belasten. Zudem wird argumentiert, Sprachenlernen sei Teil der Eigenverantwortung; öffentliche Integrationskurse stünden ohnehin zur Verfügung.\n\nAbwägend komme ich zu dem Ergebnis, dass eine geteilte Verantwortung am sinnvollsten ist: Der Betrieb stellt Arbeitszeit und Räume, die Beschäftigten investieren ihre Freizeit für Hausaufgaben, und öffentliche Programme übernehmen einen Teil der Kosten. Voraussetzung dafür wäre allerdings ein unbürokratisches Förderverfahren, damit auch Kleinbetriebe davon profitieren können.",
  },
  {
    slug: "formelle-email-b2",
    level: "B2",
    title: "Formelle E-Mail: Verhandlung mit einem Kunden",
    kind: "email",
    minutes: 30,
    scenario:
      "Ein Kunde beschwert sich über eine verspätete Lieferung und fordert 20 % Rabatt. Antworten Sie im Namen der Firma.",
    bullets: [
      "Beschwerde bestätigen und sich entschuldigen",
      "Ursache erklären, ohne Schuld abzuwälzen",
      "konkretes Angebot machen (nicht 20 %)",
      "Vertrauen wiederherstellen",
    ],
    minWords: 120,
    maxWords: 170,
    structure: [
      { part: "Betreff", detail: "Ihre Reklamation vom 12. Mai – Auftrag 8842" },
      { part: "Anrede", detail: "Sehr geehrter Herr Brandt," },
      { part: "Dank/Entschuldigung", detail: "vielen Dank für Ihre Nachricht … bitte entschuldigen Sie" },
      { part: "Erklärung", detail: "Ursache sachlich, im Passiv" },
      { part: "Angebot", detail: "Gegenvorschlag mit Zahl und Frist" },
      { part: "Ausblick", detail: "Maßnahmen für die Zukunft" },
      { part: "Gruß", detail: "Mit freundlichen Grüßen + Position" },
    ],
    usefulPhrases: [
      { de: "Vielen Dank für Ihre Nachricht vom …", en: "Thank you for your message of …" },
      { de: "Bitte entschuldigen Sie die entstandenen Unannehmlichkeiten.", en: "Please excuse the inconvenience caused." },
      { de: "Die Verzögerung ist darauf zurückzuführen, dass …", en: "The delay is due to the fact that …" },
      { de: "Als Ausgleich möchten wir Ihnen … anbieten.", en: "As compensation we would like to offer you …" },
      { de: "Wir haben umgehend Maßnahmen eingeleitet, damit …", en: "We have immediately taken measures so that …" },
    ],
    checklist: [
      "Betreff mit Auftragsnummer",
      "Entschuldigung ohne Ausreden",
      "Ursache im Passiv oder mit Passiversatz",
      "konkretes Gegenangebot",
      "Maßnahme für die Zukunft",
      "formeller Abschluss mit Funktion",
    ],
    sampleAnswer:
      "Betreff: Ihre Reklamation vom 12. Mai – Auftrag 8842\n\nSehr geehrter Herr Brandt,\n\nvielen Dank für Ihre Nachricht. Bitte entschuldigen Sie die Unannehmlichkeiten, die durch die verspätete Lieferung entstanden sind – Ihre Kritik ist berechtigt.\n\nDie Verzögerung ist darauf zurückzuführen, dass unser Zulieferer die Bauteile mit zwei Wochen Rückstand geliefert hat. Das entschuldigt die späte Information an Sie jedoch nicht; hier haben wir intern nachgesteuert und die Auftragsverfolgung umgestellt, sodass Sie künftig automatisch über Terminänderungen informiert werden.\n\nEinen Preisnachlass von 20 % können wir leider nicht darstellen. Als Ausgleich möchten wir Ihnen jedoch 8 % auf den betroffenen Auftrag sowie die kostenfreie Expresslieferung Ihrer nächsten drei Bestellungen anbieten. Über eine kurze Rückmeldung bis Freitag wären wir Ihnen dankbar.\n\nFür Rückfragen stehe ich Ihnen gern zur Verfügung.\n\nMit freundlichen Grüßen\nSabine Kaya\nVertrieb, Sommer & Partner GmbH",
  },
];
