import type { MockExam } from "@/lib/types";

export const goetheExams: MockExam[] = [
  {
    slug: "goethe-a1-mock-1",
    provider: "goethe",
    level: "A1",
    title: "Goethe-Zertifikat A1 — Mock exam 1",
    officialName: "Start Deutsch 1",
    minutes: 65,
    passMark: 60,
    description:
      "Full-length simulation of Start Deutsch 1: Lesen (25 min), Hören (20 min), Schreiben (20 min) and Sprechen (about 15 min in a group).",
    strategies: [
      { title: "Read the questions first", body: "In Lesen Teil 1 and 2 the questions tell you what to look for. Scan for names, times, prices and places instead of reading every word." },
      { title: "Only one hearing in Teil 2", body: "Hören Teil 1 is played twice, Teil 2 only once. Write short notes while listening; do not wait until the end." },
      { title: "Answer all three writing bullets", body: "In Schreiben Teil 2 the examiner ticks one point per bullet. Missing a bullet costs more than a grammar mistake." },
      { title: "Speak in full phrases", body: "In Sprechen Teil 1 spell your name slowly. In Teil 2 and 3 always answer with a complete sentence, then add one detail." },
    ],
    sections: [
      {
        id: "a1-lesen",
        skill: "reading",
        title: "Lesen",
        minutes: 25,
        maxPoints: 15,
        weight: 25,
        parts: [
          {
            id: "a1-lesen-1",
            title: "Teil 1 — Zwei kurze Texte",
            instructions: "Lesen Sie die Texte und die Aufgaben. Kreuzen Sie an: richtig oder falsch.",
            skill: "reading",
            minutes: 10,
            maxPoints: 5,
            reading: [
              "Hallo Sofia, ich bin heute Abend nicht zu Hause. Ich habe von 18 bis 20 Uhr Deutschkurs. Danach gehe ich noch schnell einkaufen. Kannst du bitte den Müll rausbringen? Der gelbe Sack muss heute vor die Tür. Danke! Bis morgen, Nour",
              "Liebe Nachbarn, am Samstag, 15. Juni, feiern wir im Hof ein kleines Fest. Beginn: 15 Uhr. Bitte bringen Sie etwas zu essen oder zu trinken mit. Bei Regen findet das Fest im Keller statt. Familie Weber, Wohnung 3B",
            ],
            items: [
              {
                id: "e-a1-l1-1", type: "true-false",
                prompt: "Nour ist heute Abend zu Hause.",
                answer: false,
                explanation: "„ich bin heute Abend nicht zu Hause“.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l1-2", type: "true-false",
                prompt: "Sofia soll den gelben Sack rausbringen.",
                answer: true,
                explanation: "„Der gelbe Sack muss heute vor die Tür.“", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l1-3", type: "true-false",
                prompt: "Das Fest beginnt um 17 Uhr.",
                answer: false,
                explanation: "„Beginn: 15 Uhr“.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l1-4", type: "true-false",
                prompt: "Die Gäste sollen Essen oder Getränke mitbringen.",
                answer: true,
                explanation: "„Bitte bringen Sie etwas zu essen oder zu trinken mit.“", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l1-5", type: "multiple-choice",
                prompt: "Wo ist das Fest, wenn es regnet?",
                options: ["Im Hof", "Im Keller", "In Wohnung 3B", "Im Park"],
                answerIndex: 1,
                explanation: "„Bei Regen findet das Fest im Keller statt.“", skill: "reading", points: 1,
              },
            ],
          },
          {
            id: "a1-lesen-2",
            title: "Teil 2 — Anzeigen vergleichen",
            instructions: "Lesen Sie die Anzeigen und wählen Sie die richtige Lösung a oder b.",
            skill: "reading",
            minutes: 8,
            maxPoints: 5,
            reading: [
              "a) Sprachschule Mitte — Deutschkurse A1 bis C1. Montag bis Donnerstag, 18–20 Uhr. Kursgebühr 180 €. Anmeldung online. Tel. 0341 22 44 66.",
              "b) Volkshochschule Süd — Deutsch für den Beruf, A2/B1. Samstags 9–13 Uhr. 220 €, mit Bildungsgutschein kostenlos. Anmeldung nur persönlich, Zimmer 105.",
            ],
            items: [
              {
                id: "e-a1-l2-1", type: "multiple-choice",
                prompt: "Sie arbeiten von Montag bis Freitag den ganzen Tag. Welcher Kurs passt?",
                options: ["a", "b"], answerIndex: 1,
                explanation: "Der Kurs an der VHS ist samstags.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l2-2", type: "multiple-choice",
                prompt: "Sie möchten sich online anmelden. Welcher Kurs?",
                options: ["a", "b"], answerIndex: 0,
                explanation: "„Anmeldung online“ steht nur bei a.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l2-3", type: "multiple-choice",
                prompt: "Sie haben einen Bildungsgutschein. Welcher Kurs ist kostenlos?",
                options: ["a", "b"], answerIndex: 1,
                explanation: "„mit Bildungsgutschein kostenlos“.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l2-4", type: "multiple-choice",
                prompt: "Sie brauchen einen Kurs auf dem Niveau C1. Welcher Kurs?",
                options: ["a", "b"], answerIndex: 0,
                explanation: "Nur a bietet A1 bis C1.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l2-5", type: "fill-blank",
                prompt: "Wie viel kostet der Kurs an der Sprachschule Mitte?",
                sentence: "Die Kursgebühr beträgt ___ Euro.",
                answers: [["180"]],
                explanation: "Siehe Anzeige a.", skill: "reading", points: 1,
              },
            ],
          },
          {
            id: "a1-lesen-3",
            title: "Teil 3 — Kurze Mitteilungen",
            instructions: "Lesen Sie die Nachricht und beantworten Sie die Fragen.",
            skill: "reading",
            minutes: 7,
            maxPoints: 5,
            reading: [
              "Sehr geehrte Frau Benali, Ihr Termin bei Dr. Hoffmann am Mittwoch, 14 Uhr, muss leider verschoben werden. Wir bieten Ihnen einen neuen Termin am Freitag um 9 Uhr 30 an. Bitte bringen Sie Ihre Versichertenkarte mit. Wenn der Termin nicht passt, rufen Sie uns bitte bis Dienstag 12 Uhr an. Praxis Dr. Hoffmann, Tel. 0341 44 55 66",
            ],
            items: [
              {
                id: "e-a1-l3-1", type: "multiple-choice",
                prompt: "Wann ist der neue Termin?",
                options: ["Mittwoch 14 Uhr", "Freitag 9:30", "Dienstag 12 Uhr", "Freitag 14 Uhr"],
                answerIndex: 1, explanation: "„am Freitag um 9 Uhr 30“.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l3-2", type: "multiple-choice",
                prompt: "Was soll Frau Benali mitbringen?",
                options: ["Geld", "Die Versichertenkarte", "Ein Rezept", "Einen Ausweis"],
                answerIndex: 1, explanation: "„Bitte bringen Sie Ihre Versichertenkarte mit.“", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l3-3", type: "true-false",
                prompt: "Frau Benali muss anrufen, wenn der Termin nicht passt.",
                answer: true, explanation: "„rufen Sie uns bitte bis Dienstag 12 Uhr an“.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l3-4", type: "true-false",
                prompt: "Der alte Termin bleibt gültig.",
                answer: false, explanation: "Der Termin „muss verschoben werden“.", skill: "reading", points: 1,
              },
              {
                id: "e-a1-l3-5", type: "fill-blank",
                prompt: "Bis wann muss man anrufen?",
                sentence: "Bis ___ um ___ Uhr.",
                answers: [["Dienstag"], ["12"]],
                explanation: "„bis Dienstag 12 Uhr“.", skill: "reading", points: 1,
              },
            ],
          },
        ],
      },
      {
        id: "a1-hoeren",
        skill: "listening",
        title: "Hören",
        minutes: 20,
        maxPoints: 15,
        weight: 25,
        parts: [
          {
            id: "a1-hoeren-1",
            title: "Teil 1 — Kurze Gespräche (2× hören)",
            instructions: "Sie hören drei kurze Gespräche. Wählen Sie die richtige Antwort.",
            skill: "listening",
            minutes: 8,
            maxPoints: 6,
            playLimit: 2,
            audio: [
              { speaker: "Verkäuferin", de: "Guten Tag, was möchten Sie?" },
              { speaker: "Kunde", de: "Ich möchte zwei Brötchen und ein Stück Kuchen, bitte." },
              { speaker: "Verkäuferin", de: "Das macht drei Euro vierzig." },
              { speaker: "Frau am Telefon", de: "Der Kurs beginnt am Montag um achtzehn Uhr, im Raum zwei null vier." },
              { speaker: "Mann", de: "Entschuldigung, wie komme ich zum Bahnhof?" },
              { speaker: "Passantin", de: "Gehen Sie geradeaus und dann an der Ampel links. Das sind fünf Minuten zu Fuß." },
            ],
            items: [
              {
                id: "e-a1-h1-1", type: "multiple-choice",
                prompt: "Was kauft der Kunde?",
                options: ["Zwei Brötchen und Kuchen", "Ein Brötchen und Kaffee", "Zwei Stück Kuchen", "Brot und Milch"],
                answerIndex: 0, explanation: "„zwei Brötchen und ein Stück Kuchen“.", skill: "listening", points: 2,
              },
              {
                id: "e-a1-h1-2", type: "multiple-choice",
                prompt: "In welchem Raum ist der Kurs?",
                options: ["204", "240", "024", "402"],
                answerIndex: 0, explanation: "„Raum zwei null vier“.", skill: "listening", points: 2,
              },
              {
                id: "e-a1-h1-3", type: "multiple-choice",
                prompt: "Wie weit ist der Bahnhof?",
                options: ["Zwei Minuten", "Fünf Minuten zu Fuß", "Fünfzehn Minuten", "Mit dem Bus"],
                answerIndex: 1, explanation: "„fünf Minuten zu Fuß“.", skill: "listening", points: 2,
              },
            ],
          },
          {
            id: "a1-hoeren-2",
            title: "Teil 2 — Ansagen (1× hören)",
            instructions: "Sie hören drei Ansagen nur einmal. Richtig oder falsch?",
            skill: "listening",
            minutes: 6,
            maxPoints: 5,
            playLimit: 1,
            audio: [
              { speaker: "Ansage", de: "Liebe Kunden, unser Markt schließt heute bereits um achtzehn Uhr. Morgen sind wir wieder ab sieben Uhr für Sie da." },
              { speaker: "Ansage", de: "Achtung an Gleis drei: Der Zug nach Dresden fährt heute von Gleis fünf." },
              { speaker: "Ansage", de: "Der Deutschkurs A1 findet morgen nicht statt. Die Lehrerin ist krank." },
            ],
            items: [
              {
                id: "e-a1-h2-1", type: "true-false",
                prompt: "Der Markt schließt heute früher.", answer: true,
                explanation: "„schließt heute bereits um achtzehn Uhr“.", skill: "listening", points: 1,
              },
              {
                id: "e-a1-h2-2", type: "true-false",
                prompt: "Der Zug nach Dresden fährt von Gleis drei.", answer: false,
                explanation: "Er fährt von Gleis fünf.", skill: "listening", points: 2,
              },
              {
                id: "e-a1-h2-3", type: "true-false",
                prompt: "Der Deutschkurs findet morgen statt.", answer: false,
                explanation: "„findet morgen nicht statt“.", skill: "listening", points: 2,
              },
            ],
          },
          {
            id: "a1-hoeren-3",
            title: "Teil 3 — Nachrichten auf dem Anrufbeantworter",
            instructions: "Notieren Sie die Informationen.",
            skill: "listening",
            minutes: 6,
            maxPoints: 4,
            playLimit: 2,
            audio: [
              { speaker: "Lena", de: "Hallo Nour, hier ist Lena. Wir treffen uns morgen um neunzehn Uhr dreißig vor dem Kino, nicht um neunzehn Uhr. Bring bitte deinen Studentenausweis mit, dann ist es billiger. Bis dann!" },
            ],
            items: [
              {
                id: "e-a1-h3-1", type: "fill-blank",
                prompt: "Wann treffen sie sich?",
                sentence: "Um ___ Uhr ___.",
                answers: [["19", "neunzehn"], ["30", "dreißig"]],
                explanation: "„neunzehn Uhr dreißig“.", skill: "listening", points: 2,
              },
              {
                id: "e-a1-h3-2", type: "multiple-choice",
                prompt: "Was soll Nour mitbringen?",
                options: ["Geld", "Den Studentenausweis", "Eine Jacke", "Popcorn"],
                answerIndex: 1, explanation: "„Bring bitte deinen Studentenausweis mit“.", skill: "listening", points: 2,
              },
            ],
          },
        ],
      },
      {
        id: "a1-schreiben",
        skill: "writing",
        title: "Schreiben",
        minutes: 20,
        maxPoints: 10,
        weight: 25,
        parts: [
          {
            id: "a1-schreiben-1",
            title: "Teil 1 — Formular ausfüllen",
            instructions: "Ergänzen Sie die fehlenden Angaben im Anmeldeformular für den Sprachkurs.",
            skill: "writing",
            minutes: 8,
            maxPoints: 5,
            reading: [
              "Anmeldeformular Sprachschule Mitte: Familienname ______ | Vorname ______ | Geburtsdatum ______ | Staatsangehörigkeit ______ | Kursniveau ______",
              "Angaben: Nour Benali, geboren am 3. März 2003 in Rabat, Marokko, möchte einen A1-Kurs besuchen.",
            ],
            items: [
              {
                id: "e-a1-s1-1", type: "fill-blank",
                prompt: "Ergänzen Sie das Formular.",
                sentence: "Familienname: ___ | Vorname: ___ | Staatsangehörigkeit: ___ | Kursniveau: ___",
                answers: [["Benali"], ["Nour"], ["marokkanisch", "Marokko"], ["A1"]],
                explanation: "Familienname = Nachname; Staatsangehörigkeit als Adjektiv oder Land.",
                skill: "writing", points: 5,
              },
            ],
          },
          {
            id: "a1-schreiben-2",
            title: "Teil 2 — Kurze Mitteilung",
            instructions:
              "Ihr Deutschkurs beginnt nächste Woche. Schreiben Sie Ihrer Freundin Lena (ca. 30 Wörter): Kursbeginn nennen, Uhrzeit, und fragen, ob sie mitkommt.",
            skill: "writing",
            minutes: 12,
            maxPoints: 5,
            items: [
              {
                id: "e-a1-s2-1", type: "writing",
                prompt: "Schreiben Sie die Nachricht (Anrede, drei Punkte, Gruß).",
                minWords: 30,
                checklist: ["Anrede", "Kursbeginn", "Uhrzeit", "Frage an Lena", "Gruß"],
                sampleAnswer:
                  "Hallo Lena,\n\nmein Deutschkurs beginnt am Montag. Der Unterricht ist von 18 bis 20 Uhr in der Sprachschule Mitte. Kommst du mit? Wir können zusammen hingehen.\n\nLiebe Grüße\nNour",
                explanation: "Alle drei Inhaltspunkte plus Anrede und Gruß sind Pflicht.",
                skill: "writing", points: 5,
              },
            ],
          },
        ],
      },
      {
        id: "a1-sprechen",
        skill: "speaking",
        title: "Sprechen",
        minutes: 15,
        maxPoints: 15,
        weight: 25,
        parts: [
          {
            id: "a1-sprechen-1",
            title: "Teil 1 — Sich vorstellen",
            instructions:
              "Stellen Sie sich vor: Name, Alter, Land, Wohnort, Sprachen, Beruf. Buchstabieren Sie am Ende Ihren Namen und sagen Sie Ihre Telefonnummer.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 5,
            items: [
              {
                id: "e-a1-sp1-1", type: "speaking",
                prompt: "Sprechen Sie 60 Sekunden über sich.",
                target:
                  "Ich heiße Nour Benali. Ich bin 23 Jahre alt und komme aus Marokko. Ich wohne in Leipzig. Ich spreche Arabisch, Französisch und ein bisschen Deutsch. Ich arbeite in einem Café.",
                tips: ["Sechs Informationen nennen", "langsam buchstabieren", "Telefonnummer in Zweiergruppen"],
                skill: "speaking", points: 5,
              },
            ],
          },
          {
            id: "a1-sprechen-2",
            title: "Teil 2 — Um Informationen bitten",
            instructions: "Stellen Sie Fragen zum Thema „Wohnung“ und antworten Sie auf Fragen.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 5,
            items: [
              {
                id: "e-a1-sp2-1", type: "speaking",
                prompt: "Stichwort: Miete — stellen Sie eine Frage.",
                target: "Wie hoch ist die Miete?",
                tips: ["W-Frage bilden", "Verb an Position 2"],
                skill: "speaking", points: 2,
              },
              {
                id: "e-a1-sp2-2", type: "speaking",
                prompt: "Stichwort: Zimmer — stellen Sie eine Frage.",
                target: "Wie viele Zimmer hat die Wohnung?",
                skill: "speaking", points: 3,
              },
            ],
          },
          {
            id: "a1-sprechen-3",
            title: "Teil 3 — Bitten und darauf reagieren",
            instructions: "Formulieren Sie höfliche Bitten mit den Bildkarten (Fenster, Stift, Wasser).",
            skill: "speaking",
            minutes: 5,
            maxPoints: 5,
            items: [
              {
                id: "e-a1-sp3-1", type: "speaking",
                prompt: "Bildkarte: Fenster",
                target: "Können Sie bitte das Fenster öffnen?",
                tips: ["Modalverb + bitte", "Verb am Ende"],
                skill: "speaking", points: 3,
              },
              {
                id: "e-a1-sp3-2", type: "speaking",
                prompt: "Reagieren Sie freundlich auf eine Bitte.",
                target: "Ja, natürlich. Gern!",
                skill: "speaking", points: 2,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    slug: "goethe-a2-mock-1",
    provider: "goethe",
    level: "A2",
    title: "Goethe-Zertifikat A2 — Mock exam 1",
    officialName: "Goethe-Zertifikat A2",
    minutes: 90,
    passMark: 60,
    description:
      "Lesen (30 min), Hören (30 min), Schreiben (30 min), Sprechen (15 min). Everyday topics: work, health, housing, free time.",
    strategies: [
      { title: "Match tasks by keyword", body: "In Lesen Teil 2 you match people to adverts. Underline the one decisive keyword for each person first." },
      { title: "Use your notes", body: "In Hören you may write on the sheet. Note numbers and names as digits and initials to keep up." },
      { title: "Plan 5 minutes for writing", body: "Two short texts in 30 minutes: sketch the three bullets, then write, then check verb position and endings." },
      { title: "Sprechen Teil 3 is negotiation", body: "Make a proposal, react to your partner, and agree on a final time and place." },
    ],
    sections: [
      {
        id: "a2-lesen",
        skill: "reading",
        title: "Lesen",
        minutes: 30,
        maxPoints: 20,
        weight: 25,
        parts: [
          {
            id: "a2-lesen-1",
            title: "Teil 1 — E-Mail verstehen",
            instructions: "Lesen Sie die E-Mail und wählen Sie die richtige Antwort.",
            skill: "reading",
            minutes: 10,
            maxPoints: 8,
            reading: [
              "Hallo Karim,\n\nendlich habe ich eine Wohnung gefunden! Sie liegt in Plagwitz, hat zwei Zimmer und kostet 590 Euro warm. Am Samstag ziehe ich um. Kannst du mir helfen? Wir fangen um 9 Uhr an, ein Freund bringt einen Transporter mit. Zu essen bestellen wir mittags Pizza.\n\nEine Bitte: Ich brauche noch einen Tisch. Hast du noch den alten aus deiner WG? Wenn nicht, kaufe ich einen gebrauchten.\n\nSag mir bitte bis Donnerstag Bescheid.\n\nViele Grüße\nNour",
            ],
            items: [
              {
                id: "e-a2-l1-1", type: "multiple-choice",
                prompt: "Warum schreibt Nour?",
                options: ["Sie sucht eine Wohnung.", "Sie braucht Hilfe beim Umzug.", "Sie möchte Pizza essen.", "Sie verkauft einen Tisch."],
                answerIndex: 1, explanation: "„Kannst du mir helfen?“ beim Umzug.", skill: "reading", points: 2,
              },
              {
                id: "e-a2-l1-2", type: "multiple-choice",
                prompt: "Wann beginnt der Umzug?",
                options: ["Donnerstag 9 Uhr", "Samstag 9 Uhr", "Samstag mittags", "Sonntag 9 Uhr"],
                answerIndex: 1, explanation: "„Am Samstag … um 9 Uhr“.", skill: "reading", points: 2,
              },
              {
                id: "e-a2-l1-3", type: "true-false",
                prompt: "Nour hat schon einen Tisch.", answer: false,
                explanation: "„Ich brauche noch einen Tisch.“", skill: "reading", points: 2,
              },
              {
                id: "e-a2-l1-4", type: "fill-blank",
                prompt: "Wie viel kostet die Wohnung?",
                sentence: "___ Euro warm.", answers: [["590"]],
                explanation: "Siehe Absatz 1.", skill: "reading", points: 2,
              },
            ],
          },
          {
            id: "a2-lesen-2",
            title: "Teil 2 — Anzeigen zuordnen",
            instructions: "Welche Anzeige passt zu welcher Person?",
            skill: "reading",
            minutes: 10,
            maxPoints: 6,
            reading: [
              "1) Nebenjob: Zeitungen austragen, früh morgens, 2 Stunden täglich, 12 €/Stunde.",
              "2) Deutschkurs für Pflegekräfte, B1/B2, dienstags und donnerstags abends, mit Fachvokabular.",
              "3) Fahrrad zu verkaufen, 21 Gänge, guter Zustand, 120 € VB, Abholung in Leipzig-Süd.",
              "4) Wohnung gesucht? Wir vermitteln WG-Zimmer ab 300 € warm, keine Provision.",
            ],
            items: [
              {
                id: "e-a2-l2-1", type: "multiple-choice",
                prompt: "Karim arbeitet als Pflegehelfer und möchte sein Fachdeutsch verbessern.",
                options: ["Anzeige 1", "Anzeige 2", "Anzeige 3", "Anzeige 4"],
                answerIndex: 1, explanation: "Deutschkurs für Pflegekräfte.", skill: "reading", points: 2,
              },
              {
                id: "e-a2-l2-2", type: "multiple-choice",
                prompt: "Sofia hat vormittags Kurs und sucht Arbeit am frühen Morgen.",
                options: ["Anzeige 1", "Anzeige 2", "Anzeige 3", "Anzeige 4"],
                answerIndex: 0, explanation: "Zeitungen austragen, früh morgens.", skill: "reading", points: 2,
              },
              {
                id: "e-a2-l2-3", type: "multiple-choice",
                prompt: "Ali braucht ein günstiges Zimmer.",
                options: ["Anzeige 1", "Anzeige 2", "Anzeige 3", "Anzeige 4"],
                answerIndex: 3, explanation: "WG-Zimmer ab 300 € warm.", skill: "reading", points: 2,
              },
            ],
          },
          {
            id: "a2-lesen-3",
            title: "Teil 3 — Informationstext",
            instructions: "Lesen Sie den Text über Mülltrennung und beantworten Sie die Fragen.",
            skill: "reading",
            minutes: 10,
            maxPoints: 6,
            reading: [
              "In Deutschland wird der Müll getrennt. Papier und Kartons gehören in die blaue Tonne. Verpackungen aus Plastik und Metall kommen in den gelben Sack. Essensreste und Gartenabfälle gehören in die braune Biotonne. Alles andere ist Restmüll und kommt in die schwarze oder graue Tonne. Glas bringt man zum Container und sortiert es nach Farben: weiß, grün und braun. Achtung: Flaschen mit Pfand gibt man im Supermarkt zurück und bekommt Geld dafür. Batterien und Elektrogeräte dürfen nicht in den Hausmüll; sie gehören zu speziellen Sammelstellen.",
            ],
            items: [
              {
                id: "e-a2-l3-1", type: "multiple-choice",
                prompt: "Wohin kommen Plastikverpackungen?",
                options: ["Blaue Tonne", "Gelber Sack", "Biotonne", "Restmüll"],
                answerIndex: 1, explanation: "„Verpackungen aus Plastik und Metall kommen in den gelben Sack.“", skill: "reading", points: 2,
              },
              {
                id: "e-a2-l3-2", type: "true-false",
                prompt: "Batterien darf man in den Hausmüll werfen.", answer: false,
                explanation: "Sie gehören zu Sammelstellen.", skill: "reading", points: 2,
              },
              {
                id: "e-a2-l3-3", type: "multiple-choice",
                prompt: "Was macht man mit Pfandflaschen?",
                options: ["Zum Container bringen", "In den gelben Sack", "Im Supermarkt zurückgeben", "In die Biotonne"],
                answerIndex: 2, explanation: "„gibt man im Supermarkt zurück“.", skill: "reading", points: 2,
              },
            ],
          },
        ],
      },
      {
        id: "a2-hoeren",
        skill: "listening",
        title: "Hören",
        minutes: 30,
        maxPoints: 20,
        weight: 25,
        parts: [
          {
            id: "a2-hoeren-1",
            title: "Teil 1 — Gespräch am Telefon",
            instructions: "Sie hören ein Telefongespräch. Beantworten Sie die Fragen.",
            skill: "listening",
            minutes: 12,
            maxPoints: 10,
            playLimit: 2,
            audio: [
              { speaker: "Praxis", de: "Praxis Dr. Hoffmann, guten Tag." },
              { speaker: "Karim", de: "Guten Tag, Karim Aziz. Ich würde gern einen Termin vereinbaren." },
              { speaker: "Praxis", de: "Wir hätten am Donnerstag um zehn Uhr dreißig oder am Freitag um sechzehn Uhr etwas frei." },
              { speaker: "Karim", de: "Donnerstag passt besser, am Freitag arbeite ich." },
              { speaker: "Praxis", de: "Gut. Bringen Sie bitte Ihre Versichertenkarte mit und kommen Sie zehn Minuten früher." },
            ],
            items: [
              {
                id: "e-a2-h1-1", type: "multiple-choice",
                prompt: "Welchen Termin nimmt Karim?",
                options: ["Donnerstag 10:30", "Freitag 16:00", "Donnerstag 16:00", "Freitag 10:30"],
                answerIndex: 0, explanation: "„Donnerstag passt besser“.", skill: "listening", points: 4,
              },
              {
                id: "e-a2-h1-2", type: "multiple-choice",
                prompt: "Warum passt der andere Termin nicht?",
                options: ["Er ist krank.", "Er arbeitet.", "Er hat Kurs.", "Er ist im Urlaub."],
                answerIndex: 1, explanation: "„am Freitag arbeite ich“.", skill: "listening", points: 3,
              },
              {
                id: "e-a2-h1-3", type: "fill-blank",
                prompt: "Was soll er mitbringen?",
                sentence: "Die ___.", answers: [["Versichertenkarte"]],
                explanation: "Standardfrage im Gesundheitswesen.", skill: "listening", points: 3,
              },
            ],
          },
          {
            id: "a2-hoeren-2",
            title: "Teil 2 — Durchsagen und Nachrichten",
            instructions: "Sie hören drei Texte einmal. Richtig oder falsch?",
            skill: "listening",
            minutes: 10,
            maxPoints: 6,
            playLimit: 1,
            audio: [
              { speaker: "Ansage", de: "Wegen einer Baustelle fährt die Linie zwölf heute nur bis zur Haltestelle Hafenstraße. Bitte steigen Sie dort in den Ersatzbus um." },
              { speaker: "Mailbox", de: "Hallo Nour, hier ist Frau Berger. Der Unterricht morgen beginnt erst um zehn Uhr, nicht um neun." },
              { speaker: "Ansage", de: "Im Supermarkt gibt es heute Äpfel im Angebot: ein Kilo für einen Euro neunundneunzig." },
            ],
            items: [
              {
                id: "e-a2-h2-1", type: "true-false",
                prompt: "Die Linie 12 fährt heute die ganze Strecke.", answer: false,
                explanation: "Nur bis Hafenstraße, dann Ersatzbus.", skill: "listening", points: 2,
              },
              {
                id: "e-a2-h2-2", type: "true-false",
                prompt: "Der Unterricht beginnt morgen später.", answer: true,
                explanation: "„erst um zehn Uhr“.", skill: "listening", points: 2,
              },
              {
                id: "e-a2-h2-3", type: "fill-blank",
                prompt: "Was kostet ein Kilo Äpfel?",
                sentence: "___ Euro ___.", answers: [["1", "ein", "einen"], ["99", "neunundneunzig"]],
                explanation: "1,99 €.", skill: "listening", points: 2,
              },
            ],
          },
          {
            id: "a2-hoeren-3",
            title: "Teil 3 — Radiointerview",
            instructions: "Hören Sie das Interview und wählen Sie die richtige Antwort.",
            skill: "listening",
            minutes: 8,
            maxPoints: 4,
            playLimit: 2,
            audio: [
              { speaker: "Moderator", de: "Herr Sommer, Sie suchen Auszubildende. Was ist Ihnen wichtig?" },
              { speaker: "Herr Sommer", de: "Ehrlich gesagt nicht die perfekte Note, sondern Pünktlichkeit und Interesse an der Technik. Deutsch auf dem Niveau B1 reicht am Anfang; Fachwörter lernen die Azubis bei uns." },
              { speaker: "Moderator", de: "Und wie bewirbt man sich?" },
              { speaker: "Herr Sommer", de: "Am besten per E-Mail mit Lebenslauf. Ein kurzes Anschreiben genügt." },
            ],
            items: [
              {
                id: "e-a2-h3-1", type: "multiple-choice",
                prompt: "Was ist Herrn Sommer am wichtigsten?",
                options: ["Sehr gute Noten", "Pünktlichkeit und Interesse", "Perfektes Deutsch", "Berufserfahrung"],
                answerIndex: 1, explanation: "„nicht die perfekte Note, sondern Pünktlichkeit und Interesse“.", skill: "listening", points: 2,
              },
              {
                id: "e-a2-h3-2", type: "multiple-choice",
                prompt: "Wie soll man sich bewerben?",
                options: ["Persönlich", "Per Post", "Per E-Mail mit Lebenslauf", "Über die Kammer"],
                answerIndex: 2, explanation: "„Am besten per E-Mail mit Lebenslauf.“", skill: "listening", points: 2,
              },
            ],
          },
        ],
      },
      {
        id: "a2-schreiben",
        skill: "writing",
        title: "Schreiben",
        minutes: 30,
        maxPoints: 20,
        weight: 25,
        parts: [
          {
            id: "a2-schreiben-1",
            title: "Teil 1 — SMS / kurze Nachricht",
            instructions:
              "Sie kommen später zur Arbeit, weil die Straßenbahn ausgefallen ist. Schreiben Sie Ihrer Chefin (ca. 30 Wörter).",
            skill: "writing",
            minutes: 10,
            maxPoints: 8,
            items: [
              {
                id: "e-a2-s1-1", type: "writing",
                prompt: "Schreiben Sie die Nachricht.",
                minWords: 30,
                checklist: ["Anrede (Sie-Form)", "Grund", "voraussichtliche Verspätung", "Entschuldigung"],
                sampleAnswer:
                  "Guten Morgen Frau Vogt,\n\nleider ist die Straßenbahn ausgefallen. Ich komme etwa 20 Minuten später. Es tut mir leid. Ich beginne dann sofort mit der Übergabe.\n\nViele Grüße\nKarim Aziz",
                skill: "writing", points: 8,
              },
            ],
          },
          {
            id: "a2-schreiben-2",
            title: "Teil 2 — E-Mail schreiben",
            instructions:
              "Ihr Kurs macht einen Ausflug. Schreiben Sie an Ihre Kursleiterin: Sie können nicht mitkommen. Nennen Sie den Grund, entschuldigen Sie sich und fragen Sie nach den Aufgaben (ca. 60 Wörter).",
            skill: "writing",
            minutes: 20,
            maxPoints: 12,
            items: [
              {
                id: "e-a2-s2-1", type: "writing",
                prompt: "Schreiben Sie die E-Mail.",
                minWords: 60,
                checklist: [
                  "formelle Anrede und Grußformel",
                  "Grund genannt",
                  "Entschuldigung",
                  "Frage nach Aufgaben",
                  "Nebensatz mit weil oder dass",
                ],
                sampleAnswer:
                  "Sehr geehrte Frau Berger,\n\nleider kann ich am Ausflug nächste Woche nicht teilnehmen, weil ich an diesem Tag arbeiten muss. Mein Chef hat den Dienstplan erst gestern geändert. Ich finde das sehr schade und entschuldige mich.\n\nKönnten Sie mir bitte sagen, welche Aufgaben ich zu Hause machen soll? Ich möchte nichts verpassen.\n\nVielen Dank und viele Grüße\nKarim Aziz",
                skill: "writing", points: 12,
              },
            ],
          },
        ],
      },
      {
        id: "a2-sprechen",
        skill: "speaking",
        title: "Sprechen",
        minutes: 15,
        maxPoints: 20,
        weight: 25,
        parts: [
          {
            id: "a2-sprechen-1",
            title: "Teil 1 — Über sich sprechen",
            instructions: "Stichworte: Wohnort, Familie, Arbeit/Kurs, Sprachen, Hobbys, Zukunftsplan.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 6,
            items: [
              {
                id: "e-a2-sp1-1", type: "speaking",
                prompt: "Sprechen Sie 90 Sekunden über sich, mit einem Satz über Ihre Pläne.",
                target:
                  "Ich wohne seit acht Monaten in Leipzig. Ich arbeite in einem Café und besuche abends einen Deutschkurs. Nächstes Jahr möchte ich eine Ausbildung als Pflegefachkraft anfangen.",
                tips: ["Perfekt für Vergangenheit", "möchten für Pläne"],
                skill: "speaking", points: 6,
              },
            ],
          },
          {
            id: "a2-sprechen-2",
            title: "Teil 2 — Über ein Thema sprechen",
            instructions: "Thema: „Mein Weg zur Arbeit“. Beschreiben Sie und vergleichen Sie mit Ihrem Heimatland.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 7,
            items: [
              {
                id: "e-a2-sp2-1", type: "speaking",
                prompt: "Sprechen Sie 2 Minuten.",
                target:
                  "Normalerweise fahre ich mit der Straßenbahn zur Arbeit, das dauert 20 Minuten. In Marokko bin ich meistens mit dem Bus oder zu Fuß gegangen, weil die Wege kürzer waren.",
                tips: ["Vergleich mit als/wie", "Zeitangaben nutzen"],
                skill: "speaking", points: 7,
              },
            ],
          },
          {
            id: "a2-sprechen-3",
            title: "Teil 3 — Etwas gemeinsam planen",
            instructions: "Planen Sie mit Ihrem Partner einen Ausflug am Samstag: Zeit, Ort, Treffpunkt, Essen.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 7,
            items: [
              {
                id: "e-a2-sp3-1", type: "speaking",
                prompt: "Machen Sie einen Vorschlag und reagieren Sie auf einen Gegenvorschlag.",
                target:
                  "Wollen wir am Samstag um zehn Uhr zum See fahren? Wir könnten uns am Hauptbahnhof treffen. Ich bringe Wasser und Obst mit.",
                tips: ["Wollen wir …?", "Ich schlage vor, …", "Einverstanden!"],
                skill: "speaking", points: 7,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    slug: "goethe-b1-mock-1",
    provider: "goethe",
    level: "B1",
    title: "Goethe-Zertifikat B1 — Mock exam 1",
    officialName: "Goethe-Zertifikat B1 (Zertifikat Deutsch)",
    minutes: 165,
    passMark: 60,
    description:
      "Lesen (65 min), Hören (40 min), Schreiben (60 min), Sprechen (15 min). Each module is passed separately with 60 %.",
    strategies: [
      { title: "Modules are independent", body: "You can retake a single failed module. Plan your revision around your weakest skill, not around the average." },
      { title: "Lesen Teil 2 = matching", body: "Read the headline and the first sentence of each text; that is usually enough for the matching task." },
      { title: "Schreiben Teil 1 is a forum post", body: "80 words, personal opinion, at least one reason and one example. Teil 2 is a formal email — switch register completely." },
      { title: "Sprechen Teil 1 is planning", body: "You plan something together. Make three concrete proposals and react to your partner rather than reading a monologue." },
    ],
    sections: [
      {
        id: "b1-lesen",
        skill: "reading",
        title: "Lesen",
        minutes: 65,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b1-lesen-1",
            title: "Teil 1 — Blogbeitrag",
            instructions: "Lesen Sie den Text und entscheiden Sie: richtig oder falsch.",
            skill: "reading",
            minutes: 20,
            maxPoints: 12,
            reading: [
              "Vor zwei Jahren bin ich für eine Ausbildung nach Deutschland gekommen. Am Anfang war alles fremd: das Wetter, das Essen und besonders die Bürokratie. Ich musste mich innerhalb von zwei Wochen anmelden, ein Konto eröffnen und eine Krankenversicherung abschließen — und das alles auf Deutsch, obwohl mein Niveau damals nur A2 war.",
              "Am schwierigsten war für mich nicht die Grammatik, sondern das Tempo. Im Betrieb sprechen alle schnell und benutzen Wörter, die in keinem Lehrbuch stehen. Ich habe mir deshalb angewöhnt, jeden Tag fünf neue Fachwörter aufzuschreiben und sie abends laut zu wiederholen. Nach drei Monaten habe ich zum ersten Mal ein Kundengespräch allein geführt.",
              "Was mir wirklich geholfen hat, war ein Kollege, der geduldig war und mich korrigiert hat, ohne mich vor anderen bloßzustellen. Wenn ich heute neuen Azubis einen Tipp geben soll, sage ich: Fragt sofort nach, wenn ihr etwas nicht versteht. Niemand denkt, dass ihr dumm seid — im Gegenteil, es zeigt, dass ihr sicher arbeiten wollt.",
            ],
            items: [
              {
                id: "e-b1-l1-1", type: "true-false",
                prompt: "Der Autor hatte am Anfang das Niveau B1.", answer: false,
                explanation: "„mein Niveau damals nur A2“.", skill: "reading", points: 2,
              },
              {
                id: "e-b1-l1-2", type: "true-false",
                prompt: "Für den Autor war die Grammatik das größte Problem.", answer: false,
                explanation: "„nicht die Grammatik, sondern das Tempo“.", skill: "reading", points: 2,
              },
              {
                id: "e-b1-l1-3", type: "multiple-choice",
                prompt: "Welche Lernstrategie beschreibt der Autor?",
                options: [
                  "Er hat Grammatikübungen gemacht.",
                  "Er hat täglich fünf Fachwörter notiert und laut wiederholt.",
                  "Er hat Filme auf Deutsch gesehen.",
                  "Er hat einen Privatlehrer genommen.",
                ],
                answerIndex: 1, explanation: "Absatz 2.", skill: "reading", points: 3,
              },
              {
                id: "e-b1-l1-4", type: "multiple-choice",
                prompt: "Welchen Tipp gibt er neuen Azubis?",
                options: [
                  "Nur zuhören und nicht störe",
                  "Sofort nachfragen, wenn man etwas nicht versteht",
                  "Zuerst die Sprache perfekt lernen",
                  "Kollegen nicht um Hilfe bitten",
                ],
                answerIndex: 1, explanation: "Letzter Absatz.", skill: "reading", points: 3,
              },
              {
                id: "e-b1-l1-5", type: "fill-blank",
                prompt: "Ergänzen Sie.",
                sentence: "Nach ___ Monaten führte er das erste Kundengespräch allein.",
                answers: [["drei", "3"]],
                explanation: "„Nach drei Monaten“.", skill: "reading", points: 2,
              },
            ],
          },
          {
            id: "b1-lesen-2",
            title: "Teil 2 — Meinungen zuordnen",
            instructions: "Wer sagt was? Ordnen Sie die Aussagen den Personen zu.",
            skill: "reading",
            minutes: 20,
            maxPoints: 9,
            reading: [
              "Sabine: Ich habe nach der Schule sofort studiert, aber nach zwei Semestern gemerkt, dass mir die Praxis fehlt. Heute mache ich eine Ausbildung und bereue nichts.",
              "Markus: Für mich war klar: erst Geld verdienen, dann eventuell studieren. Mit dem Meisterbrief kann man in Deutschland auch ohne Abitur studieren.",
              "Aylin: Ich habe beides kombiniert — ein duales Studium. Es ist anstrengend, aber ich habe einen Abschluss und Berufserfahrung gleichzeitig.",
            ],
            items: [
              {
                id: "e-b1-l2-1", type: "match",
                prompt: "Ordnen Sie zu.",
                pairs: [
                  { left: "hat das Studium abgebrochen", right: "Sabine" },
                  { left: "wollte zuerst Geld verdienen", right: "Markus" },
                  { left: "macht Studium und Ausbildung gleichzeitig", right: "Aylin" },
                ],
                explanation: "Jede Person nennt ihren Weg explizit.", skill: "reading", points: 6,
              },
              {
                id: "e-b1-l2-2", type: "multiple-choice",
                prompt: "Wer nennt einen Weg zum Studium ohne Abitur?",
                options: ["Sabine", "Markus", "Aylin", "Niemand"],
                answerIndex: 1, explanation: "Meisterbrief als Hochschulzugang.", skill: "reading", points: 3,
              },
            ],
          },
          {
            id: "b1-lesen-3",
            title: "Teil 3 — Anzeigen und Situationen",
            instructions: "Welche Anzeige passt zu welcher Situation? Es gibt eine Anzeige zu viel.",
            skill: "reading",
            minutes: 15,
            maxPoints: 9,
            reading: [
              "A) Sprachcafé jeden Mittwoch, 18–20 Uhr, kostenlos, alle Niveaus, Anmeldung nicht nötig.",
              "B) Nachhilfe Mathematik für Berufsschüler, 15 €/Stunde, online oder vor Ort.",
              "C) Bewerbungstraining: Lebenslauf und Anschreiben prüfen lassen, Termine nach Absprache, kostenlos für Azubis.",
              "D) Umzugshelfer gesucht, Samstag, 10 €/Stunde, kurzfristig.",
            ],
            items: [
              {
                id: "e-b1-l3-1", type: "multiple-choice",
                prompt: "Karim möchte sein Anschreiben korrigieren lassen.",
                options: ["A", "B", "C", "D"], answerIndex: 2,
                explanation: "Bewerbungstraining.", skill: "reading", points: 3,
              },
              {
                id: "e-b1-l3-2", type: "multiple-choice",
                prompt: "Nour will ohne Anmeldung locker Deutsch sprechen.",
                options: ["A", "B", "C", "D"], answerIndex: 0,
                explanation: "Sprachcafé, keine Anmeldung.", skill: "reading", points: 3,
              },
              {
                id: "e-b1-l3-3", type: "multiple-choice",
                prompt: "Ali hat Probleme in Mathematik in der Berufsschule.",
                options: ["A", "B", "C", "D"], answerIndex: 1,
                explanation: "Nachhilfe Mathematik.", skill: "reading", points: 3,
              },
            ],
          },
        ],
      },
      {
        id: "b1-hoeren",
        skill: "listening",
        title: "Hören",
        minutes: 40,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b1-hoeren-1",
            title: "Teil 1 — Alltagsgespräch",
            instructions: "Sie hören ein Gespräch zweimal. Beantworten Sie die Fragen.",
            skill: "listening",
            minutes: 15,
            maxPoints: 12,
            playLimit: 2,
            audio: [
              { speaker: "Frau Vogt", de: "Herr Aziz, wir müssen über Ihren Dienstplan sprechen. Nächsten Monat brauchen wir Sie zweimal in der Spätschicht." },
              { speaker: "Karim", de: "Grundsätzlich gern, aber am Dienstag habe ich Berufsschule bis achtzehn Uhr." },
              { speaker: "Frau Vogt", de: "Dann nehmen wir Mittwoch und Donnerstag. Die Spätschicht geht von vierzehn bis zweiundzwanzig Uhr." },
              { speaker: "Karim", de: "Das passt. Bekomme ich dafür einen freien Tag?" },
              { speaker: "Frau Vogt", de: "Ja, den Freitag. Und denken Sie daran: Bei Spätschicht ist die Übergabe besonders wichtig." },
            ],
            items: [
              {
                id: "e-b1-h1-1", type: "multiple-choice",
                prompt: "An welchen Tagen macht Karim Spätschicht?",
                options: ["Montag und Dienstag", "Mittwoch und Donnerstag", "Dienstag und Freitag", "Donnerstag und Freitag"],
                answerIndex: 1, explanation: "„Dann nehmen wir Mittwoch und Donnerstag.“", skill: "listening", points: 4,
              },
              {
                id: "e-b1-h1-2", type: "fill-blank",
                prompt: "Wann ist die Spätschicht?",
                sentence: "Von ___ bis ___ Uhr.",
                answers: [["14", "vierzehn"], ["22", "zweiundzwanzig"]],
                explanation: "14–22 Uhr.", skill: "listening", points: 4,
              },
              {
                id: "e-b1-h1-3", type: "multiple-choice",
                prompt: "Warum kann er am Dienstag nicht?",
                options: ["Arzttermin", "Berufsschule", "Urlaub", "Sprachkurs"],
                answerIndex: 1, explanation: "„am Dienstag habe ich Berufsschule“.", skill: "listening", points: 4,
              },
            ],
          },
          {
            id: "b1-hoeren-2",
            title: "Teil 2 — Radiobeitrag",
            instructions: "Sie hören den Beitrag einmal. Wählen Sie die richtige Antwort.",
            skill: "listening",
            minutes: 15,
            maxPoints: 12,
            playLimit: 1,
            audio: [
              { speaker: "Sprecherin", de: "Wer in Deutschland eine Wohnung sucht, braucht Geduld. Auf eine Anzeige kommen in Großstädten oft mehr als hundert Bewerbungen." },
              { speaker: "Beraterin", de: "Wichtig sind vollständige Unterlagen: Gehaltsnachweise der letzten drei Monate, eine Schufa-Auskunft und der Ausweis. Wer das digital bereit hat, ist deutlich schneller." },
              { speaker: "Sprecherin", de: "Und wenn man neu im Land ist?" },
              { speaker: "Beraterin", de: "Dann hilft eine Arbeitgeberbestätigung oder ein Bürge. Manche Vermieter akzeptieren auch eine höhere Kaution." },
            ],
            items: [
              {
                id: "e-b1-h2-1", type: "multiple-choice",
                prompt: "Welche Unterlagen nennt die Beraterin?",
                options: [
                  "Nur den Ausweis",
                  "Gehaltsnachweise, Schufa-Auskunft, Ausweis",
                  "Mietvertrag und Foto",
                  "Nur die Schufa-Auskunft",
                ],
                answerIndex: 1, explanation: "Zweiter Beitrag.", skill: "listening", points: 4,
              },
              {
                id: "e-b1-h2-2", type: "multiple-choice",
                prompt: "Was hilft Neuankömmlingen?",
                options: ["Arbeitgeberbestätigung oder Bürge", "Ein Auto", "Ein Studium", "Nichts"],
                answerIndex: 0, explanation: "Letzter Beitrag.", skill: "listening", points: 4,
              },
              {
                id: "e-b1-h2-3", type: "true-false",
                prompt: "Auf eine Anzeige kommen in Großstädten oft über 100 Bewerbungen.",
                answer: true, explanation: "Erste Aussage.", skill: "listening", points: 4,
              },
            ],
          },
          {
            id: "b1-hoeren-3",
            title: "Teil 3 — Diskussion",
            instructions: "Wer sagt was? Ordnen Sie zu.",
            skill: "listening",
            minutes: 10,
            maxPoints: 6,
            playLimit: 1,
            audio: [
              { speaker: "Tom", de: "Ich finde, der Betrieb sollte den Sprachkurs bezahlen. Wir arbeiten ja auch besser, wenn wir alles verstehen." },
              { speaker: "Lena", de: "Das sehe ich anders. Sprache ist Privatsache, und der Betrieb zahlt schon die Ausbildung." },
              { speaker: "Aylin", de: "Vielleicht ein Kompromiss: Der Betrieb stellt die Arbeitszeit, wir zahlen die Kursgebühr." },
            ],
            items: [
              {
                id: "e-b1-h3-1", type: "match",
                prompt: "Ordnen Sie die Positionen zu.",
                pairs: [
                  { left: "Tom", right: "Betrieb soll zahlen" },
                  { left: "Lena", right: "Sprache ist Privatsache" },
                  { left: "Aylin", right: "Kompromiss vorschlagen" },
                ],
                explanation: "Drei klare Positionen.", skill: "listening", points: 6,
              },
            ],
          },
        ],
      },
      {
        id: "b1-schreiben",
        skill: "writing",
        title: "Schreiben",
        minutes: 60,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b1-schreiben-1",
            title: "Teil 1 — Forumsbeitrag (ca. 80 Wörter)",
            instructions:
              "Im Forum wird diskutiert: „Sollten Betriebe Deutschkurse für Auszubildende bezahlen?“ Schreiben Sie Ihre Meinung mit Begründung und Beispiel.",
            skill: "writing",
            minutes: 20,
            maxPoints: 10,
            items: [
              {
                id: "e-b1-s1-1", type: "writing",
                prompt: "Schreiben Sie Ihren Forumsbeitrag.",
                minWords: 80,
                checklist: ["Meinung klar", "Begründung mit weil/denn", "Beispiel", "Gegenargument", "Fazit"],
                sampleAnswer:
                  "Meiner Meinung nach sollten Betriebe Deutschkurse mitfinanzieren. Wer die Sprache besser versteht, macht weniger Fehler und arbeitet sicherer. In meinem Betrieb ist letzten Monat eine Bestellung falsch rausgegangen, weil ein Kollege eine Anweisung nicht verstanden hat. Natürlich kostet ein Kurs Geld und Arbeitszeit, aber Fehler kosten am Ende mehr. Ein guter Kompromiss wäre, dass der Betrieb die Arbeitszeit stellt und die Azubis die Hausaufgaben in ihrer Freizeit machen. So investieren beide Seiten etwas.",
                skill: "writing", points: 10,
              },
            ],
          },
          {
            id: "b1-schreiben-2",
            title: "Teil 2 — Formelle E-Mail (ca. 40 Wörter)",
            instructions:
              "Sie können an einer Betriebsbesprechung nicht teilnehmen. Schreiben Sie eine formelle Nachricht an Frau Vogt.",
            skill: "writing",
            minutes: 15,
            maxPoints: 10,
            items: [
              {
                id: "e-b1-s2-1", type: "writing",
                prompt: "Schreiben Sie die formelle Nachricht.",
                minWords: 40,
                checklist: ["Sehr geehrte …", "Grund", "Alternative anbieten", "Mit freundlichen Grüßen"],
                sampleAnswer:
                  "Sehr geehrte Frau Vogt,\n\nleider kann ich an der Besprechung am Mittwoch nicht teilnehmen, da ich an diesem Tag Berufsschule habe. Könnten Sie mir das Protokoll zusenden? Gern stehe ich am Donnerstag für Rückfragen zur Verfügung.\n\nMit freundlichen Grüßen\nKarim Aziz",
                skill: "writing", points: 10,
              },
            ],
          },
          {
            id: "b1-schreiben-3",
            title: "Teil 3 — Private Nachricht (ca. 40 Wörter)",
            instructions: "Schreiben Sie Ihrem Freund, dass Sie am Wochenende umziehen und Hilfe brauchen.",
            skill: "writing",
            minutes: 25,
            maxPoints: 10,
            items: [
              {
                id: "e-b1-s3-1", type: "writing",
                prompt: "Schreiben Sie die Nachricht.",
                minWords: 40,
                checklist: ["informelle Anrede", "Anlass", "konkrete Bitte", "Uhrzeit/Ort", "informeller Gruß"],
                sampleAnswer:
                  "Hallo Ali,\n\nam Samstag ziehe ich endlich um! Hättest du Zeit zu helfen? Wir fangen um 9 Uhr in der Hafenstraße 14 an, ein Freund bringt einen Transporter. Mittags gibt es Pizza. Sag mir bitte bis Donnerstag Bescheid.\n\nLiebe Grüße\nKarim",
                skill: "writing", points: 10,
              },
            ],
          },
        ],
      },
      {
        id: "b1-sprechen",
        skill: "speaking",
        title: "Sprechen",
        minutes: 15,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b1-sprechen-1",
            title: "Teil 1 — Gemeinsam etwas planen",
            instructions: "Planen Sie mit Ihrem Partner eine Abschiedsfeier für eine Kollegin.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 10,
            items: [
              {
                id: "e-b1-sp1-1", type: "speaking",
                prompt: "Machen Sie Vorschläge zu Termin, Ort, Essen und Geschenk.",
                target:
                  "Ich schlage vor, wir feiern am Freitag nach der Spätschicht. Wir könnten den Pausenraum dekorieren und etwas zu essen bestellen. Was hältst du von einem gemeinsamen Geschenk?",
                tips: ["Ich schlage vor, …", "Was hältst du von …?", "Einverstanden, aber …"],
                skill: "speaking", points: 10,
              },
            ],
          },
          {
            id: "b1-sprechen-2",
            title: "Teil 2 — Präsentation",
            instructions: "Thema: „Lernen mit dem Handy“. Struktur: Einleitung, eigene Erfahrung, Situation im Heimatland, Vor- und Nachteile, Fazit.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 10,
            items: [
              {
                id: "e-b1-sp2-1", type: "speaking",
                prompt: "Halten Sie die Präsentation (ca. 3 Minuten).",
                target:
                  "Ich möchte über das Lernen mit dem Handy sprechen. Ich benutze jeden Tag eine App für Vokabeln, meistens in der Straßenbahn. In Marokko lernen viele Freunde ebenfalls mit dem Handy, weil Kurse teuer sind. Ein Vorteil ist die Flexibilität, ein Nachteil die Ablenkung. Zusammenfassend finde ich, dass eine Kombination aus App und Kurs am besten funktioniert.",
                tips: ["fünf Abschnitte einhalten", "Konnektoren nutzen", "Fazit nicht vergessen"],
                skill: "speaking", points: 10,
              },
            ],
          },
          {
            id: "b1-sprechen-3",
            title: "Teil 3 — Rückmeldung und Fragen",
            instructions: "Stellen Sie Ihrem Partner eine Frage zur Präsentation und beantworten Sie eine Frage zu Ihrer.",
            skill: "speaking",
            minutes: 5,
            maxPoints: 10,
            items: [
              {
                id: "e-b1-sp3-1", type: "speaking",
                prompt: "Formulieren Sie eine Rückmeldung und eine Frage.",
                target:
                  "Vielen Dank für deine Präsentation, besonders interessant fand ich den Teil über die Ablenkung. Wie schaffst du es, nicht auf Social Media zu wechseln?",
                tips: ["Lob + konkreter Bezug", "offene Frage stellen"],
                skill: "speaking", points: 10,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    slug: "goethe-b2-mock-1",
    provider: "goethe",
    level: "B2",
    title: "Goethe-Zertifikat B2 — Mock exam 1",
    officialName: "Goethe-Zertifikat B2 (modular)",
    minutes: 190,
    passMark: 60,
    description:
      "Lesen (65 min), Hören (40 min), Schreiben (75 min), Sprechen (15 min). Argumentation, nominal style and reported speech are tested throughout.",
    strategies: [
      { title: "Lesen Teil 4 = opinions", body: "Decide first whether each statement is positive, negative or neutral, then match. Do not translate the whole text." },
      { title: "Hören Teil 2 is a lecture", body: "Note structure markers (erstens, außerdem, abschließend) — questions follow the order of the talk." },
      { title: "Schreiben Teil 1 is a forum contribution", body: "150 words: position, two arguments with examples, a concession, conclusion. Use nominal style at least twice." },
      { title: "Sprechen Teil 2 is a discussion", body: "You must react, not just present: agree, object politely, propose a compromise, summarise." },
    ],
    sections: [
      {
        id: "b2-lesen",
        skill: "reading",
        title: "Lesen",
        minutes: 65,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b2-lesen-1",
            title: "Teil 1 — Kommentar",
            instructions: "Lesen Sie den Kommentar und beantworten Sie die Fragen.",
            skill: "reading",
            minutes: 25,
            maxPoints: 15,
            reading: [
              "Die Debatte über das Homeoffice wird oft mit falschen Argumenten geführt. Wer behauptet, Beschäftigte arbeiteten zu Hause weniger, verwechselt Anwesenheit mit Leistung. Entscheidend ist nicht der Ort, sondern die Frage, ob Aufgaben klar definiert und Ergebnisse überprüfbar sind.",
              "Zugleich wäre es naiv, die Kosten zu übersehen. Der informelle Austausch, der in Büros nebenbei stattfindet, lässt sich digital nur begrenzt ersetzen. Gerade neu eingestellte Kolleginnen und Kollegen berichten, dass sie ohne Präsenztage deutlich länger brauchen, bis sie Zuständigkeiten und Abläufe verstehen.",
              "Aus meiner Sicht folgt daraus kein Entweder-oder, sondern eine Gestaltungsaufgabe: verbindliche Präsenztage für Einarbeitung und Teamarbeit, Homeoffice für konzentrierte Einzelarbeit. Voraussetzung dafür ist allerdings, dass Führungskräfte lernen, nach Ergebnissen zu steuern statt nach Sichtbarkeit.",
            ],
            items: [
              {
                id: "e-b2-l1-1", type: "multiple-choice",
                prompt: "Welchen Denkfehler kritisiert der Autor?",
                options: [
                  "Dass Homeoffice teuer ist",
                  "Dass Anwesenheit mit Leistung verwechselt wird",
                  "Dass Führungskräfte zu viel kontrollieren",
                  "Dass Büros zu klein sind",
                ],
                answerIndex: 1, explanation: "Absatz 1.", skill: "reading", points: 4,
              },
              {
                id: "e-b2-l1-2", type: "multiple-choice",
                prompt: "Welches Problem nennt er für neue Mitarbeitende?",
                options: [
                  "Sie verdienen weniger.",
                  "Sie verstehen Abläufe und Zuständigkeiten später.",
                  "Sie haben keine Technik.",
                  "Sie arbeiten zu viel.",
                ],
                answerIndex: 1, explanation: "Absatz 2.", skill: "reading", points: 4,
              },
              {
                id: "e-b2-l1-3", type: "multiple-choice",
                prompt: "Wie lautet seine Empfehlung?",
                options: [
                  "Homeoffice abschaffen",
                  "Nur Homeoffice",
                  "Präsenztage für Teamarbeit, Homeoffice für Einzelarbeit",
                  "Entscheidung den Beschäftigten allein überlassen",
                ],
                answerIndex: 2, explanation: "Absatz 3.", skill: "reading", points: 4,
              },
              {
                id: "e-b2-l1-4", type: "transform",
                prompt: "Formulieren Sie im Verbalstil.",
                input: "Voraussetzung dafür ist die Steuerung nach Ergebnissen.",
                answers: [
                  "Voraussetzung ist, dass nach Ergebnissen gesteuert wird.",
                  "Voraussetzung ist, dass man nach Ergebnissen steuert.",
                ],
                explanation: "Nominalstil → Nebensatz.", skill: "grammar", points: 3, grammar: "nominalisierung",
              },
            ],
          },
          {
            id: "b2-lesen-2",
            title: "Teil 2 — Meinungen zuordnen",
            instructions: "Vier Personen äußern sich zur Vier-Tage-Woche. Wer sagt was?",
            skill: "reading",
            minutes: 20,
            maxPoints: 8,
            reading: [
              "Person A: Ohne zusätzliche Fachkräfte ist eine Arbeitszeitverkürzung in der Pflege nicht umsetzbar.",
              "Person B: Pilotprojekte zeigen, dass die Zahl der Krankheitstage sinkt; das rechnet sich langfristig.",
              "Person C: Ich halte pauschale Regeln für falsch — jede Branche braucht ein eigenes Modell.",
              "Person D: Solange die Studien kurz und freiwillig sind, sollte man daraus keine allgemeinen Schlüsse ziehen.",
            ],
            items: [
              {
                id: "e-b2-l2-1", type: "match",
                prompt: "Ordnen Sie zu.",
                pairs: [
                  { left: "verweist auf Personalmangel", right: "A" },
                  { left: "nennt sinkende Krankheitstage", right: "B" },
                  { left: "fordert branchenspezifische Lösungen", right: "C" },
                  { left: "zweifelt an der Datenlage", right: "D" },
                ],
                explanation: "Jede Aussage enthält ein Schlüsselwort.", skill: "reading", points: 8,
              },
            ],
          },
          {
            id: "b2-lesen-3",
            title: "Teil 3 — Lückentext (Wortschatz)",
            instructions: "Wählen Sie das passende Wort.",
            skill: "reading",
            minutes: 20,
            maxPoints: 7,
            reading: [
              "Sehr geehrte Damen und Herren, ___ (1) der hohen Nachfrage verlängern wir die Anmeldefrist. Die Unterlagen sind bis zum 30. Juni ___ (2). Bei Rückfragen stehen wir Ihnen gern ___ (3) Verfügung.",
            ],
            items: [
              {
                id: "e-b2-l3-1", type: "multiple-choice",
                prompt: "Lücke 1",
                options: ["Wegen", "Aufgrund", "Trotz", "Während"],
                answerIndex: 1, explanation: "aufgrund + Genitiv, formell.", skill: "reading", points: 2,
              },
              {
                id: "e-b2-l3-2", type: "multiple-choice",
                prompt: "Lücke 2",
                options: ["einreichen", "eingereicht", "einzureichen", "eingereicht werden"],
                answerIndex: 2, explanation: "sein + zu + Infinitiv = müssen im Passiv.", skill: "reading", points: 3,
              },
              {
                id: "e-b2-l3-3", type: "multiple-choice",
                prompt: "Lücke 3",
                options: ["zur", "zu", "in", "auf"],
                answerIndex: 0, explanation: "zur Verfügung stehen.", skill: "reading", points: 2,
              },
            ],
          },
        ],
      },
      {
        id: "b2-hoeren",
        skill: "listening",
        title: "Hören",
        minutes: 40,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b2-hoeren-1",
            title: "Teil 1 — Gespräch im Betrieb",
            instructions: "Sie hören das Gespräch einmal.",
            skill: "listening",
            minutes: 15,
            maxPoints: 12,
            playLimit: 1,
            audio: [
              { speaker: "Frau Kaya", de: "Herr Aziz, wir überlegen, die Einarbeitung neuer Azubis umzustellen. Was ist Ihnen damals gefehlt?" },
              { speaker: "Karim", de: "Eine feste Ansprechperson. Ich habe jeden Tag jemand anderen gefragt und jedes Mal eine andere Antwort bekommen." },
              { speaker: "Frau Kaya", de: "Also ein Patenmodell. Und sprachlich?" },
              { speaker: "Karim", de: "Ein Glossar mit den fünfzig wichtigsten Fachwörtern hätte mir Wochen erspart. Am Anfang habe ich abends alles nachgeschlagen." },
              { speaker: "Frau Kaya", de: "Gute Idee. Wir könnten das mit dem Betriebsrat abstimmen und ab September testen." },
            ],
            items: [
              {
                id: "e-b2-h1-1", type: "multiple-choice",
                prompt: "Was fehlte Karim am meisten?",
                options: ["Mehr Geld", "Eine feste Ansprechperson", "Kürzere Arbeitszeit", "Ein Auto"],
                answerIndex: 1, explanation: "„Eine feste Ansprechperson.“", skill: "listening", points: 4,
              },
              {
                id: "e-b2-h1-2", type: "multiple-choice",
                prompt: "Welchen sprachlichen Vorschlag macht er?",
                options: ["Einen Abendkurs", "Ein Glossar mit Fachwörtern", "Einen Übersetzer", "Ein Wörterbuch kaufen"],
                answerIndex: 1, explanation: "„Ein Glossar mit den fünfzig wichtigsten Fachwörtern“.", skill: "listening", points: 4,
              },
              {
                id: "e-b2-h1-3", type: "fill-blank",
                prompt: "Wann soll getestet werden?",
                sentence: "Ab ___.", answers: [["September"]],
                explanation: "Letzter Beitrag.", skill: "listening", points: 4,
              },
            ],
          },
          {
            id: "b2-hoeren-2",
            title: "Teil 2 — Vortrag",
            instructions: "Sie hören einen Vortrag zweimal.",
            skill: "listening",
            minutes: 15,
            maxPoints: 12,
            playLimit: 2,
            audio: [
              { speaker: "Referentin", de: "Ich stelle drei Befunde unserer Studie zur Sprachförderung im Betrieb vor." },
              { speaker: "Referentin", de: "Erstens: Kurse während der Arbeitszeit führen zu einer um vierzig Prozent höheren Abschlussquote als Kurse in der Freizeit." },
              { speaker: "Referentin", de: "Zweitens: Entscheidend ist nicht die Stundenzahl, sondern die Regelmäßigkeit. Zwei Stunden pro Woche über ein Jahr wirken stärker als ein Intensivkurs im Sommer." },
              { speaker: "Referentin", de: "Drittens: Betriebe, die Sprachförderung anbieten, verzeichnen eine deutlich geringere Fluktuation im ersten Jahr." },
              { speaker: "Referentin", de: "Abschließend meine Empfehlung: kleine, verbindliche Einheiten im Arbeitsalltag statt großer Einmalprojekte." },
            ],
            items: [
              {
                id: "e-b2-h2-1", type: "multiple-choice",
                prompt: "Wie hoch ist die Differenz bei der Abschlussquote?",
                options: ["14 %", "24 %", "40 %", "60 %"],
                answerIndex: 2, explanation: "„um vierzig Prozent höhere Abschlussquote“.", skill: "listening", points: 4,
              },
              {
                id: "e-b2-h2-2", type: "multiple-choice",
                prompt: "Was ist laut Studie entscheidend?",
                options: ["Die Stundenzahl", "Die Regelmäßigkeit", "Die Gruppengröße", "Die Lehrkraft"],
                answerIndex: 1, explanation: "Zweiter Befund.", skill: "listening", points: 4,
              },
              {
                id: "e-b2-h2-3", type: "multiple-choice",
                prompt: "Welche Empfehlung gibt die Referentin?",
                options: [
                  "Intensivkurse im Sommer",
                  "Kleine verbindliche Einheiten im Arbeitsalltag",
                  "Kurse nur für Führungskräfte",
                  "Online-Kurse ohne Betreuung",
                ],
                answerIndex: 1, explanation: "Schlusssatz.", skill: "listening", points: 4,
              },
            ],
          },
          {
            id: "b2-hoeren-3",
            title: "Teil 3 — Interview",
            instructions: "Richtig oder falsch?",
            skill: "listening",
            minutes: 10,
            maxPoints: 6,
            playLimit: 1,
            audio: [
              { speaker: "Moderator", de: "Herr Brandt, Sie halten die Vier-Tage-Woche in der Produktion für unrealistisch?" },
              { speaker: "Herr Brandt", de: "In der jetzigen Personallage ja. Ich sage nicht, dass die Idee falsch sei — sie setzt aber voraus, dass genügend Fachkräfte verfügbar sind." },
              { speaker: "Moderator", de: "Was wäre Ihr Vorschlag?" },
              { speaker: "Herr Brandt", de: "Flexiblere Schichtmodelle und mehr Mitbestimmung bei der Planung. Das kostet weniger und wirkt schneller." },
            ],
            items: [
              {
                id: "e-b2-h3-1", type: "true-false",
                prompt: "Herr Brandt lehnt die Idee grundsätzlich ab.", answer: false,
                explanation: "„Ich sage nicht, dass die Idee falsch sei.“", skill: "listening", points: 3,
              },
              {
                id: "e-b2-h3-2", type: "multiple-choice",
                prompt: "Was schlägt er vor?",
                options: [
                  "Höhere Löhne",
                  "Flexiblere Schichtmodelle und mehr Mitbestimmung",
                  "Weniger Urlaub",
                  "Automatisierung",
                ],
                answerIndex: 1, explanation: "Letzter Beitrag.", skill: "listening", points: 3,
              },
            ],
          },
        ],
      },
      {
        id: "b2-schreiben",
        skill: "writing",
        title: "Schreiben",
        minutes: 75,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b2-schreiben-1",
            title: "Teil 1 — Forumsbeitrag (ca. 150 Wörter)",
            instructions:
              "Diskussion: „Sollten Unternehmen Sprachkurse während der Arbeitszeit anbieten?“ Nehmen Sie begründet Stellung.",
            skill: "writing",
            minutes: 50,
            maxPoints: 20,
            items: [
              {
                id: "e-b2-s1-1", type: "writing",
                prompt: "Schreiben Sie Ihren Beitrag.",
                minWords: 150,
                checklist: [
                  "klare Position in der Einleitung",
                  "zwei Argumente mit Beispiel oder Zahl",
                  "ein Gegenargument eingeräumt",
                  "Nominalstil mindestens zweimal (aufgrund, trotz, nach …)",
                  "Passiv oder Passiversatz",
                  "Fazit mit Empfehlung",
                ],
                sampleAnswer:
                  "Aufgrund des Fachkräftemangels halte ich betriebliche Sprachkurse während der Arbeitszeit für sinnvoll und wirtschaftlich vernünftig. Zum einen lassen sich Missverständnisse reduzieren, die in technischen Berufen teuer und mitunter gefährlich sind; in meinem Betrieb wurde vor kurzem eine Bestellung falsch ausgeführt, weil eine mündliche Anweisung nicht verstanden worden war. Zum anderen steigt die Bindung an das Unternehmen: Wer betrieblich gefördert wird, wechselt seltener den Arbeitgeber, sodass die Kosten der Einarbeitung sinken.\n\nZwar ist einzuwenden, dass Kurse Arbeitszeit kosten und gerade kleine Betriebe belasten. Dieses Argument wiegt jedoch weniger schwer, wenn man die Ausgaben den Folgekosten von Fehlern und hoher Fluktuation gegenüberstellt.\n\nMeiner Ansicht nach wäre eine geteilte Verantwortung der beste Weg: Der Betrieb stellt zwei Stunden Arbeitszeit pro Woche zur Verfügung, die Beschäftigten übernehmen die Vor- und Nachbereitung. Nach Abschluss des Kurses sollte eine Prüfung stehen, damit der Erfolg messbar bleibt.",
                skill: "writing", points: 20,
              },
            ],
          },
          {
            id: "b2-schreiben-2",
            title: "Teil 2 — Formelle Nachricht (ca. 100 Wörter)",
            instructions:
              "Ein Kunde beschwert sich über eine verspätete Lieferung und fordert 20 % Rabatt. Antworten Sie im Namen der Firma.",
            skill: "writing",
            minutes: 25,
            maxPoints: 10,
            items: [
              {
                id: "e-b2-s2-1", type: "writing",
                prompt: "Schreiben Sie die Antwort.",
                minWords: 100,
                checklist: [
                  "Betreff mit Auftragsnummer",
                  "Entschuldigung ohne Schuldzuweisung",
                  "Ursache im Passiv",
                  "konkretes Gegenangebot",
                  "Maßnahme für die Zukunft",
                ],
                sampleAnswer:
                  "Betreff: Ihre Reklamation vom 12. Mai – Auftrag 8842\n\nSehr geehrter Herr Brandt,\n\nvielen Dank für Ihre Nachricht; bitte entschuldigen Sie die entstandenen Unannehmlichkeiten. Die Verzögerung ist darauf zurückzuführen, dass die Bauteile von unserem Zulieferer mit zwei Wochen Rückstand geliefert wurden. Dass Sie darüber nicht informiert wurden, war ein Fehler unserer Auftragsverfolgung, die wir inzwischen umgestellt haben.\n\nEinen Nachlass von 20 % können wir leider nicht darstellen. Als Ausgleich bieten wir Ihnen 8 % auf den betroffenen Auftrag sowie drei kostenfreie Expresslieferungen an. Über eine kurze Rückmeldung bis Freitag wären wir Ihnen dankbar.\n\nMit freundlichen Grüßen\nSabine Kaya, Vertrieb",
                skill: "writing", points: 10,
              },
            ],
          },
        ],
      },
      {
        id: "b2-sprechen",
        skill: "speaking",
        title: "Sprechen",
        minutes: 15,
        maxPoints: 30,
        weight: 25,
        parts: [
          {
            id: "b2-sprechen-1",
            title: "Teil 1 — Vortrag",
            instructions: "Halten Sie einen Kurzvortrag (4 Minuten): Einleitung, zwei Argumente, Beispiel, Fazit.",
            skill: "speaking",
            minutes: 8,
            maxPoints: 15,
            items: [
              {
                id: "e-b2-sp1-1", type: "speaking",
                prompt: "Thema: „Digitalisierung im Handwerk — Chance oder Risiko?“",
                target:
                  "Ich möchte heute darlegen, warum ich die Digitalisierung im Handwerk vor allem als Chance sehe. Zunächst verändert sie die Aufgaben, ohne die Fachkräfte zu ersetzen. Darüber hinaus profitieren kleine Betriebe, sofern sie kooperieren. Ein Beispiel aus meinem Betrieb: Seit wir Aufträge digital dokumentieren, sparen wir pro Woche mehrere Stunden. Zusammenfassend lässt sich sagen, dass Qualifizierung wichtiger ist als Technik.",
                tips: ["Struktur ankündigen", "Konnektoren variieren", "mit Empfehlung enden"],
                skill: "speaking", points: 15,
              },
            ],
          },
          {
            id: "b2-sprechen-2",
            title: "Teil 2 — Diskussion",
            instructions: "Diskutieren Sie den Vorschlag: „Alle Azubis sollen einen Pflicht-Sprachkurs besuchen.“",
            skill: "speaking",
            minutes: 7,
            maxPoints: 15,
            items: [
              {
                id: "e-b2-sp2-1", type: "speaking",
                prompt: "Nehmen Sie Stellung, widersprechen Sie höflich und schlagen Sie einen Kompromiss vor.",
                target:
                  "Grundsätzlich halte ich den Vorschlag für sinnvoll, allerdings sehe ich ein Problem bei Azubis, die schon C1 sprechen. Da bin ich anderer Meinung als Sie: Eine Pflicht für alle wäre nicht effizient. Könnten wir uns darauf einigen, den Kurs ab Niveau B1 verpflichtend zu machen und darüber freiwillig?",
                tips: ["Position + Einschränkung", "höflicher Widerspruch", "Kompromissfrage am Ende"],
                skill: "speaking", points: 15,
              },
            ],
          },
        ],
      },
    ],
  },
];
