import type { Course, Lesson } from "@/lib/types";

export const a1Lessons: Lesson[] = [
  {
    slug: "a1-l1-begruessung",
    level: "A1",
    moduleSlug: "a1-m1-erste-kontakte",
    order: 1,
    title: "Hello! Greetings and introducing yourself",
    titleDe: "Hallo! Begrüßung und Vorstellung",
    summary:
      "Say hello, give your name, spell it, say where you are from and where you live — plus the pronouns and the verbs sein and haben.",
    minutes: 50,
    xp: 60,
    skills: ["vocabulary", "grammar", "speaking", "pronunciation"],
    objectives: [
      "Greet people formally and informally",
      "Introduce yourself with six pieces of information",
      "Conjugate sein and haben in the present tense",
      "Spell your name on the phone",
    ],
    blocks: [
      { kind: "objectives", items: ["Begrüßen und sich vorstellen", "sein und haben", "du oder Sie?", "Das Alphabet"] },
      {
        kind: "dialogue",
        title: "Im Sprachkurs",
        setting: "Erster Kurstag, Sprachschule Mitte",
        lines: [
          { speaker: "Frau Berger", de: "Guten Tag! Ich bin Frau Berger, Ihre Kursleiterin. Wie heißen Sie?", en: "Hello! I'm Ms Berger, your course teacher. What's your name?" },
          { speaker: "Nour", de: "Guten Tag. Ich heiße Nour Benali.", en: "Hello. My name is Nour Benali." },
          { speaker: "Frau Berger", de: "Woher kommen Sie, Frau Benali?", en: "Where are you from, Ms Benali?" },
          { speaker: "Nour", de: "Ich komme aus Marokko, aus Rabat. Und ich wohne jetzt in Leipzig.", en: "I'm from Morocco, from Rabat. And I live in Leipzig now." },
          { speaker: "Frau Berger", de: "Sehr gut. Und wie alt sind Sie?", en: "Very good. And how old are you?" },
          { speaker: "Nour", de: "Ich bin 23 Jahre alt. Ich bin ledig und habe keine Kinder.", en: "I'm 23 years old. I'm single and have no children." },
          { speaker: "Karim", de: "Hallo, ich bin Karim. Wir sind im gleichen Kurs, oder?", en: "Hi, I'm Karim. We're in the same course, right?" },
          { speaker: "Nour", de: "Ja, genau. Freut mich!", en: "Yes, exactly. Nice to meet you!" },
        ],
      },
      { kind: "vocab", title: "Wortschatz: Begrüßung und Vorstellung", deck: "a1-greetings" },
      { kind: "grammar", slug: "personalpronomen-sein-haben" },
      {
        kind: "tip",
        title: "du oder Sie?",
        body:
          "Im Kurs, bei der Arbeit und mit Fremden: Sie. Mit Freunden, Familie und meist mit anderen Lernenden im gleichen Alter: du. Warten Sie ab, bis das Du angeboten wird.",
      },
      { kind: "pronunciation", slug: "das-alphabet" },
      {
        kind: "checklist",
        title: "Kann ich das schon?",
        items: [
          "Ich kann jemanden formell und informell begrüßen.",
          "Ich kann meinen Namen buchstabieren.",
          "Ich kann sein und haben ohne Nachdenken konjugieren.",
          "Ich kann sechs Informationen über mich sagen.",
        ],
      },
    ],
    grammar: ["personalpronomen-sein-haben"],
    vocabDecks: ["a1-greetings"],
    reading: "steckbrief-nour",
    speaking: "sich-vorstellen",
    pronunciation: ["das-alphabet"],
    exercises: [
      {
        id: "l-a1-1-e1", type: "fill-blank",
        prompt: "Ergänzen Sie sein oder haben.",
        sentence: "Ich ___ Nour und ich ___ 23 Jahre alt. Wir ___ im gleichen Kurs.",
        answers: [["bin"], ["bin"], ["sind"]],
        explanation: "Alter mit sein: Ich bin 23 Jahre alt.",
        skill: "grammar",
      },
      {
        id: "l-a1-1-e2", type: "multiple-choice",
        prompt: "Sie sprechen mit einer Beamtin im Amt. Was sagen Sie?",
        options: ["Wie heißt du?", "Wie heißen Sie?", "Wie heißt ihr?", "Wer bist du?"],
        answerIndex: 1,
        explanation: "Formelle Situation → Sie.",
        skill: "grammar",
      },
      {
        id: "l-a1-1-e3", type: "order",
        prompt: "Bilden Sie den Satz.",
        tokens: ["aus", "Ich", "Marokko", "komme"],
        answer: "Ich komme aus Marokko",
        explanation: "Verb an Position 2.",
        skill: "grammar",
      },
      {
        id: "l-a1-1-e4", type: "speaking",
        prompt: "Stellen Sie sich in sechs Sätzen vor.",
        target: "Ich heiße Karim Aziz. Ich komme aus Marokko und wohne in Leipzig. Ich bin 23 Jahre alt und ledig. Ich lerne Deutsch und arbeite in einem Café.",
        tips: ["Langsam sprechen", "Namen buchstabieren", "Verb an Position 2"],
        skill: "speaking",
      },
      {
        id: "l-a1-1-e5", type: "match",
        prompt: "Ordnen Sie Frage und Antwort zu.",
        pairs: [
          { left: "Wie heißen Sie?", right: "Ich heiße Nour." },
          { left: "Woher kommen Sie?", right: "Aus Marokko." },
          { left: "Wo wohnen Sie?", right: "In Leipzig." },
          { left: "Wie alt sind Sie?", right: "23 Jahre." },
        ],
        explanation: "W-Fragen und passende Antworten.",
        skill: "vocabulary",
      },
    ],
    homework: [
      "Schreiben Sie einen Steckbrief über sich (6 Sätze) und lesen Sie ihn laut vor.",
      "Buchstabieren Sie fünf Namen aus Ihrem Handy laut auf Deutsch.",
      "Lernen Sie die 10 Vokabeln der Kartei „Begrüßung und Vorstellung“.",
    ],
    revision: [
      "sein: bin, bist, ist, sind, seid, sind",
      "haben: habe, hast, hat, haben, habt, haben",
      "Formell = Sie (großes S), informell = du",
    ],
  },
  {
    slug: "a1-l2-familie-zahlen",
    level: "A1",
    moduleSlug: "a1-m1-erste-kontakte",
    order: 2,
    title: "Family, numbers and time",
    titleDe: "Familie, Zahlen und Uhrzeit",
    summary:
      "Talk about your family, count, tell the time and make a first appointment — with articles, gender and plural forms.",
    minutes: 55,
    xp: 60,
    skills: ["vocabulary", "grammar", "listening"],
    objectives: [
      "Name family members with the correct article",
      "Use numbers 0–100 and tell the time",
      "Form the plural of common nouns",
      "Arrange a simple appointment",
    ],
    blocks: [
      { kind: "objectives", items: ["Familie beschreiben", "Zahlen und Uhrzeit", "der/die/das + Plural", "Termine machen"] },
      { kind: "vocab", title: "Wortschatz: Familie", deck: "a1-family" },
      { kind: "vocab", title: "Wortschatz: Zahlen, Uhrzeit, Datum", deck: "a1-time" },
      { kind: "grammar", slug: "nomen-artikel-genus" },
      {
        kind: "table",
        table: {
          title: "Uhrzeit: offiziell und umgangssprachlich",
          headers: ["Uhr", "Offiziell", "Umgangssprachlich"],
          rows: [
            ["07:15", "sieben Uhr fünfzehn", "Viertel nach sieben"],
            ["07:30", "sieben Uhr dreißig", "halb acht"],
            ["07:45", "sieben Uhr fünfundvierzig", "Viertel vor acht"],
            ["12:00", "zwölf Uhr", "Mittag"],
            ["18:20", "achtzehn Uhr zwanzig", "zwanzig nach sechs"],
          ],
          note: "Achtung: halb acht = 7:30, nicht 8:30!",
        },
      },
      {
        kind: "examples",
        title: "Termine",
        items: [
          { de: "Ich habe am Montag um 10 Uhr einen Termin.", en: "I have an appointment on Monday at 10." },
          { de: "Wann hast du Zeit?", en: "When do you have time?" },
          { de: "Passt es dir um halb sechs?", en: "Does half past five suit you?" },
        ],
      },
      {
        kind: "warning",
        title: "Typischer Fehler",
        body: "Nicht „Ich habe 23 Jahre“ (aus dem Französischen/Arabischen), sondern „Ich bin 23 Jahre alt“.",
      },
    ],
    grammar: ["nomen-artikel-genus"],
    vocabDecks: ["a1-family", "a1-time"],
    listening: "im-cafe-bestellen",
    exercises: [
      {
        id: "l-a1-2-e1", type: "fill-blank",
        prompt: "Ergänzen Sie den Artikel.",
        sentence: "___ Mutter, ___ Vater, ___ Kind, ___ Eltern",
        answers: [["die"], ["der"], ["das"], ["die"]],
        explanation: "Plural immer die.",
        skill: "grammar",
      },
      {
        id: "l-a1-2-e2", type: "fill-blank",
        prompt: "Schreiben Sie die Uhrzeit umgangssprachlich.",
        sentence: "08:30 = ___ neun ; 09:15 = Viertel ___ neun",
        answers: [["halb"], ["nach"]],
        explanation: "halb neun = 8:30.",
        skill: "vocabulary",
      },
      {
        id: "l-a1-2-e3", type: "multiple-choice",
        prompt: "Wie viele Geschwister hat Nour? „Ich habe zwei Brüder und eine Schwester.“",
        options: ["Zwei", "Drei", "Vier", "Eine"],
        answerIndex: 1,
        explanation: "2 + 1 = 3 Geschwister.",
        skill: "reading",
      },
      {
        id: "l-a1-2-e4", type: "dictation",
        prompt: "Schreiben Sie, was Sie hören.",
        audioText: "Mein Termin ist am Dienstag um Viertel vor neun.",
        answers: ["Mein Termin ist am Dienstag um Viertel vor neun."],
        explanation: "am + Wochentag, um + Uhrzeit.",
        skill: "listening",
      },
    ],
    homework: [
      "Zeichnen Sie Ihren Familienstammbaum und schreiben Sie zu jeder Person einen Satz.",
      "Notieren Sie eine Woche lang jeden Tag drei Uhrzeiten auf Deutsch.",
      "Lernen Sie die Pluralformen der 10 Wörter aus der Kartei „Familie“.",
    ],
    revision: [
      "der/die/das im Singular, die im Plural",
      "halb + folgende Stunde (halb acht = 7:30)",
      "am Montag, um 10 Uhr, im Januar",
    ],
  },
  {
    slug: "a1-l3-wohnen",
    level: "A1",
    moduleSlug: "a1-m2-alltag-und-wohnen",
    order: 1,
    title: "Living: flat, furniture and adverts",
    titleDe: "Wohnen: Wohnung, Möbel, Anzeigen",
    summary:
      "Describe your flat, understand housing adverts and use the accusative for objects you need and buy.",
    minutes: 55,
    xp: 65,
    skills: ["vocabulary", "grammar", "reading", "writing"],
    objectives: [
      "Describe rooms and furniture",
      "Read a German housing advert and extract the key facts",
      "Use the accusative case with haben, brauchen, suchen and kaufen",
      "Write a short enquiry about a flat",
    ],
    blocks: [
      { kind: "objectives", items: ["Wohnung beschreiben", "Anzeigen lesen", "Akkusativ", "Anfrage schreiben"] },
      { kind: "vocab", title: "Wortschatz: Wohnen und Möbel", deck: "a1-home" },
      { kind: "grammar", slug: "akkusativ" },
      {
        kind: "text",
        title: "Abkürzungen in Anzeigen",
        body: [
          "Deutsche Wohnungsanzeigen sind extrem abgekürzt. 2-ZKB = zwei Zimmer, Küche, Bad. NK = Nebenkosten. KM = Kaltmiete, WM = Warmmiete. EG = Erdgeschoss, OG = Obergeschoss, DG = Dachgeschoss. VB = Verhandlungsbasis.",
          "Achten Sie immer auf drei Zahlen: Quadratmeter, Miete (kalt oder warm) und Kaution. Die Kaution beträgt meist zwei bis drei Monatsmieten.",
        ],
      },
      {
        kind: "mistakes",
        items: [
          { wrong: "Ich habe ein Bruder und ein Tisch.", right: "Ich habe einen Bruder und einen Tisch.", why: "haben + Akkusativ: maskulin ein → einen." },
          { wrong: "Die Wohnung hat zwei Zimmern.", right: "Die Wohnung hat zwei Zimmer.", why: "das Zimmer hat den gleichen Plural." },
        ],
      },
      {
        kind: "culture",
        title: "Gut zu wissen",
        body: [
          "In Deutschland sind Küchen oft nicht eingebaut („ohne Küche“) — man bringt seine eigene mit.",
          "Die Wohnungsgeberbestätigung vom Vermieter brauchen Sie für die Anmeldung beim Amt.",
          "Ruhezeiten sind ernst: 22–6 Uhr und sonntags ganztägig.",
        ],
      },
    ],
    grammar: ["akkusativ"],
    vocabDecks: ["a1-home"],
    reading: "wohnungsanzeigen",
    writing: "formular-anmeldung",
    exercises: [
      {
        id: "l-a1-3-e1", type: "fill-blank",
        prompt: "Ergänzen Sie den unbestimmten Artikel im Akkusativ.",
        sentence: "Ich brauche ___ Tisch, ___ Lampe und ___ Bett.",
        answers: [["einen"], ["eine"], ["ein"]],
        explanation: "Nur maskulin verändert sich: einen.",
        skill: "grammar",
      },
      {
        id: "l-a1-3-e2", type: "multiple-choice",
        prompt: "Was bedeutet „520 € KM + 130 € NK“?",
        options: [
          "520 € warm inklusive",
          "520 € Kaltmiete plus 130 € Nebenkosten",
          "520 € Kaution",
          "650 € Kaltmiete",
        ],
        answerIndex: 1,
        explanation: "KM = Kaltmiete, NK = Nebenkosten. Warmmiete = 650 €.",
        skill: "reading",
      },
      {
        id: "l-a1-3-e3", type: "transform",
        prompt: "Ersetzen Sie das Objekt durch ein Pronomen.",
        input: "Ich nehme die Wohnung.",
        answers: ["Ich nehme sie."],
        explanation: "die Wohnung → sie (Akkusativ feminin unverändert).",
        skill: "grammar",
      },
      {
        id: "l-a1-3-e4", type: "writing",
        prompt: "Schreiben Sie drei Sätze über Ihre Wohnung (Zimmer, Möbel, Miete).",
        minWords: 25,
        checklist: ["drei Sätze", "Artikel korrekt", "eine Zahl"],
        sampleAnswer:
          "Meine Wohnung hat zwei Zimmer, eine Küche und ein Bad. Im Wohnzimmer stehen ein Sofa, ein Tisch und zwei Stühle. Die Warmmiete kostet 590 Euro.",
        skill: "writing",
      },
    ],
    homework: [
      "Suchen Sie drei echte Anzeigen und notieren Sie Größe, Miete und Kaution.",
      "Schreiben Sie eine kurze Anfrage an eine Hausverwaltung (5 Sätze).",
      "Zeichnen Sie Ihren Grundriss und benennen Sie 10 Gegenstände mit Artikel.",
    ],
    revision: [
      "Akkusativ: nur der → den, ein → einen",
      "KM/WM/NK/Kaution verstehen",
      "es gibt + Akkusativ",
    ],
  },
  {
    slug: "a1-l4-essen-einkaufen",
    level: "A1",
    moduleSlug: "a1-m2-alltag-und-wohnen",
    order: 2,
    title: "Food, ordering and shopping",
    titleDe: "Essen, Bestellen und Einkaufen",
    summary:
      "Order in a café, shop for food, ask for prices and use the modal verb möchten politely.",
    minutes: 50,
    xp: 60,
    skills: ["vocabulary", "listening", "speaking", "grammar"],
    objectives: [
      "Order food and drinks politely",
      "Ask for and understand prices",
      "Use möchten and the negation kein-",
      "Understand a café conversation at normal speed",
    ],
    blocks: [
      { kind: "objectives", items: ["Bestellen im Café", "Preise verstehen", "möchten", "kein / nicht"] },
      { kind: "vocab", title: "Wortschatz: Essen und Trinken", deck: "a1-food" },
      { kind: "grammar", slug: "negation-nicht-kein" },
      {
        kind: "examples",
        title: "Höflich bestellen",
        items: [
          { de: "Ich möchte einen Kaffee, bitte.", en: "I'd like a coffee, please." },
          { de: "Ich nehme den Salat.", en: "I'll have the salad." },
          { de: "Was empfehlen Sie?", en: "What do you recommend?" },
          { de: "Zahlen, bitte! — Zusammen oder getrennt?", en: "The bill, please! — Together or separately?" },
          { de: "Stimmt so.", en: "Keep the change." },
        ],
      },
      {
        kind: "tip",
        title: "Trinkgeld",
        body:
          "In Deutschland rundet man auf: 5–10 %. Man sagt den Gesamtbetrag beim Bezahlen („Machen Sie neun Euro“) und gibt das Trinkgeld nicht auf den Tisch.",
      },
    ],
    grammar: ["negation-nicht-kein"],
    vocabDecks: ["a1-food"],
    listening: "im-cafe-bestellen",
    speaking: "im-geschaeft-einkaufen",
    exercises: [
      {
        id: "l-a1-4-e1", type: "fill-blank",
        prompt: "nicht oder kein-?",
        sentence: "Ich trinke ___ Kaffee, und Zucker nehme ich ___.",
        answers: [["keinen"], ["nicht"]],
        explanation: "Nomen ohne Artikel → kein-; Verbgruppe → nicht.",
        skill: "grammar",
      },
      {
        id: "l-a1-4-e2", type: "multiple-choice",
        prompt: "Sie möchten höflich bestellen. Was sagen Sie?",
        options: ["Ich will einen Kaffee.", "Gib mir Kaffee.", "Ich möchte einen Kaffee, bitte.", "Kaffee!"],
        answerIndex: 2,
        explanation: "möchten + bitte ist die höfliche Standardform.",
        skill: "speaking",
      },
      {
        id: "l-a1-4-e3", type: "dictation",
        prompt: "Preis notieren.",
        audioText: "Das macht sechs Euro achtzig.",
        answers: ["Das macht sechs Euro achtzig.", "6,80"],
        explanation: "Preise immer als Zahl mitschreiben.",
        skill: "listening",
      },
      {
        id: "l-a1-4-e4", type: "order",
        prompt: "Bilden Sie die Frage.",
        tokens: ["das", "Was", "kostet"],
        answer: "Was kostet das",
        explanation: "W-Wort + Verb + Subjekt.",
        skill: "grammar",
      },
    ],
    homework: [
      "Lernen Sie zehn Lebensmittel mit Artikel und Plural.",
      "Spielen Sie mit einem Partner eine Bestellung im Café (5 Minuten).",
      "Schreiben Sie Ihre Einkaufsliste eine Woche lang auf Deutsch.",
    ],
    revision: ["möchten: möchte, möchtest, möchte, möchten", "kein + Nomen, nicht + Rest", "Zahlen und Preise"],
  },
  {
    slug: "a1-l5-tagesablauf",
    level: "A1",
    moduleSlug: "a1-m3-arbeit-und-zeit",
    order: 1,
    title: "Daily routine and separable verbs",
    titleDe: "Tagesablauf und trennbare Verben",
    summary:
      "Describe your day from waking up to going to bed, and master the sentence bracket of separable verbs.",
    minutes: 55,
    xp: 65,
    skills: ["grammar", "vocabulary", "speaking"],
    objectives: [
      "Describe a typical day in chronological order",
      "Use separable verbs correctly in main clauses",
      "Use modal verbs to talk about obligations",
      "Ask a colleague about their working hours",
    ],
    blocks: [
      { kind: "objectives", items: ["Tagesablauf beschreiben", "trennbare Verben", "Modalverben", "Zeitangaben"] },
      { kind: "grammar", slug: "trennbare-verben" },
      { kind: "grammar", slug: "modalverben" },
      {
        kind: "examples",
        title: "Ein Tag von Karim",
        items: [
          { de: "Ich stehe um halb sechs auf.", en: "I get up at half past five." },
          { de: "Um sechs fange ich in der Bäckerei an.", en: "At six I start at the bakery." },
          { de: "Um halb eins habe ich Feierabend.", en: "At half twelve I finish work." },
          { de: "Am Abend rufe ich meine Familie an.", en: "In the evening I call my family." },
          { de: "Ich muss um zehn ins Bett gehen, weil ich früh aufstehe.", en: "I have to go to bed at ten because I get up early." },
        ],
      },
      {
        kind: "table",
        table: {
          title: "Zeitangaben",
          headers: ["Frage", "Präposition", "Beispiel"],
          rows: [
            ["Wann?", "am + Tag", "am Montag"],
            ["Wann?", "um + Uhrzeit", "um 8 Uhr"],
            ["Wann?", "im + Monat", "im Juli"],
            ["Wie lange?", "von … bis …", "von 9 bis 17 Uhr"],
            ["Wie oft?", "jeden / einmal pro …", "jeden Tag, zweimal pro Woche"],
          ],
        },
      },
    ],
    grammar: ["trennbare-verben", "modalverben"],
    vocabDecks: ["a1-time"],
    speaking: "aussprache-training-taeglich",
    exercises: [
      {
        id: "l-a1-5-e1", type: "order",
        prompt: "Bilden Sie den Satz.",
        tokens: ["auf", "Ich", "um", "sechs", "stehe", "Uhr"],
        answer: "Ich stehe um sechs Uhr auf",
        explanation: "Trennbares Verb: Präfix am Ende.",
        skill: "grammar",
      },
      {
        id: "l-a1-5-e2", type: "fill-blank",
        prompt: "Ergänzen Sie das trennbare Verb (einkaufen, anfangen).",
        sentence: "Wir ___ am Samstag ___. Der Kurs ___ um neun ___.",
        answers: [["kaufen"], ["ein"], ["fängt"], ["an"]],
        explanation: "kaufen … ein / fängt … an.",
        skill: "grammar",
      },
      {
        id: "l-a1-5-e3", type: "multiple-choice",
        prompt: "Hier ___ man nicht rauchen.",
        options: ["muss", "darf", "will", "möchte"],
        answerIndex: 1,
        explanation: "Verbot → nicht dürfen.",
        skill: "grammar",
      },
      {
        id: "l-a1-5-e4", type: "speaking",
        prompt: "Beschreiben Sie Ihren Tag in sechs Sätzen mit mindestens drei trennbaren Verben.",
        target: "Ich stehe um sechs Uhr auf. Um sieben fange ich mit der Arbeit an. Am Abend kaufe ich ein und rufe meine Familie an.",
        skill: "speaking",
      },
    ],
    homework: [
      "Schreiben Sie Ihren Tagesablauf (8 Sätze) mit Uhrzeiten.",
      "Markieren Sie in Ihrem Text alle trennbaren Verben.",
      "Fragen Sie eine Person nach ihrem Tagesablauf und notieren Sie die Antworten.",
    ],
    revision: [
      "Trennbar: Verb Position 2, Präfix am Ende",
      "Modalverben: kein Ending bei ich/er, Infinitiv am Ende",
      "am / um / im / von … bis",
    ],
  },
  {
    slug: "a1-l6-stadt-orientierung",
    level: "A1",
    moduleSlug: "a1-m3-arbeit-und-zeit",
    order: 2,
    title: "In the city: directions and transport",
    titleDe: "In der Stadt: Wegbeschreibung und Verkehr",
    summary:
      "Ask for and understand directions, buy tickets and survive station announcements.",
    minutes: 50,
    xp: 60,
    skills: ["vocabulary", "listening", "speaking"],
    objectives: [
      "Ask for the way politely",
      "Understand a direction with three steps",
      "Buy a ticket and ask about changes and delays",
      "Understand numbers in announcements",
    ],
    blocks: [
      { kind: "objectives", items: ["Nach dem Weg fragen", "Wegbeschreibung verstehen", "Fahrkarten kaufen", "Ansagen verstehen"] },
      { kind: "vocab", title: "Wortschatz: Stadt und Verkehr", deck: "a1-city" },
      {
        kind: "examples",
        title: "Nach dem Weg fragen",
        items: [
          { de: "Entschuldigung, wie komme ich zum Bahnhof?", en: "Excuse me, how do I get to the station?" },
          { de: "Ist es weit? — Nein, fünf Minuten zu Fuß.", en: "Is it far? — No, five minutes on foot." },
          { de: "Gehen Sie geradeaus und dann an der Ampel links.", en: "Go straight ahead and then left at the traffic light." },
          { de: "Eine Fahrkarte nach Dresden, bitte. Einfach oder hin und zurück?", en: "One ticket to Dresden, please. Single or return?" },
          { de: "Muss ich umsteigen? — Ja, in Riesa.", en: "Do I have to change? — Yes, in Riesa." },
        ],
      },
      {
        kind: "tip",
        title: "Zum oder zur?",
        body: "zum + maskulin/neutrum (zum Bahnhof, zum Amt), zur + feminin (zur Apotheke, zur Post). Beides ist Dativ.",
      },
      { kind: "pronunciation", slug: "wortakzent" },
    ],
    grammar: ["wortstellung-fragen"],
    vocabDecks: ["a1-city"],
    listening: "ansage-bahnhof",
    exercises: [
      {
        id: "l-a1-6-e1", type: "fill-blank",
        prompt: "zum oder zur?",
        sentence: "Wie komme ich ___ Bahnhof und ___ Apotheke?",
        answers: [["zum"], ["zur"]],
        explanation: "der Bahnhof → zum; die Apotheke → zur.",
        skill: "grammar",
      },
      {
        id: "l-a1-6-e2", type: "multiple-choice",
        prompt: "Welche Frage passt zur Antwort „Aus Marokko“?",
        options: ["Wo wohnen Sie?", "Wohin fahren Sie?", "Woher kommen Sie?", "Wann kommen Sie?"],
        answerIndex: 2,
        explanation: "woher = Herkunft.",
        skill: "grammar",
      },
      {
        id: "l-a1-6-e3", type: "dictation",
        prompt: "Notieren Sie die Ansage.",
        audioText: "Der Zug nach Dresden fährt heute von Gleis fünf.",
        answers: ["Der Zug nach Dresden fährt heute von Gleis fünf.", "Gleis 5"],
        explanation: "Gleisnummern sind Prüfungsstandard.",
        skill: "listening",
      },
      {
        id: "l-a1-6-e4", type: "speaking",
        prompt: "Erklären Sie den Weg von Ihrer Wohnung zum Supermarkt.",
        target: "Gehen Sie aus dem Haus nach links, dann geradeaus bis zur Ampel. An der Ampel rechts, und der Supermarkt ist auf der linken Seite.",
        skill: "speaking",
      },
    ],
    homework: [
      "Erklären Sie schriftlich den Weg von Ihrer Wohnung zum Kurs.",
      "Hören Sie drei echte Bahnhofsansagen und notieren Sie Gleis und Zeit.",
      "Lernen Sie die 10 Wörter der Kartei „Stadt und Verkehr“.",
    ],
    revision: ["W-Fragen: wo, wohin, woher, wann, wie", "zum / zur", "links, rechts, geradeaus, bis zur"],
  },
  {
    slug: "a1-l7-perfekt-erzaehlen",
    level: "A1",
    moduleSlug: "a1-m4-vergangenheit",
    order: 1,
    title: "Talking about the past: Perfekt",
    titleDe: "Über die Vergangenheit sprechen: Perfekt",
    summary:
      "Tell someone what you did yesterday and at the weekend using haben/sein + Partizip II.",
    minutes: 60,
    xp: 70,
    skills: ["grammar", "speaking", "writing"],
    objectives: [
      "Form the Partizip II of weak, strong and separable verbs",
      "Choose between haben and sein",
      "Tell a short story about yesterday",
      "Write a message about your weekend",
    ],
    blocks: [
      { kind: "objectives", items: ["Partizip II bilden", "haben oder sein", "Über gestern erzählen", "Nachricht schreiben"] },
      { kind: "grammar", slug: "perfekt" },
      {
        kind: "dialogue",
        title: "Am Montagmorgen",
        lines: [
          { speaker: "Lena", de: "Und, was hast du am Wochenende gemacht?", en: "So, what did you do at the weekend?" },
          { speaker: "Nour", de: "Am Samstag habe ich gearbeitet, aber am Sonntag bin ich mit Karim an den See gefahren.", en: "On Saturday I worked, but on Sunday I went to the lake with Karim." },
          { speaker: "Lena", de: "Schön! Und wie war das Wetter?", en: "Nice! And how was the weather?" },
          { speaker: "Nour", de: "Es war warm. Wir haben gegrillt und sind geschwommen. Abends bin ich früh ins Bett gegangen.", en: "It was warm. We barbecued and swam. In the evening I went to bed early." },
        ],
      },
      {
        kind: "tip",
        title: "Merksatz",
        body: "Bewegung von A nach B oder Zustandsänderung → sein. Alles andere, besonders mit Akkusativobjekt → haben.",
      },
      {
        kind: "mistakes",
        items: [
          { wrong: "Ich habe nach Berlin gefahren.", right: "Ich bin nach Berlin gefahren.", why: "Bewegung A → B." },
          { wrong: "Ich habe getelefoniert mit meiner Mutter.", right: "Ich habe mit meiner Mutter telefoniert.", why: "-ieren ohne ge-, Partizip am Ende." },
        ],
      },
    ],
    grammar: ["perfekt"],
    vocabDecks: ["a1-time"],
    reading: "erster-arbeitstag",
    writing: "kurze-nachricht-freundin",
    exercises: [
      {
        id: "l-a1-7-e1", type: "fill-blank",
        prompt: "haben oder sein?",
        sentence: "Ich ___ gestern gearbeitet und dann ___ ich nach Hause gefahren.",
        answers: [["habe"], ["bin"]],
        explanation: "arbeiten → haben, fahren → sein.",
        skill: "grammar",
      },
      {
        id: "l-a1-7-e2", type: "fill-blank",
        prompt: "Partizip II bilden.",
        sentence: "lernen → ___ ; sprechen → ___ ; aufstehen → ___ ; studieren → ___",
        answers: [["gelernt"], ["gesprochen"], ["aufgestanden"], ["studiert"]],
        explanation: "schwach, stark, trennbar, -ieren.",
        skill: "grammar",
      },
      {
        id: "l-a1-7-e3", type: "transform",
        prompt: "Setzen Sie ins Perfekt.",
        input: "Ich kaufe am Samstag ein.",
        answers: ["Ich habe am Samstag eingekauft."],
        explanation: "ein + ge + kauft.",
        skill: "grammar",
      },
      {
        id: "l-a1-7-e4", type: "writing",
        prompt: "Schreiben Sie fünf Sätze über Ihr letztes Wochenende im Perfekt.",
        minWords: 40,
        checklist: ["fünf Sätze", "mindestens ein Satz mit sein", "Partizip am Satzende"],
        sampleAnswer:
          "Am Samstag habe ich lange geschlafen. Danach habe ich die Wohnung geputzt und eingekauft. Am Sonntag bin ich mit Freunden in den Park gegangen. Wir haben Fußball gespielt und Tee getrunken. Abends habe ich für den Kurs gelernt.",
        skill: "writing",
      },
    ],
    homework: [
      "Schreiben Sie ein Tagebuch für drei Tage im Perfekt (je 3 Sätze).",
      "Lernen Sie 15 Partizipien aus der Verbliste.",
      "Erzählen Sie einer Person zwei Minuten über Ihr Wochenende.",
    ],
    revision: [
      "haben/sein Position 2, Partizip II am Ende",
      "ge- + -t (schwach) / ge- + -en (stark)",
      "kein ge- bei -ieren und be-, ver-, er-, ent-",
    ],
  },
  {
    slug: "a1-l8-abschluss-a1",
    level: "A1",
    moduleSlug: "a1-m5-pruefungstraining",
    order: 1,
    title: "A1 exam training and revision",
    titleDe: "Prüfungstraining und Wiederholung A1",
    summary:
      "Systematic revision of all A1 grammar plus a walk-through of every part of Start Deutsch 1.",
    minutes: 70,
    xp: 90,
    skills: ["grammar", "reading", "listening", "writing", "speaking"],
    objectives: [
      "Revise all A1 grammar in one session",
      "Know the format of every exam part",
      "Practise the writing task under time pressure",
      "Complete a full mock exam",
    ],
    blocks: [
      { kind: "objectives", items: ["Grammatik wiederholen", "Prüfungsformat kennen", "Zeitmanagement üben", "Mock-Prüfung schreiben"] },
      {
        kind: "table",
        table: {
          title: "Start Deutsch 1 im Überblick",
          headers: ["Teil", "Zeit", "Aufgabe", "Tipp"],
          rows: [
            ["Hören", "20 min", "3 Teile, Teil 1 zweimal", "Zahlen sofort notieren"],
            ["Lesen", "25 min", "Texte, Anzeigen, Mitteilungen", "Fragen zuerst lesen"],
            ["Schreiben", "20 min", "Formular + kurze Mitteilung", "Alle 3 Punkte bearbeiten"],
            ["Sprechen", "15 min", "Vorstellen, fragen, bitten", "In ganzen Sätzen antworten"],
          ],
        },
      },
      {
        kind: "checklist",
        title: "Grammatik-Check A1",
        items: [
          "sein und haben fehlerfrei",
          "Präsens inkl. arbeiten/heißen",
          "der/die/das + Plural",
          "Akkusativ (den/einen)",
          "kein / nicht",
          "Possessivartikel",
          "Modalverben",
          "trennbare Verben",
          "W-Fragen und Satzstellung",
          "Perfekt mit haben und sein",
        ],
      },
      {
        kind: "tip",
        title: "Zeitmanagement Schreiben",
        body: "2 Minuten planen (drei Punkte notieren), 12 Minuten schreiben, 3 Minuten prüfen: Verbposition, Artikel, Groß-/Kleinschreibung.",
      },
    ],
    grammar: ["personalpronomen-sein-haben", "akkusativ", "perfekt", "modalverben", "wortstellung-fragen"],
    vocabDecks: ["a1-greetings", "a1-family", "a1-time", "a1-food", "a1-home", "a1-city"],
    reading: "wohnungsanzeigen",
    listening: "ansage-bahnhof",
    writing: "kurze-nachricht-freundin",
    speaking: "sich-vorstellen",
    exercises: [
      {
        id: "l-a1-8-e1", type: "fill-blank",
        prompt: "Gemischte Wiederholung.",
        sentence: "Ich ___ (haben) einen Termin und ___ (müssen) um acht Uhr dort ___ (sein).",
        answers: [["habe"], ["muss"], ["sein"]],
        explanation: "Modalverb + Infinitiv am Ende.",
        skill: "grammar",
      },
      {
        id: "l-a1-8-e2", type: "multiple-choice",
        prompt: "Welcher Satz ist korrekt?",
        options: [
          "Morgen ich gehe zum Arzt.",
          "Morgen gehe ich zum Arzt.",
          "Morgen gehen ich zum Arzt.",
          "Ich morgen gehe zum Arzt.",
        ],
        answerIndex: 1,
        explanation: "Verb bleibt an Position 2.",
        skill: "grammar",
      },
      {
        id: "l-a1-8-e3", type: "writing",
        prompt: "Prüfungsaufgabe: Sie können nicht zum Kurs kommen. Schreiben Sie 30 Wörter an Ihre Kursleiterin (Grund, Entschuldigung, Frage).",
        minWords: 30,
        checklist: ["Anrede", "Grund", "Entschuldigung", "Frage", "Gruß"],
        sampleAnswer:
          "Sehr geehrte Frau Berger,\n\nleider kann ich morgen nicht zum Kurs kommen, weil ich krank bin. Es tut mir leid. Können Sie mir sagen, welche Hausaufgaben ich machen soll?\n\nViele Grüße\nNour",
        skill: "writing",
      },
      {
        id: "l-a1-8-e4", type: "speaking",
        prompt: "Prüfungssimulation Teil 3: Bitten Sie höflich um drei Dinge (Fenster, Stift, Wasser).",
        target: "Können Sie bitte das Fenster öffnen? Haben Sie einen Stift für mich? Könnten Sie mir bitte Wasser bringen?",
        skill: "speaking",
      },
    ],
    homework: [
      "Schreiben Sie den kompletten Mock-Test „Goethe A1 Mock 1“ unter Zeitdruck.",
      "Wiederholen Sie alle Karteikarten mit Status „schwer“.",
      "Nehmen Sie Ihre Selbstvorstellung auf und vergleichen Sie mit dem Modell.",
    ],
    revision: [
      "Alle 10 A1-Grammatikthemen in der Cheat-Sheet-Ansicht durchgehen",
      "60 Kernvokabeln aus sechs Karteien",
      "Prüfungsformat und Zeiten",
    ],
  },
];

export const a1Course: Course = {
  level: "A1",
  title: "German A1 — Absolute beginner",
  subtitle: "From your first Hallo to the Start Deutsch 1 certificate",
  description:
    "A complete beginner course: greetings, family, numbers, home, food, city, daily routine and the past tense. You finish able to handle everyday situations with simple sentences and to sit Goethe A1 or telc A1.",
  hours: 90,
  vocabularyTarget: 650,
  color: "a1",
  canDo: [
    "Introduce yourself and ask simple personal questions",
    "Understand and use everyday expressions and very basic phrases",
    "Fill in simple forms with personal details",
    "Order food, shop and ask for directions",
    "Write short messages about everyday matters",
  ],
  grammarFocus: [
    "sein / haben and the present tense",
    "Nouns, gender, plural, accusative",
    "Negation with nicht and kein",
    "Modal and separable verbs",
    "Word order and W-questions",
    "Perfekt with haben and sein",
  ],
  exams: ["goethe-a1-mock-1"],
  finalExam: "goethe-a1-mock-1",
  modules: [
    {
      slug: "a1-m1-erste-kontakte",
      level: "A1",
      order: 1,
      title: "First contacts",
      titleDe: "Erste Kontakte",
      description: "Greet, introduce yourself, talk about your family and tell the time.",
      icon: "Handshake",
      outcomes: ["Sich vorstellen", "sein und haben", "Familie und Zahlen", "Artikel und Plural"],
      lessons: ["a1-l1-begruessung", "a1-l2-familie-zahlen"],
      miniTest: "a1-m1-test",
    },
    {
      slug: "a1-m2-alltag-und-wohnen",
      level: "A1",
      order: 2,
      title: "Everyday life and housing",
      titleDe: "Alltag und Wohnen",
      description: "Describe your flat, read adverts, order food and go shopping.",
      icon: "Home",
      outcomes: ["Wohnung beschreiben", "Akkusativ", "Bestellen", "Negation"],
      lessons: ["a1-l3-wohnen", "a1-l4-essen-einkaufen"],
      miniTest: "a1-m2-test",
    },
    {
      slug: "a1-m3-arbeit-und-zeit",
      level: "A1",
      order: 3,
      title: "Work, time and the city",
      titleDe: "Arbeit, Zeit und Stadt",
      description: "Talk about your day, use separable and modal verbs, get around town.",
      icon: "Clock",
      outcomes: ["Tagesablauf", "trennbare Verben", "Modalverben", "Wegbeschreibung"],
      lessons: ["a1-l5-tagesablauf", "a1-l6-stadt-orientierung"],
      miniTest: "a1-m3-test",
    },
    {
      slug: "a1-m4-vergangenheit",
      level: "A1",
      order: 4,
      title: "Talking about the past",
      titleDe: "Über die Vergangenheit sprechen",
      description: "Tell people what you did — the Perfekt in real conversations.",
      icon: "History",
      outcomes: ["Partizip II", "haben oder sein", "Erzählen", "Nachricht schreiben"],
      lessons: ["a1-l7-perfekt-erzaehlen"],
      miniTest: "a1-m4-test",
    },
    {
      slug: "a1-m5-pruefungstraining",
      level: "A1",
      order: 5,
      title: "Exam training A1",
      titleDe: "Prüfungstraining A1",
      description: "Revision of all A1 grammar plus a full Start Deutsch 1 simulation.",
      icon: "GraduationCap",
      outcomes: ["Grammatik-Check", "Prüfungsformat", "Zeitmanagement", "Mock-Prüfung"],
      lessons: ["a1-l8-abschluss-a1"],
    },
  ],
};
