import type { Course, Lesson } from "@/lib/types";

export const a2Lessons: Lesson[] = [
  {
    slug: "a2-l1-dativ-alltag",
    level: "A2",
    moduleSlug: "a2-m1-menschen-und-wege",
    order: 1,
    title: "The dative in everyday life",
    titleDe: "Der Dativ im Alltag",
    summary:
      "mit dem Bus, bei meiner Familie, seit einem Jahr — the dative prepositions and verbs you cannot avoid.",
    minutes: 55,
    xp: 70,
    skills: ["grammar", "vocabulary", "speaking"],
    objectives: [
      "Use the eight dative prepositions correctly",
      "Use dative verbs (helfen, gefallen, gehören, schmecken)",
      "Use dative pronouns in real sentences",
      "Talk about how you get to work and who helps you",
    ],
    blocks: [
      { kind: "objectives", items: ["Dativ-Präpositionen", "Dativ-Verben", "Pronomen im Dativ", "Kontraktionen"] },
      { kind: "grammar", slug: "dativ" },
      {
        kind: "examples",
        title: "Sätze, die Sie täglich brauchen",
        items: [
          { de: "Wie geht es Ihnen? — Danke, mir geht es gut.", en: "How are you? — Thanks, I'm fine." },
          { de: "Ich fahre mit der Straßenbahn zur Arbeit.", en: "I take the tram to work." },
          { de: "Seit einem Jahr wohne ich bei meiner Tante.", en: "I've been living at my aunt's for a year." },
          { de: "Kannst du mir bitte helfen?", en: "Can you help me, please?" },
          { de: "Das Essen schmeckt mir sehr gut.", en: "I really like the food." },
        ],
      },
      { kind: "vocab", title: "Wortschatz: Alltag und Freizeit", deck: "a2-routine" },
      {
        kind: "warning",
        title: "Zwei Verben, die alle verwechseln",
        body: "helfen + Dativ (Ich helfe dir), aber unterstützen + Akkusativ (Ich unterstütze dich). Lernen Sie das Paar zusammen.",
      },
    ],
    grammar: ["dativ"],
    vocabDecks: ["a2-routine"],
    speaking: "ueber-den-alltag-sprechen",
    exercises: [
      {
        id: "l-a2-1-e1", type: "fill-blank",
        prompt: "Ergänzen Sie den Dativ.",
        sentence: "Ich fahre mit ___ Bus zu ___ Arbeit und komme nach ___ Kurs nach Hause.",
        answers: [["dem"], ["der"], ["dem"]],
        explanation: "mit + Dativ, zu + Dativ (zur Arbeit), nach + Dativ.",
        skill: "grammar",
      },
      {
        id: "l-a2-1-e2", type: "multiple-choice",
        prompt: "Das Buch gehört ___ Kollegin.",
        options: ["die", "der", "den", "dem"],
        answerIndex: 1,
        explanation: "gehören + Dativ, feminin → der.",
        skill: "grammar",
      },
      {
        id: "l-a2-1-e3", type: "transform",
        prompt: "Ersetzen Sie durch ein Pronomen.",
        input: "Ich schreibe meinem Bruder eine Nachricht.",
        answers: ["Ich schreibe ihm eine Nachricht."],
        explanation: "meinem Bruder → ihm.",
        skill: "grammar",
      },
      {
        id: "l-a2-1-e4", type: "speaking",
        prompt: "Erzählen Sie: Wie kommen Sie zur Arbeit, und wer hilft Ihnen beim Deutschlernen?",
        target: "Ich fahre mit dem Fahrrad zur Arbeit. Beim Deutschlernen hilft mir meine Kollegin, weil sie sehr geduldig ist.",
        skill: "speaking",
      },
    ],
    homework: [
      "Schreiben Sie zehn Sätze mit den acht Dativ-Präpositionen.",
      "Lernen Sie die Dativ-Verben mit einem Beispielsatz.",
      "Notieren Sie eine Woche lang jeden Tag einen Satz mit „Wie geht es …?“",
    ],
    revision: ["dem/der/dem/den + n", "aus bei mit nach seit von zu gegenüber", "mir dir ihm ihr uns euch ihnen"],
  },
  {
    slug: "a2-l2-wechselpraepositionen",
    level: "A2",
    moduleSlug: "a2-m1-menschen-und-wege",
    order: 2,
    title: "Where or where to? Two-way prepositions",
    titleDe: "Wo oder wohin? Wechselpräpositionen",
    summary:
      "in, an, auf, unter, vor, hinter, neben, zwischen with accusative for movement and dative for position.",
    minutes: 55,
    xp: 70,
    skills: ["grammar", "listening"],
    objectives: [
      "Decide between accusative and dative with the two-way prepositions",
      "Use the verb pairs legen/liegen, stellen/stehen, setzen/sitzen",
      "Understand a spoken description of a location",
      "Describe where things are in your workplace",
    ],
    blocks: [
      { kind: "objectives", items: ["wo vs. wohin", "Verbpaare", "Kontraktionen ins/im/ans/am", "Ortsangaben verstehen"] },
      { kind: "grammar", slug: "wechselpraepositionen" },
      {
        kind: "examples",
        title: "Am Arbeitsplatz",
        items: [
          { de: "Legen Sie die Unterlagen bitte auf den Schreibtisch.", en: "Please put the documents on the desk." },
          { de: "Die Unterlagen liegen auf dem Schreibtisch.", en: "The documents are on the desk." },
          { de: "Das Werkzeug steht im Schrank, nicht im Auto.", en: "The tools are in the cupboard, not in the car." },
          { de: "Hängen Sie den Dienstplan an die Wand.", en: "Hang the roster on the wall." },
        ],
      },
      {
        kind: "tip",
        title: "Zwei Sekunden Regel",
        body: "Bevor Sie sprechen, fragen Sie sich: Bewegung oder Position? Bewegung → Akkusativ. Position → Dativ. Das reicht für 95 % der Fälle.",
      },
    ],
    grammar: ["wechselpraepositionen"],
    vocabDecks: ["a2-work"],
    listening: "wegbeschreibung-kollege",
    exercises: [
      {
        id: "l-a2-2-e1", type: "fill-blank",
        prompt: "Akkusativ oder Dativ?",
        sentence: "Ich gehe in ___ Werkstatt. Jetzt bin ich in ___ Werkstatt.",
        answers: [["die"], ["der"]],
        explanation: "wohin → die, wo → der.",
        skill: "grammar",
      },
      {
        id: "l-a2-2-e2", type: "multiple-choice",
        prompt: "Der Schlüssel liegt ___ Tisch.",
        options: ["auf den", "auf dem", "aufs", "auf die"],
        answerIndex: 1,
        explanation: "liegen = Position → Dativ.",
        skill: "grammar",
      },
      {
        id: "l-a2-2-e3", type: "match",
        prompt: "Ordnen Sie Bewegung und Position zu.",
        pairs: [
          { left: "stellen", right: "stehen" },
          { left: "legen", right: "liegen" },
          { left: "setzen", right: "sitzen" },
          { left: "hängen (Akk.)", right: "hängen (Dat.)" },
        ],
        explanation: "Links Bewegung (Akkusativ), rechts Position (Dativ).",
        skill: "grammar",
      },
      {
        id: "l-a2-2-e4", type: "writing",
        prompt: "Beschreiben Sie Ihren Arbeitsplatz oder Ihr Zimmer mit fünf Ortsangaben.",
        minWords: 40,
        checklist: ["fünf Präpositionen", "mindestens ein Dativ", "mindestens ein Akkusativ"],
        sampleAnswer:
          "Auf meinem Schreibtisch steht ein Computer. Neben dem Computer liegen zwei Ordner. An der Wand hängt ein Kalender. Unter dem Tisch steht ein Papierkorb. Wenn ich komme, lege ich meine Tasche auf den Stuhl.",
        skill: "writing",
      },
    ],
    homework: [
      "Fotografieren Sie einen Raum und beschreiben Sie zehn Positionen.",
      "Üben Sie die Verbpaare mit je zwei Sätzen.",
      "Hören Sie „Wegbeschreibung zum Betrieb“ und schreiben Sie den Weg auf.",
    ],
    revision: ["wohin → Akkusativ, wo → Dativ", "ins, im, ans, am, aufs", "legen/liegen, stellen/stehen, setzen/sitzen"],
  },
  {
    slug: "a2-l3-arbeit-und-bewerbung",
    level: "A2",
    moduleSlug: "a2-m2-arbeit-und-gesundheit",
    order: 1,
    title: "Work, applications and the Ausbildung path",
    titleDe: "Arbeit, Bewerbung und Ausbildung",
    summary:
      "Job vocabulary, describing your experience, and writing your first formal German email.",
    minutes: 60,
    xp: 75,
    skills: ["vocabulary", "writing", "reading"],
    objectives: [
      "Talk about jobs, contracts and working hours",
      "Describe your experience in three sentences",
      "Write a formal email with the correct opening and closing",
      "Understand a job advert",
    ],
    blocks: [
      { kind: "objectives", items: ["Berufe und Arbeitszeit", "Erfahrung beschreiben", "Formelle E-Mail", "Anzeigen verstehen"] },
      { kind: "vocab", title: "Wortschatz: Arbeit und Berufe", deck: "a2-work" },
      {
        kind: "table",
        table: {
          title: "Formelle E-Mail: Bausteine",
          headers: ["Teil", "Formulierung"],
          rows: [
            ["Anrede (unbekannt)", "Sehr geehrte Damen und Herren,"],
            ["Anrede (bekannt)", "Sehr geehrte Frau Vogt,"],
            ["Einstieg", "ich habe Ihre Anzeige gelesen und interessiere mich für …"],
            ["Kern", "Ich habe zwei Jahre als … gearbeitet."],
            ["Bitte", "Könnten Sie mir bitte mitteilen, …?"],
            ["Schluss", "Über eine Antwort würde ich mich freuen."],
            ["Grußformel", "Mit freundlichen Grüßen"],
          ],
        },
      },
      {
        kind: "tip",
        title: "Klein nach der Anrede",
        body: "Nach „Sehr geehrte Frau Vogt,“ folgt ein Komma und der nächste Satz beginnt klein: „ich habe …“. Das ist ein sicheres Zeichen für gutes Deutsch.",
      },
      {
        kind: "mistakes",
        items: [
          { wrong: "Ich bin ein Elektriker.", right: "Ich bin Elektriker.", why: "Berufe ohne Artikel nach sein." },
          { wrong: "Ich arbeite bei Bäckerei.", right: "Ich arbeite in einer Bäckerei.", why: "in + Dativ für Betriebe; bei + Firmenname." },
        ],
      },
    ],
    grammar: ["nebensaetze-a2"],
    vocabDecks: ["a2-work"],
    reading: "erster-arbeitstag",
    writing: "email-entschuldigung-kurs",
    exercises: [
      {
        id: "l-a2-3-e1", type: "multiple-choice",
        prompt: "Welche Anrede ist korrekt, wenn Sie den Namen nicht kennen?",
        options: ["Hallo!", "Liebe Firma,", "Sehr geehrte Damen und Herren,", "Guten Tag Sie,"],
        answerIndex: 2,
        explanation: "Standard für unbekannte Empfänger.",
        skill: "writing",
      },
      {
        id: "l-a2-3-e2", type: "fill-blank",
        prompt: "Ergänzen Sie.",
        sentence: "Ich arbeite seit zwei Jahren ___ einer Bäckerei und möchte eine Ausbildung ___ Pflegefachkraft machen.",
        answers: [["in"], ["als"]],
        explanation: "in einer Bäckerei; Ausbildung als …",
        skill: "vocabulary",
      },
      {
        id: "l-a2-3-e3", type: "order",
        prompt: "Bilden Sie den Nebensatz.",
        tokens: ["weil", "ich", "Erfahrung", "habe", "in der Gastronomie"],
        answer: "weil ich Erfahrung in der Gastronomie habe",
        explanation: "Verb am Ende.",
        skill: "grammar",
      },
      {
        id: "l-a2-3-e4", type: "writing",
        prompt: "Schreiben Sie eine formelle E-Mail (60 Wörter): Sie interessieren sich für eine Stelle und fragen nach dem Beginn und den Arbeitszeiten.",
        minWords: 60,
        checklist: ["Sehr geehrte …", "Bezug zur Anzeige", "zwei Fragen", "Mit freundlichen Grüßen"],
        sampleAnswer:
          "Sehr geehrte Damen und Herren,\n\nich habe Ihre Anzeige für eine Stelle als Küchenhilfe gelesen und interessiere mich sehr dafür. Ich arbeite seit zwei Jahren in einem Restaurant und habe Erfahrung mit Hygienevorschriften.\n\nKönnten Sie mir bitte mitteilen, wann die Stelle beginnt und wie die Arbeitszeiten sind?\n\nÜber eine Antwort würde ich mich freuen.\n\nMit freundlichen Grüßen\nKarim Aziz",
        skill: "writing",
      },
    ],
    homework: [
      "Schreiben Sie Ihren tabellarischen Lebenslauf (Vorlage im Ausbildung-Bereich).",
      "Lernen Sie die zehn Wörter der Kartei „Arbeit und Berufe“.",
      "Suchen Sie zwei echte Ausbildungsanzeigen und notieren Sie die Anforderungen.",
    ],
    revision: ["Berufe ohne Artikel nach sein", "in + Dativ / bei + Firma", "Formelle E-Mail-Bausteine"],
  },
  {
    slug: "a2-l4-gesundheit",
    level: "A2",
    moduleSlug: "a2-m2-arbeit-und-gesundheit",
    order: 2,
    title: "Health: doctor, symptoms, sick leave",
    titleDe: "Gesundheit: Arzt, Beschwerden, Krankmeldung",
    summary:
      "Make an appointment, describe symptoms and report sick correctly — with reflexive verbs and the imperative.",
    minutes: 55,
    xp: 70,
    skills: ["vocabulary", "listening", "speaking", "grammar"],
    objectives: [
      "Describe symptoms precisely",
      "Make and change an appointment on the phone",
      "Use reflexive verbs (sich fühlen, sich erkälten, sich ausruhen)",
      "Understand a doctor's instructions",
    ],
    blocks: [
      { kind: "objectives", items: ["Beschwerden beschreiben", "Termin am Telefon", "Reflexive Verben", "Imperativ verstehen"] },
      { kind: "vocab", title: "Wortschatz: Gesundheit und Körper", deck: "a2-health" },
      { kind: "grammar", slug: "reflexive-verben" },
      { kind: "grammar", slug: "imperativ" },
      {
        kind: "examples",
        title: "Beim Arzt",
        items: [
          { de: "Ich habe seit drei Tagen Halsschmerzen und Fieber.", en: "I've had a sore throat and fever for three days." },
          { de: "Mir ist schwindelig.", en: "I feel dizzy." },
          { de: "Nehmen Sie die Tabletten dreimal täglich nach dem Essen.", en: "Take the tablets three times a day after meals." },
          { de: "Sie sollten sich ein paar Tage ausruhen.", en: "You should rest for a few days." },
          { de: "Ich brauche eine Bescheinigung für meinen Arbeitgeber.", en: "I need a sick note for my employer." },
        ],
      },
      {
        kind: "culture",
        title: "Krankmeldung in Deutschland",
        body: [
          "Melden Sie sich am ersten Tag vor Arbeitsbeginn telefonisch krank — nicht per WhatsApp, außer das ist im Betrieb üblich.",
          "Die Arbeitsunfähigkeitsbescheinigung (AU) verlangen viele Betriebe schon ab dem ersten Tag, gesetzlich ab dem vierten.",
          "Der Arzt schreibt Sie krank; Sie entscheiden nicht selbst, wie lange.",
        ],
      },
    ],
    grammar: ["reflexive-verben", "imperativ"],
    vocabDecks: ["a2-health"],
    listening: "termin-beim-arzt",
    speaking: "termin-vereinbaren-rollenspiel",
    exercises: [
      {
        id: "l-a2-4-e1", type: "fill-blank",
        prompt: "Ergänzen Sie das Reflexivpronomen.",
        sentence: "Ich fühle ___ nicht gut und habe ___ erkältet.",
        answers: [["mich"], ["mich"]],
        explanation: "sich fühlen, sich erkälten → mich.",
        skill: "grammar",
      },
      {
        id: "l-a2-4-e2", type: "transform",
        prompt: "Bilden Sie den höflichen Imperativ.",
        input: "Sie ruhen sich aus.",
        answers: ["Ruhen Sie sich aus!"],
        explanation: "Verb + Sie + sich + Präfix.",
        skill: "grammar",
      },
      {
        id: "l-a2-4-e3", type: "multiple-choice",
        prompt: "Was sagen Sie am Telefon in der Praxis?",
        options: [
          "Ich will einen Termin.",
          "Ich würde gern einen Termin vereinbaren.",
          "Gib mir einen Termin.",
          "Termin, bitte!",
        ],
        answerIndex: 1,
        explanation: "Konjunktiv II ist höflich und Standard.",
        skill: "speaking",
      },
      {
        id: "l-a2-4-e4", type: "speaking",
        prompt: "Melden Sie sich telefonisch krank (Name, Grund, Arztbesuch, Bescheinigung).",
        target: "Guten Morgen, hier ist Karim Aziz. Ich muss mich leider krankmelden. Ich habe Fieber und gehe heute zum Arzt. Die Bescheinigung schicke ich per E-Mail.",
        skill: "speaking",
      },
    ],
    homework: [
      "Lernen Sie zehn Körperteile mit Artikel.",
      "Üben Sie ein Telefongespräch „Termin verschieben“ mit einem Partner.",
      "Schreiben Sie eine kurze Krankmeldung per E-Mail.",
    ],
    revision: ["mich/dich/sich/uns/euch/sich", "Imperativ: Komm! Kommt! Kommen Sie!", "seit + Dativ für Beschwerden"],
  },
  {
    slug: "a2-l5-praeteritum-erzaehlen",
    level: "A2",
    moduleSlug: "a2-m3-erzaehlen-und-vergleichen",
    order: 1,
    title: "Telling stories: Präteritum and adjectives",
    titleDe: "Erzählen: Präteritum und Adjektive",
    summary:
      "war, hatte, konnte plus adjective endings and comparisons — everything you need to tell a story well.",
    minutes: 60,
    xp: 75,
    skills: ["grammar", "reading", "writing"],
    objectives: [
      "Use war, hatte and the modal Präteritum in speech",
      "Add correct adjective endings",
      "Compare with als and so … wie",
      "Write a short narrative text",
    ],
    blocks: [
      { kind: "objectives", items: ["Präteritum", "Adjektivendungen", "Vergleiche", "Erzähltext schreiben"] },
      { kind: "grammar", slug: "praeteritum" },
      { kind: "grammar", slug: "adjektivdeklination" },
      { kind: "grammar", slug: "komparativ-superlativ" },
      {
        kind: "examples",
        title: "Erzählen mit Struktur",
        items: [
          { de: "Als Kind wohnte ich in einer kleinen Stadt.", en: "As a child I lived in a small town." },
          { de: "Damals hatte ich kein Handy und es gab kein Internet.", en: "Back then I had no mobile and there was no internet." },
          { de: "Zuerst … dann … danach … am Ende …", en: "First … then … after that … in the end …" },
          { de: "Der Umzug war schwieriger als ich dachte.", en: "The move was harder than I thought." },
        ],
      },
    ],
    grammar: ["praeteritum", "adjektivdeklination", "komparativ-superlativ"],
    vocabDecks: ["a2-travel"],
    reading: "mietwohnung-hausordnung",
    writing: "brief-wohnungsanfrage",
    exercises: [
      {
        id: "l-a2-5-e1", type: "transform",
        prompt: "Setzen Sie ins Präteritum.",
        input: "Ich bin müde und habe keine Zeit.",
        answers: ["Ich war müde und hatte keine Zeit."],
        explanation: "sein → war, haben → hatte.",
        skill: "grammar",
      },
      {
        id: "l-a2-5-e2", type: "fill-blank",
        prompt: "Adjektivendungen ergänzen.",
        sentence: "Wir haben eine klein___ Wohnung mit einem groß___ Balkon.",
        answers: [["e"], ["en"]],
        explanation: "eine kleine Wohnung; mit einem großen Balkon (Dativ).",
        skill: "grammar",
      },
      {
        id: "l-a2-5-e3", type: "multiple-choice",
        prompt: "Die Miete ist hier höher ___ in meiner Heimatstadt.",
        options: ["wie", "als", "so", "wie als"],
        answerIndex: 1,
        explanation: "Komparativ + als.",
        skill: "grammar",
      },
      {
        id: "l-a2-5-e4", type: "writing",
        prompt: "Schreiben Sie 60 Wörter über Ihren ersten Monat in Deutschland (Präteritum und Perfekt gemischt).",
        minWords: 60,
        checklist: ["war/hatte verwendet", "zwei Adjektive mit Endung", "ein Vergleich", "chronologische Konnektoren"],
        sampleAnswer:
          "Mein erster Monat in Deutschland war schwierig. Ich hatte eine kleine Wohnung ohne Möbel und kannte niemanden. Zuerst musste ich mich beim Amt anmelden, dann habe ich ein Konto eröffnet. Das Wetter war kälter als in Marokko und die Bürokratie komplizierter als erwartet. Am Ende des Monats hatte ich aber schon zwei Freunde im Sprachkurs.",
        skill: "writing",
      },
    ],
    homework: [
      "Schreiben Sie eine Kindheitserinnerung (80 Wörter) im Präteritum.",
      "Markieren Sie in einem Zeitungstext alle Adjektivendungen.",
      "Bilden Sie zehn Vergleiche über Ihre Stadt und Ihre Heimatstadt.",
    ],
    revision: ["war, hatte, konnte, musste, wollte, es gab", "Dativ/Plural + Artikel → -en", "als für Vergleiche"],
  },
  {
    slug: "a2-l6-pruefungstraining-a2",
    level: "A2",
    moduleSlug: "a2-m4-pruefungstraining",
    order: 1,
    title: "A2 exam training",
    titleDe: "Prüfungstraining A2",
    summary: "Format, timing and strategies for Goethe A2 and telc A2, plus a grammar sweep.",
    minutes: 70,
    xp: 90,
    skills: ["reading", "listening", "writing", "speaking", "grammar"],
    objectives: [
      "Know every part of the A2 exam",
      "Handle the Sprachbausteine section of telc",
      "Write both A2 writing tasks in 30 minutes",
      "Do the paired speaking task confidently",
    ],
    blocks: [
      { kind: "objectives", items: ["Prüfungsteile", "Sprachbausteine", "Schreiben unter Zeitdruck", "Paarprüfung Sprechen"] },
      {
        kind: "table",
        table: {
          title: "Goethe A2 vs. telc A2",
          headers: ["Teil", "Goethe A2", "telc A2"],
          rows: [
            ["Lesen", "30 min, 4 Teile", "im Block mit Sprachbausteinen"],
            ["Grammatik", "integriert", "eigener Teil: Sprachbausteine"],
            ["Hören", "30 min", "20 min"],
            ["Schreiben", "30 min, 2 Aufgaben", "20 min, 1 Aufgabe"],
            ["Sprechen", "15 min, 3 Teile, paarweise", "15 min, 3 Teile, paarweise"],
          ],
        },
      },
      {
        kind: "checklist",
        title: "Grammatik-Check A2",
        items: [
          "Dativ (Präpositionen und Verben)",
          "Wechselpräpositionen",
          "Präteritum von sein/haben/Modalverben",
          "Perfekt sicher",
          "Adjektivendungen",
          "Komparativ und Superlativ",
          "Nebensätze mit weil, dass, wenn, obwohl",
          "Reflexive Verben",
          "Imperativ",
        ],
      },
      {
        kind: "tip",
        title: "Sprachbausteine-Strategie",
        body: "Lesen Sie den ganzen Satz, nicht nur die Lücke. Prüfen Sie zuerst, ob ein Konnektor, eine Präposition oder eine Verbform fehlt — das halbiert die Optionen.",
      },
    ],
    grammar: ["dativ", "wechselpraepositionen", "praeteritum", "adjektivdeklination", "nebensaetze-a2"],
    vocabDecks: ["a2-work", "a2-health", "a2-shopping", "a2-travel", "a2-routine"],
    reading: "mietwohnung-hausordnung",
    listening: "termin-beim-arzt",
    writing: "email-entschuldigung-kurs",
    speaking: "ueber-den-alltag-sprechen",
    exercises: [
      {
        id: "l-a2-6-e1", type: "multiple-choice",
        prompt: "Sprachbaustein: Ich interessiere mich ___ Technik.",
        options: ["für", "auf", "über", "an"],
        answerIndex: 0,
        explanation: "sich interessieren für.",
        skill: "grammar",
      },
      {
        id: "l-a2-6-e2", type: "fill-blank",
        prompt: "Gemischt.",
        sentence: "___ ich krank war, konnte ich nicht arbeiten. Deshalb ___ ich zum Arzt gegangen.",
        answers: [["Weil", "Als"], ["bin"]],
        explanation: "Weil/Als + Verb am Ende; gehen → sein.",
        skill: "grammar",
      },
      {
        id: "l-a2-6-e3", type: "writing",
        prompt: "Prüfungsaufgabe (30 Wörter): Sie kommen später zur Arbeit. Schreiben Sie Ihrer Chefin.",
        minWords: 30,
        checklist: ["Anrede Sie-Form", "Grund", "Verspätung in Minuten", "Entschuldigung"],
        sampleAnswer:
          "Guten Morgen Frau Vogt,\n\nleider ist mein Zug ausgefallen und ich komme etwa 25 Minuten später. Es tut mir sehr leid. Ich beginne dann sofort mit der Arbeit.\n\nViele Grüße\nKarim Aziz",
        skill: "writing",
      },
      {
        id: "l-a2-6-e4", type: "speaking",
        prompt: "Paarprüfung Teil 3: Planen Sie mit Ihrem Partner einen Kursausflug.",
        target: "Ich schlage vor, wir fahren am Samstag nach Dresden. Treffpunkt um acht Uhr am Hauptbahnhof. Wir kaufen ein Gruppenticket. Bist du einverstanden?",
        skill: "speaking",
      },
    ],
    homework: [
      "Schreiben Sie den Mock-Test „Goethe A2 Mock 1“ komplett.",
      "Machen Sie den telc-A2-Sprachbausteine-Teil zweimal.",
      "Wiederholen Sie alle A2-Cheat-Sheets.",
    ],
    revision: ["Alle A2-Grammatikthemen", "50 Kernvokabeln pro Kartei", "Prüfungszeiten einhalten"],
  },
];

export const a2Course: Course = {
  level: "A2",
  title: "German A2 — Elementary",
  subtitle: "Everyday independence: work, health, housing and the past",
  description:
    "A2 turns fragments into conversations. You learn the dative, two-way prepositions, the Präteritum, adjective endings and subordinate clauses, and you handle doctor's appointments, job enquiries and complaints on your own.",
  hours: 110,
  vocabularyTarget: 1300,
  color: "a2",
  canDo: [
    "Communicate in routine tasks requiring simple exchange of information",
    "Describe your background, education and immediate needs",
    "Handle appointments, sick leave and shopping situations",
    "Write short formal and informal messages",
    "Understand short announcements and simple conversations",
  ],
  grammarFocus: [
    "Dative case, prepositions and verbs",
    "Two-way prepositions (wo / wohin)",
    "Präteritum of sein, haben and modals",
    "Adjective endings",
    "Comparative and superlative",
    "Subordinate clauses (weil, dass, wenn, obwohl)",
    "Reflexive verbs and the imperative",
  ],
  exams: ["goethe-a2-mock-1", "telc-a2-mock-1"],
  finalExam: "goethe-a2-mock-1",
  modules: [
    {
      slug: "a2-m1-menschen-und-wege",
      level: "A2",
      order: 1,
      title: "People and places",
      titleDe: "Menschen und Wege",
      description: "The dative in everyday life and the difference between wo and wohin.",
      icon: "Users",
      outcomes: ["Dativ-Präpositionen", "Dativ-Verben", "Wechselpräpositionen", "Ortsangaben"],
      lessons: ["a2-l1-dativ-alltag", "a2-l2-wechselpraepositionen"],
      miniTest: "a2-m1-test",
    },
    {
      slug: "a2-m2-arbeit-und-gesundheit",
      level: "A2",
      order: 2,
      title: "Work and health",
      titleDe: "Arbeit und Gesundheit",
      description: "Applications, formal emails, symptoms and sick leave.",
      icon: "Briefcase",
      outcomes: ["Formelle E-Mail", "Berufe", "Beschwerden", "Reflexive Verben"],
      lessons: ["a2-l3-arbeit-und-bewerbung", "a2-l4-gesundheit"],
      miniTest: "a2-m2-test",
    },
    {
      slug: "a2-m3-erzaehlen-und-vergleichen",
      level: "A2",
      order: 3,
      title: "Narrating and comparing",
      titleDe: "Erzählen und Vergleichen",
      description: "Präteritum, adjective endings and comparisons for real stories.",
      icon: "BookOpen",
      outcomes: ["Präteritum", "Adjektivendungen", "Vergleiche", "Erzähltexte"],
      lessons: ["a2-l5-praeteritum-erzaehlen"],
      miniTest: "a2-m3-test",
    },
    {
      slug: "a2-m4-pruefungstraining",
      level: "A2",
      order: 4,
      title: "Exam training A2",
      titleDe: "Prüfungstraining A2",
      description: "Goethe A2 and telc A2 formats, Sprachbausteine and timing.",
      icon: "GraduationCap",
      outcomes: ["Prüfungsformate", "Sprachbausteine", "Schreibaufgaben", "Paarprüfung"],
      lessons: ["a2-l6-pruefungstraining-a2"],
    },
  ],
};
