import type { Course, Lesson } from "@/lib/types";

export const b1Lessons: Lesson[] = [
  {
    slug: "b1-l1-hoeflichkeit-konjunktiv",
    level: "B1",
    moduleSlug: "b1-m1-hoeflich-und-genau",
    order: 1,
    title: "Politeness and hypotheses: Konjunktiv II",
    titleDe: "Höflichkeit und Hypothesen: Konjunktiv II",
    summary:
      "Könnten Sie …? Ich hätte gern … Wenn ich Zeit hätte … — the single fastest upgrade to your spoken German.",
    minutes: 60,
    xp: 80,
    skills: ["grammar", "speaking", "writing"],
    objectives: [
      "Make polite requests with könnten, würden, hätten",
      "Give advice with sollte and an deiner Stelle würde ich",
      "Build unreal conditions with wenn",
      "Use the past Konjunktiv II for regrets",
    ],
    blocks: [
      { kind: "objectives", items: ["Höfliche Bitten", "Ratschläge", "Irreale Bedingungen", "Vergangenheit: hätte/wäre"] },
      { kind: "grammar", slug: "konjunktiv-2" },
      {
        kind: "dialogue",
        title: "Bei der Ausländerbehörde",
        lines: [
          { speaker: "Karim", de: "Guten Tag, ich hätte eine Frage zu meinem Aufenthaltstitel." },
          { speaker: "Sachbearbeiterin", de: "Gern. Haben Sie einen Termin?" },
          { speaker: "Karim", de: "Ja, um zehn Uhr. Könnten Sie mir sagen, welche Unterlagen ich für die Verlängerung brauche?" },
          { speaker: "Sachbearbeiterin", de: "Sie bräuchten den Ausbildungsvertrag, den Nachweis der Krankenversicherung und ein Passfoto." },
          { speaker: "Karim", de: "Wäre es möglich, die Unterlagen später per E-Mail nachzureichen?" },
          { speaker: "Sachbearbeiterin", de: "Das ginge, aber nur bis Ende des Monats." },
        ],
      },
      {
        kind: "examples",
        title: "Register-Vergleich",
        items: [
          { de: "Ich will einen Termin. → Ich würde gern einen Termin vereinbaren.", en: "direct → polite" },
          { de: "Gib mir das Formular. → Könnten Sie mir bitte das Formular geben?", en: "command → request" },
          { de: "Du musst mehr lernen. → Du solltest mehr lernen.", en: "obligation → advice" },
        ],
      },
      {
        kind: "tip",
        title: "Prüfungstipp",
        body: "In der mündlichen Prüfung reichen drei Formen für einen besseren Eindruck: Könnten Sie …?, Ich würde gern …, Ich hätte eine Frage.",
      },
    ],
    grammar: ["konjunktiv-2"],
    vocabDecks: ["b1-education"],
    speaking: "problem-loesen-am-telefon",
    writing: "beschwerde-brief",
    exercises: [
      {
        id: "l-b1-1-e1", type: "transform",
        prompt: "Machen Sie die Bitte höflich.",
        input: "Geben Sie mir das Formular.",
        answers: ["Könnten Sie mir bitte das Formular geben?", "Würden Sie mir bitte das Formular geben?"],
        explanation: "Konjunktiv II + bitte.",
        skill: "grammar",
      },
      {
        id: "l-b1-1-e2", type: "fill-blank",
        prompt: "Irreale Bedingung.",
        sentence: "Wenn ich mehr Zeit ___ (haben), ___ ich einen Abendkurs ___ (besuchen).",
        answers: [["hätte"], ["würde"], ["besuchen"]],
        explanation: "hätte + würde … besuchen.",
        skill: "grammar",
      },
      {
        id: "l-b1-1-e3", type: "transform",
        prompt: "Formulieren Sie einen Ratschlag.",
        input: "Er lernt zu wenig.",
        answers: ["Er sollte mehr lernen.", "An seiner Stelle würde ich mehr lernen."],
        explanation: "sollte oder an … Stelle würde ich.",
        skill: "grammar",
      },
      {
        id: "l-b1-1-e4", type: "writing",
        prompt: "Schreiben Sie fünf höfliche Sätze für einen Behördentermin.",
        minWords: 45,
        checklist: ["fünf Sätze", "drei verschiedene Konjunktiv-II-Formen", "Sie-Form"],
        sampleAnswer:
          "Guten Tag, ich hätte eine Frage zu meinem Antrag. Könnten Sie mir sagen, wie lange die Bearbeitung dauert? Wäre es möglich, den Termin auf nächste Woche zu verschieben? Ich würde die Unterlagen gern per E-Mail nachreichen. Dürfte ich Sie um eine schriftliche Bestätigung bitten?",
        skill: "writing",
      },
    ],
    homework: [
      "Schreiben Sie zehn höfliche Bitten für Alltagssituationen.",
      "Formulieren Sie fünf irreale Sätze über Ihr Leben („Wenn ich …“).",
      "Üben Sie den Dialog „Bei der Ausländerbehörde“ laut mit Rollentausch.",
    ],
    revision: ["wäre, hätte, würde, könnte, müsste, sollte", "würde + Infinitiv für andere Verben", "hätte/wäre + Partizip II"],
  },
  {
    slug: "b1-l2-passiv-und-formell",
    level: "B1",
    moduleSlug: "b1-m1-hoeflich-und-genau",
    order: 2,
    title: "The passive and formal German",
    titleDe: "Passiv und formelle Sprache",
    summary:
      "Understand official letters, house rules and workplace instructions — and write them yourself.",
    minutes: 60,
    xp: 80,
    skills: ["grammar", "reading", "writing"],
    objectives: [
      "Form the passive in all common tenses",
      "Combine the passive with modal verbs",
      "Distinguish process and state passive",
      "Write two formal sentences with passive structures",
    ],
    blocks: [
      { kind: "objectives", items: ["werden + Partizip II", "Passiv mit Modalverb", "Zustandspassiv", "Formelle Texte"] },
      { kind: "grammar", slug: "passiv" },
      {
        kind: "examples",
        title: "Passiv im Alltag",
        items: [
          { de: "Die Unterlagen müssen bis Freitag eingereicht werden.", en: "The documents must be submitted by Friday." },
          { de: "Hier wird nicht geraucht.", en: "No smoking here." },
          { de: "Das Treppenhaus wird jede Woche gereinigt.", en: "The stairwell is cleaned every week." },
          { de: "Der Antrag ist bereits bearbeitet.", en: "The application has already been processed." },
        ],
      },
      {
        kind: "table",
        table: {
          title: "Aktiv → Passiv im Betrieb",
          headers: ["Aktiv", "Passiv"],
          rows: [
            ["Man kontrolliert die Maschinen täglich.", "Die Maschinen werden täglich kontrolliert."],
            ["Der Meister hat den Fehler gefunden.", "Der Fehler ist (vom Meister) gefunden worden."],
            ["Man muss das Formular unterschreiben.", "Das Formular muss unterschrieben werden."],
          ],
        },
      },
    ],
    grammar: ["passiv"],
    vocabDecks: ["b1-media"],
    reading: "ausbildung-in-deutschland",
    writing: "beschwerde-brief",
    exercises: [
      {
        id: "l-b1-2-e1", type: "transform",
        prompt: "Ins Passiv setzen.",
        input: "Man prüft die Unterlagen sorgfältig.",
        answers: ["Die Unterlagen werden sorgfältig geprüft."],
        explanation: "man verschwindet, Akkusativ wird Subjekt.",
        skill: "grammar",
      },
      {
        id: "l-b1-2-e2", type: "transform",
        prompt: "Passiv mit Modalverb.",
        input: "Man muss die Frist einhalten.",
        answers: ["Die Frist muss eingehalten werden."],
        explanation: "Modal + Partizip II + werden.",
        skill: "grammar",
      },
      {
        id: "l-b1-2-e3", type: "multiple-choice",
        prompt: "Der Laden ___ sonntags geschlossen. (Zustand)",
        options: ["wird", "ist", "hat", "wurde"],
        answerIndex: 1,
        explanation: "Zustandspassiv mit sein.",
        skill: "grammar",
      },
      {
        id: "l-b1-2-e4", type: "fill-blank",
        prompt: "Passiv Perfekt.",
        sentence: "Die Wohnung ___ schon ___ ___.",
        answers: [["ist"], ["vermietet"], ["worden"]],
        explanation: "ist + Partizip II + worden.",
        skill: "grammar",
      },
    ],
    homework: [
      "Suchen Sie einen offiziellen Brief und markieren Sie alle Passivformen.",
      "Schreiben Sie eine Hausordnung mit sechs Passivsätzen.",
      "Wandeln Sie zehn Aktivsätze aus Ihrem Betrieb ins Passiv um.",
    ],
    revision: ["wird/wurde/ist … worden", "Modal + Partizip II + werden", "sein + Partizip II = Zustand"],
  },
  {
    slug: "b1-l3-relativsaetze-beschreiben",
    level: "B1",
    moduleSlug: "b1-m2-argumentieren",
    order: 1,
    title: "Describing precisely: relative clauses",
    titleDe: "Genau beschreiben: Relativsätze",
    summary:
      "Turn two short sentences into one precise sentence — the structure that makes you sound B1 rather than A2.",
    minutes: 55,
    xp: 75,
    skills: ["grammar", "reading", "speaking"],
    objectives: [
      "Choose the right relative pronoun (gender, number, case)",
      "Use prepositions with relative pronouns",
      "Use wo for places and was for whole ideas",
      "Describe people and jobs precisely",
    ],
    blocks: [
      { kind: "objectives", items: ["Relativpronomen", "Präposition + Relativpronomen", "wo / was", "Personen beschreiben"] },
      { kind: "grammar", slug: "relativsaetze" },
      {
        kind: "examples",
        title: "Im Bewerbungsgespräch",
        items: [
          { de: "Das ist die Kollegin, die mich eingearbeitet hat.", en: "That's the colleague who trained me." },
          { de: "Ein Betrieb, in dem man viel lernt, ist mir wichtiger als das Gehalt.", en: "A company where you learn a lot matters more to me than the salary." },
          { de: "Die Aufgabe, die mir am meisten Spaß macht, ist die Kundenberatung.", en: "The task I enjoy most is customer advice." },
          { de: "Er kam zu spät, was den Chef geärgert hat.", en: "He arrived late, which annoyed the boss." },
        ],
      },
      {
        kind: "warning",
        title: "denen nicht vergessen",
        body: "Dativ Plural ist denen: die Kollegen, denen ich helfe. Das ist die einzige Form, die von den Artikeln abweicht (plus Genitiv dessen/deren).",
      },
    ],
    grammar: ["relativsaetze"],
    vocabDecks: ["b1-feelings"],
    reading: "leben-in-der-stadt-oder-auf-dem-land",
    speaking: "bewerbungsgespraech",
    exercises: [
      {
        id: "l-b1-3-e1", type: "fill-blank",
        prompt: "Relativpronomen ergänzen.",
        sentence: "Der Betrieb, ___ mich eingeladen hat, liegt in Leipzig. Die Kollegin, ___ ich helfe, ist neu.",
        answers: [["der"], ["der"]],
        explanation: "Subjekt maskulin → der; helfen + Dativ feminin → der.",
        skill: "grammar",
      },
      {
        id: "l-b1-3-e2", type: "fill-blank",
        prompt: "Dativ Plural.",
        sentence: "Die Azubis, ___ wir das Glossar gegeben haben, lernen schneller.",
        answers: [["denen"]],
        explanation: "Dativ Plural = denen.",
        skill: "grammar",
      },
      {
        id: "l-b1-3-e3", type: "transform",
        prompt: "Verbinden Sie zu einem Satz.",
        input: "Ich habe eine Stelle gefunden. Die Stelle passt perfekt zu meiner Erfahrung.",
        answers: ["Ich habe eine Stelle gefunden, die perfekt zu meiner Erfahrung passt."],
        explanation: "Relativsatz statt zwei Hauptsätze.",
        skill: "grammar",
      },
      {
        id: "l-b1-3-e4", type: "speaking",
        prompt: "Beschreiben Sie drei Personen aus Ihrem Betrieb mit Relativsätzen.",
        target: "Das ist Frau Vogt, die für den Dienstplan zuständig ist. Und das ist Ali, mit dem ich meistens die Spätschicht mache.",
        skill: "speaking",
      },
    ],
    homework: [
      "Schreiben Sie zehn Relativsätze über Menschen und Orte in Ihrem Leben.",
      "Markieren Sie in einem Zeitungsartikel alle Relativpronomen und ihren Kasus.",
      "Beschreiben Sie Ihren Traumbetrieb in fünf Sätzen mit Relativsätzen.",
    ],
    revision: ["Genus/Numerus vom Bezugswort, Kasus von der Funktion", "denen (Dativ Plural)", "wo / in dem / in der"],
  },
  {
    slug: "b1-l4-meinung-argumentieren",
    level: "B1",
    moduleSlug: "b1-m2-argumentieren",
    order: 2,
    title: "Expressing and defending an opinion",
    titleDe: "Meinung äußern und begründen",
    summary:
      "Structure an argument, concede a point and reach a conclusion — for the forum task and the speaking exam.",
    minutes: 60,
    xp: 80,
    skills: ["writing", "speaking", "grammar"],
    objectives: [
      "Open with a clear position",
      "Support it with reasons and examples",
      "Concede a counter-argument",
      "Use two-part connectors",
    ],
    blocks: [
      { kind: "objectives", items: ["Position formulieren", "Argumente strukturieren", "Gegenargument einräumen", "Konnektoren"] },
      { kind: "grammar", slug: "zweiteilige-konnektoren" },
      { kind: "grammar", slug: "verben-mit-praeposition" },
      {
        kind: "table",
        table: {
          title: "Bausteine für Argumentation",
          headers: ["Funktion", "Formulierung"],
          rows: [
            ["Position", "Meiner Meinung nach … / Ich bin der Ansicht, dass …"],
            ["Argument", "Erstens … Zweitens … / Ein wichtiger Punkt ist, dass …"],
            ["Beispiel", "Aus meiner Erfahrung … / Zum Beispiel …"],
            ["Einräumen", "Zwar …, aber … / Natürlich …, dennoch …"],
            ["Gegenposition", "Manche behaupten, dass … Dagegen spricht, dass …"],
            ["Fazit", "Zusammenfassend … / Insgesamt halte ich … für …"],
          ],
        },
      },
      {
        kind: "tip",
        title: "Die 4-Satz-Formel",
        body: "Position → Grund → Beispiel → Fazit. Vier gute Sätze sind besser als zehn vage. Fügen Sie dann ein Gegenargument dazu, und Sie haben eine B1-Antwort.",
      },
    ],
    grammar: ["zweiteilige-konnektoren", "verben-mit-praeposition"],
    vocabDecks: ["b1-environment", "b1-media"],
    reading: "leben-in-der-stadt-oder-auf-dem-land",
    writing: "forumsbeitrag-meinung",
    exercises: [
      {
        id: "l-b1-4-e1", type: "fill-blank",
        prompt: "Konnektoren ergänzen.",
        sentence: "___ ist die Miete hoch, ___ die Lage ist perfekt.",
        answers: [["Zwar"], ["aber"]],
        explanation: "zwar … aber.",
        skill: "grammar",
      },
      {
        id: "l-b1-4-e2", type: "fill-blank",
        prompt: "Verben mit Präposition.",
        sentence: "Ich interessiere mich ___ Technik und bewerbe mich ___ eine Ausbildung.",
        answers: [["für"], ["um"]],
        explanation: "sich interessieren für, sich bewerben um.",
        skill: "grammar",
      },
      {
        id: "l-b1-4-e3", type: "order",
        prompt: "Bilden Sie den Satz.",
        tokens: ["Je", "mehr", "ich", "übe,", "desto", "sicherer", "werde", "ich"],
        answer: "Je mehr ich übe, desto sicherer werde ich",
        explanation: "je + Verb am Ende, desto + Komparativ + Verb + Subjekt.",
        skill: "grammar",
      },
      {
        id: "l-b1-4-e4", type: "writing",
        prompt: "Forumsbeitrag (80 Wörter): „Sollten Handys im Unterricht erlaubt sein?“",
        minWords: 80,
        checklist: ["Position", "zwei Argumente", "Beispiel", "Gegenargument", "Fazit"],
        sampleAnswer:
          "Meiner Meinung nach sollten Handys im Unterricht erlaubt sein, aber mit Regeln. Erstens brauche ich mein Handy als Wörterbuch, weil ich Deutsch noch lerne. Zweitens arbeiten wir auch im Betrieb mit digitalen Anleitungen. Zum Beispiel lese ich technische Texte auf dem Tablet. Natürlich stört es, wenn ständig Nachrichten kommen; deshalb sollte das Handy lautlos auf dem Tisch liegen. Zusammenfassend halte ich klare Regeln für besser als ein Verbot.",
        skill: "writing",
      },
    ],
    homework: [
      "Schreiben Sie zwei Forumsbeiträge zu unterschiedlichen Themen (je 80 Wörter).",
      "Sammeln Sie zehn Verben mit Präposition aus Ihrem Alltag.",
      "Diskutieren Sie ein Thema fünf Minuten mit einem Lernpartner.",
    ],
    revision: ["Meiner Meinung nach / Ich bin der Ansicht, dass", "zwar … aber, nicht nur … sondern auch, je … desto", "Verb + Präposition + Kasus"],
  },
  {
    slug: "b1-l5-pruefungstraining-b1",
    level: "B1",
    moduleSlug: "b1-m3-pruefungstraining",
    order: 1,
    title: "B1 exam training (Goethe & telc)",
    titleDe: "Prüfungstraining B1",
    summary:
      "Module by module: what is tested, how it is graded, and how to spend every minute.",
    minutes: 75,
    xp: 100,
    skills: ["reading", "listening", "writing", "speaking", "grammar"],
    objectives: [
      "Know the four modules and their timing",
      "Apply a fixed plan to each writing task",
      "Handle the paired speaking exam",
      "Identify your weakest module and revise it",
    ],
    blocks: [
      { kind: "objectives", items: ["Modulaufbau", "Schreibpläne", "Sprechprüfung", "Schwachstellenanalyse"] },
      {
        kind: "table",
        table: {
          title: "Goethe B1 — Zeitplan",
          headers: ["Modul", "Zeit", "Aufgaben", "Strategie"],
          rows: [
            ["Lesen", "65 min", "5 Teile", "Fragen zuerst, dann scannen"],
            ["Hören", "40 min", "4 Teile", "Teil 1 zweimal, Teil 2 einmal"],
            ["Schreiben", "60 min", "3 Aufgaben (80/40/40 Wörter)", "20/15/25 Minuten"],
            ["Sprechen", "15 min", "Planen, Präsentation, Feedback", "Interaktion zeigen"],
          ],
        },
      },
      {
        kind: "checklist",
        title: "Grammatik-Check B1",
        items: [
          "Konjunktiv II (höflich und irreal)",
          "Passiv in allen Zeiten",
          "Relativsätze inkl. denen",
          "Genitiv und Genitiv-Präpositionen",
          "Verben mit Präposition + da-/wo-Formen",
          "Indirekte Fragen und Infinitivsätze",
          "Zweiteilige Konnektoren",
        ],
      },
      {
        kind: "tip",
        title: "Punkte retten",
        body: "Im Schreiben zählt Vollständigkeit stärker als Perfektion: alle Inhaltspunkte bearbeiten, Anrede und Gruß nie vergessen, Register durchhalten.",
      },
    ],
    grammar: ["konjunktiv-2", "passiv", "relativsaetze", "genitiv", "verben-mit-praeposition", "indirekte-fragen"],
    vocabDecks: ["b1-education", "b1-environment", "b1-media", "b1-feelings"],
    reading: "ausbildung-in-deutschland",
    listening: "radiobeitrag-wohnen",
    writing: "forumsbeitrag-meinung",
    speaking: "bewerbungsgespraech",
    exercises: [
      {
        id: "l-b1-5-e1", type: "multiple-choice",
        prompt: "Welche Formulierung passt in eine formelle E-Mail?",
        options: [
          "Hey, ich kann nicht kommen.",
          "Leider kann ich an der Besprechung nicht teilnehmen.",
          "Ich komme nicht, sorry.",
          "Bin krank, bis dann.",
        ],
        answerIndex: 1,
        explanation: "Register: formell und vollständig.",
        skill: "writing",
      },
      {
        id: "l-b1-5-e2", type: "fill-blank",
        prompt: "Gemischte Grammatik.",
        sentence: "Die Unterlagen, ___ Sie eingereicht haben, müssen noch ___ (prüfen) werden.",
        answers: [["die"], ["geprüft"]],
        explanation: "Relativpronomen Akkusativ Plural + Passiv.",
        skill: "grammar",
      },
      {
        id: "l-b1-5-e3", type: "writing",
        prompt: "Prüfungsaufgabe Teil 2 (40 Wörter): formelle Nachricht — Termin verschieben.",
        minWords: 40,
        checklist: ["Sehr geehrte …", "Grund", "Alternativtermin", "Mit freundlichen Grüßen"],
        sampleAnswer:
          "Sehr geehrte Frau Vogt,\n\nleider muss ich unseren Termin am Mittwoch verschieben, da ich an diesem Tag Berufsschule habe. Wäre Donnerstag um 14 Uhr möglich? Für Ihre Rückmeldung wäre ich dankbar.\n\nMit freundlichen Grüßen\nKarim Aziz",
        skill: "writing",
      },
      {
        id: "l-b1-5-e4", type: "speaking",
        prompt: "Sprechen Teil 2: Halten Sie eine dreiminütige Präsentation zu „Lernen mit dem Handy“.",
        target:
          "Ich möchte über das Lernen mit dem Handy sprechen. Zuerst erzähle ich von meiner Erfahrung, dann vergleiche ich mit meinem Heimatland, danach nenne ich Vor- und Nachteile und am Ende gebe ich meine Meinung.",
        tips: ["Struktur ankündigen", "Beispiel nennen", "mit Fazit enden"],
        skill: "speaking",
      },
    ],
    homework: [
      "Schreiben Sie den Mock-Test „Goethe B1 Mock 1“ unter Prüfungsbedingungen.",
      "Machen Sie zusätzlich den telc-B1-Test und vergleichen Sie Ihre Ergebnisse.",
      "Wiederholen Sie das schwächste Modul zwei Wochen intensiv.",
    ],
    revision: ["Vier Module, jedes einzeln bestehen", "Schreibpläne 20/15/25 Minuten", "Alle B1-Grammatikthemen"],
  },
];

export const b1Course: Course = {
  level: "B1",
  title: "German B1 — Intermediate",
  subtitle: "Independence at work, in writing and in argument",
  description:
    "B1 is the level most Ausbildung places and residence procedures require. You learn Konjunktiv II, the passive, relative clauses, the genitive and verb–preposition patterns, and you argue your opinion in writing and speech.",
  hours: 130,
  vocabularyTarget: 2400,
  color: "b1",
  canDo: [
    "Deal with most situations while living and working in Germany",
    "Produce connected text on familiar topics",
    "Describe experiences, plans and opinions with reasons",
    "Write formal letters, complaints and forum posts",
    "Understand the main points of radio programmes and workplace discussions",
  ],
  grammarFocus: [
    "Konjunktiv II for politeness and hypotheses",
    "Passive voice in all tenses",
    "Relative clauses",
    "Genitive and genitive prepositions",
    "Verbs with fixed prepositions, da-/wo- forms",
    "Indirect questions and infinitive clauses",
    "Two-part connectors",
  ],
  exams: ["goethe-b1-mock-1", "telc-b1-mock-1"],
  finalExam: "goethe-b1-mock-1",
  modules: [
    {
      slug: "b1-m1-hoeflich-und-genau",
      level: "B1",
      order: 1,
      title: "Polite and precise",
      titleDe: "Höflich und genau",
      description: "Konjunktiv II and the passive: the two structures of formal German.",
      icon: "Sparkles",
      outcomes: ["Höfliche Bitten", "Irreale Bedingungen", "Passiv", "Formelle Texte"],
      lessons: ["b1-l1-hoeflichkeit-konjunktiv", "b1-l2-passiv-und-formell"],
      miniTest: "b1-m1-test",
    },
    {
      slug: "b1-m2-argumentieren",
      level: "B1",
      order: 2,
      title: "Describing and arguing",
      titleDe: "Beschreiben und argumentieren",
      description: "Relative clauses, connectors and a repeatable structure for opinions.",
      icon: "MessageSquare",
      outcomes: ["Relativsätze", "Konnektoren", "Verben mit Präposition", "Forumsbeitrag"],
      lessons: ["b1-l3-relativsaetze-beschreiben", "b1-l4-meinung-argumentieren"],
      miniTest: "b1-m2-test",
    },
    {
      slug: "b1-m3-pruefungstraining",
      level: "B1",
      order: 3,
      title: "Exam training B1",
      titleDe: "Prüfungstraining B1",
      description: "Module-by-module preparation for Goethe B1 and telc B1.",
      icon: "GraduationCap",
      outcomes: ["Modulaufbau", "Zeitmanagement", "Schreibpläne", "Sprechprüfung"],
      lessons: ["b1-l5-pruefungstraining-b1"],
    },
  ],
};
