import type { Course, Lesson } from "@/lib/types";

export const b2Lessons: Lesson[] = [
  {
    slug: "b2-l1-nominalstil",
    level: "B2",
    moduleSlug: "b2-m1-register-und-stil",
    order: 1,
    title: "Nominal style and formal register",
    titleDe: "Nominalstil und formelles Register",
    summary:
      "Aufgrund der hohen Nachfrage … Nach Abschluss der Ausbildung … — how to write and read administrative German.",
    minutes: 65,
    xp: 95,
    skills: ["grammar", "writing", "reading"],
    objectives: [
      "Transform clauses into noun phrases and back",
      "Use the genitive prepositions confidently",
      "Recognise nominal style in official documents",
      "Write a formal paragraph in nominal style",
    ],
    blocks: [
      { kind: "objectives", items: ["Nominalisierung", "Genitiv-Präpositionen", "Register erkennen", "Formell schreiben"] },
      { kind: "grammar", slug: "nominalisierung" },
      { kind: "grammar", slug: "genitiv" },
      {
        kind: "examples",
        title: "Zwei Register, ein Inhalt",
        items: [
          { de: "Weil die Nachfrage gestiegen ist, verlängern wir die Frist. → Aufgrund der gestiegenen Nachfrage verlängern wir die Frist.", en: "verbal → nominal" },
          { de: "Nachdem ich die Ausbildung abgeschlossen habe, möchte ich arbeiten. → Nach Abschluss der Ausbildung möchte ich arbeiten.", en: "verbal → nominal" },
          { de: "Wenn Sie Fragen haben, rufen Sie an. → Bei Fragen rufen Sie an.", en: "verbal → nominal" },
        ],
      },
      {
        kind: "tip",
        title: "Dosierung",
        body:
          "Nominalstil in Einleitung und Schluss, Verbalstil im Hauptteil. So bleibt der Text formell und trotzdem lesbar — genau das bewerten Prüfende positiv.",
      },
    ],
    grammar: ["nominalisierung", "genitiv"],
    vocabDecks: ["b2-academic"],
    reading: "fachkraeftemangel",
    writing: "formelle-email-b2",
    exercises: [
      {
        id: "l-b2-1-e1", type: "transform",
        prompt: "Nominalisieren Sie.",
        input: "Weil das Wetter schlecht war, wurde das Fest abgesagt.",
        answers: ["Wegen des schlechten Wetters wurde das Fest abgesagt.", "Aufgrund des schlechten Wetters wurde das Fest abgesagt."],
        explanation: "weil → wegen/aufgrund + Genitiv.",
        skill: "grammar",
      },
      {
        id: "l-b2-1-e2", type: "transform",
        prompt: "Verbalisieren Sie.",
        input: "Trotz der hohen Kosten hat sich die Investition gelohnt.",
        answers: ["Obwohl die Kosten hoch waren, hat sich die Investition gelohnt."],
        explanation: "trotz → obwohl.",
        skill: "grammar",
      },
      {
        id: "l-b2-1-e3", type: "fill-blank",
        prompt: "Nominalisierungen bilden.",
        sentence: "einführen → die ___ ; entscheiden → die ___ ; steigen → der ___",
        answers: [["Einführung"], ["Entscheidung"], ["Anstieg"]],
        explanation: "Standardformen.",
        skill: "grammar",
      },
      {
        id: "l-b2-1-e4", type: "writing",
        prompt: "Schreiben Sie einen formellen Absatz (60 Wörter) mit mindestens drei Nominalisierungen.",
        minWords: 60,
        checklist: ["drei Nominalisierungen", "eine Genitiv-Präposition", "formelles Register"],
        sampleAnswer:
          "Aufgrund der steigenden Zahl von Bewerbungen wurde die Bearbeitungszeit verlängert. Nach Prüfung der Unterlagen erhalten Sie innerhalb von vier Wochen einen Bescheid. Bei Rückfragen zur Anerkennung Ihres Abschlusses steht Ihnen die Beratungsstelle zur Verfügung. Trotz der hohen Auslastung bemühen wir uns um eine zügige Entscheidung.",
        skill: "writing",
      },
    ],
    homework: [
      "Nominalisieren Sie zehn Sätze und verbalisieren Sie zehn Nominalphrasen.",
      "Analysieren Sie einen Behördenbrief: markieren Sie Nominalstil und Passiv.",
      "Lernen Sie die Konjunktion-Präposition-Paare auswendig.",
    ],
    revision: ["weil→wegen, obwohl→trotz, nachdem→nach, wenn→bei, damit→zur", "-ung, -heit, -keit, -tion, -nis", "Genitiv-Präpositionen"],
  },
  {
    slug: "b2-l2-indirekte-rede",
    level: "B2",
    moduleSlug: "b2-m1-register-und-stil",
    order: 2,
    title: "Reporting what others say",
    titleDe: "Indirekte Rede und Distanzierung",
    summary:
      "Konjunktiv I, hearsay modals and hedging — how to report information without vouching for it.",
    minutes: 60,
    xp: 90,
    skills: ["grammar", "reading", "listening"],
    objectives: [
      "Form Konjunktiv I for the key verbs",
      "Report statements, questions and imperatives",
      "Use sollen and wollen for hearsay and claims",
      "Hedge with dürfte, wohl and angeblich",
    ],
    blocks: [
      { kind: "objectives", items: ["Konjunktiv I", "Indirekte Rede", "sollen / wollen subjektiv", "Vermutungen"] },
      { kind: "grammar", slug: "konjunktiv-1-indirekte-rede" },
      { kind: "grammar", slug: "subjektive-modalverben" },
      {
        kind: "examples",
        title: "Presse und Betrieb",
        items: [
          { de: "Die Firma teilte mit, sie werde 200 Stellen schaffen.", en: "The company announced it would create 200 jobs." },
          { de: "Der neue Kollege soll aus Marokko kommen.", en: "The new colleague is said to be from Morocco." },
          { de: "Er will nichts davon gewusst haben.", en: "He claims he knew nothing about it." },
          { de: "Die Lieferung dürfte morgen ankommen.", en: "The delivery should arrive tomorrow." },
        ],
      },
      {
        kind: "table",
        table: {
          title: "Sicherheitsskala",
          headers: ["Ausdruck", "Bedeutung"],
          rows: [
            ["muss … sein", "fast sicher"],
            ["dürfte … sein", "wahrscheinlich"],
            ["könnte … sein", "möglich"],
            ["kann nicht … sein", "ausgeschlossen"],
            ["soll … sein", "Hörensagen"],
            ["will … sein", "eigene Behauptung"],
          ],
        },
      },
    ],
    grammar: ["konjunktiv-1-indirekte-rede", "subjektive-modalverben"],
    vocabDecks: ["b2-society"],
    reading: "fachkraeftemangel",
    listening: "diskussion-arbeitszeit",
    exercises: [
      {
        id: "l-b2-2-e1", type: "transform",
        prompt: "Indirekte Rede.",
        input: '"Ich bin mit dem Ergebnis zufrieden."',
        answers: ["Er sagte, er sei mit dem Ergebnis zufrieden.", "Sie sagte, sie sei mit dem Ergebnis zufrieden."],
        explanation: "sein → sei.",
        skill: "grammar",
      },
      {
        id: "l-b2-2-e2", type: "transform",
        prompt: "Hörensagen ausdrücken.",
        input: "Man sagt, das Restaurant sei sehr gut.",
        answers: ["Das Restaurant soll sehr gut sein."],
        explanation: "sollen = Hörensagen.",
        skill: "grammar",
      },
      {
        id: "l-b2-2-e3", type: "fill-blank",
        prompt: "Konjunktiv I ergänzen.",
        sentence: "Der Sprecher betonte, die Lage ___ (sein) stabil und man ___ (haben) genug Zeit.",
        answers: [["sei"], ["habe"]],
        explanation: "sei, habe.",
        skill: "grammar",
      },
      {
        id: "l-b2-2-e4", type: "multiple-choice",
        prompt: "Er ist nicht da. Er ___ den Zug verpasst haben.",
        options: ["will", "soll", "muss", "darf"],
        answerIndex: 2,
        explanation: "Starke Vermutung → müssen.",
        skill: "grammar",
      },
    ],
    homework: [
      "Wandeln Sie zehn Zitate aus einem Zeitungsartikel in indirekte Rede um.",
      "Schreiben Sie eine kurze Meldung (80 Wörter) mit drei Konjunktiv-I-Formen.",
      "Sammeln Sie fünf Sätze mit soll/will in subjektiver Bedeutung.",
    ],
    revision: ["sei, habe, werde, könne, müsse", "habe/sei + Partizip II", "muss > dürfte > könnte; soll = man sagt"],
  },
  {
    slug: "b2-l3-komplexe-attribute",
    level: "B2",
    moduleSlug: "b2-m2-komplexe-strukturen",
    order: 1,
    title: "Reading dense texts: participial attributes",
    titleDe: "Dichte Texte lesen: Partizipialattribute",
    summary:
      "Unpack die von der Regierung im Mai beschlossenen Maßnahmen — and compress your own sentences.",
    minutes: 60,
    xp: 90,
    skills: ["grammar", "reading"],
    objectives: [
      "Distinguish Partizip I and Partizip II attributes",
      "Unpack extended attributes into relative clauses",
      "Use zu + Partizip I for necessity",
      "Read a dense administrative sentence quickly",
    ],
    blocks: [
      { kind: "objectives", items: ["Partizip I / II", "Erweiterte Attribute", "zu + Partizip I", "Lesestrategie"] },
      { kind: "grammar", slug: "partizipialattribute" },
      { kind: "grammar", slug: "passiversatzformen" },
      {
        kind: "text",
        title: "Lesestrategie in vier Schritten",
        body: [
          "1. Finden Sie den Artikel am Anfang und das Nomen am Ende des Blocks.",
          "2. Lesen Sie Artikel + Nomen zusammen — das ist der Kern.",
          "3. Prüfen Sie das Partizip: aktiv (Partizip I) oder passiv (Partizip II)?",
          "4. Bauen Sie im Kopf einen Relativsatz: „die Maßnahmen, die … beschlossen wurden“.",
        ],
      },
      {
        kind: "examples",
        title: "Beispiele aus Behörden und Presse",
        items: [
          { de: "die im Ausland erworbenen Qualifikationen", en: "the qualifications acquired abroad" },
          { de: "die stetig steigenden Energiekosten", en: "the continuously rising energy costs" },
          { de: "die bis Freitag einzureichenden Unterlagen", en: "the documents to be submitted by Friday" },
        ],
      },
    ],
    grammar: ["partizipialattribute", "passiversatzformen"],
    vocabDecks: ["b2-academic", "b2-workplace"],
    reading: "homeoffice-debatte",
    exercises: [
      {
        id: "l-b2-3-e1", type: "transform",
        prompt: "Lösen Sie das Attribut in einen Relativsatz auf.",
        input: "die von der Kammer anerkannten Abschlüsse",
        answers: ["die Abschlüsse, die von der Kammer anerkannt wurden", "die Abschlüsse, die von der Kammer anerkannt worden sind"],
        explanation: "Partizip II → Passiv-Relativsatz.",
        skill: "grammar",
      },
      {
        id: "l-b2-3-e2", type: "transform",
        prompt: "Komprimieren Sie zu einem Attribut.",
        input: "die Kosten, die immer weiter steigen",
        answers: ["die immer weiter steigenden Kosten"],
        explanation: "Partizip I + Endung.",
        skill: "grammar",
      },
      {
        id: "l-b2-3-e3", type: "multiple-choice",
        prompt: "die ___ Aufgaben (müssen erledigt werden)",
        options: ["erledigenden", "zu erledigenden", "erledigten", "erledigend"],
        answerIndex: 1,
        explanation: "zu + Partizip I + Endung.",
        skill: "grammar",
      },
      {
        id: "l-b2-3-e4", type: "transform",
        prompt: "Formulieren Sie mit sich lassen.",
        input: "Das Problem kann leicht gelöst werden.",
        answers: ["Das Problem lässt sich leicht lösen."],
        explanation: "Passiversatz.",
        skill: "grammar",
      },
    ],
    homework: [
      "Markieren Sie in einem Fachartikel fünf erweiterte Attribute und lösen Sie sie auf.",
      "Schreiben Sie fünf Sätze mit Partizipialattributen über Ihren Beruf.",
      "Üben Sie alle vier Passiversatzformen an je zwei Sätzen.",
    ],
    revision: ["Partizip I = aktiv, Partizip II = passiv", "zu + Partizip I = Notwendigkeit", "man / sich lassen / sein+zu / -bar"],
  },
  {
    slug: "b2-l4-diskutieren-verhandeln",
    level: "B2",
    moduleSlug: "b2-m2-komplexe-strukturen",
    order: 2,
    title: "Discussing, disagreeing, negotiating",
    titleDe: "Diskutieren, widersprechen, verhandeln",
    summary:
      "Interrupt politely, object without offending, propose compromises and summarise the outcome.",
    minutes: 60,
    xp: 90,
    skills: ["speaking", "listening", "writing"],
    objectives: [
      "Use discussion strategies (einhaken, präzisieren, zusammenfassen)",
      "Disagree politely at B2 register",
      "Propose and accept a compromise",
      "Summarise a discussion result precisely",
    ],
    blocks: [
      { kind: "objectives", items: ["Redemittel für Diskussionen", "Höflich widersprechen", "Kompromisse", "Ergebnis sichern"] },
      {
        kind: "table",
        table: {
          title: "Redemittel B2",
          headers: ["Funktion", "Formulierung"],
          rows: [
            ["Wort ergreifen", "Darf ich kurz einhaken?"],
            ["Zustimmen", "Da bin ich ganz Ihrer Meinung."],
            ["Teilweise zustimmen", "Im Grundsatz ja, allerdings …"],
            ["Widersprechen", "Das sehe ich anders, weil …"],
            ["Nachfragen", "Könnten Sie das präzisieren?"],
            ["Kompromiss", "Wie wäre es, wenn wir …?"],
            ["Zusammenfassen", "Wir sind uns also einig, dass …"],
          ],
        },
      },
      { kind: "grammar", slug: "futur-2" },
      {
        kind: "warning",
        title: "Register-Falle",
        body:
          "„Das ist falsch“ wirkt im Deutschen sachlich, aber im Gespräch mit Vorgesetzten besser: „Ich sehe das anders“ oder „Da würde ich widersprechen“.",
      },
    ],
    grammar: ["futur-2", "subjektive-modalverben"],
    vocabDecks: ["b2-workplace", "b2-idioms"],
    listening: "diskussion-arbeitszeit",
    speaking: "diskussion-fuehren",
    writing: "eroerterung-b2",
    exercises: [
      {
        id: "l-b2-4-e1", type: "multiple-choice",
        prompt: "Wie widersprechen Sie höflich einer Führungskraft?",
        options: [
          "Das ist völlig falsch.",
          "Da sehe ich das etwas anders, weil …",
          "Nein.",
          "Sie irren sich.",
        ],
        answerIndex: 1,
        explanation: "Abschwächung + Begründung.",
        skill: "speaking",
      },
      {
        id: "l-b2-4-e2", type: "transform",
        prompt: "Formulieren Sie mit Futur II.",
        input: "Bis Freitag schreibe ich den Bericht fertig.",
        answers: ["Bis Freitag werde ich den Bericht fertiggeschrieben haben."],
        explanation: "werden + Partizip II + haben.",
        skill: "grammar",
      },
      {
        id: "l-b2-4-e3", type: "speaking",
        prompt: "Diskussion: Ihr Betrieb will Überstunden nur in Freizeit ausgleichen. Nehmen Sie Stellung und schlagen Sie einen Kompromiss vor.",
        target:
          "Im Grundsatz kann ich das nachvollziehen, allerdings ist Freizeitausgleich in der Spätschicht schwer umsetzbar. Wie wäre es, wenn wir die Wahl zwischen Auszahlung und Ausgleich hätten?",
        tips: ["teilweise zustimmen", "Einwand begründen", "Kompromiss als Frage"],
        skill: "speaking",
      },
      {
        id: "l-b2-4-e4", type: "writing",
        prompt: "Fassen Sie das Ergebnis einer Diskussion in vier Sätzen zusammen (Protokollstil).",
        minWords: 50,
        checklist: ["Passiv oder Nominalstil", "Ergebnis konkret", "nächste Schritte", "Frist"],
        sampleAnswer:
          "In der Besprechung wurde vereinbart, dass Überstunden künftig wahlweise ausgezahlt oder in Freizeit ausgeglichen werden. Die Entscheidung ist jeweils bis zum Monatsende schriftlich mitzuteilen. Die Personalabteilung erstellt bis Freitag ein Formular. Eine Überprüfung der Regelung erfolgt nach sechs Monaten.",
        skill: "writing",
      },
    ],
    homework: [
      "Lernen Sie 15 Redemittel für Diskussionen auswendig.",
      "Führen Sie eine 10-minütige Diskussion mit einem Lernpartner und nehmen Sie sie auf.",
      "Schreiben Sie ein Kurzprotokoll (80 Wörter) im Passiv.",
    ],
    revision: ["Einhaken, präzisieren, zusammenfassen", "Höflich widersprechen", "Futur II für Fristen"],
  },
  {
    slug: "b2-l5-pruefungstraining-b2",
    level: "B2",
    moduleSlug: "b2-m3-pruefungstraining",
    order: 1,
    title: "B2 exam training and certification",
    titleDe: "Prüfungstraining B2 und Zertifizierung",
    summary:
      "The full B2 picture: Goethe modules, telc format, assessment criteria and a final self-check.",
    minutes: 80,
    xp: 120,
    skills: ["reading", "listening", "writing", "speaking", "grammar"],
    objectives: [
      "Know exactly how B2 writing and speaking are graded",
      "Produce a 150-word argumentative text in 50 minutes",
      "Deliver a structured 4-minute presentation",
      "Run a final self-assessment against the B2 descriptors",
    ],
    blocks: [
      { kind: "objectives", items: ["Bewertungskriterien", "Schreiben unter Zeitdruck", "Präsentation", "Selbsteinschätzung"] },
      {
        kind: "table",
        table: {
          title: "Bewertungskriterien Schreiben (B2)",
          headers: ["Kriterium", "Worauf geachtet wird", "Ihr Hebel"],
          rows: [
            ["Erfüllung", "alle Punkte, Textsorte, Länge", "Punkte nummerieren und abhaken"],
            ["Kohärenz", "Konnektoren, Absätze, Logik", "pro Absatz ein Gedanke"],
            ["Wortschatz", "Präzision, Register, Variation", "Synonyme statt Wiederholung"],
            ["Strukturen", "Nebensätze, Passiv, Nominalstil", "je zwei Belege einbauen"],
            ["Korrektheit", "Verbposition, Endungen, Zeichen", "3 Minuten Endkontrolle"],
          ],
        },
      },
      {
        kind: "checklist",
        title: "Grammatik-Check B2",
        items: [
          "Konjunktiv I in indirekter Rede",
          "Partizipialattribute lesen und bilden",
          "Passiversatzformen (man, sich lassen, sein+zu, -bar)",
          "subjektive Modalverben",
          "Nominal- und Verbalstil umwandeln",
          "Futur I und II für Vermutungen",
        ],
      },
      {
        kind: "tip",
        title: "Letzte zwei Wochen",
        body:
          "Nicht mehr Neues lernen. Täglich: 20 Minuten Karteikarten, ein Schreibtext im Wechsel formell/argumentativ, eine Aufnahme von 4 Minuten Sprechen. Fehlerliste führen und zweimal wiederholen.",
      },
    ],
    grammar: ["konjunktiv-1-indirekte-rede", "partizipialattribute", "passiversatzformen", "subjektive-modalverben", "nominalisierung", "futur-2"],
    vocabDecks: ["b2-workplace", "b2-society", "b2-academic", "b2-idioms"],
    reading: "homeoffice-debatte",
    listening: "vortrag-digitalisierung",
    writing: "eroerterung-b2",
    speaking: "praesentation-halten",
    exercises: [
      {
        id: "l-b2-5-e1", type: "writing",
        prompt: "Prüfungsaufgabe: Forumsbeitrag (150 Wörter) zu „Sollte Weiterbildung Pflicht sein?“",
        minWords: 150,
        checklist: [
          "Position in der Einleitung",
          "zwei Argumente mit Beispiel",
          "Gegenargument eingeräumt",
          "Nominalstil zweimal",
          "Passiv oder Passiversatz",
          "Fazit mit Empfehlung",
        ],
        sampleAnswer:
          "Aufgrund des rasanten technischen Wandels halte ich verpflichtende Weiterbildung für sinnvoll, sofern sie flexibel gestaltet wird. Zum einen veraltet Fachwissen heute innerhalb weniger Jahre; wer nicht regelmäßig lernt, verliert an Sicherheit im Beruf. In meinem Betrieb wurde nach der Einführung neuer Steuerungstechnik deutlich, dass ohne Schulung selbst erfahrene Kollegen Fehler machten. Zum anderen profitieren die Unternehmen unmittelbar, da Ausfälle und Nacharbeit reduziert werden können.\n\nEinzuwenden ist allerdings, dass Pflichtangebote ohne Mitbestimmung Widerstand erzeugen und als Kontrolle empfunden werden. Diesem Argument lässt sich begegnen, indem die Beschäftigten aus einem Katalog auswählen und die Termine mitplanen.\n\nInsgesamt plädiere ich für ein Modell mit zwei verbindlichen Weiterbildungstagen pro Jahr, freier Themenwahl und betrieblicher Finanzierung. Damit werden sowohl die Interessen der Betriebe als auch die Selbstbestimmung der Beschäftigten berücksichtigt.",
        skill: "writing",
      },
      {
        id: "l-b2-5-e2", type: "fill-blank",
        prompt: "Gemischte B2-Grammatik.",
        sentence: "Die Unterlagen sind bis Freitag ___ (einreichen). Der Sprecher erklärte, die Frist ___ (können) nicht verlängert werden.",
        answers: [["einzureichen"], ["könne"]],
        explanation: "sein + zu + Infinitiv; Konjunktiv I könne.",
        skill: "grammar",
      },
      {
        id: "l-b2-5-e3", type: "speaking",
        prompt: "Halten Sie eine vierminütige Präsentation zu einem gesellschaftlichen Thema Ihrer Wahl.",
        target:
          "Ich möchte heute darlegen, welche Folgen der Fachkräftemangel für kleine Betriebe hat. Zunächst skizziere ich die Ausgangslage, anschließend nenne ich zwei Ursachen und abschließend formuliere ich eine Empfehlung.",
        tips: ["Gliederung ankündigen", "Zahlen nennen", "mit Empfehlung schließen"],
        skill: "speaking",
      },
      {
        id: "l-b2-5-e4", type: "multiple-choice",
        prompt: "Welcher Satz ist im B2-Register am besten?",
        options: [
          "Ich finde das nicht gut.",
          "Diesem Argument lässt sich entgegenhalten, dass die Kosten unterschätzt werden.",
          "Das stimmt nicht.",
          "Das ist Quatsch.",
        ],
        answerIndex: 1,
        explanation: "Formelle Argumentation mit Passiversatz.",
        skill: "writing",
      },
    ],
    homework: [
      "Schreiben Sie den kompletten Mock-Test „Goethe B2 Mock 1“ unter Zeitdruck.",
      "Machen Sie zusätzlich telc B2 und vergleichen Sie die Kriterien.",
      "Nehmen Sie drei Präsentationen auf und werten Sie sie mit der Kriterientabelle aus.",
    ],
    revision: ["Bewertungskriterien kennen", "Alle sechs B2-Themen", "Register bewusst wählen"],
  },
];

export const b2Course: Course = {
  level: "B2",
  title: "German B2 — Upper intermediate",
  subtitle: "Argue, negotiate and read professional German",
  description:
    "B2 is the level required for nursing, many technical professions and university entry. You master reported speech, participial attributes, passive alternatives and nominal style, and you argue a position in writing and in discussion.",
  hours: 150,
  vocabularyTarget: 4000,
  color: "b2",
  canDo: [
    "Understand the main ideas of complex text on concrete and abstract topics",
    "Interact with a degree of fluency that makes conversation with native speakers natural",
    "Produce clear, detailed text and defend a point of view",
    "Read administrative and professional documents",
    "Take part in workplace discussions and negotiations",
  ],
  grammarFocus: [
    "Konjunktiv I and reported speech",
    "Participial and extended attributes",
    "Alternatives to the passive",
    "Subjective modal verbs",
    "Nominal vs. verbal style",
    "Futur I and II for assumptions",
  ],
  exams: ["goethe-b2-mock-1", "telc-b2-mock-1"],
  finalExam: "goethe-b2-mock-1",
  modules: [
    {
      slug: "b2-m1-register-und-stil",
      level: "B2",
      order: 1,
      title: "Register and style",
      titleDe: "Register und Stil",
      description: "Nominal style, the genitive and reported speech: the language of documents and news.",
      icon: "FileText",
      outcomes: ["Nominalisierung", "Genitiv", "Konjunktiv I", "Vermutungen"],
      lessons: ["b2-l1-nominalstil", "b2-l2-indirekte-rede"],
      miniTest: "b2-m1-test",
    },
    {
      slug: "b2-m2-komplexe-strukturen",
      level: "B2",
      order: 2,
      title: "Complex structures and discussion",
      titleDe: "Komplexe Strukturen und Diskussion",
      description: "Participial attributes, passive alternatives and negotiation strategies.",
      icon: "Layers",
      outcomes: ["Partizipialattribute", "Passiversatz", "Diskussionsstrategien", "Protokoll"],
      lessons: ["b2-l3-komplexe-attribute", "b2-l4-diskutieren-verhandeln"],
      miniTest: "b2-m2-test",
    },
    {
      slug: "b2-m3-pruefungstraining",
      level: "B2",
      order: 3,
      title: "Exam training B2",
      titleDe: "Prüfungstraining B2",
      description: "Assessment criteria, timed writing, presentation practice and certification.",
      icon: "Award",
      outcomes: ["Kriterien", "Schreiben 150 Wörter", "Präsentation", "Selbsteinschätzung"],
      lessons: ["b2-l5-pruefungstraining-b2"],
    },
  ],
};
