import type { GrammarTopic } from "@/lib/types";

export const a1Grammar: GrammarTopic[] = [
  {
    slug: "personalpronomen-sein-haben",
    level: "A1",
    category: "Verbs",
    title: "Personal pronouns + sein & haben",
    titleDe: "Personalpronomen + sein und haben",
    minutes: 25,
    simple:
      "German has six persons (ich, du, er/sie/es, wir, ihr, sie/Sie). The two most important verbs, sein (to be) and haben (to have), are irregular and must be memorised.",
    detailed: [
      "Every German sentence needs a subject and a conjugated verb. The subject decides the verb ending, so learning the six persons first makes all other verbs easier.",
      "sein and haben are the two verbs you will use most often: for identity and states (Ich bin Student, Der Kaffee ist heiß) and for possession and age (Ich habe Zeit, Sie hat zwei Kinder). Later they also form the Perfekt tense, so this table is an investment for the whole A1 level.",
      "German distinguishes informal du / ihr from formal Sie. Sie is always written with a capital S and uses the same form as the plural sie (they). Use Sie with strangers, officials, teachers and at work until you are invited to say du.",
    ],
    tables: [
      {
        title: "sein (to be) — Präsens",
        headers: ["Person", "Form", "Example"],
        rows: [
          ["ich", "bin", "Ich bin Ayoub."],
          ["du", "bist", "Du bist nett."],
          ["er / sie / es", "ist", "Sie ist Ärztin."],
          ["wir", "sind", "Wir sind aus Marokko."],
          ["ihr", "seid", "Ihr seid spät."],
          ["sie / Sie", "sind", "Sind Sie Herr Weber?"],
        ],
        highlightColumn: 1,
      },
      {
        title: "haben (to have) — Präsens",
        headers: ["Person", "Form", "Example"],
        rows: [
          ["ich", "habe", "Ich habe Hunger."],
          ["du", "hast", "Hast du Zeit?"],
          ["er / sie / es", "hat", "Er hat ein Auto."],
          ["wir", "haben", "Wir haben Deutschunterricht."],
          ["ihr", "habt", "Habt ihr Fragen?"],
          ["sie / Sie", "haben", "Haben Sie Kinder?"],
        ],
        highlightColumn: 1,
      },
    ],
    visuals: [
      {
        label: "Statement pattern",
        pattern: "Subjekt + Verb (Position 2) + Rest",
        parts: ["Ich", "bin", "seit zwei Jahren in Deutschland."],
      },
    ],
    examples: [
      { de: "Ich bin 24 Jahre alt.", en: "I am 24 years old.", note: "Age uses sein + Jahre alt." },
      { de: "Wir haben am Montag Unterricht.", en: "We have class on Monday." },
      { de: "Sind Sie Frau Schneider?", en: "Are you Mrs Schneider?", note: "Formal question." },
      { de: "Das Zimmer ist klein, aber es hat ein Fenster.", en: "The room is small, but it has a window." },
    ],
    mistakes: [
      {
        wrong: "Ich bin 24 Jahre.",
        right: "Ich bin 24 Jahre alt.",
        why: "German keeps the word alt when giving an age.",
      },
      {
        wrong: "Ich habe kalt.",
        right: "Mir ist kalt.",
        why: "Feeling cold/warm uses sein with a dative pronoun, not haben.",
      },
      {
        wrong: "Du bist recht.",
        right: "Du hast recht.",
        why: "recht haben is a fixed expression with haben.",
      },
    ],
    tips: [
      "Learn the pairs bin/bist/ist and habe/hast/hat as sound patterns, not as isolated words.",
      "Sie (formal) always takes the same form as sie (they): Sie sind, sie sind.",
      "In a statement the conjugated verb is always the second element — count elements, not words.",
    ],
    practice: [
      {
        id: "g-a1-1-p1",
        type: "fill-blank",
        prompt: "Complete with the correct form of sein.",
        sentence: "Ich ___ Student und meine Schwester ___ Krankenschwester.",
        answers: [["bin"], ["ist"]],
        explanation: "ich → bin, sie (meine Schwester) → ist.",
        grammar: "personalpronomen-sein-haben",
      },
      {
        id: "g-a1-1-p2",
        type: "fill-blank",
        prompt: "Complete with the correct form of haben.",
        sentence: "___ ihr heute Zeit? — Nein, wir ___ leider keine Zeit.",
        answers: [["habt"], ["haben"]],
        explanation: "ihr → habt, wir → haben.",
      },
      {
        id: "g-a1-1-p3",
        type: "multiple-choice",
        prompt: "Which sentence is formally correct when you address a stranger?",
        options: ["Wie heißt du?", "Wie heißen Sie?", "Wie heißt ihr?", "Wie heiße Sie?"],
        answerIndex: 1,
        explanation: "Formal address uses Sie + the plural verb form heißen.",
      },
      {
        id: "g-a1-1-p4",
        type: "order",
        prompt: "Put the sentence in the correct order.",
        tokens: ["aus", "Ich", "Marokko", "bin"],
        answer: "Ich bin aus Marokko",
        explanation: "Subject – verb – rest. The verb sein stays in position 2.",
      },
    ],
    quiz: [
      {
        id: "g-a1-1-q1",
        type: "multiple-choice",
        prompt: "Wir ___ zwei Kinder.",
        options: ["habt", "haben", "hat", "sind"],
        answerIndex: 1,
        explanation: "wir haben.",
      },
      {
        id: "g-a1-1-q2",
        type: "multiple-choice",
        prompt: "Du ___ sehr freundlich.",
        options: ["bin", "ist", "bist", "seid"],
        answerIndex: 2,
        explanation: "du bist.",
      },
      {
        id: "g-a1-1-q3",
        type: "true-false",
        prompt: "Formal Sie and plural sie use the same verb form.",
        answer: true,
        explanation: "Both take the -en form: Sie sind / sie sind.",
      },
    ],
    revision: [
      "sein: bin, bist, ist, sind, seid, sind.",
      "haben: habe, hast, hat, haben, habt, haben.",
      "Fixed expressions: Hunger haben, Zeit haben, recht haben, … Jahre alt sein.",
    ],
    cheatSheet: [
      { label: "ich", value: "bin / habe" },
      { label: "du", value: "bist / hast" },
      { label: "er, sie, es", value: "ist / hat" },
      { label: "wir", value: "sind / haben" },
      { label: "ihr", value: "seid / habt" },
      { label: "sie, Sie", value: "sind / haben" },
    ],
    related: ["praesens-regelmaessig", "wortstellung-fragen"],
  },
  {
    slug: "praesens-regelmaessig",
    level: "A1",
    category: "Verbs",
    title: "Present tense — regular verbs",
    titleDe: "Präsens: regelmäßige Verben",
    minutes: 25,
    simple:
      "Take the infinitive, remove -en, and add the ending for the person: -e, -st, -t, -en, -t, -en.",
    detailed: [
      "German verbs are built from a stem plus an ending. wohnen → stem wohn- → ich wohne, du wohnst, er wohnt. Once you know the six endings you can conjugate thousands of verbs.",
      "Small spelling rules keep the words pronounceable. Verbs whose stem ends in -t, -d or a consonant + m/n add an extra -e (arbeiten → du arbeitest, er arbeitet). Verbs whose stem ends in -s, -ß, -z or -x only add -t in the du form (reisen → du reist).",
      "The German present tense covers three English tenses: Ich lerne Deutsch = I learn / I am learning / I have been learning German. With a time expression it can even express the future: Morgen fahre ich nach Berlin.",
    ],
    tables: [
      {
        title: "Endings and spelling variants",
        headers: ["Person", "Ending", "wohnen", "arbeiten (-t stem)", "reisen (-s stem)"],
        rows: [
          ["ich", "-e", "wohne", "arbeite", "reise"],
          ["du", "-st", "wohnst", "arbeitest", "reist"],
          ["er/sie/es", "-t", "wohnt", "arbeitet", "reist"],
          ["wir", "-en", "wohnen", "arbeiten", "reisen"],
          ["ihr", "-t", "wohnt", "arbeitet", "reist"],
          ["sie/Sie", "-en", "wohnen", "arbeiten", "reisen"],
        ],
        highlightColumn: 1,
        note: "Stem-changing verbs (fahren → du fährst, sprechen → du sprichst) follow the same endings but change the vowel in du and er/sie/es.",
      },
    ],
    visuals: [
      {
        label: "Verb formula",
        pattern: "Stamm + Endung",
        parts: ["lern", "+", "-st", "→", "du lernst"],
      },
    ],
    examples: [
      { de: "Ich wohne in Casablanca und arbeite in einem Café.", en: "I live in Casablanca and work in a café." },
      { de: "Du sprichst schon sehr gut Deutsch.", en: "You already speak German very well.", note: "Stem change e → i." },
      { de: "Wann fährt der Zug nach Köln?", en: "When does the train to Cologne leave?" },
      { de: "Ihr lernt seit einem Jahr Deutsch.", en: "You have been learning German for a year." },
    ],
    mistakes: [
      {
        wrong: "Ich bin arbeiten in Berlin.",
        right: "Ich arbeite in Berlin.",
        why: "German has no continuous form with sein + verb.",
      },
      {
        wrong: "Du arbeitst viel.",
        right: "Du arbeitest viel.",
        why: "Stems ending in -t insert an -e before the ending.",
      },
      {
        wrong: "Er sprecht Deutsch.",
        right: "Er spricht Deutsch.",
        why: "sprechen is a stem-changing verb: e → i in du/er/sie/es.",
      },
    ],
    tips: [
      "Say the six forms out loud as a rhythm: -e, -st, -t, -en, -t, -en.",
      "wir and sie/Sie always look like the infinitive.",
      "Write new verbs in your notebook with the du and er forms, because that is where irregularities appear.",
    ],
    practice: [
      {
        id: "g-a1-2-p1",
        type: "fill-blank",
        prompt: "Conjugate the verbs in brackets.",
        sentence: "Er ___ (arbeiten) bei Siemens und ___ (wohnen) in München.",
        answers: [["arbeitet"], ["wohnt"]],
        explanation: "3rd person singular: -t, with an extra -e after the -t stem of arbeiten.",
      },
      {
        id: "g-a1-2-p2",
        type: "transform",
        prompt: "Change the sentence to du.",
        input: "Ich lerne jeden Tag zwanzig neue Wörter.",
        answers: ["Du lernst jeden Tag zwanzig neue Wörter."],
        explanation: "du + Stamm + -st.",
      },
      {
        id: "g-a1-2-p3",
        type: "multiple-choice",
        prompt: "Wohin ___ du in den Ferien?",
        options: ["fahre", "fahrst", "fährst", "fährt"],
        answerIndex: 2,
        explanation: "fahren changes a → ä in du and er/sie/es: du fährst.",
      },
    ],
    quiz: [
      {
        id: "g-a1-2-q1",
        type: "multiple-choice",
        prompt: "Ihr ___ sehr schnell.",
        options: ["lernen", "lernt", "lernst", "lerne"],
        answerIndex: 1,
        explanation: "ihr lernt.",
      },
      {
        id: "g-a1-2-q2",
        type: "fill-blank",
        prompt: "Complete: heißen",
        sentence: "Wie ___ du? — Ich ___ Lena.",
        answers: [["heißt", "heisst"], ["heiße", "heisse"]],
        explanation: "Stems in -ß only add -t in the du form.",
      },
      {
        id: "g-a1-2-q3",
        type: "true-false",
        prompt: "German uses a separate continuous tense for actions happening right now.",
        answer: false,
        explanation: "The simple present covers both: Ich esse = I eat / I am eating.",
      },
    ],
    revision: [
      "Endings: -e, -st, -t, -en, -t, -en.",
      "Stems in -t/-d add -e: du arbeitest, er findet.",
      "Stems in -s/-ß/-z: du reist, du heißt.",
    ],
    cheatSheet: [
      { label: "ich wohn-", value: "e" },
      { label: "du wohn-", value: "st" },
      { label: "er wohn-", value: "t" },
      { label: "wir wohn-", value: "en" },
      { label: "ihr wohn-", value: "t" },
      { label: "sie wohn-", value: "en" },
    ],
    related: ["trennbare-verben", "modalverben"],
  },
  {
    slug: "nomen-artikel-genus",
    level: "A1",
    category: "Nouns",
    title: "Nouns, gender and plural",
    titleDe: "Nomen, Genus und Plural",
    minutes: 30,
    simple:
      "Every German noun is written with a capital letter and has one of three genders: der (masculine), die (feminine) or das (neuter). In the plural all nouns take die.",
    detailed: [
      "Gender is grammatical, not logical: der Tisch, die Lampe, das Fenster. Always learn a noun together with its article and its plural form — der Stuhl, die Stühle — because the article changes in every case later on.",
      "Endings help you predict gender. Nouns ending in -ung, -heit, -keit, -schaft, -tion, -ei and -in are feminine; -er, -ling, -or, -ismus are usually masculine; -chen, -lein, -ment, -um and most nouns starting with Ge- are neuter.",
      "There are five plural patterns: -e (der Tisch → die Tische), -(e)n (die Lampe → die Lampen), -er (das Kind → die Kinder), -s (das Auto → die Autos) and no ending (der Lehrer → die Lehrer). Many plurals also add an Umlaut.",
    ],
    tables: [
      {
        title: "Definite and indefinite articles (Nominativ)",
        headers: ["Genus", "definite", "indefinite", "negative"],
        rows: [
          ["maskulin", "der Mann", "ein Mann", "kein Mann"],
          ["feminin", "die Frau", "eine Frau", "keine Frau"],
          ["neutrum", "das Kind", "ein Kind", "kein Kind"],
          ["Plural", "die Leute", "— Leute", "keine Leute"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Typical endings",
        headers: ["Ending", "Gender", "Example"],
        rows: [
          ["-ung, -heit, -keit, -schaft, -tion, -in", "die", "die Wohnung, die Freiheit, die Lehrerin"],
          ["-er, -ling, -or, -ismus", "der", "der Lehrer, der Lehrling, der Motor"],
          ["-chen, -lein, -ment, -um, Ge-", "das", "das Mädchen, das Dokument, das Gemüse"],
        ],
      },
      {
        title: "Plural patterns",
        headers: ["Pattern", "Singular", "Plural"],
        rows: [
          ["-e (+ Umlaut)", "der Stuhl", "die Stühle"],
          ["-(e)n", "die Schwester", "die Schwestern"],
          ["-er (+ Umlaut)", "das Kind / das Haus", "die Kinder / die Häuser"],
          ["-s", "das Handy", "die Handys"],
          ["no ending (+ Umlaut)", "der Lehrer / der Vater", "die Lehrer / die Väter"],
        ],
      },
    ],
    visuals: [
      {
        label: "Always learn three things",
        pattern: "Artikel + Nomen + Plural",
        parts: ["die", "Wohnung", "die Wohnungen"],
      },
    ],
    examples: [
      { de: "Das ist ein Zimmer. Das Zimmer ist hell.", en: "This is a room. The room is bright.", note: "ein → das when the noun is known." },
      { de: "Ich habe zwei Brüder und eine Schwester.", en: "I have two brothers and one sister." },
      { de: "Die Wohnungen in München sind teuer.", en: "Flats in Munich are expensive." },
      { de: "Das Mädchen heißt Anna.", en: "The girl is called Anna.", note: "-chen is always neuter." },
    ],
    mistakes: [
      { wrong: "die haus", right: "das Haus", why: "Nouns are capitalised and Haus is neuter." },
      {
        wrong: "Ich habe ein Zeit.",
        right: "Ich habe Zeit.",
        why: "Uncountable nouns usually take no article.",
      },
      {
        wrong: "Ich bin ein Student.",
        right: "Ich bin Student.",
        why: "Professions and nationalities take no article after sein/werden.",
      },
    ],
    tips: [
      "Colour-code your vocabulary: blue for der, red for die, green for das.",
      "Learn nouns inside a short phrase, not alone: die Rechnung, bitte!",
      "Compound nouns take the gender of the last part: das Haus + die Tür → die Haustür.",
    ],
    practice: [
      {
        id: "g-a1-3-p1",
        type: "match",
        prompt: "Match each noun with its article.",
        pairs: [
          { left: "Wohnung", right: "die" },
          { left: "Lehrer", right: "der" },
          { left: "Mädchen", right: "das" },
          { left: "Freiheit", right: "die" },
        ],
        explanation: "-ung and -heit are feminine, -er masculine, -chen neuter.",
      },
      {
        id: "g-a1-3-p2",
        type: "fill-blank",
        prompt: "Write the plural.",
        sentence: "der Stuhl → die ___ ; das Kind → die ___ ; das Auto → die ___",
        answers: [["Stühle"], ["Kinder"], ["Autos"]],
        explanation: "Umlaut + -e, -er, -s.",
      },
      {
        id: "g-a1-3-p3",
        type: "multiple-choice",
        prompt: "Which article does Wohnungstür take?",
        options: ["der", "die", "das", "no article"],
        answerIndex: 1,
        explanation: "The last element Tür is feminine, so the compound is feminine.",
      },
    ],
    quiz: [
      {
        id: "g-a1-3-q1",
        type: "multiple-choice",
        prompt: "___ Bahnhof ist neu.",
        options: ["Der", "Die", "Das", "Den"],
        answerIndex: 0,
        explanation: "der Bahnhof.",
      },
      {
        id: "g-a1-3-q2",
        type: "true-false",
        prompt: "All plural nouns take die in the nominative.",
        answer: true,
        explanation: "Gender differences disappear in the plural: die Männer, die Frauen, die Kinder.",
      },
      {
        id: "g-a1-3-q3",
        type: "fill-blank",
        prompt: "Complete with the indefinite article.",
        sentence: "Ich suche ___ Wohnung und ___ Zimmer für meinen Bruder.",
        answers: [["eine"], ["ein"]],
        explanation: "die Wohnung → eine; das Zimmer → ein (accusative neuter is identical).",
      },
    ],
    revision: [
      "Three genders in the singular, one shared article die in the plural.",
      "Endings are your best predictor of gender.",
      "Five plural patterns; always memorise the plural with the noun.",
    ],
    cheatSheet: [
      { label: "maskulin", value: "der / ein / kein" },
      { label: "feminin", value: "die / eine / keine" },
      { label: "neutrum", value: "das / ein / kein" },
      { label: "Plural", value: "die / – / keine" },
      { label: "-ung, -heit, -keit", value: "die" },
      { label: "-chen, -lein", value: "das" },
    ],
    related: ["akkusativ", "negation-nicht-kein"],
  },
  {
    slug: "akkusativ",
    level: "A1",
    category: "Cases",
    title: "The accusative case",
    titleDe: "Der Akkusativ",
    minutes: 30,
    simple:
      "The accusative marks the direct object — the thing the verb acts on. Only masculine articles change: der → den, ein → einen.",
    detailed: [
      "Ask wen? or was? after the verb to find the accusative object: Ich kaufe einen Tisch. — Was kaufe ich? Einen Tisch. Feminine, neuter and plural articles look exactly like the nominative, which makes the accusative the easiest case to master.",
      "Some prepositions always trigger the accusative: durch, für, gegen, ohne, um, bis, entlang. Memorise them as a chant — durch, für, gegen, ohne, um.",
      "Personal pronouns also change: ich → mich, du → dich, er → ihn, sie → sie, es → es, wir → uns, ihr → euch, sie/Sie → sie/Sie. Note the useful pattern Ich liebe dich, Ich verstehe ihn nicht.",
    ],
    tables: [
      {
        title: "Articles: Nominativ vs. Akkusativ",
        headers: ["Genus", "Nominativ", "Akkusativ"],
        rows: [
          ["maskulin", "der / ein / kein Mann", "den / einen / keinen Mann"],
          ["feminin", "die / eine / keine Frau", "die / eine / keine Frau"],
          ["neutrum", "das / ein / kein Kind", "das / ein / kein Kind"],
          ["Plural", "die / – / keine Kinder", "die / – / keine Kinder"],
        ],
        highlightColumn: 2,
        note: "Only the masculine row changes. Learn the -en signal: den, einen, keinen, meinen, ihn.",
      },
      {
        title: "Accusative pronouns",
        headers: ["Nominativ", "Akkusativ", "Example"],
        rows: [
          ["ich", "mich", "Kannst du mich hören?"],
          ["du", "dich", "Ich rufe dich später an."],
          ["er", "ihn", "Ich kenne ihn gut."],
          ["sie", "sie", "Ich besuche sie am Wochenende."],
          ["es", "es", "Ich finde es interessant."],
          ["wir", "uns", "Sie holt uns ab."],
          ["ihr", "euch", "Ich sehe euch morgen."],
          ["sie / Sie", "sie / Sie", "Ich verstehe Sie nicht."],
        ],
      },
    ],
    visuals: [
      {
        label: "Finding the object",
        pattern: "Subjekt (Nom.) + Verb + Objekt (Akk.)",
        parts: ["Der Kellner", "bringt", "den Kaffee."],
      },
      {
        label: "Accusative prepositions",
        pattern: "durch · für · gegen · ohne · um · bis · entlang",
        parts: ["für meinen Bruder", "ohne dich", "um den Tisch"],
      },
    ],
    examples: [
      { de: "Ich nehme den Salat und einen Apfelsaft.", en: "I'll take the salad and an apple juice." },
      { de: "Wir suchen eine Wohnung für unsere Familie.", en: "We are looking for a flat for our family." },
      { de: "Ohne meinen Ausweis kann ich nicht reisen.", en: "Without my ID I cannot travel." },
      { de: "Verstehst du mich?", en: "Do you understand me?" },
    ],
    mistakes: [
      { wrong: "Ich habe ein Bruder.", right: "Ich habe einen Bruder.", why: "haben takes an accusative object; masculine ein → einen." },
      { wrong: "Das Geschenk ist für er.", right: "Das Geschenk ist für ihn.", why: "für is an accusative preposition, so er → ihn." },
      { wrong: "Ich sehe der Film.", right: "Ich sehe den Film.", why: "Direct object of sehen must be accusative." },
    ],
    tips: [
      "If the sentence has a normal action verb plus a masculine object, you almost always need den/einen.",
      "Chant the five core accusative prepositions until they are automatic: durch, für, gegen, ohne, um.",
      "es gibt is always followed by the accusative: Es gibt einen Supermarkt.",
    ],
    practice: [
      {
        id: "g-a1-4-p1",
        type: "fill-blank",
        prompt: "Complete with the accusative article.",
        sentence: "Ich kaufe ___ Tisch, ___ Lampe und ___ Regal.",
        answers: [["einen", "den"], ["eine", "die"], ["ein", "das"]],
        explanation: "Masculine changes to einen/den, feminine and neuter stay the same.",
      },
      {
        id: "g-a1-4-p2",
        type: "transform",
        prompt: "Replace the object with a pronoun.",
        input: "Ich kenne den Lehrer.",
        answers: ["Ich kenne ihn."],
        explanation: "den Lehrer → ihn.",
      },
      {
        id: "g-a1-4-p3",
        type: "multiple-choice",
        prompt: "Der Bus fährt ___ die Stadt.",
        options: ["durch", "für", "ohne", "mit"],
        answerIndex: 0,
        explanation: "durch + Akkusativ expresses movement through a place. mit takes the dative.",
      },
      {
        id: "g-a1-4-p4",
        type: "order",
        prompt: "Build the sentence.",
        tokens: ["einen", "Ich", "Kaffee", "bestelle"],
        answer: "Ich bestelle einen Kaffee",
        explanation: "Subject – verb – accusative object.",
      },
    ],
    quiz: [
      {
        id: "g-a1-4-q1",
        type: "multiple-choice",
        prompt: "Ich brauche ___ neuen Kugelschreiber.",
        options: ["ein", "einen", "eine", "einem"],
        answerIndex: 1,
        explanation: "der Kugelschreiber → Akkusativ einen.",
      },
      {
        id: "g-a1-4-q2",
        type: "fill-blank",
        prompt: "Pronoun practice.",
        sentence: "Ich liebe ___ (du). Rufst du ___ (ich) heute Abend an?",
        answers: [["dich"], ["mich"]],
        explanation: "du → dich, ich → mich.",
      },
      {
        id: "g-a1-4-q3",
        type: "true-false",
        prompt: "Feminine articles change in the accusative.",
        answer: false,
        explanation: "die/eine/keine stay identical; only masculine changes.",
      },
    ],
    revision: [
      "Only masculine articles change: den, einen, keinen, meinen.",
      "Accusative prepositions: durch, für, gegen, ohne, um, bis, entlang.",
      "Pronouns: mich, dich, ihn, sie, es, uns, euch, sie/Sie.",
    ],
    cheatSheet: [
      { label: "der Mann", value: "→ den Mann" },
      { label: "ein Mann", value: "→ einen Mann" },
      { label: "die Frau", value: "→ die Frau" },
      { label: "das Kind", value: "→ das Kind" },
      { label: "Prepositions", value: "durch, für, gegen, ohne, um" },
      { label: "Pronouns", value: "mich, dich, ihn, uns, euch" },
    ],
    related: ["nomen-artikel-genus", "dativ"],
  },
  {
    slug: "negation-nicht-kein",
    level: "A1",
    category: "Sentence structure",
    title: "Negation with nicht and kein",
    titleDe: "Negation: nicht und kein",
    minutes: 20,
    simple:
      "Use kein to negate a noun that has ein or no article. Use nicht for everything else — verbs, adjectives, adverbs and nouns with der/die/das or a possessive.",
    detailed: [
      "kein behaves exactly like ein and takes the same endings: kein Auto, keine Zeit, keinen Bruder, keine Kinder. Because ein has no plural, kein is the only way to negate plural nouns: Ich habe keine Geschwister.",
      "nicht normally stands at the end of the sentence, but it moves in front of the element it negates: before adjectives (Das ist nicht teuer), before prepositional phrases (Ich fahre nicht nach Berlin) and before the second verb (Ich kann heute nicht kommen).",
      "To contradict a negative question or statement, answer with doch: Hast du kein Auto? — Doch, ich habe ein Auto.",
    ],
    tables: [
      {
        title: "kein — all forms",
        headers: ["Kasus", "maskulin", "feminin", "neutrum", "Plural"],
        rows: [
          ["Nominativ", "kein", "keine", "kein", "keine"],
          ["Akkusativ", "keinen", "keine", "kein", "keine"],
          ["Dativ", "keinem", "keiner", "keinem", "keinen"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Position of nicht",
        headers: ["What is negated", "Position", "Example"],
        rows: [
          ["the whole sentence / verb", "at the end", "Ich verstehe das nicht."],
          ["adjective", "before the adjective", "Der Kurs ist nicht schwer."],
          ["place / direction", "before the phrase", "Wir fahren nicht nach Hamburg."],
          ["second verb", "before the infinitive", "Ich möchte heute nicht arbeiten."],
        ],
      },
    ],
    visuals: [
      {
        label: "Decision rule",
        pattern: "Noun with ein / no article → kein · everything else → nicht",
        parts: ["Ich habe keine Zeit.", "Ich komme nicht."],
      },
    ],
    examples: [
      { de: "Ich habe keinen Hunger, aber ich habe Durst.", en: "I'm not hungry, but I'm thirsty." },
      { de: "Das ist nicht mein Koffer.", en: "That's not my suitcase.", note: "Possessive → nicht." },
      { de: "Wir wohnen nicht in Berlin.", en: "We don't live in Berlin." },
      { de: "Sprichst du kein Englisch? — Doch, ein bisschen.", en: "Don't you speak English? — Yes, a little." },
    ],
    mistakes: [
      { wrong: "Ich habe nicht Zeit.", right: "Ich habe keine Zeit.", why: "Zeit has no article, so it needs kein-." },
      { wrong: "Ich nicht verstehe.", right: "Ich verstehe nicht.", why: "nicht never stands between subject and conjugated verb." },
      { wrong: "Das ist kein mein Buch.", right: "Das ist nicht mein Buch.", why: "Nouns with a possessive take nicht." },
    ],
    tips: [
      "kein = ein + negation, so the endings are identical to ein.",
      "Answer negative questions with doch when you disagree.",
      "nicht immediately before an element negates only that element — this changes the meaning.",
    ],
    practice: [
      {
        id: "g-a1-5-p1",
        type: "fill-blank",
        prompt: "nicht or kein-?",
        sentence: "Ich habe ___ Auto und ich fahre ___ gern Fahrrad.",
        answers: [["kein"], ["nicht"]],
        explanation: "Auto with no article → kein; the verb phrase → nicht.",
      },
      {
        id: "g-a1-5-p2",
        type: "transform",
        prompt: "Negate the sentence.",
        input: "Ich kenne deinen Bruder.",
        answers: ["Ich kenne deinen Bruder nicht."],
        explanation: "A noun with a possessive article is negated with nicht at the end.",
      },
      {
        id: "g-a1-5-p3",
        type: "multiple-choice",
        prompt: "Hast du keine Geschwister? — ___, ich habe zwei Schwestern.",
        options: ["Ja", "Nein", "Doch", "Nicht"],
        answerIndex: 2,
        explanation: "doch contradicts a negative question.",
      },
    ],
    quiz: [
      {
        id: "g-a1-5-q1",
        type: "multiple-choice",
        prompt: "Er trinkt ___ Alkohol.",
        options: ["nicht", "keinen", "kein", "keine"],
        answerIndex: 1,
        explanation: "der Alkohol → Akkusativ keinen.",
      },
      {
        id: "g-a1-5-q2",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Der Film war ___ interessant.",
        answers: [["nicht"]],
        explanation: "Adjectives are negated with nicht.",
      },
      {
        id: "g-a1-5-q3",
        type: "true-false",
        prompt: "kein is the only way to negate a plural noun.",
        answer: true,
        explanation: "ein has no plural, so use keine + Plural.",
      },
    ],
    revision: [
      "kein + noun (with ein or zero article).",
      "nicht + verb, adjective, adverb, prepositional phrase, definite/possessive noun.",
      "doch = yes, contradicting a negative.",
    ],
    cheatSheet: [
      { label: "ein Auto", value: "kein Auto" },
      { label: "Zeit", value: "keine Zeit" },
      { label: "mein Buch", value: "nicht mein Buch" },
      { label: "teuer", value: "nicht teuer" },
      { label: "Negative question", value: "answer with doch" },
    ],
    related: ["akkusativ", "wortstellung-fragen"],
  },
  {
    slug: "possessivartikel",
    level: "A1",
    category: "Determiners",
    title: "Possessive articles",
    titleDe: "Possessivartikel",
    minutes: 20,
    simple:
      "mein, dein, sein, ihr, unser, euer, ihr, Ihr take the same endings as ein/kein. The stem shows the owner, the ending shows the following noun.",
    detailed: [
      "Choose the stem according to the owner: ich → mein, du → dein, er/es → sein, sie → ihr, wir → unser, ihr → euer, sie (plural) → ihr, Sie → Ihr.",
      "Then add the ein-ending for the gender and case of the noun that follows: mein Vater (m, Nom.), meinen Vater (m, Akk.), meine Mutter (f), mein Kind (n), meine Eltern (Pl.).",
      "Careful with sein vs. ihr: the choice depends on the owner, not on the object. Anna und ihr Mann — Peter und seine Frau.",
    ],
    tables: [
      {
        title: "Stems",
        headers: ["Person", "Stem", "Example"],
        rows: [
          ["ich", "mein-", "mein Zimmer"],
          ["du", "dein-", "deine Adresse"],
          ["er / es", "sein-", "seine Schwester"],
          ["sie", "ihr-", "ihr Bruder"],
          ["wir", "unser-", "unsere Wohnung"],
          ["ihr", "euer- (eur-)", "euer Auto / eure Kinder"],
          ["sie (Pl.)", "ihr-", "ihre Eltern"],
          ["Sie (formal)", "Ihr-", "Ihre Telefonnummer"],
        ],
      },
      {
        title: "Endings (like ein/kein)",
        headers: ["Kasus", "maskulin", "feminin", "neutrum", "Plural"],
        rows: [
          ["Nominativ", "mein", "meine", "mein", "meine"],
          ["Akkusativ", "meinen", "meine", "mein", "meine"],
          ["Dativ", "meinem", "meiner", "meinem", "meinen"],
        ],
        highlightColumn: 1,
      },
    ],
    visuals: [
      {
        label: "Two decisions",
        pattern: "Owner → Stamm · Noun → Endung",
        parts: ["du", "+", "die Schwester", "→", "deine Schwester"],
      },
    ],
    examples: [
      { de: "Wie ist deine Telefonnummer?", en: "What's your phone number?" },
      { de: "Ich besuche meinen Onkel in Frankfurt.", en: "I'm visiting my uncle in Frankfurt.", note: "Akkusativ maskulin." },
      { de: "Unsere Wohnung hat drei Zimmer.", en: "Our flat has three rooms." },
      { de: "Herr Weber, ist das Ihr Mantel?", en: "Mr Weber, is this your coat?" },
    ],
    mistakes: [
      { wrong: "Ich liebe mein Familie.", right: "Ich liebe meine Familie.", why: "die Familie is feminine → meine." },
      { wrong: "Peter und ihre Frau", right: "Peter und seine Frau", why: "The owner is masculine → sein-." },
      { wrong: "euere Kinder", right: "eure Kinder", why: "euer loses the second e before an ending." },
    ],
    tips: [
      "Endings are identical to kein — learn one table, use it three times.",
      "Formal Ihr always has a capital I.",
      "For family members practise whole phrases: meine Mutter, mein Vater, meine Eltern.",
    ],
    practice: [
      {
        id: "g-a1-6-p1",
        type: "fill-blank",
        prompt: "Complete with the possessive article.",
        sentence: "Das ist Anna und das ist ___ Bruder. Er wohnt bei ___ Eltern.",
        answers: [["ihr"], ["ihren", "seinen"]],
        explanation: "Anna → ihr-; bei + Dativ Plural → ihren Eltern.",
      },
      {
        id: "g-a1-6-p2",
        type: "multiple-choice",
        prompt: "Ich suche ___ Schlüssel. (der Schlüssel)",
        options: ["mein", "meine", "meinen", "meinem"],
        answerIndex: 2,
        explanation: "Accusative masculine → meinen.",
      },
      {
        id: "g-a1-6-p3",
        type: "transform",
        prompt: "Rewrite politely with Sie.",
        input: "Wie ist deine Adresse?",
        answers: ["Wie ist Ihre Adresse?"],
        explanation: "dein- → Ihr- with a capital letter.",
      },
    ],
    quiz: [
      {
        id: "g-a1-6-q1",
        type: "multiple-choice",
        prompt: "Wo sind ___ Bücher? (ihr, Plural)",
        options: ["euer", "eure", "euren", "euerem"],
        answerIndex: 1,
        explanation: "Plural nominative → eure.",
      },
      {
        id: "g-a1-6-q2",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Wir fahren mit ___ Auto. (wir)",
        answers: [["unserem"]],
        explanation: "mit + Dativ neutrum → unserem.",
      },
    ],
    revision: [
      "Stems: mein, dein, sein, ihr, unser, euer, ihr, Ihr.",
      "Endings identical to ein/kein.",
      "sein = his/its, ihr = her/their.",
    ],
    cheatSheet: [
      { label: "ich", value: "mein-" },
      { label: "du", value: "dein-" },
      { label: "er/es", value: "sein-" },
      { label: "sie", value: "ihr-" },
      { label: "wir", value: "unser-" },
      { label: "ihr", value: "eur-" },
      { label: "Sie", value: "Ihr-" },
    ],
    related: ["nomen-artikel-genus", "akkusativ"],
  },
  {
    slug: "modalverben",
    level: "A1",
    category: "Verbs",
    title: "Modal verbs",
    titleDe: "Modalverben",
    minutes: 30,
    simple:
      "können, müssen, wollen, dürfen, sollen, möchten change the vowel in the singular, have no ending in ich and er/sie/es, and send the second verb to the end as an infinitive.",
    detailed: [
      "Modal verbs express ability, obligation, wish and permission. They form a sentence frame (Satzklammer): the modal verb is conjugated in position 2, the main verb stays in the infinitive at the very end. Ich muss heute früh aufstehen.",
      "In the singular the stem vowel changes (können → ich kann) and ich and er/sie/es have exactly the same form with no ending. The plural forms are regular.",
      "Meaning matters: müssen = necessity, nicht müssen = it isn't necessary, nicht dürfen = it is forbidden. möchten is the polite wish form of mögen and is what you use when ordering food.",
    ],
    tables: [
      {
        title: "All six modal verbs — Präsens",
        headers: ["Person", "können", "müssen", "wollen", "dürfen", "sollen", "möchten"],
        rows: [
          ["ich", "kann", "muss", "will", "darf", "soll", "möchte"],
          ["du", "kannst", "musst", "willst", "darfst", "sollst", "möchtest"],
          ["er/sie/es", "kann", "muss", "will", "darf", "soll", "möchte"],
          ["wir", "können", "müssen", "wollen", "dürfen", "sollen", "möchten"],
          ["ihr", "könnt", "müsst", "wollt", "dürft", "sollt", "möchtet"],
          ["sie/Sie", "können", "müssen", "wollen", "dürfen", "sollen", "möchten"],
        ],
        note: "ich and er/sie/es are always identical — no -e and no -t.",
      },
      {
        title: "Meaning",
        headers: ["Modal", "Meaning", "Example"],
        rows: [
          ["können", "ability / possibility", "Ich kann schwimmen."],
          ["müssen", "necessity", "Ich muss arbeiten."],
          ["wollen", "strong wish / intention", "Er will Arzt werden."],
          ["dürfen", "permission", "Darf ich hier rauchen?"],
          ["sollen", "recommendation / instruction", "Du sollst mehr schlafen."],
          ["möchten", "polite wish", "Ich möchte einen Kaffee, bitte."],
        ],
      },
    ],
    visuals: [
      {
        label: "Satzklammer (sentence bracket)",
        pattern: "Modalverb (Pos. 2) … Infinitiv (Ende)",
        parts: ["Ich", "kann", "am Wochenende", "kommen."],
      },
    ],
    examples: [
      { de: "Ich muss um sechs Uhr aufstehen.", en: "I have to get up at six." },
      { de: "Kannst du mir bitte helfen?", en: "Can you help me, please?" },
      { de: "Hier darf man nicht parken.", en: "You mustn't park here.", note: "nicht dürfen = prohibition." },
      { de: "Möchten Sie noch etwas trinken?", en: "Would you like something else to drink?" },
    ],
    mistakes: [
      { wrong: "Ich kann sprechen Deutsch.", right: "Ich kann Deutsch sprechen.", why: "The infinitive goes to the very end." },
      { wrong: "Er kannst gut kochen.", right: "Er kann gut kochen.", why: "er/sie/es takes no ending with modal verbs." },
      { wrong: "Du musst nicht rauchen. (= forbidden)", right: "Du darfst nicht rauchen.", why: "nicht müssen means it isn't necessary; prohibition needs nicht dürfen." },
    ],
    tips: [
      "Learn ich kann / ich muss / ich will / ich darf as a block — the vowel change is the hard part.",
      "In questions the modal comes first: Können Sie mir helfen?",
      "Use möchten, not wollen, in shops and restaurants — wollen can sound blunt.",
    ],
    practice: [
      {
        id: "g-a1-7-p1",
        type: "order",
        prompt: "Build the sentence.",
        tokens: ["heute", "Ich", "arbeiten", "muss", "länger"],
        answer: "Ich muss heute länger arbeiten",
        explanation: "Modal in position 2, infinitive at the end.",
      },
      {
        id: "g-a1-7-p2",
        type: "fill-blank",
        prompt: "Choose the right modal verb.",
        sentence: "Ich habe morgen eine Prüfung. Ich ___ heute Abend lernen. — ___ ich dir helfen?",
        answers: [["muss"], ["Soll", "Kann"]],
        explanation: "Obligation → müssen; offering help → Soll/Kann ich …?",
      },
      {
        id: "g-a1-7-p3",
        type: "multiple-choice",
        prompt: "Im Krankenhaus ___ man nicht telefonieren.",
        options: ["muss", "darf", "will", "möchte"],
        answerIndex: 1,
        explanation: "Prohibition → nicht dürfen.",
      },
    ],
    quiz: [
      {
        id: "g-a1-7-q1",
        type: "multiple-choice",
        prompt: "___ du am Samstag mitkommen?",
        options: ["Willst", "Will", "Wollt", "Wollen"],
        answerIndex: 0,
        explanation: "du willst.",
      },
      {
        id: "g-a1-7-q2",
        type: "fill-blank",
        prompt: "Complete with können.",
        sentence: "Wir ___ leider nicht kommen, aber sie ___ kommen.",
        answers: [["können"], ["kann"]],
        explanation: "wir können, sie (Singular) kann.",
      },
      {
        id: "g-a1-7-q3",
        type: "true-false",
        prompt: "In a modal sentence the main verb stays in the infinitive at the end.",
        answer: true,
        explanation: "That is the Satzklammer.",
      },
    ],
    revision: [
      "No ending in ich and er/sie/es.",
      "Vowel change in the singular (können → kann).",
      "Infinitive at the end of the clause.",
    ],
    cheatSheet: [
      { label: "können", value: "kann, kannst, kann, können" },
      { label: "müssen", value: "muss, musst, muss, müssen" },
      { label: "wollen", value: "will, willst, will, wollen" },
      { label: "dürfen", value: "darf, darfst, darf, dürfen" },
      { label: "sollen", value: "soll, sollst, soll, sollen" },
      { label: "möchten", value: "möchte, möchtest, möchte, möchten" },
    ],
    related: ["trennbare-verben", "wortstellung-fragen"],
  },
  {
    slug: "trennbare-verben",
    level: "A1",
    category: "Verbs",
    title: "Separable and inseparable verbs",
    titleDe: "Trennbare und nicht trennbare Verben",
    minutes: 25,
    simple:
      "Separable verbs split in a main clause: the prefix jumps to the end. aufstehen → Ich stehe um 7 Uhr auf.",
    detailed: [
      "Prefixes that carry the word stress are separable: an-, auf-, aus-, ab-, ein-, mit-, vor-, zu-, zurück-, weg-, fern-, statt-. In a main clause the conjugated verb goes to position 2 and the prefix to the end, creating the sentence bracket.",
      "Prefixes that are unstressed are inseparable and never move: be-, ge-, er-, ver-, zer-, ent-, emp-, miss-. Ich verstehe die Frage. Er bekommt einen Brief.",
      "The prefix stays attached when the verb is an infinitive after a modal (Ich muss früh aufstehen), in a subordinate clause (…, weil ich früh aufstehe) and in the Partizip II, where ge- is inserted in the middle: aufgestanden, eingekauft.",
    ],
    tables: [
      {
        title: "Separable vs. inseparable",
        headers: ["Type", "Prefixes", "Präsens", "Partizip II"],
        rows: [
          ["separable (stressed)", "an-, auf-, aus-, ein-, mit-, vor-, zu-, zurück-", "Ich rufe dich an.", "angerufen"],
          ["inseparable (unstressed)", "be-, ent-, er-, ge-, ver-, zer-, miss-", "Ich verstehe dich.", "verstanden"],
        ],
      },
      {
        title: "Common separable verbs",
        headers: ["Verb", "Meaning", "Example"],
        rows: [
          ["aufstehen", "to get up", "Ich stehe um 6 Uhr auf."],
          ["einkaufen", "to shop", "Wir kaufen am Samstag ein."],
          ["anrufen", "to call", "Ruf mich bitte an!"],
          ["fernsehen", "to watch TV", "Er sieht abends fern."],
          ["mitkommen", "to come along", "Kommst du mit?"],
          ["ausfüllen", "to fill in", "Füllen Sie das Formular aus."],
        ],
      },
    ],
    visuals: [
      {
        label: "The bracket",
        pattern: "Verb (Pos. 2) … Präfix (Ende)",
        parts: ["Ich", "stehe", "jeden Tag um 6 Uhr", "auf."],
      },
    ],
    examples: [
      { de: "Der Zug kommt um 14:20 Uhr an.", en: "The train arrives at 2:20 pm." },
      { de: "Bitte füllen Sie das Formular aus.", en: "Please fill in the form." },
      { de: "Ich muss noch einkaufen.", en: "I still have to go shopping.", note: "After a modal the verb stays whole." },
      { de: "Wann fängt der Kurs an?", en: "When does the course start?" },
    ],
    mistakes: [
      { wrong: "Ich aufstehe um 7 Uhr.", right: "Ich stehe um 7 Uhr auf.", why: "In a main clause the prefix must go to the end." },
      { wrong: "Ich habe eingekauft am Samstag.", right: "Ich habe am Samstag eingekauft.", why: "The Partizip II stays at the end of the sentence." },
      { wrong: "Ich verstehe auf.", right: "Ich verstehe.", why: "ver- is inseparable, there is no prefix to move." },
    ],
    tips: [
      "Listen for the stress: AUFstehen is separable, verSTEHen is not.",
      "In dictionaries separable verbs are often written auf|stehen.",
      "In yes/no questions the prefix still goes last: Kommst du mit?",
    ],
    practice: [
      {
        id: "g-a1-8-p1",
        type: "transform",
        prompt: "Make a main clause with ich.",
        input: "aufstehen — um halb sieben",
        answers: ["Ich stehe um halb sieben auf."],
        explanation: "Verb position 2, prefix at the end.",
      },
      {
        id: "g-a1-8-p2",
        type: "order",
        prompt: "Build the question.",
        tokens: ["an", "Wann", "der Film", "fängt"],
        answer: "Wann fängt der Film an",
        explanation: "W-question: question word, verb, subject, … prefix.",
      },
      {
        id: "g-a1-8-p3",
        type: "multiple-choice",
        prompt: "Which verb is inseparable?",
        options: ["mitbringen", "bekommen", "ausgehen", "zurückrufen"],
        answerIndex: 1,
        explanation: "be- is always inseparable.",
      },
    ],
    quiz: [
      {
        id: "g-a1-8-q1",
        type: "fill-blank",
        prompt: "Complete with anrufen.",
        sentence: "Ich ___ dich morgen ___.",
        answers: [["rufe"], ["an"]],
        explanation: "rufe … an.",
      },
      {
        id: "g-a1-8-q2",
        type: "true-false",
        prompt: "After a modal verb, separable verbs stay in one piece.",
        answer: true,
        explanation: "Ich möchte früh aufstehen.",
      },
    ],
    revision: [
      "Stressed prefix → separable; unstressed → inseparable.",
      "Main clause: prefix at the end. Modal/subordinate clause: verb stays whole.",
      "Partizip II: ge- in the middle (angerufen), inseparable verbs have no ge- (verstanden).",
    ],
    cheatSheet: [
      { label: "Separable", value: "an-, auf-, aus-, ein-, mit-, vor-, zu-, zurück-" },
      { label: "Inseparable", value: "be-, ent-, er-, ge-, ver-, zer-, miss-" },
      { label: "Main clause", value: "Ich rufe an." },
      { label: "With modal", value: "Ich will anrufen." },
      { label: "Perfekt", value: "Ich habe angerufen." },
    ],
    related: ["perfekt", "modalverben"],
  },
  {
    slug: "wortstellung-fragen",
    level: "A1",
    category: "Sentence structure",
    title: "Word order and questions",
    titleDe: "Wortstellung und Fragen",
    minutes: 25,
    simple:
      "In a statement the conjugated verb is always in position 2. In a yes/no question it comes first. In a W-question it comes after the question word.",
    detailed: [
      "German word order is verb-second (V2). Position 1 can be the subject or any other element — a time, a place, an object — but the conjugated verb must stay in position 2 and the subject then follows it: Heute arbeite ich zu Hause.",
      "Yes/no questions simply put the verb first: Arbeitest du heute? W-questions start with a question word: Wann arbeitest du? The rest of the order does not change.",
      "The middle field follows the tendency TeKaMoLo: Temporal (when) – Kausal (why) – Modal (how) – Lokal (where). Ich fahre morgen wegen der Prüfung schnell nach Bonn.",
    ],
    tables: [
      {
        title: "Three sentence types",
        headers: ["Type", "Position 1", "Position 2", "Rest"],
        rows: [
          ["Statement", "Ich", "lerne", "jeden Tag Deutsch."],
          ["Statement (fronted time)", "Jeden Tag", "lerne", "ich Deutsch."],
          ["Yes/no question", "Lernst", "du", "jeden Tag Deutsch?"],
          ["W-question", "Wann", "lernst", "du Deutsch?"],
          ["Imperative", "Lern", "—", "jeden Tag Deutsch!"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Question words",
        headers: ["Wort", "Meaning", "Example"],
        rows: [
          ["wer / wen / wem", "who / whom", "Wer kommt mit?"],
          ["was", "what", "Was machst du?"],
          ["wo / wohin / woher", "where / where to / where from", "Woher kommst du?"],
          ["wann", "when", "Wann beginnt der Kurs?"],
          ["wie / wie viel / wie lange", "how / how much / how long", "Wie lange lernst du Deutsch?"],
          ["warum / wieso", "why", "Warum lernst du Deutsch?"],
          ["welcher / welche / welches", "which", "Welches Buch möchtest du?"],
        ],
      },
    ],
    visuals: [
      {
        label: "V2 rule",
        pattern: "[Element 1] [Verb] [Subjekt] [Rest]",
        parts: ["Am Montag", "habe", "ich", "einen Termin."],
      },
      {
        label: "TeKaMoLo",
        pattern: "Temporal → Kausal → Modal → Lokal",
        parts: ["morgen", "wegen der Arbeit", "mit dem Zug", "nach Köln"],
      },
    ],
    examples: [
      { de: "Morgen fahre ich nach Berlin.", en: "Tomorrow I'm going to Berlin.", note: "Verb still in position 2." },
      { de: "Wie heißen Sie, bitte?", en: "What's your name, please?" },
      { de: "Kommt der Bus pünktlich?", en: "Is the bus on time?" },
      { de: "Ich gehe heute mit meiner Freundin ins Kino.", en: "I'm going to the cinema with my girlfriend today." },
    ],
    mistakes: [
      { wrong: "Morgen ich fahre nach Berlin.", right: "Morgen fahre ich nach Berlin.", why: "Only one element before the verb." },
      { wrong: "Warum du lernst Deutsch?", right: "Warum lernst du Deutsch?", why: "The verb follows the question word directly." },
      { wrong: "Ich gehe ins Kino heute.", right: "Ich gehe heute ins Kino.", why: "Time normally comes before place." },
    ],
    tips: [
      "Count elements, not words: Am nächsten Montag is ONE element.",
      "If you start with a time expression, remember to swap subject and verb.",
      "Answer yes/no questions with Ja / Nein / Doch.",
    ],
    practice: [
      {
        id: "g-a1-9-p1",
        type: "order",
        prompt: "Start with Am Wochenende.",
        tokens: ["Am Wochenende", "ich", "meine Familie", "besuche"],
        answer: "Am Wochenende besuche ich meine Familie",
        explanation: "Element 1 – verb – subject – rest.",
      },
      {
        id: "g-a1-9-p2",
        type: "multiple-choice",
        prompt: "Which question asks for a destination?",
        options: ["Wo wohnst du?", "Woher kommst du?", "Wohin fährst du?", "Wann fährst du?"],
        answerIndex: 2,
        explanation: "wohin = where to.",
      },
      {
        id: "g-a1-9-p3",
        type: "transform",
        prompt: "Turn into a yes/no question.",
        input: "Du hast morgen Zeit.",
        answers: ["Hast du morgen Zeit?"],
        explanation: "Verb first, then subject.",
      },
    ],
    quiz: [
      {
        id: "g-a1-9-q1",
        type: "multiple-choice",
        prompt: "___ kostet das Ticket?",
        options: ["Wie viel", "Wie lange", "Wohin", "Wer"],
        answerIndex: 0,
        explanation: "Price → wie viel.",
      },
      {
        id: "g-a1-9-q2",
        type: "order",
        prompt: "Build the sentence.",
        tokens: ["heute", "Ich", "ins Kino", "gehe", "mit Anna"],
        answer: "Ich gehe heute mit Anna ins Kino",
        explanation: "TeKaMoLo: time – modal (with whom) – place.",
      },
    ],
    revision: [
      "Conjugated verb in position 2 in every statement.",
      "Yes/no question: verb first. W-question: question word + verb.",
      "Middle field order: time – reason – manner – place.",
    ],
    cheatSheet: [
      { label: "Statement", value: "Ich lerne heute." },
      { label: "Fronted element", value: "Heute lerne ich." },
      { label: "Yes/no", value: "Lernst du heute?" },
      { label: "W-question", value: "Wann lernst du?" },
      { label: "Order", value: "TeKaMoLo" },
    ],
    related: ["modalverben", "negation-nicht-kein"],
  },
  {
    slug: "perfekt",
    level: "A1",
    category: "Tenses",
    title: "The Perfekt (spoken past)",
    titleDe: "Das Perfekt",
    minutes: 35,
    simple:
      "The Perfekt is the normal past tense in spoken German: haben or sein in position 2 + Partizip II at the end. Ich habe gearbeitet. Ich bin gefahren.",
    detailed: [
      "Regular (weak) verbs form the Partizip II with ge- + stem + -t: arbeiten → gearbeitet. Irregular (strong) verbs use ge- + changed stem + -en: sprechen → gesprochen, fahren → gefahren. Verbs ending in -ieren and inseparable verbs take no ge-: studiert, verstanden.",
      "Most verbs use haben. Use sein with verbs of movement from A to B (gehen, fahren, fliegen, kommen, reisen) and change of state (aufstehen, einschlafen, werden, passieren, sterben), plus sein and bleiben.",
      "Separable verbs insert ge- between prefix and stem: einkaufen → eingekauft, aufstehen → aufgestanden. In writing, especially in narratives, sein/haben and modal verbs prefer the Präteritum (war, hatte, konnte).",
    ],
    tables: [
      {
        title: "Partizip II formation",
        headers: ["Verb type", "Pattern", "Example"],
        rows: [
          ["weak", "ge- + Stamm + -t", "lernen → gelernt"],
          ["weak with -t/-d stem", "ge- + Stamm + -et", "arbeiten → gearbeitet"],
          ["strong", "ge- + (changed) Stamm + -en", "sprechen → gesprochen"],
          ["separable", "Präfix + ge- + … ", "einkaufen → eingekauft"],
          ["inseparable", "no ge-", "verstehen → verstanden"],
          ["-ieren", "no ge-, + -t", "studieren → studiert"],
        ],
        highlightColumn: 1,
      },
      {
        title: "haben or sein?",
        headers: ["Auxiliary", "When", "Examples"],
        rows: [
          ["haben", "most verbs, all with an accusative object", "Ich habe einen Film gesehen."],
          ["sein", "movement A → B", "Wir sind nach Köln gefahren."],
          ["sein", "change of state", "Er ist früh eingeschlafen."],
          ["sein", "sein, bleiben, passieren, werden", "Ich bin krank gewesen."],
        ],
      },
      {
        title: "Frequent irregular participles",
        headers: ["Infinitiv", "Partizip II", "Auxiliary"],
        rows: [
          ["essen", "gegessen", "haben"],
          ["trinken", "getrunken", "haben"],
          ["sprechen", "gesprochen", "haben"],
          ["schreiben", "geschrieben", "haben"],
          ["lesen", "gelesen", "haben"],
          ["gehen", "gegangen", "sein"],
          ["fahren", "gefahren", "sein"],
          ["kommen", "gekommen", "sein"],
          ["bleiben", "geblieben", "sein"],
          ["sein", "gewesen", "sein"],
        ],
      },
    ],
    visuals: [
      {
        label: "Perfekt bracket",
        pattern: "haben/sein (Pos. 2) … Partizip II (Ende)",
        parts: ["Ich", "habe", "gestern einen Film", "gesehen."],
      },
    ],
    examples: [
      { de: "Gestern habe ich für die Prüfung gelernt.", en: "Yesterday I studied for the exam." },
      { de: "Wir sind am Samstag nach Frankfurt gefahren.", en: "We drove to Frankfurt on Saturday." },
      { de: "Hast du schon gefrühstückt?", en: "Have you had breakfast yet?" },
      { de: "Ich habe drei Jahre in Marokko Deutsch studiert.", en: "I studied German in Morocco for three years." },
    ],
    mistakes: [
      { wrong: "Ich habe nach Berlin gefahren.", right: "Ich bin nach Berlin gefahren.", why: "Movement A → B takes sein." },
      { wrong: "Ich habe gestern gearbeitet nicht.", right: "Ich habe gestern nicht gearbeitet.", why: "nicht comes before the Partizip II." },
      { wrong: "Ich habe getelefoniert.", right: "Ich habe telefoniert.", why: "-ieren verbs have no ge-." },
    ],
    tips: [
      "Learn irregular verbs in threes: sprechen – sprach – gesprochen.",
      "If the verb has an accusative object, the auxiliary is almost always haben.",
      "For sein and haben themselves, speakers prefer war and hatte.",
    ],
    practice: [
      {
        id: "g-a1-10-p1",
        type: "fill-blank",
        prompt: "haben or sein?",
        sentence: "Ich ___ gestern einen Film gesehen und dann ___ ich früh ins Bett gegangen.",
        answers: [["habe"], ["bin"]],
        explanation: "sehen → haben; gehen (movement) → sein.",
      },
      {
        id: "g-a1-10-p2",
        type: "transform",
        prompt: "Put into the Perfekt.",
        input: "Ich kaufe am Samstag ein.",
        answers: ["Ich habe am Samstag eingekauft."],
        explanation: "Separable verb: ein + ge + kauft.",
      },
      {
        id: "g-a1-10-p3",
        type: "multiple-choice",
        prompt: "Was ___ du am Wochenende gemacht?",
        options: ["bist", "hast", "habt", "hat"],
        answerIndex: 1,
        explanation: "machen → haben, du hast.",
      },
      {
        id: "g-a1-10-p4",
        type: "order",
        prompt: "Build the sentence.",
        tokens: ["Wir", "in Berlin", "sind", "geblieben", "drei Tage"],
        answer: "Wir sind drei Tage in Berlin geblieben",
        explanation: "bleiben takes sein; participle at the end.",
      },
    ],
    quiz: [
      {
        id: "g-a1-10-q1",
        type: "multiple-choice",
        prompt: "Er ___ zwei Jahre in München gewohnt.",
        options: ["ist", "hat", "war", "sind"],
        answerIndex: 1,
        explanation: "wohnen is a state, not a movement → haben.",
      },
      {
        id: "g-a1-10-q2",
        type: "fill-blank",
        prompt: "Write the Partizip II.",
        sentence: "trinken → ___ ; verstehen → ___ ; aufstehen → ___",
        answers: [["getrunken"], ["verstanden"], ["aufgestanden"]],
        explanation: "Strong, inseparable (no ge-), separable (ge- inside).",
      },
      {
        id: "g-a1-10-q3",
        type: "true-false",
        prompt: "Verbs with an accusative object usually take sein in the Perfekt.",
        answer: false,
        explanation: "They take haben.",
      },
    ],
    revision: [
      "haben/sein in position 2, Partizip II at the end.",
      "ge- + -t (weak) / ge- + -en (strong); no ge- for -ieren and inseparable verbs.",
      "sein for movement and change of state.",
    ],
    cheatSheet: [
      { label: "lernen", value: "hat gelernt" },
      { label: "arbeiten", value: "hat gearbeitet" },
      { label: "sprechen", value: "hat gesprochen" },
      { label: "fahren", value: "ist gefahren" },
      { label: "aufstehen", value: "ist aufgestanden" },
      { label: "studieren", value: "hat studiert" },
    ],
    related: ["trennbare-verben", "praeteritum"],
  },
];
