import type { GrammarTopic } from "@/lib/types";

export const a2Grammar: GrammarTopic[] = [
  {
    slug: "dativ",
    level: "A2",
    category: "Cases",
    title: "The dative case",
    titleDe: "Der Dativ",
    minutes: 30,
    simple:
      "The dative marks the indirect object (to whom?) and follows prepositions like mit, nach, aus, bei, seit, von, zu. Signals: dem, der, dem, den + -n.",
    detailed: [
      "Ask wem? to find the dative: Ich gebe dem Kind ein Buch. — Wem gebe ich ein Buch? Dem Kind. With two objects the person is dative and the thing is accusative.",
      "The dative prepositions must be memorised: aus, bei, mit, nach, seit, von, zu, gegenüber. Many of them are extremely frequent (mit dem Bus, nach der Arbeit, bei meiner Familie, zum Arzt).",
      "Some verbs always take the dative even though they feel like direct objects in English: helfen, danken, gefallen, gehören, passen, schmecken, antworten, gratulieren, folgen. In the dative plural the noun itself adds -n: mit den Kindern, mit den Freunden.",
    ],
    tables: [
      {
        title: "Articles in the dative",
        headers: ["Genus", "definite", "indefinite", "possessive"],
        rows: [
          ["maskulin", "dem Mann", "einem Mann", "meinem Mann"],
          ["feminin", "der Frau", "einer Frau", "meiner Frau"],
          ["neutrum", "dem Kind", "einem Kind", "meinem Kind"],
          ["Plural", "den Kindern", "— Kindern", "meinen Kindern"],
        ],
        highlightColumn: 1,
        note: "Dative plural nouns take an extra -n unless they already end in -n or -s.",
      },
      {
        title: "Dative pronouns",
        headers: ["Nominativ", "Dativ", "Example"],
        rows: [
          ["ich", "mir", "Kannst du mir helfen?"],
          ["du", "dir", "Wie geht es dir?"],
          ["er / es", "ihm", "Ich gebe ihm das Buch."],
          ["sie", "ihr", "Das Kleid gefällt ihr."],
          ["wir", "uns", "Können Sie uns helfen?"],
          ["ihr", "euch", "Ich zeige euch die Stadt."],
          ["sie / Sie", "ihnen / Ihnen", "Ich danke Ihnen."],
        ],
      },
      {
        title: "Contractions",
        headers: ["Full form", "Contraction"],
        rows: [
          ["zu dem", "zum"],
          ["zu der", "zur"],
          ["bei dem", "beim"],
          ["von dem", "vom"],
          ["in dem", "im"],
          ["an dem", "am"],
        ],
      },
    ],
    visuals: [
      {
        label: "Two objects",
        pattern: "Subjekt + Verb + Person (Dativ) + Sache (Akkusativ)",
        parts: ["Ich", "schenke", "meiner Mutter", "Blumen."],
      },
      {
        label: "Dative prepositions",
        pattern: "aus · bei · mit · nach · seit · von · zu · gegenüber",
        parts: ["mit dem Zug", "seit einem Jahr", "zur Arbeit"],
      },
    ],
    examples: [
      { de: "Ich fahre mit dem Fahrrad zur Arbeit.", en: "I ride my bike to work." },
      { de: "Kannst du mir bitte helfen?", en: "Can you help me, please?", note: "helfen + Dativ." },
      { de: "Seit zwei Jahren wohne ich in Deutschland.", en: "I've been living in Germany for two years." },
      { de: "Das Essen schmeckt meinen Kindern sehr gut.", en: "My children really like the food." },
    ],
    mistakes: [
      { wrong: "Ich helfe dich.", right: "Ich helfe dir.", why: "helfen takes the dative." },
      { wrong: "mit meine Freunde", right: "mit meinen Freunden", why: "Dative plural: article -n and noun -n." },
      { wrong: "Ich fahre zu Arzt.", right: "Ich fahre zum Arzt.", why: "zu dem contracts to zum." },
    ],
    tips: [
      "Memorise the dative prepositions as a song: aus-bei-mit-nach-seit-von-zu.",
      "Learn dative verbs as fixed pairs: jemandem helfen, jemandem danken, jemandem gefallen.",
      "Wie geht es dir/Ihnen? is dative — a phrase you will use every day.",
    ],
    practice: [
      {
        id: "g-a2-1-p1",
        type: "fill-blank",
        prompt: "Complete with dative articles.",
        sentence: "Ich fahre mit ___ Bus zu ___ Universität.",
        answers: [["dem"], ["der"]],
        explanation: "mit + Dativ maskulin dem; zu + Dativ feminin der (or zur).",
      },
      {
        id: "g-a2-1-p2",
        type: "transform",
        prompt: "Replace the person with a pronoun.",
        input: "Ich schreibe meiner Schwester eine E-Mail.",
        answers: ["Ich schreibe ihr eine E-Mail."],
        explanation: "meiner Schwester → ihr.",
      },
      {
        id: "g-a2-1-p3",
        type: "multiple-choice",
        prompt: "Das Buch gehört ___ Lehrer.",
        options: ["den", "dem", "der", "das"],
        answerIndex: 1,
        explanation: "gehören + Dativ, maskulin → dem.",
      },
      {
        id: "g-a2-1-p4",
        type: "order",
        prompt: "Build the sentence.",
        tokens: ["meinem", "Ich", "Bruder", "helfe", "oft"],
        answer: "Ich helfe meinem Bruder oft",
        explanation: "helfen + Dativ.",
      },
    ],
    quiz: [
      {
        id: "g-a2-1-q1",
        type: "multiple-choice",
        prompt: "Wie geht es ___? (formal)",
        options: ["dir", "Ihnen", "ihnen", "Sie"],
        answerIndex: 1,
        explanation: "Formal dative pronoun Ihnen with a capital I.",
      },
      {
        id: "g-a2-1-q2",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Ich wohne ___ (bei) ___ Eltern und arbeite ___ (seit) ___ Jahr in Bonn.",
        answers: [["bei"], ["meinen"], ["seit"], ["einem"]],
        explanation: "bei + Dativ Plural meinen Eltern; seit + Dativ neutrum einem Jahr.",
      },
      {
        id: "g-a2-1-q3",
        type: "true-false",
        prompt: "With two objects, the thing is dative and the person accusative.",
        answer: false,
        explanation: "It is the opposite: person = dative, thing = accusative.",
      },
    ],
    revision: [
      "Signals: dem / der / dem / den + noun -n.",
      "Prepositions: aus, bei, mit, nach, seit, von, zu, gegenüber.",
      "Dative verbs: helfen, danken, gefallen, gehören, passen, schmecken, antworten.",
    ],
    cheatSheet: [
      { label: "maskulin", value: "dem / einem / meinem" },
      { label: "feminin", value: "der / einer / meiner" },
      { label: "neutrum", value: "dem / einem / meinem" },
      { label: "Plural", value: "den …-n" },
      { label: "Pronouns", value: "mir, dir, ihm, ihr, uns, euch, ihnen" },
      { label: "Contractions", value: "zum, zur, beim, vom, im, am" },
    ],
    related: ["akkusativ", "wechselpraepositionen"],
  },
  {
    slug: "wechselpraepositionen",
    level: "A2",
    category: "Prepositions",
    title: "Two-way prepositions (Wechselpräpositionen)",
    titleDe: "Wechselpräpositionen",
    minutes: 30,
    simple:
      "in, an, auf, über, unter, vor, hinter, neben, zwischen take the accusative for movement (wohin?) and the dative for position (wo?).",
    detailed: [
      "Ask wohin? (where to) → accusative: Ich gehe in die Küche. Ask wo? (where) → dative: Ich bin in der Küche. The preposition does not change, only the article.",
      "Verb pairs help: legen/liegen, stellen/stehen, setzen/sitzen, hängen/hängen, stecken/stecken. The first of each pair is a movement verb with the accusative, the second describes a position with the dative.",
      "Frequent contractions: in das → ins, in dem → im, an das → ans, an dem → am, auf das → aufs. Time expressions with an/in are always dative: am Montag, im Januar, in einer Woche.",
    ],
    tables: [
      {
        title: "The nine two-way prepositions",
        headers: ["Präposition", "Meaning", "wohin? (Akk.)", "wo? (Dat.)"],
        rows: [
          ["in", "in / into", "Ich gehe in die Stadt.", "Ich bin in der Stadt."],
          ["an", "at / to (vertical surface)", "Ich hänge das Bild an die Wand.", "Das Bild hängt an der Wand."],
          ["auf", "on / onto", "Ich lege das Buch auf den Tisch.", "Das Buch liegt auf dem Tisch."],
          ["über", "over / above", "Der Vogel fliegt über den See.", "Die Lampe hängt über dem Tisch."],
          ["unter", "under", "Die Katze läuft unter das Bett.", "Die Katze schläft unter dem Bett."],
          ["vor", "in front of / before", "Ich stelle den Stuhl vor das Fenster.", "Der Stuhl steht vor dem Fenster."],
          ["hinter", "behind", "Er geht hinter das Haus.", "Der Garten ist hinter dem Haus."],
          ["neben", "next to", "Setz dich neben mich!", "Er sitzt neben mir."],
          ["zwischen", "between", "Ich stelle die Vase zwischen die Bücher.", "Die Vase steht zwischen den Büchern."],
        ],
      },
      {
        title: "Verb pairs",
        headers: ["Movement (Akkusativ)", "Position (Dativ)"],
        rows: [
          ["legen — Ich lege das Handy auf den Tisch.", "liegen — Das Handy liegt auf dem Tisch."],
          ["stellen — Ich stelle die Flasche in den Kühlschrank.", "stehen — Die Flasche steht im Kühlschrank."],
          ["setzen — Ich setze mich auf das Sofa.", "sitzen — Ich sitze auf dem Sofa."],
          ["hängen (schwach) — Ich hänge das Foto an die Wand.", "hängen (stark) — Das Foto hängt an der Wand."],
        ],
      },
    ],
    visuals: [
      {
        label: "The key question",
        pattern: "Wohin? → Akkusativ · Wo? → Dativ",
        parts: ["in die Schule (wohin)", "in der Schule (wo)"],
      },
    ],
    examples: [
      { de: "Ich gehe ins Kino. — Ich bin im Kino.", en: "I'm going to the cinema. — I'm at the cinema." },
      { de: "Stell die Teller bitte auf den Tisch.", en: "Please put the plates on the table." },
      { de: "Der Schlüssel liegt unter der Zeitung.", en: "The key is under the newspaper." },
      { de: "Am Montag habe ich einen Termin beim Arzt.", en: "On Monday I have a doctor's appointment." },
    ],
    mistakes: [
      { wrong: "Ich gehe in der Schule.", right: "Ich gehe in die Schule.", why: "gehen expresses movement → accusative." },
      { wrong: "Das Buch liegt auf den Tisch.", right: "Das Buch liegt auf dem Tisch.", why: "liegen describes position → dative." },
      { wrong: "in Montag", right: "am Montag", why: "Days take an + Dativ, contracted to am." },
    ],
    tips: [
      "Always ask the question first: wohin or wo?",
      "Movement verbs: gehen, fahren, legen, stellen, setzen, hängen (weak).",
      "nach and zu are not two-way prepositions: nach Berlin, zum Arzt (always dative).",
    ],
    practice: [
      {
        id: "g-a2-2-p1",
        type: "fill-blank",
        prompt: "Accusative or dative?",
        sentence: "Ich hänge das Bild an ___ Wand. Jetzt hängt es an ___ Wand.",
        answers: [["die"], ["der"]],
        explanation: "Movement → die Wand; position → der Wand.",
      },
      {
        id: "g-a2-2-p2",
        type: "multiple-choice",
        prompt: "Wir treffen uns ___ Bahnhof.",
        options: ["an den", "am", "an die", "ans"],
        answerIndex: 1,
        explanation: "Position → an dem → am.",
      },
      {
        id: "g-a2-2-p3",
        type: "match",
        prompt: "Match movement and position verbs.",
        pairs: [
          { left: "legen", right: "liegen" },
          { left: "stellen", right: "stehen" },
          { left: "setzen", right: "sitzen" },
        ],
        explanation: "Movement verbs are weak and take the accusative.",
      },
    ],
    quiz: [
      {
        id: "g-a2-2-q1",
        type: "multiple-choice",
        prompt: "Die Kinder spielen ___ Garten.",
        options: ["in den", "im", "ins", "in die"],
        answerIndex: 1,
        explanation: "spielen = position → im Garten.",
      },
      {
        id: "g-a2-2-q2",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Leg die Wäsche bitte ___ ___ Schrank (in). Sie liegt jetzt ___ ___ Schrank.",
        answers: [["in"], ["den"], ["in"], ["dem"]],
        explanation: "Movement accusative, then position dative.",
      },
    ],
    revision: [
      "Nine prepositions: in, an, auf, über, unter, vor, hinter, neben, zwischen.",
      "wohin → Akkusativ, wo → Dativ.",
      "Contractions: ins, im, ans, am, aufs.",
    ],
    cheatSheet: [
      { label: "wohin?", value: "Akkusativ" },
      { label: "wo?", value: "Dativ" },
      { label: "legen / liegen", value: "Akk. / Dat." },
      { label: "in das", value: "ins" },
      { label: "an dem", value: "am" },
      { label: "Time (Montag, Januar)", value: "am / im (Dativ)" },
    ],
    related: ["dativ", "akkusativ"],
  },
  {
    slug: "praeteritum",
    level: "A2",
    category: "Tenses",
    title: "Präteritum (simple past)",
    titleDe: "Das Präteritum",
    minutes: 30,
    simple:
      "The Präteritum is the written past tense. In speech it is used mainly with sein (war), haben (hatte), modal verbs and es gab.",
    detailed: [
      "Weak verbs insert -te between stem and ending: lernen → ich lernte, du lerntest, er lernte, wir lernten. Strong verbs change the stem and take no -te: fahren → ich fuhr, du fuhrst, er fuhr, wir fuhren.",
      "Note that ich and er/sie/es always have the same form in the Präteritum — a useful shortcut.",
      "Use the Präteritum in stories, reports, newspaper articles and formal letters. In everyday conversation Germans use the Perfekt, except for war, hatte, konnte, musste, wollte, durfte, sollte and es gab.",
    ],
    tables: [
      {
        title: "Endings",
        headers: ["Person", "weak (lernen)", "strong (fahren)", "mixed (bringen)"],
        rows: [
          ["ich", "lernte", "fuhr", "brachte"],
          ["du", "lerntest", "fuhrst", "brachtest"],
          ["er/sie/es", "lernte", "fuhr", "brachte"],
          ["wir", "lernten", "fuhren", "brachten"],
          ["ihr", "lerntet", "fuhrt", "brachtet"],
          ["sie/Sie", "lernten", "fuhren", "brachten"],
        ],
        highlightColumn: 1,
      },
      {
        title: "The forms you must know by heart",
        headers: ["Infinitiv", "Präteritum (ich)", "Meaning"],
        rows: [
          ["sein", "war", "was"],
          ["haben", "hatte", "had"],
          ["werden", "wurde", "became"],
          ["können", "konnte", "could"],
          ["müssen", "musste", "had to"],
          ["wollen", "wollte", "wanted"],
          ["dürfen", "durfte", "was allowed"],
          ["sollen", "sollte", "was supposed to"],
          ["es gibt", "es gab", "there was/were"],
        ],
      },
      {
        title: "Frequent strong verbs",
        headers: ["Infinitiv", "Präteritum", "Partizip II"],
        rows: [
          ["gehen", "ging", "gegangen"],
          ["kommen", "kam", "gekommen"],
          ["sprechen", "sprach", "gesprochen"],
          ["schreiben", "schrieb", "geschrieben"],
          ["sehen", "sah", "gesehen"],
          ["nehmen", "nahm", "genommen"],
          ["finden", "fand", "gefunden"],
          ["essen", "aß", "gegessen"],
        ],
      },
    ],
    visuals: [
      {
        label: "Weak formula",
        pattern: "Stamm + te + Endung",
        parts: ["arbeit", "+", "ete", "→", "ich arbeitete"],
      },
    ],
    examples: [
      { de: "Als Kind war ich sehr schüchtern.", en: "As a child I was very shy." },
      { de: "Wir hatten keine Zeit, deshalb nahmen wir ein Taxi.", en: "We had no time, so we took a taxi." },
      { de: "Er konnte damals kein Deutsch.", en: "He couldn't speak German at that time." },
      { de: "Früher gab es hier ein Kino.", en: "There used to be a cinema here." },
    ],
    mistakes: [
      { wrong: "Ich habe als Kind in Rabat gewohnt und habe sehr glücklich gewesen.", right: "… und war sehr glücklich.", why: "sein prefers the Präteritum war." },
      { wrong: "Ich fuhrte nach Berlin.", right: "Ich fuhr nach Berlin.", why: "Strong verbs take no -te." },
      { wrong: "Er sprachte mit dem Chef.", right: "Er sprach mit dem Chef.", why: "sprechen is strong: sprach." },
    ],
    tips: [
      "ich and er/sie/es are identical — learn one form for both.",
      "In everyday speech use war, hatte and the modal verbs; use the Perfekt for the rest.",
      "Learn strong verbs in threes and revise them with flashcards.",
    ],
    practice: [
      {
        id: "g-a2-3-p1",
        type: "transform",
        prompt: "Rewrite in the Präteritum.",
        input: "Ich habe keine Zeit und ich bin müde.",
        answers: ["Ich hatte keine Zeit und ich war müde."],
        explanation: "haben → hatte, sein → war.",
      },
      {
        id: "g-a2-3-p2",
        type: "fill-blank",
        prompt: "Complete the story.",
        sentence: "Letztes Jahr ___ (fahren) wir nach Wien. Das Wetter ___ (sein) schön und wir ___ (können) viel besichtigen.",
        answers: [["fuhren"], ["war"], ["konnten"]],
        explanation: "Strong verb fuhren, war, konnten.",
      },
      {
        id: "g-a2-3-p3",
        type: "multiple-choice",
        prompt: "Als ich klein war, ___ es hier einen Park.",
        options: ["gibt", "gab", "gegeben", "hatte"],
        answerIndex: 1,
        explanation: "es gibt → es gab.",
      },
    ],
    quiz: [
      {
        id: "g-a2-3-q1",
        type: "multiple-choice",
        prompt: "Wir ___ gestern zu Hause bleiben.",
        options: ["mussten", "müssten", "musste", "müssen"],
        answerIndex: 0,
        explanation: "wir mussten.",
      },
      {
        id: "g-a2-3-q2",
        type: "fill-blank",
        prompt: "Präteritum forms.",
        sentence: "gehen → ich ___ ; nehmen → ich ___ ; schreiben → ich ___",
        answers: [["ging"], ["nahm"], ["schrieb"]],
        explanation: "Strong verbs with stem change.",
      },
      {
        id: "g-a2-3-q3",
        type: "true-false",
        prompt: "In spoken German the Präteritum of regular verbs is very common.",
        answer: false,
        explanation: "Speakers use the Perfekt; the Präteritum is mainly written.",
      },
    ],
    revision: [
      "Weak: Stamm + -te + ending. Strong: new stem, no -te.",
      "ich = er/sie/es.",
      "Spoken German: war, hatte, konnte, wollte, musste, es gab.",
    ],
    cheatSheet: [
      { label: "sein", value: "war, warst, war, waren" },
      { label: "haben", value: "hatte, hattest, hatte, hatten" },
      { label: "werden", value: "wurde" },
      { label: "können", value: "konnte" },
      { label: "müssen", value: "musste" },
      { label: "es gibt", value: "es gab" },
    ],
    related: ["perfekt", "konjunktiv-2"],
  },
  {
    slug: "adjektivdeklination",
    level: "A2",
    category: "Adjectives",
    title: "Adjective endings",
    titleDe: "Adjektivdeklination",
    minutes: 35,
    simple:
      "An adjective before a noun needs an ending. After der/die/das the endings are -e or -en; after ein/kein/mein the adjective shows the gender; with no article it copies the article ending.",
    detailed: [
      "There are three patterns. (1) Weak declension after a definite article (der, die, das, diese, jede, alle): only -e or -en. (2) Mixed declension after ein, kein and possessives: in the three nominative/accusative singular slots where ein has no ending, the adjective takes over (ein kleiner Tisch, ein kleines Kind). (3) Strong declension with no article: the adjective takes the article's ending (guter Kaffee, kaltes Wasser).",
      "A practical shortcut: in the whole dative and genitive, and in the entire plural after an article, the ending is always -en.",
      "Adjectives after sein, werden and bleiben take no ending at all: Der Tisch ist klein. Das Wetter wird schön.",
    ],
    tables: [
      {
        title: "After the definite article (weak)",
        headers: ["Kasus", "maskulin", "feminin", "neutrum", "Plural"],
        rows: [
          ["Nominativ", "der kleine Tisch", "die kleine Lampe", "das kleine Kind", "die kleinen Kinder"],
          ["Akkusativ", "den kleinen Tisch", "die kleine Lampe", "das kleine Kind", "die kleinen Kinder"],
          ["Dativ", "dem kleinen Tisch", "der kleinen Lampe", "dem kleinen Kind", "den kleinen Kindern"],
        ],
        highlightColumn: 1,
      },
      {
        title: "After ein / kein / mein (mixed)",
        headers: ["Kasus", "maskulin", "feminin", "neutrum", "Plural"],
        rows: [
          ["Nominativ", "ein kleiner Tisch", "eine kleine Lampe", "ein kleines Kind", "keine kleinen Kinder"],
          ["Akkusativ", "einen kleinen Tisch", "eine kleine Lampe", "ein kleines Kind", "keine kleinen Kinder"],
          ["Dativ", "einem kleinen Tisch", "einer kleinen Lampe", "einem kleinen Kind", "keinen kleinen Kindern"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Without an article (strong)",
        headers: ["Kasus", "maskulin", "feminin", "neutrum", "Plural"],
        rows: [
          ["Nominativ", "guter Kaffee", "frische Milch", "kaltes Wasser", "gute Ideen"],
          ["Akkusativ", "guten Kaffee", "frische Milch", "kaltes Wasser", "gute Ideen"],
          ["Dativ", "gutem Kaffee", "frischer Milch", "gutem Wasser", "guten Ideen"],
        ],
      },
    ],
    visuals: [
      {
        label: "Shortcut rule",
        pattern: "Dativ / Genitiv / Plural mit Artikel → immer -en",
        parts: ["mit dem neuen Auto", "den neuen Kollegen", "die neuen Kollegen"],
      },
      {
        label: "Three slots where ein has no ending",
        pattern: "m. Nom. -er · n. Nom. -es · n. Akk. -es",
        parts: ["ein neuer Kollege", "ein neues Handy"],
      },
    ],
    examples: [
      { de: "Ich suche eine kleine Wohnung mit einem großen Balkon.", en: "I'm looking for a small flat with a big balcony." },
      { de: "Der neue Kollege kommt aus Marokko.", en: "The new colleague is from Morocco." },
      { de: "Ich trinke gern schwarzen Kaffee.", en: "I like drinking black coffee.", note: "No article → strong ending." },
      { de: "Das Zimmer ist hell und modern.", en: "The room is bright and modern.", note: "After sein: no ending." },
    ],
    mistakes: [
      { wrong: "ein kleines Tisch", right: "ein kleiner Tisch", why: "der Tisch is masculine nominative → -er." },
      { wrong: "mit dem neue Auto", right: "mit dem neuen Auto", why: "Dative always -en." },
      { wrong: "Das Wetter ist schönes.", right: "Das Wetter ist schön.", why: "Predicative adjectives take no ending." },
    ],
    tips: [
      "Learn the shortcut first: dative, genitive and plural-with-article are all -en. That is over half of the table.",
      "Then learn the three -er / -es slots after ein.",
      "Practise with real phrases from flat adverts and menus, where adjectives are everywhere.",
    ],
    practice: [
      {
        id: "g-a2-4-p1",
        type: "fill-blank",
        prompt: "Add the endings.",
        sentence: "Ich habe ein neu___ Handy und eine alt___ Uhr.",
        answers: [["es"], ["e"]],
        explanation: "das Handy → ein neues; die Uhr → eine alte.",
      },
      {
        id: "g-a2-4-p2",
        type: "fill-blank",
        prompt: "Add the endings.",
        sentence: "Wir fahren mit dem neu___ Auto zu unseren deutsch___ Freunden.",
        answers: [["en"], ["en"]],
        explanation: "Dative singular and dative plural → -en.",
      },
      {
        id: "g-a2-4-p3",
        type: "multiple-choice",
        prompt: "Ich möchte ___ Tee, bitte.",
        options: ["grünen", "grüner", "grünes", "grüne"],
        answerIndex: 0,
        explanation: "No article, accusative masculine → -en.",
      },
    ],
    quiz: [
      {
        id: "g-a2-4-q1",
        type: "multiple-choice",
        prompt: "Das ist der ___ Zug nach Hamburg.",
        options: ["schnelle", "schneller", "schnellen", "schnelles"],
        answerIndex: 0,
        explanation: "After der, nominative masculine → -e.",
      },
      {
        id: "g-a2-4-q2",
        type: "fill-blank",
        prompt: "Endings.",
        sentence: "Ich suche einen ruhig___ Platz in einer klein___ Stadt.",
        answers: [["en"], ["en"]],
        explanation: "Accusative masculine after ein → -en; dative feminine → -en.",
      },
      {
        id: "g-a2-4-q3",
        type: "true-false",
        prompt: "Adjectives after sein and werden take endings.",
        answer: false,
        explanation: "They stay in the base form.",
      },
    ],
    revision: [
      "Weak (after der): -e / -en only.",
      "Mixed (after ein): -er, -es fill in for the missing article ending.",
      "Strong (no article): adjective takes the article ending.",
    ],
    cheatSheet: [
      { label: "der kleine …", value: "-e" },
      { label: "den kleinen …", value: "-en" },
      { label: "ein kleiner Tisch", value: "-er" },
      { label: "ein kleines Kind", value: "-es" },
      { label: "Dativ / Plural + Artikel", value: "-en" },
      { label: "after sein/werden", value: "no ending" },
    ],
    related: ["komparativ-superlativ", "dativ"],
  },
  {
    slug: "komparativ-superlativ",
    level: "A2",
    category: "Adjectives",
    title: "Comparative and superlative",
    titleDe: "Komparativ und Superlativ",
    minutes: 25,
    simple:
      "Add -er for the comparative and -(e)st for the superlative: schnell – schneller – am schnellsten. Compare with als, and use (genau)so … wie for equality.",
    detailed: [
      "Short adjectives with a, o, u often add an Umlaut: alt – älter – am ältesten, groß – größer – am größten, jung – jünger – am jüngsten.",
      "The superlative has two shapes: am schnellsten after a verb (Er läuft am schnellsten) and der/die/das schnellste before a noun (der schnellste Zug).",
      "Irregular: gut – besser – am besten, viel – mehr – am meisten, gern – lieber – am liebsten, hoch – höher – am höchsten, nah – näher – am nächsten.",
    ],
    tables: [
      {
        title: "Regular and irregular forms",
        headers: ["Positiv", "Komparativ", "Superlativ"],
        rows: [
          ["schnell", "schneller", "am schnellsten"],
          ["billig", "billiger", "am billigsten"],
          ["alt", "älter", "am ältesten"],
          ["groß", "größer", "am größten"],
          ["gut", "besser", "am besten"],
          ["viel", "mehr", "am meisten"],
          ["gern", "lieber", "am liebsten"],
          ["hoch", "höher", "am höchsten"],
          ["nah", "näher", "am nächsten"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Comparison structures",
        headers: ["Structure", "Meaning", "Example"],
        rows: [
          ["so … wie", "equal", "Berlin ist so groß wie …"],
          ["nicht so … wie", "less than", "Der Bus ist nicht so schnell wie der Zug."],
          ["Komparativ + als", "more than", "Der Zug ist schneller als der Bus."],
          ["immer + Komparativ", "increasingly", "Es wird immer wärmer."],
          ["je … desto", "the more … the more", "Je mehr ich lerne, desto besser verstehe ich."],
        ],
      },
    ],
    visuals: [
      {
        label: "Building the forms",
        pattern: "Adjektiv + er (+ als) · am + Adjektiv + sten",
        parts: ["billiger als", "am billigsten"],
      },
    ],
    examples: [
      { de: "Der Zug ist schneller als das Auto.", en: "The train is faster than the car." },
      { de: "Ich trinke lieber Tee als Kaffee.", en: "I prefer tea to coffee." },
      { de: "München ist eine der teuersten Städte Deutschlands.", en: "Munich is one of the most expensive cities in Germany." },
      { de: "Je mehr ich übe, desto sicherer werde ich.", en: "The more I practise, the more confident I get." },
    ],
    mistakes: [
      { wrong: "Er ist größer wie ich.", right: "Er ist größer als ich.", why: "Comparative uses als, not wie." },
      { wrong: "Das ist der meist teure Zug.", right: "Das ist der teuerste Zug.", why: "German does not use 'most' + adjective." },
      { wrong: "Ich mag mehr Tee als Kaffee.", right: "Ich mag Tee lieber als Kaffee.", why: "Preference uses lieber." },
    ],
    tips: [
      "als = comparison, wie = equality.",
      "Before a noun the superlative needs an adjective ending: das beste Restaurant.",
      "Learn gut/viel/gern as a set; they appear constantly.",
    ],
    practice: [
      {
        id: "g-a2-5-p1",
        type: "fill-blank",
        prompt: "Comparative or superlative?",
        sentence: "Berlin ist ___ (groß) als Köln, aber Tokio ist ___ (groß) von allen.",
        answers: [["größer"], ["am größten"]],
        explanation: "Comparative + als; superlative with am.",
      },
      {
        id: "g-a2-5-p2",
        type: "multiple-choice",
        prompt: "Ich finde Deutsch ___ als Englisch.",
        options: ["schwer", "schwerer", "am schwersten", "schwerste"],
        answerIndex: 1,
        explanation: "Comparison with als needs the comparative.",
      },
      {
        id: "g-a2-5-p3",
        type: "transform",
        prompt: "Express equality.",
        input: "Der Bus ist langsam. Die Straßenbahn ist auch langsam.",
        answers: ["Der Bus ist so langsam wie die Straßenbahn."],
        explanation: "so + Positiv + wie.",
      },
    ],
    quiz: [
      {
        id: "g-a2-5-q1",
        type: "multiple-choice",
        prompt: "Was isst du ___? — Pizza!",
        options: ["gern", "lieber", "am liebsten", "best"],
        answerIndex: 2,
        explanation: "Favourite → am liebsten.",
      },
      {
        id: "g-a2-5-q2",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "gut → ___ → am ___ ; viel → ___ → am ___",
        answers: [["besser"], ["besten"], ["mehr"], ["meisten"]],
        explanation: "Irregular forms.",
      },
    ],
    revision: [
      "-er / am -sten, with Umlaut in many short adjectives.",
      "als for comparison, so … wie for equality.",
      "Irregular: gut/besser/am besten, viel/mehr/am meisten, gern/lieber/am liebsten.",
    ],
    cheatSheet: [
      { label: "schnell", value: "schneller / am schnellsten" },
      { label: "gut", value: "besser / am besten" },
      { label: "viel", value: "mehr / am meisten" },
      { label: "gern", value: "lieber / am liebsten" },
      { label: "equality", value: "so … wie" },
      { label: "difference", value: "Komparativ + als" },
    ],
    related: ["adjektivdeklination"],
  },
  {
    slug: "nebensaetze-a2",
    level: "A2",
    category: "Sentence structure",
    title: "Subordinate clauses: weil, dass, wenn, obwohl",
    titleDe: "Nebensätze mit weil, dass, wenn, obwohl",
    minutes: 30,
    simple:
      "A subordinating conjunction sends the conjugated verb to the very end of its clause: Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.",
    detailed: [
      "Subordinating conjunctions (weil, dass, wenn, als, obwohl, damit, ob, bevor, nachdem, während, bis, seit, falls) create a dependent clause with verb-final word order. A comma always separates the clauses.",
      "Coordinating conjunctions (und, aber, oder, denn, sondern) do NOT change the word order: Ich lerne Deutsch, denn ich möchte in Deutschland arbeiten.",
      "If the subordinate clause comes first, it occupies position 1 of the whole sentence, so the main clause starts with its verb: Weil ich krank bin, bleibe ich zu Hause. Watch the pattern verb-comma-verb.",
    ],
    tables: [
      {
        title: "Conjunction types",
        headers: ["Type", "Words", "Word order"],
        rows: [
          ["subordinating", "weil, dass, wenn, als, obwohl, damit, ob, bevor, nachdem, während, bis, falls", "verb at the end"],
          ["coordinating", "und, aber, oder, denn, sondern", "no change (verb in position 2)"],
          ["adverbial connectors", "deshalb, deswegen, trotzdem, dann, außerdem", "verb in position 2 (connector = position 1)"],
        ],
      },
      {
        title: "Meaning and use",
        headers: ["Conjunction", "Meaning", "Example"],
        rows: [
          ["weil", "because (reason)", "Ich bleibe zu Hause, weil es regnet."],
          ["dass", "that (reported content)", "Ich glaube, dass er recht hat."],
          ["wenn", "if / whenever (present, repeated)", "Wenn ich Zeit habe, lese ich."],
          ["als", "when (single past event)", "Als ich klein war, wohnte ich in Fès."],
          ["obwohl", "although", "Obwohl es regnet, gehe ich spazieren."],
          ["damit", "so that (purpose)", "Ich lerne viel, damit ich die Prüfung schaffe."],
          ["ob", "whether (indirect yes/no question)", "Ich weiß nicht, ob er kommt."],
        ],
      },
    ],
    visuals: [
      {
        label: "Verb-final rule",
        pattern: "…, weil + Subjekt + … + Verb.",
        parts: ["Ich komme nicht,", "weil", "ich heute lange", "arbeiten muss."],
      },
      {
        label: "Front position",
        pattern: "[Nebensatz], Verb + Subjekt …",
        parts: ["Wenn ich Zeit habe,", "gehe", "ich schwimmen."],
      },
    ],
    examples: [
      { de: "Ich lerne Deutsch, weil ich eine Ausbildung in Deutschland machen will.", en: "I'm learning German because I want to do vocational training in Germany." },
      { de: "Ich hoffe, dass ich die Prüfung bestehe.", en: "I hope that I pass the exam." },
      { de: "Wenn das Wetter gut ist, fahren wir an den See.", en: "If the weather is good, we'll drive to the lake." },
      { de: "Obwohl er müde war, hat er weitergearbeitet.", en: "Although he was tired, he kept working." },
    ],
    mistakes: [
      { wrong: "Ich bleibe zu Hause, weil es regnet nicht draußen gut.", right: "Ich bleibe zu Hause, weil das Wetter nicht gut ist.", why: "The verb must be the last element of the weil-clause." },
      { wrong: "Ich lerne Deutsch, denn ich möchte arbeiten in Deutschland.", right: "…, denn ich möchte in Deutschland arbeiten.", why: "denn keeps normal order, but the infinitive still goes last." },
      { wrong: "Weil ich krank bin, ich bleibe zu Hause.", right: "Weil ich krank bin, bleibe ich zu Hause.", why: "After a fronted clause the main verb comes first." },
    ],
    tips: [
      "weil answers warum?, deshalb introduces the consequence: Es regnet, deshalb bleibe ich zu Hause.",
      "With a modal verb, the modal is the last word: …, weil ich arbeiten muss.",
      "als = one moment in the past; wenn = repeated or present/future.",
    ],
    practice: [
      {
        id: "g-a2-6-p1",
        type: "order",
        prompt: "Build the subordinate clause.",
        tokens: ["weil", "ich", "muss", "arbeiten", "morgen"],
        answer: "weil ich morgen arbeiten muss",
        explanation: "The modal verb takes the final position.",
      },
      {
        id: "g-a2-6-p2",
        type: "transform",
        prompt: "Join with dass.",
        input: "Ich denke: Er kommt zu spät.",
        answers: ["Ich denke, dass er zu spät kommt."],
        explanation: "Verb-final in the dass-clause.",
      },
      {
        id: "g-a2-6-p3",
        type: "multiple-choice",
        prompt: "___ ich in Deutschland war, habe ich viel gelernt.",
        options: ["Wenn", "Als", "Ob", "Dass"],
        answerIndex: 1,
        explanation: "A single completed past event → als.",
      },
    ],
    quiz: [
      {
        id: "g-a2-6-q1",
        type: "multiple-choice",
        prompt: "Ich gehe nicht zur Arbeit, ___ ich krank bin.",
        options: ["denn", "weil", "deshalb", "trotzdem"],
        answerIndex: 1,
        explanation: "Both denn and weil are possible, but only weil fits verb-final order in the following clause here.",
      },
      {
        id: "g-a2-6-q2",
        type: "order",
        prompt: "Start with the subordinate clause.",
        tokens: ["Wenn", "ich", "Zeit", "habe,", "ich", "lese", "ein Buch"],
        answer: "Wenn ich Zeit habe, lese ich ein Buch",
        explanation: "Fronted clause → verb first in the main clause.",
      },
      {
        id: "g-a2-6-q3",
        type: "true-false",
        prompt: "aber and und change the word order of the following clause.",
        answer: false,
        explanation: "They are coordinating conjunctions and keep verb-second order.",
      },
    ],
    revision: [
      "Subordinating conjunction → verb at the end.",
      "und, aber, oder, denn, sondern → no change.",
      "deshalb/trotzdem occupy position 1, so the verb follows immediately.",
    ],
    cheatSheet: [
      { label: "weil", value: "reason, verb last" },
      { label: "dass", value: "content, verb last" },
      { label: "wenn / als", value: "if-whenever / when (past)" },
      { label: "obwohl", value: "although" },
      { label: "denn", value: "because, no change" },
      { label: "deshalb", value: "therefore, verb position 2" },
    ],
    related: ["wortstellung-fragen", "relativsaetze"],
  },
  {
    slug: "reflexive-verben",
    level: "A2",
    category: "Verbs",
    title: "Reflexive verbs",
    titleDe: "Reflexive Verben",
    minutes: 20,
    simple:
      "Reflexive verbs need a reflexive pronoun: mich, dich, sich, uns, euch, sich. Ich freue mich. Ich wasche mich.",
    detailed: [
      "The reflexive pronoun refers back to the subject. In the accusative the forms are mich, dich, sich, uns, euch, sich; in the dative mir, dir, sich, uns, euch, sich. The dative appears when there is already an accusative object: Ich putze mir die Zähne.",
      "Many German reflexive verbs are not reflexive in English: sich freuen (to be glad), sich beeilen (to hurry), sich erholen (to recover), sich bewerben (to apply), sich vorstellen (to introduce oneself / to imagine).",
      "The pronoun stands directly after the conjugated verb in a main clause, and after the subject if the subject is not in first position: Heute freue ich mich sehr. In a subordinate clause: …, weil ich mich freue.",
    ],
    tables: [
      {
        title: "Reflexive pronouns",
        headers: ["Person", "Akkusativ", "Dativ", "Example"],
        rows: [
          ["ich", "mich", "mir", "Ich wasche mich. / Ich wasche mir die Hände."],
          ["du", "dich", "dir", "Du beeilst dich."],
          ["er/sie/es", "sich", "sich", "Er zieht sich an."],
          ["wir", "uns", "uns", "Wir treffen uns um acht."],
          ["ihr", "euch", "euch", "Setzt euch, bitte!"],
          ["sie/Sie", "sich", "sich", "Bitte stellen Sie sich vor."],
        ],
        highlightColumn: 1,
      },
      {
        title: "Frequent reflexive verbs",
        headers: ["Verb", "Meaning", "Example"],
        rows: [
          ["sich freuen (über/auf)", "to be glad / look forward to", "Ich freue mich auf das Wochenende."],
          ["sich interessieren für", "to be interested in", "Ich interessiere mich für Technik."],
          ["sich beeilen", "to hurry", "Beeil dich, der Bus kommt!"],
          ["sich bewerben um", "to apply for", "Ich bewerbe mich um eine Ausbildung."],
          ["sich treffen mit", "to meet", "Wir treffen uns mit Freunden."],
          ["sich vorstellen", "to introduce oneself", "Darf ich mich vorstellen?"],
          ["sich erinnern an", "to remember", "Erinnerst du dich an mich?"],
          ["sich entschuldigen", "to apologise", "Ich entschuldige mich für die Verspätung."],
        ],
      },
    ],
    visuals: [
      {
        label: "Position",
        pattern: "Verb + Reflexivpronomen + Rest",
        parts: ["Ich", "freue", "mich", "auf den Kurs."],
      },
    ],
    examples: [
      { de: "Ich bewerbe mich um einen Ausbildungsplatz als Pflegefachkraft.", en: "I'm applying for a training place as a nurse." },
      { de: "Wir treffen uns morgen um 18 Uhr am Bahnhof.", en: "We're meeting tomorrow at 6 pm at the station." },
      { de: "Ich putze mir zweimal am Tag die Zähne.", en: "I brush my teeth twice a day.", note: "Dative reflexive." },
      { de: "Bitte setzen Sie sich.", en: "Please have a seat." },
    ],
    mistakes: [
      { wrong: "Ich freue auf den Urlaub.", right: "Ich freue mich auf den Urlaub.", why: "The reflexive pronoun is obligatory." },
      { wrong: "Ich wasche mich die Hände.", right: "Ich wasche mir die Hände.", why: "With an accusative object the reflexive becomes dative." },
      { wrong: "Er interessiert sich in Musik.", right: "Er interessiert sich für Musik.", why: "Fixed preposition für." },
    ],
    tips: [
      "Learn the verb together with its preposition: sich freuen auf + Akkusativ.",
      "sich is the same for er/sie/es and sie/Sie — a small mercy.",
      "In the imperative the pronoun follows the verb: Beeil dich! Setzen Sie sich!",
    ],
    practice: [
      {
        id: "g-a2-7-p1",
        type: "fill-blank",
        prompt: "Add the reflexive pronoun.",
        sentence: "Ich interessiere ___ für Technik und mein Bruder interessiert ___ für Sport.",
        answers: [["mich"], ["sich"]],
        explanation: "ich → mich, er → sich.",
      },
      {
        id: "g-a2-7-p2",
        type: "multiple-choice",
        prompt: "Wir ___ uns am Samstag.",
        options: ["treffe", "treffen", "trefft", "trifft"],
        answerIndex: 1,
        explanation: "wir treffen uns.",
      },
      {
        id: "g-a2-7-p3",
        type: "transform",
        prompt: "Make a polite imperative with Sie.",
        input: "sich vorstellen",
        answers: ["Stellen Sie sich vor!", "Stellen Sie sich bitte vor!"],
        explanation: "Verb + Sie + sich + prefix.",
      },
    ],
    quiz: [
      {
        id: "g-a2-7-q1",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Beeil ___! Der Zug fährt in fünf Minuten.",
        answers: [["dich"]],
        explanation: "Imperative du → dich.",
      },
      {
        id: "g-a2-7-q2",
        type: "true-false",
        prompt: "sich is used for both er/sie/es and Sie.",
        answer: true,
        explanation: "Third person and formal address share sich.",
      },
    ],
    revision: [
      "Akkusativ: mich, dich, sich, uns, euch, sich.",
      "Dativ (with an accusative object): mir, dir, sich, uns, euch, sich.",
      "Learn verb + preposition together.",
    ],
    cheatSheet: [
      { label: "sich freuen auf", value: "+ Akkusativ" },
      { label: "sich interessieren für", value: "+ Akkusativ" },
      { label: "sich bewerben um", value: "+ Akkusativ" },
      { label: "sich erinnern an", value: "+ Akkusativ" },
      { label: "sich treffen mit", value: "+ Dativ" },
    ],
    related: ["verben-mit-praeposition", "imperativ"],
  },
  {
    slug: "imperativ",
    level: "A2",
    category: "Verbs",
    title: "The imperative",
    titleDe: "Der Imperativ",
    minutes: 20,
    simple:
      "Three forms: du (stem, no ending), ihr (like the present) and Sie (verb + Sie). Komm! Kommt! Kommen Sie!",
    detailed: [
      "For du take the present stem and drop the ending: du kommst → Komm! Verbs with an e → i change keep it: du sprichst → Sprich! Verbs with a → ä lose the Umlaut: du fährst → Fahr!",
      "For ihr the form is identical to the present tense: Kommt! Sprecht! For Sie you keep the pronoun: Kommen Sie! Sprechen Sie bitte langsamer!",
      "sein is irregular: Sei ruhig! Seid ruhig! Seien Sie ruhig! Add bitte and mal to soften a command: Komm mal bitte her!",
    ],
    tables: [
      {
        title: "Imperative forms",
        headers: ["Infinitiv", "du", "ihr", "Sie"],
        rows: [
          ["kommen", "Komm!", "Kommt!", "Kommen Sie!"],
          ["sprechen", "Sprich!", "Sprecht!", "Sprechen Sie!"],
          ["fahren", "Fahr!", "Fahrt!", "Fahren Sie!"],
          ["arbeiten", "Arbeite!", "Arbeitet!", "Arbeiten Sie!"],
          ["sein", "Sei!", "Seid!", "Seien Sie!"],
          ["haben", "Hab!", "Habt!", "Haben Sie!"],
          ["aufstehen", "Steh auf!", "Steht auf!", "Stehen Sie auf!"],
        ],
        highlightColumn: 1,
      },
    ],
    visuals: [
      {
        label: "Softening a command",
        pattern: "Imperativ + bitte / mal / doch",
        parts: ["Schreib", "mir", "bitte", "eine E-Mail!"],
      },
    ],
    examples: [
      { de: "Sprechen Sie bitte langsamer!", en: "Please speak more slowly." },
      { de: "Nimm die U-Bahn, das ist schneller.", en: "Take the underground, it's faster." },
      { de: "Seid bitte pünktlich!", en: "Please be on time." },
      { de: "Füllen Sie das Formular bitte aus.", en: "Please fill in the form." },
    ],
    mistakes: [
      { wrong: "Du komm hier!", right: "Komm her!", why: "The imperative drops the pronoun du." },
      { wrong: "Fährst du langsamer!", right: "Fahr langsamer!", why: "No -st ending and no Umlaut in the du imperative." },
      { wrong: "Sein Sie ruhig!", right: "Seien Sie ruhig!", why: "Irregular polite form of sein." },
    ],
    tips: [
      "Add bitte — German commands sound harsh without it.",
      "Stems ending in -t/-d keep the -e: Arbeite! Warte!",
      "For instructions in manuals German often uses the infinitive: Bitte Formular ausfüllen.",
    ],
    practice: [
      {
        id: "g-a2-8-p1",
        type: "transform",
        prompt: "Make a du imperative.",
        input: "Du hilfst mir.",
        answers: ["Hilf mir!"],
        explanation: "e → i is kept, no ending.",
      },
      {
        id: "g-a2-8-p2",
        type: "transform",
        prompt: "Make a polite Sie imperative.",
        input: "Sie warten hier.",
        answers: ["Warten Sie hier!", "Warten Sie bitte hier!"],
        explanation: "Verb + Sie.",
      },
      {
        id: "g-a2-8-p3",
        type: "multiple-choice",
        prompt: "___ bitte leise, das Baby schläft. (ihr)",
        options: ["Sei", "Seid", "Seien", "Sind"],
        answerIndex: 1,
        explanation: "ihr form of sein → Seid.",
      },
    ],
    quiz: [
      {
        id: "g-a2-8-q1",
        type: "fill-blank",
        prompt: "du imperative.",
        sentence: "___ (nehmen) den Bus und ___ (fahren) bis zum Hauptbahnhof.",
        answers: [["Nimm"], ["fahr", "Fahr"]],
        explanation: "nehmen: e → i; fahren loses the Umlaut.",
      },
      {
        id: "g-a2-8-q2",
        type: "true-false",
        prompt: "The ihr imperative looks exactly like the present tense form.",
        answer: true,
        explanation: "ihr kommt → Kommt!",
      },
    ],
    revision: [
      "du: stem only (keep e → i, drop Umlaut).",
      "ihr: present form. Sie: verb + Sie.",
      "sein: Sei! Seid! Seien Sie!",
    ],
    cheatSheet: [
      { label: "kommen", value: "Komm! Kommt! Kommen Sie!" },
      { label: "sprechen", value: "Sprich!" },
      { label: "fahren", value: "Fahr!" },
      { label: "sein", value: "Sei! Seid! Seien Sie!" },
      { label: "Politeness", value: "+ bitte / mal" },
    ],
    related: ["reflexive-verben", "modalverben"],
  },
];
