import type { GrammarTopic } from "@/lib/types";

export const b1Grammar: GrammarTopic[] = [
  {
    slug: "konjunktiv-2",
    level: "B1",
    category: "Mood",
    title: "Konjunktiv II — polite requests, wishes, hypotheses",
    titleDe: "Konjunktiv II",
    minutes: 35,
    simple:
      "Use würde + Infinitiv for most verbs, but real Konjunktiv II forms for sein (wäre), haben (hätte) and the modal verbs (könnte, müsste, dürfte, sollte, wollte).",
    detailed: [
      "Konjunktiv II expresses unreality: polite requests (Könnten Sie mir helfen?), wishes (Ich hätte gern …), advice (Du solltest mehr schlafen) and hypothetical conditions (Wenn ich Zeit hätte, würde ich mehr lesen).",
      "Formation: take the Präteritum stem and add the endings -e, -est, -e, -en, -et, -en; strong verbs add an Umlaut where possible (ich war → ich wäre, ich hatte → ich hätte, ich konnte → ich könnte, ich fuhr → ich führe). Because these forms sound old-fashioned for most verbs, modern German uses würde + Infinitiv instead: Ich würde gern nach Berlin fahren.",
      "The past Konjunktiv II uses hätte/wäre + Partizip II: Wenn ich mehr gelernt hätte, hätte ich die Prüfung bestanden. With modals: Ich hätte kommen können.",
    ],
    tables: [
      {
        title: "The forms you really need",
        headers: ["Verb", "Präteritum", "Konjunktiv II", "Example"],
        rows: [
          ["sein", "war", "wäre", "Das wäre super."],
          ["haben", "hatte", "hätte", "Ich hätte gern einen Kaffee."],
          ["werden", "wurde", "würde", "Ich würde gern mitkommen."],
          ["können", "konnte", "könnte", "Könnten Sie mir helfen?"],
          ["müssen", "musste", "müsste", "Ich müsste eigentlich lernen."],
          ["dürfen", "durfte", "dürfte", "Dürfte ich Sie etwas fragen?"],
          ["sollen", "sollte", "sollte", "Du solltest zum Arzt gehen."],
          ["wissen", "wusste", "wüsste", "Wenn ich das wüsste!"],
        ],
        highlightColumn: 2,
      },
      {
        title: "Functions",
        headers: ["Function", "Structure", "Example"],
        rows: [
          ["polite request", "Könnten / Würden Sie …?", "Könnten Sie das bitte wiederholen?"],
          ["wish (present)", "Ich hätte gern / Ich würde gern …", "Ich würde gern einen Termin vereinbaren."],
          ["advice", "Du solltest / An deiner Stelle würde ich …", "An deiner Stelle würde ich sofort anrufen."],
          ["unreal condition", "Wenn … Konjunktiv II, … würde/wäre/hätte", "Wenn ich reich wäre, würde ich reisen."],
          ["unreal past", "hätte/wäre + Partizip II", "Wenn ich das gewusst hätte, wäre ich nicht gekommen."],
          ["comparison", "als ob / als wäre", "Er tut so, als ob er alles wüsste."],
        ],
      },
    ],
    visuals: [
      {
        label: "Modern default",
        pattern: "würde + Infinitiv",
        parts: ["Ich", "würde", "gern eine Ausbildung", "machen."],
      },
      {
        label: "Unreal past",
        pattern: "hätte / wäre + Partizip II",
        parts: ["Ich", "hätte", "früher", "angefangen."],
      },
    ],
    examples: [
      { de: "Könnten Sie mir bitte den Weg zum Bahnhof zeigen?", en: "Could you please show me the way to the station?" },
      { de: "Wenn ich mehr Zeit hätte, würde ich einen Sprachkurs besuchen.", en: "If I had more time, I would take a language course." },
      { de: "Du solltest dich früher bewerben.", en: "You should apply earlier." },
      { de: "Wenn ich das gewusst hätte, hätte ich anders reagiert.", en: "If I had known that, I would have reacted differently." },
    ],
    mistakes: [
      { wrong: "Wenn ich Zeit hätte, ich würde kommen.", right: "Wenn ich Zeit hätte, würde ich kommen.", why: "After a fronted wenn-clause the verb comes first." },
      { wrong: "Ich würde gern ein Kaffee haben.", right: "Ich hätte gern einen Kaffee.", why: "With haben use hätte, and the noun is accusative." },
      { wrong: "Wenn ich das wüsste hätte …", right: "Wenn ich das gewusst hätte …", why: "Past Konjunktiv II = hätte + Partizip II." },
    ],
    tips: [
      "In exams, polite Konjunktiv II sentences instantly raise your register: Könnten Sie …? Ich würde vorschlagen, …",
      "Use the real forms only for sein, haben, werden, wissen and the modals; würde for everything else.",
      "In a wenn-clause the verb is last: Wenn ich Zeit hätte …",
    ],
    practice: [
      {
        id: "g-b1-1-p1",
        type: "transform",
        prompt: "Make the request polite.",
        input: "Können Sie mir helfen?",
        answers: ["Könnten Sie mir helfen?"],
        explanation: "können → könnte for politeness.",
      },
      {
        id: "g-b1-1-p2",
        type: "fill-blank",
        prompt: "Complete with Konjunktiv II.",
        sentence: "Wenn ich mehr Geld ___ (haben), ___ ich eine Weltreise ___ (machen).",
        answers: [["hätte"], ["würde"], ["machen"]],
        explanation: "hätte + würde … machen.",
      },
      {
        id: "g-b1-1-p3",
        type: "multiple-choice",
        prompt: "An deiner Stelle ___ ich sofort mit dem Chef sprechen.",
        options: ["werde", "würde", "wäre", "hätte"],
        answerIndex: 1,
        explanation: "Advice → würde + Infinitiv.",
      },
      {
        id: "g-b1-1-p4",
        type: "writing",
        prompt: "Write three polite requests you could make at the Ausländerbehörde.",
        minWords: 30,
        checklist: ["Konjunktiv II forms", "Sie-form", "bitte", "different verbs"],
        sampleAnswer:
          "Könnten Sie mir bitte sagen, welche Unterlagen ich brauche? Ich hätte gern einen Termin für nächste Woche. Wäre es möglich, das Formular per E-Mail zu schicken?",
      },
    ],
    quiz: [
      {
        id: "g-b1-1-q1",
        type: "multiple-choice",
        prompt: "Das ___ super!",
        options: ["wäre", "würde", "hätte", "sollte"],
        answerIndex: 0,
        explanation: "sein → wäre.",
      },
      {
        id: "g-b1-1-q2",
        type: "fill-blank",
        prompt: "Unreal past.",
        sentence: "Wenn du früher ___ (aufstehen / sein), ___ du den Zug nicht ___ (verpassen / haben).",
        answers: [["aufgestanden wärst"], ["hättest"], ["verpasst"]],
        explanation: "wäre + Partizip II / hätte + Partizip II.",
      },
      {
        id: "g-b1-1-q3",
        type: "true-false",
        prompt: "würde + Infinitiv is acceptable for most verbs in modern German.",
        answer: true,
        explanation: "Real forms survive mainly for sein, haben, werden, wissen and modals.",
      },
    ],
    revision: [
      "wäre, hätte, würde, könnte, müsste, dürfte, sollte, wüsste.",
      "würde + Infinitiv for all other verbs.",
      "Past: hätte/wäre + Partizip II.",
    ],
    cheatSheet: [
      { label: "sein", value: "wäre" },
      { label: "haben", value: "hätte" },
      { label: "können", value: "könnte" },
      { label: "müssen", value: "müsste" },
      { label: "sollen", value: "sollte" },
      { label: "other verbs", value: "würde + Infinitiv" },
    ],
    related: ["praeteritum", "passiv"],
  },
  {
    slug: "passiv",
    level: "B1",
    category: "Voice",
    title: "The passive voice",
    titleDe: "Das Passiv",
    minutes: 35,
    simple:
      "werden + Partizip II. The focus moves from the doer to the action: Das Formular wird ausgefüllt.",
    detailed: [
      "The Vorgangspassiv (process passive) uses werden + Partizip II. Present: Der Brief wird geschrieben. Präteritum: Der Brief wurde geschrieben. Perfekt: Der Brief ist geschrieben worden. With a modal: Der Brief muss geschrieben werden.",
      "The agent is optional and appears with von + Dativ (a person) or durch + Akkusativ (a means or cause): Das Haus wurde von einem Architekten geplant. Die Stadt wurde durch das Erdbeben zerstört.",
      "The Zustandspassiv (state passive) uses sein + Partizip II and describes the result: Das Geschäft ist geschlossen (state) vs. Das Geschäft wird um 18 Uhr geschlossen (action). If the active sentence has no accusative object, the passive uses impersonal es: Hier wird nicht geraucht.",
    ],
    tables: [
      {
        title: "Tenses of the passive",
        headers: ["Tense", "Structure", "Example"],
        rows: [
          ["Präsens", "wird + Partizip II", "Die Rechnung wird bezahlt."],
          ["Präteritum", "wurde + Partizip II", "Die Rechnung wurde bezahlt."],
          ["Perfekt", "ist + Partizip II + worden", "Die Rechnung ist bezahlt worden."],
          ["Plusquamperfekt", "war + Partizip II + worden", "Die Rechnung war bezahlt worden."],
          ["Futur I", "wird + Partizip II + werden", "Die Rechnung wird bezahlt werden."],
          ["with modal", "muss/kann + Partizip II + werden", "Die Rechnung muss heute bezahlt werden."],
          ["Zustandspassiv", "ist + Partizip II", "Die Rechnung ist bezahlt."],
        ],
        highlightColumn: 1,
      },
      {
        title: "Active → passive",
        headers: ["Aktiv", "Passiv"],
        rows: [
          ["Der Techniker reparierte das Gerät.", "Das Gerät wurde (von dem Techniker) repariert."],
          ["Man muss das Formular unterschreiben.", "Das Formular muss unterschrieben werden."],
          ["Die Firma hat mir eine Stelle angeboten.", "Mir ist eine Stelle angeboten worden."],
          ["Man arbeitet hier sehr schnell.", "Hier wird sehr schnell gearbeitet."],
        ],
      },
    ],
    visuals: [
      {
        label: "Transformation",
        pattern: "Akkusativobjekt → Subjekt · Subjekt → von + Dativ",
        parts: ["Man ruft den Kunden an.", "→", "Der Kunde wird angerufen."],
      },
    ],
    examples: [
      { de: "In Deutschland wird viel Wert auf Pünktlichkeit gelegt.", en: "In Germany a lot of importance is placed on punctuality." },
      { de: "Die Unterlagen müssen bis Freitag eingereicht werden.", en: "The documents must be submitted by Friday." },
      { de: "Das Museum wurde 1892 gebaut und 2015 renoviert.", en: "The museum was built in 1892 and renovated in 2015." },
      { de: "Der Laden ist sonntags geschlossen.", en: "The shop is closed on Sundays.", note: "State passive." },
    ],
    mistakes: [
      { wrong: "Das Formular wird ausfüllen.", right: "Das Formular wird ausgefüllt.", why: "The passive needs the Partizip II." },
      { wrong: "Die Rechnung ist bezahlt geworden.", right: "Die Rechnung ist bezahlt worden.", why: "In the passive Perfekt, geworden becomes worden." },
      { wrong: "Das Auto wurde durch meinem Vater repariert.", right: "… von meinem Vater repariert.", why: "Persons take von + Dativ." },
    ],
    tips: [
      "The passive is the register of official German — learn it for letters, reports and Goethe/TELC writing tasks.",
      "Modal + passive: modal conjugated, Partizip II + werden at the end.",
      "If there is no accusative object in the active sentence, start with es or a time expression: Es wird gebaut. / Hier wird gebaut.",
    ],
    practice: [
      {
        id: "g-b1-2-p1",
        type: "transform",
        prompt: "Rewrite in the passive.",
        input: "Man renoviert das Gebäude.",
        answers: ["Das Gebäude wird renoviert."],
        explanation: "man disappears, the accusative object becomes the subject.",
      },
      {
        id: "g-b1-2-p2",
        type: "transform",
        prompt: "Rewrite in the passive with a modal verb.",
        input: "Man muss die Formulare unterschreiben.",
        answers: ["Die Formulare müssen unterschrieben werden."],
        explanation: "Modal + Partizip II + werden.",
      },
      {
        id: "g-b1-2-p3",
        type: "multiple-choice",
        prompt: "Der Vertrag ___ letzte Woche unterschrieben.",
        options: ["wird", "wurde", "ist", "hat"],
        answerIndex: 1,
        explanation: "Past process → wurde.",
      },
      {
        id: "g-b1-2-p4",
        type: "fill-blank",
        prompt: "Passive Perfekt.",
        sentence: "Die Wohnung ___ schon ___ (vermieten) ___.",
        answers: [["ist"], ["vermietet"], ["worden"]],
        explanation: "ist + Partizip II + worden.",
      },
    ],
    quiz: [
      {
        id: "g-b1-2-q1",
        type: "multiple-choice",
        prompt: "Hier ___ nicht geraucht.",
        options: ["wird", "ist", "werden", "hat"],
        answerIndex: 0,
        explanation: "Impersonal passive with wird.",
      },
      {
        id: "g-b1-2-q2",
        type: "true-false",
        prompt: "sein + Partizip II describes a state, not an action.",
        answer: true,
        explanation: "Zustandspassiv: Das Fenster ist geöffnet.",
      },
      {
        id: "g-b1-2-q3",
        type: "transform",
        prompt: "Name the agent with von.",
        input: "Das Projekt wurde geleitet. (Frau Meier)",
        answers: ["Das Projekt wurde von Frau Meier geleitet."],
        explanation: "Persons: von + Dativ.",
      },
    ],
    revision: [
      "werden + Partizip II; Perfekt uses worden.",
      "Agent: von + Dativ (person), durch + Akkusativ (cause).",
      "Modal: … + Partizip II + werden.",
    ],
    cheatSheet: [
      { label: "Präsens", value: "wird gemacht" },
      { label: "Präteritum", value: "wurde gemacht" },
      { label: "Perfekt", value: "ist gemacht worden" },
      { label: "Modal", value: "muss gemacht werden" },
      { label: "Zustand", value: "ist gemacht" },
    ],
    related: ["passiversatzformen", "konjunktiv-2"],
  },
  {
    slug: "relativsaetze",
    level: "B1",
    category: "Sentence structure",
    title: "Relative clauses",
    titleDe: "Relativsätze",
    minutes: 30,
    simple:
      "The relative pronoun matches the gender and number of the noun it describes, but its case comes from its role inside the relative clause. The verb goes to the end.",
    detailed: [
      "Relative pronouns are almost identical to definite articles: der, die, das, die (Pl.); Akkusativ den, die, das, die; Dativ dem, der, dem, denen; Genitiv dessen, deren, dessen, deren.",
      "Two questions decide the form: which noun am I describing (gender/number) and what role does the pronoun play in the relative clause (case)? Der Mann, der dort steht (subject → Nominativ). Der Mann, den ich kenne (object → Akkusativ). Der Mann, dem ich helfe (helfen + Dativ).",
      "Prepositions come before the pronoun: die Kollegin, mit der ich arbeite. For places you can use wo: die Stadt, wo ich wohne (= in der ich wohne). was refers to whole ideas: Er kam zu spät, was mich geärgert hat.",
    ],
    tables: [
      {
        title: "Relative pronouns",
        headers: ["Kasus", "maskulin", "feminin", "neutrum", "Plural"],
        rows: [
          ["Nominativ", "der", "die", "das", "die"],
          ["Akkusativ", "den", "die", "das", "die"],
          ["Dativ", "dem", "der", "dem", "denen"],
          ["Genitiv", "dessen", "deren", "dessen", "deren"],
        ],
        highlightColumn: 3,
        note: "Only the dative plural (denen) and the genitive forms differ from the definite articles.",
      },
    ],
    visuals: [
      {
        label: "Two decisions",
        pattern: "Genus/Numerus vom Bezugswort · Kasus von der Funktion",
        parts: ["die Frau (f)", "+", "Objekt (Akk.)", "→", "die Frau, die ich kenne"],
      },
    ],
    examples: [
      { de: "Das ist der Kollege, der mir bei der Bewerbung geholfen hat.", en: "That's the colleague who helped me with my application." },
      { de: "Die Wohnung, die wir gemietet haben, liegt im Zentrum.", en: "The flat we rented is in the centre." },
      { de: "Der Chef, mit dem ich gesprochen habe, war sehr freundlich.", en: "The boss I spoke to was very friendly." },
      { de: "Die Studenten, deren Prüfung morgen ist, sind nervös.", en: "The students whose exam is tomorrow are nervous." },
    ],
    mistakes: [
      { wrong: "Das Buch, das ich lese es, ist spannend.", right: "Das Buch, das ich lese, ist spannend.", why: "The relative pronoun already is the object; no extra pronoun." },
      { wrong: "Die Leute, die ich helfe", right: "Die Leute, denen ich helfe", why: "helfen takes the dative; plural dative is denen." },
      { wrong: "Der Mann, wo dort steht", right: "Der Mann, der dort steht", why: "wo is only for places, not people." },
    ],
    tips: [
      "Say the sentence twice: first as two separate sentences, then merge.",
      "denen is the only surprising form — memorise it.",
      "In writing, relative clauses make your German sound far more advanced than two short sentences.",
    ],
    practice: [
      {
        id: "g-b1-3-p1",
        type: "fill-blank",
        prompt: "Insert the relative pronoun.",
        sentence: "Das ist die Firma, ___ mich eingeladen hat. Der Kollege, ___ ich kennengelernt habe, ist Marokkaner.",
        answers: [["die"], ["den"]],
        explanation: "Subject feminine → die; object masculine → den.",
      },
      {
        id: "g-b1-3-p2",
        type: "fill-blank",
        prompt: "Insert the relative pronoun.",
        sentence: "Die Nachbarn, ___ ich oft helfe, sind sehr nett.",
        answers: [["denen"]],
        explanation: "helfen + Dativ Plural → denen.",
      },
      {
        id: "g-b1-3-p3",
        type: "transform",
        prompt: "Combine into one sentence with a relative clause.",
        input: "Ich habe einen Kurs gefunden. Der Kurs beginnt im September.",
        answers: ["Ich habe einen Kurs gefunden, der im September beginnt."],
        explanation: "Subject of the second sentence → der.",
      },
    ],
    quiz: [
      {
        id: "g-b1-3-q1",
        type: "multiple-choice",
        prompt: "Der Zug, ___ ich genommen habe, hatte Verspätung.",
        options: ["der", "den", "dem", "dessen"],
        answerIndex: 1,
        explanation: "Object of nehmen → Akkusativ den.",
      },
      {
        id: "g-b1-3-q2",
        type: "multiple-choice",
        prompt: "Die Stadt, in ___ ich wohne, ist klein.",
        options: ["die", "der", "dem", "denen"],
        answerIndex: 1,
        explanation: "in + Dativ feminine → der.",
      },
      {
        id: "g-b1-3-q3",
        type: "true-false",
        prompt: "The verb in a relative clause stands at the end.",
        answer: true,
        explanation: "Relative clauses are subordinate clauses.",
      },
    ],
    revision: [
      "Gender/number from the noun, case from the function.",
      "Dativ Plural = denen; Genitiv = dessen/deren.",
      "Preposition + relative pronoun: mit dem, für die, in der.",
    ],
    cheatSheet: [
      { label: "Nom.", value: "der, die, das, die" },
      { label: "Akk.", value: "den, die, das, die" },
      { label: "Dat.", value: "dem, der, dem, denen" },
      { label: "Gen.", value: "dessen, deren, dessen, deren" },
      { label: "Places", value: "wo / in der / in dem" },
    ],
    related: ["nebensaetze-a2", "genitiv"],
  },
  {
    slug: "genitiv",
    level: "B1",
    category: "Cases",
    title: "The genitive case",
    titleDe: "Der Genitiv",
    minutes: 25,
    simple:
      "The genitive shows possession and relationships: des Mannes, der Frau, des Kindes, der Kinder. In speech people often use von + Dativ instead.",
    detailed: [
      "Masculine and neuter nouns add -s or -es in the genitive singular: der Titel des Buches, das Auto des Vaters. Feminine and plural nouns do not change: die Farbe der Tür, die Namen der Kinder.",
      "Names take an -s without an apostrophe: Annas Bruder, Deutschlands Hauptstadt. Written and formal German prefers the genitive; spoken German often replaces it: das Auto von meinem Bruder.",
      "Some prepositions govern the genitive and appear frequently in formal texts: wegen, während, trotz, statt, aufgrund, innerhalb, außerhalb, anstelle, mithilfe.",
    ],
    tables: [
      {
        title: "Genitive forms",
        headers: ["Genus", "Artikel", "Beispiel"],
        rows: [
          ["maskulin", "des …-(e)s", "der Chef des Unternehmens"],
          ["feminin", "der", "die Adresse der Firma"],
          ["neutrum", "des …-(e)s", "das Ende des Films"],
          ["Plural", "der", "die Rechte der Arbeitnehmer"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Genitive prepositions",
        headers: ["Präposition", "Meaning", "Example"],
        rows: [
          ["wegen", "because of", "wegen des Wetters"],
          ["während", "during", "während der Arbeitszeit"],
          ["trotz", "despite", "trotz der Probleme"],
          ["statt / anstelle", "instead of", "statt eines Anrufs"],
          ["aufgrund", "due to", "aufgrund der Nachfrage"],
          ["innerhalb / außerhalb", "inside / outside (of)", "innerhalb einer Woche"],
        ],
      },
    ],
    visuals: [
      {
        label: "Formal vs. spoken",
        pattern: "des Vaters ↔ von dem Vater",
        parts: ["das Auto des Vaters", "das Auto von meinem Vater"],
      },
    ],
    examples: [
      { de: "Der Chef der Firma heißt Herr Weber.", en: "The company's boss is Mr Weber." },
      { de: "Wegen des schlechten Wetters bleibt der Markt geschlossen.", en: "Because of the bad weather the market stays closed." },
      { de: "Innerhalb einer Woche müssen Sie die Unterlagen einreichen.", en: "You must submit the documents within a week." },
      { de: "Das ist Annas Lebenslauf.", en: "That's Anna's CV." },
    ],
    mistakes: [
      { wrong: "das Auto von der Vater", right: "das Auto des Vaters / von dem Vater", why: "von always takes the dative: von dem Vater." },
      { wrong: "wegen dem Wetter (formal writing)", right: "wegen des Wetters", why: "wegen governs the genitive in standard written German." },
      { wrong: "Anna's Bruder", right: "Annas Bruder", why: "German uses no apostrophe for the genitive of names." },
    ],
    tips: [
      "In Goethe/TELC writing tasks, genitive prepositions raise your score: aufgrund, während, trotz.",
      "One-syllable masculine/neuter nouns usually take -es: des Kindes, des Tages.",
      "You can always fall back on von + Dativ when speaking.",
    ],
    practice: [
      {
        id: "g-b1-4-p1",
        type: "fill-blank",
        prompt: "Complete with the genitive.",
        sentence: "Das ist das Büro ___ Direktors und das Zimmer ___ Sekretärin.",
        answers: [["des"], ["der"]],
        explanation: "maskulin des …-s, feminin der.",
      },
      {
        id: "g-b1-4-p2",
        type: "transform",
        prompt: "Rewrite formally with the genitive.",
        input: "die Tür von dem Haus",
        answers: ["die Tür des Hauses"],
        explanation: "von dem Haus → des Hauses.",
      },
      {
        id: "g-b1-4-p3",
        type: "multiple-choice",
        prompt: "___ der Prüfung darf man nicht sprechen.",
        options: ["Während", "Wegen", "Trotz", "Statt"],
        answerIndex: 0,
        explanation: "Time span → während.",
      },
    ],
    quiz: [
      {
        id: "g-b1-4-q1",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Trotz ___ Regens (der Regen) sind wir spazieren gegangen.",
        answers: [["des"]],
        explanation: "trotz + Genitiv maskulin.",
      },
      {
        id: "g-b1-4-q2",
        type: "true-false",
        prompt: "Feminine nouns add -s in the genitive singular.",
        answer: false,
        explanation: "Only masculine and neuter nouns add -(e)s.",
      },
    ],
    revision: [
      "des …-(e)s / der / des …-(e)s / der.",
      "Genitive prepositions: wegen, während, trotz, statt, aufgrund, innerhalb.",
      "Spoken alternative: von + Dativ.",
    ],
    cheatSheet: [
      { label: "maskulin", value: "des Mannes" },
      { label: "feminin", value: "der Frau" },
      { label: "neutrum", value: "des Kindes" },
      { label: "Plural", value: "der Kinder" },
      { label: "Names", value: "Annas Buch" },
    ],
    related: ["relativsaetze", "nominalisierung"],
  },
  {
    slug: "verben-mit-praeposition",
    level: "B1",
    category: "Verbs",
    title: "Verbs with fixed prepositions + da-/wo- forms",
    titleDe: "Verben mit Präpositionen, Präpositionaladverbien",
    minutes: 30,
    simple:
      "Many verbs require a fixed preposition and case: warten auf + Akk., sich interessieren für + Akk., helfen bei + Dat. Questions use worauf/wofür, answers use darauf/dafür.",
    detailed: [
      "The preposition is part of the verb's meaning and cannot be guessed from English. Learn them in chunks with an example sentence: Ich warte auf den Bus. Ich denke an meine Familie. Ich freue mich über das Geschenk.",
      "To ask about a thing, combine wo(r)- + preposition: Worauf wartest du? Woran denkst du? To ask about a person, use the preposition + question word: Auf wen wartest du? An wen denkst du?",
      "To refer back to a thing, use da(r)- + preposition: Ich warte darauf. These da-forms also anticipate a following clause: Ich freue mich darauf, dass du kommst. / Ich denke daran, eine Ausbildung zu machen.",
    ],
    tables: [
      {
        title: "High-frequency verbs",
        headers: ["Verb + Präposition", "Kasus", "Example"],
        rows: [
          ["warten auf", "Akkusativ", "Ich warte auf die Antwort."],
          ["sich freuen auf / über", "Akkusativ", "Ich freue mich auf den Kurs. / über das Geschenk."],
          ["denken an", "Akkusativ", "Ich denke oft an meine Familie."],
          ["sich interessieren für", "Akkusativ", "Sie interessiert sich für Medizin."],
          ["sich bewerben um / bei", "Akkusativ / Dativ", "Ich bewerbe mich um eine Stelle bei BMW."],
          ["sprechen mit / über", "Dativ / Akkusativ", "Ich spreche mit dem Chef über das Projekt."],
          ["helfen bei", "Dativ", "Er hilft mir bei den Hausaufgaben."],
          ["sich kümmern um", "Akkusativ", "Ich kümmere mich um die Kinder."],
          ["Angst haben vor", "Dativ", "Ich habe Angst vor der Prüfung."],
          ["teilnehmen an", "Dativ", "Wir nehmen an dem Seminar teil."],
          ["achten auf", "Akkusativ", "Achten Sie auf die Aussprache."],
          ["sich gewöhnen an", "Akkusativ", "Ich habe mich an das Wetter gewöhnt."],
        ],
      },
      {
        title: "wo- and da- forms",
        headers: ["Referring to", "Question", "Answer"],
        rows: [
          ["a thing", "Worauf wartest du?", "Ich warte darauf."],
          ["a thing", "Wofür interessierst du dich?", "Ich interessiere mich dafür."],
          ["a person", "Auf wen wartest du?", "Ich warte auf ihn."],
          ["a clause", "—", "Ich freue mich darauf, dass du kommst."],
        ],
        note: "Insert -r- when the preposition begins with a vowel: worauf, woran, darauf, daran, darüber.",
      },
    ],
    visuals: [
      {
        label: "Chunk learning",
        pattern: "Verb + Präposition + Kasus",
        parts: ["sich bewerben", "um", "+ Akkusativ"],
      },
    ],
    examples: [
      { de: "Ich habe mich um einen Ausbildungsplatz bei Bosch beworben.", en: "I applied for a training place at Bosch." },
      { de: "Worüber habt ihr gesprochen? — Über die neuen Arbeitszeiten.", en: "What did you talk about? — About the new working hours." },
      { de: "Ich freue mich darauf, meine Kollegen kennenzulernen.", en: "I'm looking forward to getting to know my colleagues." },
      { de: "Bitte achten Sie auf die Sicherheitsvorschriften.", en: "Please pay attention to the safety regulations." },
    ],
    mistakes: [
      { wrong: "Ich warte für den Bus.", right: "Ich warte auf den Bus.", why: "warten auf is fixed." },
      { wrong: "Wo denkst du?", right: "Woran denkst du?", why: "Question about a thing needs wo(r)- + preposition." },
      { wrong: "Ich freue mich für dich zu sehen.", right: "Ich freue mich darauf, dich zu sehen.", why: "The da-form announces the infinitive clause." },
    ],
    tips: [
      "Keep a two-column list in your notes: verb + preposition | example sentence.",
      "Whenever you meet a new verb, write down which preposition it takes.",
      "The da-form + dass/zu construction is a fast way to sound B1+.",
    ],
    practice: [
      {
        id: "g-b1-5-p1",
        type: "fill-blank",
        prompt: "Insert the correct preposition and article.",
        sentence: "Ich interessiere mich ___ Technik und bewerbe mich ___ eine Ausbildung.",
        answers: [["für"], ["um"]],
        explanation: "sich interessieren für, sich bewerben um.",
      },
      {
        id: "g-b1-5-p2",
        type: "multiple-choice",
        prompt: "___ hast du Angst? — Vor der Prüfung.",
        options: ["Wovor", "Worauf", "Worüber", "Wofür"],
        answerIndex: 0,
        explanation: "Angst haben vor → wovor.",
      },
      {
        id: "g-b1-5-p3",
        type: "transform",
        prompt: "Replace the phrase with a da-form.",
        input: "Ich denke oft an meine Zukunft.",
        answers: ["Ich denke oft daran."],
        explanation: "an + thing → daran.",
      },
    ],
    quiz: [
      {
        id: "g-b1-5-q1",
        type: "multiple-choice",
        prompt: "Wir nehmen ___ dem Deutschkurs teil.",
        options: ["auf", "an", "über", "für"],
        answerIndex: 1,
        explanation: "teilnehmen an + Dativ.",
      },
      {
        id: "g-b1-5-q2",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Ich freue mich ___, dass du kommst.",
        answers: [["darauf"]],
        explanation: "sich freuen auf → darauf + dass-clause.",
      },
    ],
    revision: [
      "Learn verb + preposition + case as one unit.",
      "Things: wo(r)- / da(r)- forms. People: preposition + wen/wem, ihn/ihm.",
      "da-forms can announce a dass- or zu-clause.",
    ],
    cheatSheet: [
      { label: "warten", value: "auf + Akk." },
      { label: "denken", value: "an + Akk." },
      { label: "sich freuen", value: "auf/über + Akk." },
      { label: "helfen", value: "bei + Dat." },
      { label: "Angst haben", value: "vor + Dat." },
      { label: "teilnehmen", value: "an + Dat." },
    ],
    related: ["reflexive-verben", "indirekte-fragen"],
  },
  {
    slug: "indirekte-fragen",
    level: "B1",
    category: "Sentence structure",
    title: "Indirect questions and infinitive clauses",
    titleDe: "Indirekte Fragen und Infinitivsätze mit zu",
    minutes: 25,
    simple:
      "Indirect questions keep the question word (or use ob) and send the verb to the end. Infinitive clauses use zu + Infinitiv at the end.",
    detailed: [
      "Indirect questions are polite and typical of service situations: Können Sie mir sagen, wo der Bahnhof ist? Ich weiß nicht, ob der Zug pünktlich kommt. The verb is always final.",
      "Infinitive clauses with zu follow verbs and expressions such as versuchen, vergessen, anfangen, beginnen, hoffen, planen, vorhaben, Lust haben, es ist wichtig/möglich: Ich habe vor, eine Ausbildung zu machen. With separable verbs, zu goes inside: anzufangen, einzukaufen.",
      "Three special constructions: um … zu (purpose), ohne … zu (without doing), statt … zu (instead of doing). Ich lerne Deutsch, um in Deutschland zu arbeiten. Note that um … zu is only possible when both clauses have the same subject; otherwise use damit.",
    ],
    tables: [
      {
        title: "Direct → indirect question",
        headers: ["Direct", "Indirect"],
        rows: [
          ["Wo ist die Post?", "Können Sie mir sagen, wo die Post ist?"],
          ["Wann fährt der Zug?", "Ich möchte wissen, wann der Zug fährt."],
          ["Kommt er heute?", "Ich weiß nicht, ob er heute kommt."],
          ["Haben Sie Zeit?", "Darf ich fragen, ob Sie Zeit haben?"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Infinitive constructions",
        headers: ["Structure", "Meaning", "Example"],
        rows: [
          ["zu + Infinitiv", "complement", "Ich hoffe, bald anzufangen."],
          ["um … zu", "purpose (same subject)", "Ich lerne Deutsch, um zu studieren."],
          ["damit", "purpose (different subject)", "Ich erkläre es, damit du es verstehst."],
          ["ohne … zu", "without doing", "Er ging, ohne sich zu verabschieden."],
          ["statt … zu", "instead of doing", "Statt zu lernen, hat er gespielt."],
        ],
      },
    ],
    visuals: [
      {
        label: "Politeness formula",
        pattern: "Können Sie mir sagen, + W-Wort + … + Verb?",
        parts: ["Können Sie mir sagen,", "wann", "der nächste Bus", "fährt?"],
      },
    ],
    examples: [
      { de: "Können Sie mir sagen, wo ich das Formular abgeben muss?", en: "Can you tell me where I have to hand in the form?" },
      { de: "Ich habe vor, im September mit der Ausbildung anzufangen.", en: "I intend to start the training in September." },
      { de: "Ich lerne jeden Tag, um die B1-Prüfung zu bestehen.", en: "I study every day in order to pass the B1 exam." },
      { de: "Er ist gegangen, ohne etwas zu sagen.", en: "He left without saying anything." },
    ],
    mistakes: [
      { wrong: "Können Sie mir sagen, wo ist der Bahnhof?", right: "…, wo der Bahnhof ist?", why: "Indirect questions are verb-final." },
      { wrong: "Ich hoffe zu kommen bald.", right: "Ich hoffe, bald zu kommen.", why: "zu + Infinitiv closes the clause." },
      { wrong: "Ich lerne Deutsch, um meine Familie kann mitkommen.", right: "…, damit meine Familie mitkommen kann.", why: "Different subjects require damit." },
    ],
    tips: [
      "Start service questions with Können Sie mir sagen, … / Wissen Sie, … — examiners love it.",
      "With separable verbs zu goes between prefix and stem: aufzustehen.",
      "um … zu answers wozu? (what for?).",
    ],
    practice: [
      {
        id: "g-b1-6-p1",
        type: "transform",
        prompt: "Make the question indirect.",
        input: "Wann beginnt der Kurs?",
        answers: ["Können Sie mir sagen, wann der Kurs beginnt?", "Ich möchte wissen, wann der Kurs beginnt."],
        explanation: "Verb-final.",
      },
      {
        id: "g-b1-6-p2",
        type: "transform",
        prompt: "Join with um … zu.",
        input: "Ich mache einen Sprachkurs. Ich will besser sprechen.",
        answers: ["Ich mache einen Sprachkurs, um besser zu sprechen."],
        explanation: "Same subject → um … zu.",
      },
      {
        id: "g-b1-6-p3",
        type: "multiple-choice",
        prompt: "Ich weiß nicht, ___ er heute kommt.",
        options: ["dass", "ob", "wenn", "was"],
        answerIndex: 1,
        explanation: "Indirect yes/no question → ob.",
      },
    ],
    quiz: [
      {
        id: "g-b1-6-q1",
        type: "fill-blank",
        prompt: "Complete with zu where necessary.",
        sentence: "Ich habe vergessen, das Formular ___ (ausfüllen).",
        answers: [["auszufüllen"]],
        explanation: "zu goes inside separable verbs.",
      },
      {
        id: "g-b1-6-q2",
        type: "true-false",
        prompt: "um … zu can be used when the two clauses have different subjects.",
        answer: false,
        explanation: "Use damit instead.",
      },
    ],
    revision: [
      "Indirect question: question word or ob + verb-final.",
      "zu + Infinitiv at the end; inside separable verbs.",
      "um…zu (same subject) vs. damit (different subject).",
    ],
    cheatSheet: [
      { label: "Polite", value: "Können Sie mir sagen, …?" },
      { label: "Yes/no", value: "ob" },
      { label: "Purpose", value: "um … zu / damit" },
      { label: "Negative", value: "ohne … zu" },
      { label: "Alternative", value: "statt … zu" },
    ],
    related: ["nebensaetze-a2", "verben-mit-praeposition"],
  },
  {
    slug: "zweiteilige-konnektoren",
    level: "B1",
    category: "Sentence structure",
    title: "Two-part connectors",
    titleDe: "Zweiteilige Konnektoren",
    minutes: 20,
    simple:
      "Pairs like entweder … oder, sowohl … als auch, weder … noch, nicht nur … sondern auch, je … desto make your German more precise and more fluent.",
    detailed: [
      "These connectors link two elements of equal weight. Word order stays normal, except after je … desto, where the je-clause is verb-final and the desto-clause starts with the comparative: Je mehr ich lese, desto besser verstehe ich.",
      "weder … noch is already negative, so no additional nicht or kein is needed: Ich habe weder Zeit noch Geld.",
      "nicht nur … sondern auch is the strongest structure for writing tasks: Die Stadt ist nicht nur schön, sondern auch günstig.",
    ],
    tables: [
      {
        title: "The connectors",
        headers: ["Connector", "Meaning", "Example"],
        rows: [
          ["entweder … oder", "either … or", "Entweder fahren wir mit dem Zug oder wir fliegen."],
          ["sowohl … als auch", "both … and", "Sie spricht sowohl Arabisch als auch Deutsch."],
          ["weder … noch", "neither … nor", "Ich habe weder Zeit noch Lust."],
          ["nicht nur … sondern auch", "not only … but also", "Er ist nicht nur fleißig, sondern auch freundlich."],
          ["zwar … aber", "admittedly … but", "Die Wohnung ist zwar klein, aber sehr günstig."],
          ["je … desto/umso", "the … the", "Je früher du kommst, desto besser."],
        ],
      },
    ],
    visuals: [
      {
        label: "je … desto",
        pattern: "Je + Komparativ … Verb, desto + Komparativ + Verb + Subjekt",
        parts: ["Je mehr ich übe,", "desto sicherer", "werde ich."],
      },
    ],
    examples: [
      { de: "Ich möchte nicht nur die Sprache lernen, sondern auch die Kultur verstehen.", en: "I want not only to learn the language but also to understand the culture." },
      { de: "Sowohl die Bezahlung als auch die Arbeitszeiten sind gut.", en: "Both the pay and the working hours are good." },
      { de: "Je länger ich in Deutschland lebe, desto wohler fühle ich mich.", en: "The longer I live in Germany, the more comfortable I feel." },
      { de: "Zwar ist die Miete hoch, aber die Lage ist perfekt.", en: "The rent is high, admittedly, but the location is perfect." },
    ],
    mistakes: [
      { wrong: "Ich habe weder Zeit noch kein Geld.", right: "Ich habe weder Zeit noch Geld.", why: "weder … noch is already negative." },
      { wrong: "Je mehr ich lerne, desto ich verstehe besser.", right: "Je mehr ich lerne, desto besser verstehe ich.", why: "desto is followed directly by the comparative, then the verb." },
      { wrong: "nicht nur … aber auch", right: "nicht nur … sondern auch", why: "The fixed partner of nicht nur is sondern auch." },
    ],
    tips: [
      "Use one or two of these in every written exam task — they signal B1/B2 range.",
      "sowohl … als auch always takes a plural verb: Sowohl er als auch ich sind müde.",
      "zwar … aber is perfect for balanced arguments in a discussion.",
    ],
    practice: [
      {
        id: "g-b1-7-p1",
        type: "fill-blank",
        prompt: "Complete the connector.",
        sentence: "Ich spreche ___ Französisch ___ ___ Deutsch.",
        answers: [["sowohl"], ["als"], ["auch"]],
        explanation: "sowohl … als auch.",
      },
      {
        id: "g-b1-7-p2",
        type: "order",
        prompt: "Build the sentence.",
        tokens: ["Je", "früher", "du", "anfängst,", "desto", "mehr", "schaffst", "du"],
        answer: "Je früher du anfängst, desto mehr schaffst du",
        explanation: "je-clause verb-final, desto + comparative + verb + subject.",
      },
      {
        id: "g-b1-7-p3",
        type: "multiple-choice",
        prompt: "Er hat ___ Zeit ___ Geld für Urlaub.",
        options: ["weder / noch", "entweder / oder", "sowohl / als auch", "nicht nur / sondern auch"],
        answerIndex: 0,
        explanation: "Both are missing → weder … noch.",
      },
    ],
    quiz: [
      {
        id: "g-b1-7-q1",
        type: "fill-blank",
        prompt: "Complete.",
        sentence: "Die Wohnung ist ___ teuer, ___ sie ist sehr zentral.",
        answers: [["zwar"], ["aber"]],
        explanation: "zwar … aber.",
      },
      {
        id: "g-b1-7-q2",
        type: "true-false",
        prompt: "nicht nur is followed by aber auch.",
        answer: false,
        explanation: "It is followed by sondern auch.",
      },
    ],
    revision: [
      "entweder…oder, sowohl…als auch, weder…noch, nicht nur…sondern auch, zwar…aber, je…desto.",
      "weder…noch needs no extra negation.",
      "je-clause is verb-final.",
    ],
    cheatSheet: [
      { label: "either/or", value: "entweder … oder" },
      { label: "both/and", value: "sowohl … als auch" },
      { label: "neither/nor", value: "weder … noch" },
      { label: "not only", value: "nicht nur … sondern auch" },
      { label: "the…the", value: "je … desto" },
    ],
    related: ["nebensaetze-a2", "komparativ-superlativ"],
  },
];
