import type { GrammarTopic } from "@/lib/types";

export const b2Grammar: GrammarTopic[] = [
  {
    slug: "konjunktiv-1-indirekte-rede",
    level: "B2",
    category: "Mood",
    title: "Konjunktiv I and reported speech",
    titleDe: "Konjunktiv I und indirekte Rede",
    minutes: 30,
    simple:
      "Journalism and academic writing report other people's words with Konjunktiv I: Der Minister sagte, er sei zuversichtlich.",
    detailed: [
      "Konjunktiv I is formed from the infinitive stem + -e, -est, -e, -en, -et, -en. The most important form by far is the 3rd person singular: er sei, er habe, er komme, er müsse, er werde. sein is irregular and highly frequent: ich sei, du seist, er sei, wir seien.",
      "When the Konjunktiv I form is identical to the indicative (mostly in the plural: sie kommen), speakers switch to Konjunktiv II: sie kämen, or use würde + Infinitiv.",
      "Reported speech in the past always uses habe/sei + Partizip II, regardless of the original tense: Er sagte, er habe die Prüfung bestanden. Er sagte, er sei angekommen. Reported questions keep ob or the question word, reported imperatives use sollen: Sie sagte, ich solle warten.",
    ],
    tables: [
      {
        title: "Konjunktiv I of key verbs (3rd person singular)",
        headers: ["Infinitiv", "Indikativ", "Konjunktiv I"],
        rows: [
          ["sein", "er ist", "er sei"],
          ["haben", "er hat", "er habe"],
          ["werden", "er wird", "er werde"],
          ["können", "er kann", "er könne"],
          ["müssen", "er muss", "er müsse"],
          ["wissen", "er weiß", "er wisse"],
          ["kommen", "er kommt", "er komme"],
          ["gehen", "er geht", "er gehe"],
        ],
        highlightColumn: 2,
      },
      {
        title: "Direct → reported speech",
        headers: ["Direkte Rede", "Indirekte Rede"],
        rows: [
          ['"Ich bin müde."', "Er sagte, er sei müde."],
          ['"Ich habe keine Zeit."', "Sie erklärte, sie habe keine Zeit."],
          ['"Ich habe die Prüfung bestanden."', "Er berichtete, er habe die Prüfung bestanden."],
          ['"Kommst du mit?"', "Sie fragte, ob ich mitkomme / mitkäme."],
          ['"Warte hier!"', "Er sagte, ich solle hier warten."],
          ['"Wir gehen nach Hause."', "Sie sagten, sie gingen / würden nach Hause gehen."],
        ],
      },
    ],
    visuals: [
      {
        label: "Reporting frame",
        pattern: "Verb des Sagens + (dass) + Konjunktiv I",
        parts: ["Der Sprecher betonte,", "die Lage", "sei", "stabil."],
      },
    ],
    examples: [
      { de: "Die Firma teilte mit, sie werde 200 neue Stellen schaffen.", en: "The company announced it would create 200 new jobs." },
      { de: "Der Arzt sagte, ich solle mich ausruhen.", en: "The doctor said I should rest." },
      { de: "Laut dem Bericht habe die Nachfrage stark zugenommen.", en: "According to the report, demand has increased sharply." },
      { de: "Sie behauptete, sie hätte nichts davon gewusst.", en: "She claimed she had known nothing about it." },
    ],
    mistakes: [
      { wrong: "Er sagte, er ist krank. (formal writing)", right: "Er sagte, er sei krank.", why: "Written reported speech uses Konjunktiv I." },
      { wrong: "Sie sagte, sie hat die Prüfung bestanden.", right: "Sie sagte, sie habe die Prüfung bestanden.", why: "Reported past = habe + Partizip II." },
      { wrong: "Er fragte, kommst du mit?", right: "Er fragte, ob ich mitkomme.", why: "Reported questions are verb-final with ob." },
    ],
    tips: [
      "For the exam you mainly need sei, habe, werde, könne, müsse — the 3rd person singular.",
      "If the form looks like the indicative, use Konjunktiv II or würde.",
      "Signal phrases: laut + Dativ, nach Angaben von, angeblich, es wird berichtet, dass …",
    ],
    practice: [
      {
        id: "g-b2-1-p1",
        type: "transform",
        prompt: "Report the statement.",
        input: '"Ich bin mit dem Ergebnis zufrieden."',
        answers: ["Er sagte, er sei mit dem Ergebnis zufrieden."],
        explanation: "sein → sei.",
      },
      {
        id: "g-b2-1-p2",
        type: "transform",
        prompt: "Report the past statement.",
        input: '"Ich habe den Vertrag unterschrieben."',
        answers: ["Sie sagte, sie habe den Vertrag unterschrieben."],
        explanation: "habe + Partizip II.",
      },
      {
        id: "g-b2-1-p3",
        type: "multiple-choice",
        prompt: "Der Minister erklärte, die Reform ___ notwendig.",
        options: ["ist", "sei", "wäre gewesen", "war"],
        answerIndex: 1,
        explanation: "Konjunktiv I sei.",
      },
    ],
    quiz: [
      {
        id: "g-b2-1-q1",
        type: "fill-blank",
        prompt: "Complete with Konjunktiv I.",
        sentence: "Er sagte, er ___ (können) morgen nicht kommen und ___ (haben) viel zu tun.",
        answers: [["könne"], ["habe"]],
        explanation: "könne, habe.",
      },
      {
        id: "g-b2-1-q2",
        type: "true-false",
        prompt: "Reported imperatives use sollen.",
        answer: true,
        explanation: "Er sagte, ich solle warten.",
      },
    ],
    revision: [
      "Konjunktiv I stem + -e; sei is irregular.",
      "Past reported speech: habe/sei + Partizip II.",
      "Ambiguous forms → Konjunktiv II or würde.",
    ],
    cheatSheet: [
      { label: "sein", value: "er sei" },
      { label: "haben", value: "er habe" },
      { label: "werden", value: "er werde" },
      { label: "können", value: "er könne" },
      { label: "past", value: "habe/sei + Partizip II" },
      { label: "imperative", value: "solle" },
    ],
    related: ["konjunktiv-2", "nominalisierung"],
  },
  {
    slug: "partizipialattribute",
    level: "B2",
    category: "Attributes",
    title: "Participial attributes and extended attributes",
    titleDe: "Partizipialattribute und erweiterte Attribute",
    minutes: 30,
    simple:
      "Participles used as adjectives compress a whole relative clause: der lachende Mann (who is laughing), das reparierte Auto (which was repaired).",
    detailed: [
      "Partizip I (Infinitiv + d) has an active, simultaneous meaning: die steigenden Preise = die Preise, die steigen. Partizip II has a passive or completed meaning: die gestiegenen Preise = die Preise, die gestiegen sind; der unterschriebene Vertrag = der Vertrag, der unterschrieben wurde.",
      "Both take normal adjective endings. They can be expanded into long pre-noun blocks that are typical of academic and administrative German: die in den letzten Jahren stark gestiegenen Mietpreise.",
      "zu + Partizip I expresses necessity or possibility in the passive: die zu lösende Aufgabe = die Aufgabe, die gelöst werden muss. To read such structures, find the noun first, then unpack the block backwards into a relative clause.",
    ],
    tables: [
      {
        title: "Three attribute types",
        headers: ["Form", "Meaning", "Example", "Relative clause"],
        rows: [
          ["Partizip I (-d)", "active, ongoing", "das schlafende Kind", "das Kind, das schläft"],
          ["Partizip II", "passive / completed", "die reparierte Maschine", "die Maschine, die repariert wurde"],
          ["zu + Partizip I", "must/can be done", "die zu erledigende Aufgabe", "die Aufgabe, die erledigt werden muss"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Unpacking an extended attribute",
        headers: ["Compressed", "Unpacked"],
        rows: [
          [
            "die von der Regierung im Mai beschlossenen Maßnahmen",
            "die Maßnahmen, die von der Regierung im Mai beschlossen wurden",
          ],
          [
            "ein für Anfänger geeigneter Kurs",
            "ein Kurs, der für Anfänger geeignet ist",
          ],
          [
            "die immer weiter steigenden Kosten",
            "die Kosten, die immer weiter steigen",
          ],
        ],
      },
    ],
    visuals: [
      {
        label: "Reading strategy",
        pattern: "Artikel … [Block] … Nomen",
        parts: ["die", "von der Firma neu entwickelte", "Software"],
      },
    ],
    examples: [
      { de: "Die in Deutschland anerkannten Abschlüsse sind auf der Website aufgelistet.", en: "The qualifications recognised in Germany are listed on the website." },
      { de: "Wachsende Städte brauchen bezahlbaren Wohnraum.", en: "Growing cities need affordable housing." },
      { de: "Die zu unterschreibenden Unterlagen liegen auf dem Tisch.", en: "The documents to be signed are on the table." },
      { de: "Das vor zwei Jahren renovierte Gebäude wird heute eröffnet.", en: "The building renovated two years ago is being opened today." },
    ],
    mistakes: [
      { wrong: "der lachend Mann", right: "der lachende Mann", why: "The participle needs an adjective ending." },
      { wrong: "die repariert Maschine", right: "die reparierte Maschine", why: "Partizip II also takes endings." },
      { wrong: "die zu lösen Aufgabe", right: "die zu lösende Aufgabe", why: "zu + Partizip I + ending." },
    ],
    tips: [
      "In reading exams, always locate the noun at the end of the block first.",
      "In writing, one participial attribute per paragraph is elegant; three become unreadable.",
      "Partizip I = active, Partizip II = passive. Test with a relative clause.",
    ],
    practice: [
      {
        id: "g-b2-2-p1",
        type: "transform",
        prompt: "Compress into a participial attribute.",
        input: "die Preise, die stark steigen",
        answers: ["die stark steigenden Preise"],
        explanation: "Partizip I + ending.",
      },
      {
        id: "g-b2-2-p2",
        type: "transform",
        prompt: "Unpack into a relative clause.",
        input: "der von meinem Chef unterschriebene Vertrag",
        answers: ["der Vertrag, der von meinem Chef unterschrieben wurde"],
        explanation: "Partizip II → passive relative clause.",
      },
      {
        id: "g-b2-2-p3",
        type: "multiple-choice",
        prompt: "die ___ Aufgaben (must be done)",
        options: ["erledigenden", "zu erledigenden", "erledigten", "erledigend"],
        answerIndex: 1,
        explanation: "zu + Partizip I + ending.",
      },
    ],
    quiz: [
      {
        id: "g-b2-2-q1",
        type: "multiple-choice",
        prompt: "das ___ Kind (it is sleeping)",
        options: ["geschlafene", "schlafende", "zu schlafende", "schlafend"],
        answerIndex: 1,
        explanation: "Active, ongoing → Partizip I.",
      },
      {
        id: "g-b2-2-q2",
        type: "true-false",
        prompt: "Partizip II attributes usually have a passive meaning.",
        answer: true,
        explanation: "die geschriebene E-Mail = die E-Mail, die geschrieben wurde.",
      },
    ],
    revision: [
      "Partizip I = Infinitiv + d, active.",
      "Partizip II, passive/completed.",
      "zu + Partizip I = necessity/possibility.",
    ],
    cheatSheet: [
      { label: "lachen", value: "der lachende Mann" },
      { label: "reparieren", value: "das reparierte Auto" },
      { label: "lösen", value: "die zu lösende Aufgabe" },
      { label: "Test", value: "expand into a relative clause" },
    ],
    related: ["relativsaetze", "passiv"],
  },
  {
    slug: "passiversatzformen",
    level: "B2",
    category: "Voice",
    title: "Alternatives to the passive",
    titleDe: "Passiversatzformen",
    minutes: 25,
    simple:
      "man, sich lassen, sein + zu + Infinitiv and adjectives in -bar express passive meaning without werden.",
    detailed: [
      "Instead of Das Problem kann gelöst werden you can say: Man kann das Problem lösen. / Das Problem lässt sich lösen. / Das Problem ist zu lösen. / Das Problem ist lösbar. All four are common in written German and are regularly tested at B2.",
      "sich lassen + Infinitiv expresses possibility (kann gemacht werden). sein + zu + Infinitiv expresses possibility or necessity depending on context: Die Rechnung ist bis Freitag zu bezahlen (must be paid).",
      "Adjectives with -bar (machbar, lesbar, erreichbar) and -lich (verständlich, unverzichtbar) also carry passive-possibility meaning.",
    ],
    tables: [
      {
        title: "Four alternatives",
        headers: ["Structure", "Meaning", "Example"],
        rows: [
          ["man + Aktiv", "general agent", "Man löst das Problem schnell."],
          ["sich lassen + Infinitiv", "can be done", "Das Problem lässt sich schnell lösen."],
          ["sein + zu + Infinitiv", "can / must be done", "Das Formular ist auszufüllen."],
          ["Adjektiv auf -bar / -lich", "can be done", "Das Problem ist lösbar."],
        ],
        highlightColumn: 1,
      },
      {
        title: "Transformations",
        headers: ["Passiv mit Modalverb", "Ersatzform"],
        rows: [
          ["Der Text kann leicht gelesen werden.", "Der Text lässt sich leicht lesen. / ist leicht lesbar."],
          ["Die Frist muss eingehalten werden.", "Die Frist ist einzuhalten."],
          ["Das kann nicht geändert werden.", "Das lässt sich nicht ändern. / ist nicht änderbar."],
        ],
      },
    ],
    visuals: [
      {
        label: "Same meaning, four styles",
        pattern: "werden-Passiv ↔ man ↔ sich lassen ↔ sein + zu",
        parts: ["kann gemacht werden", "man kann machen", "lässt sich machen", "ist zu machen"],
      },
    ],
    examples: [
      { de: "Die Unterlagen sind bis zum 15. März einzureichen.", en: "The documents must be submitted by 15 March." },
      { de: "Dieses Problem lässt sich leicht beheben.", en: "This problem can easily be fixed." },
      { de: "Der Termin ist online buchbar.", en: "The appointment can be booked online." },
      { de: "In dieser Abteilung arbeitet man sehr selbstständig.", en: "In this department people work very independently." },
    ],
    mistakes: [
      { wrong: "Das Problem lässt lösen.", right: "Das Problem lässt sich lösen.", why: "The reflexive pronoun is obligatory." },
      { wrong: "Die Rechnung ist bezahlen.", right: "Die Rechnung ist zu bezahlen.", why: "zu is required." },
      { wrong: "Man kann das Problem gelöst werden.", right: "Man kann das Problem lösen.", why: "man takes an active infinitive." },
    ],
    tips: [
      "sein + zu + Infinitiv is the register of official notices — perfect for formal writing tasks.",
      "sich lassen is very frequent in spoken B2 German.",
      "Vary your structures in an essay instead of repeating werden.",
    ],
    practice: [
      {
        id: "g-b2-3-p1",
        type: "transform",
        prompt: "Rewrite with sich lassen.",
        input: "Das Gerät kann leicht reparieren werden.",
        answers: ["Das Gerät lässt sich leicht reparieren."],
        explanation: "lassen + sich + Infinitiv.",
      },
      {
        id: "g-b2-3-p2",
        type: "transform",
        prompt: "Rewrite with sein + zu + Infinitiv.",
        input: "Die Formulare müssen ausgefüllt werden.",
        answers: ["Die Formulare sind auszufüllen."],
        explanation: "Necessity.",
      },
      {
        id: "g-b2-3-p3",
        type: "multiple-choice",
        prompt: "Der Fehler ist leicht ___.",
        options: ["erklären", "erklärbar", "erklärt werden", "zu erklären sein"],
        answerIndex: 1,
        explanation: "-bar adjective.",
      },
    ],
    quiz: [
      {
        id: "g-b2-3-q1",
        type: "transform",
        prompt: "Rewrite with man.",
        input: "In Deutschland wird viel Bier getrunken.",
        answers: ["In Deutschland trinkt man viel Bier."],
        explanation: "man + active.",
      },
      {
        id: "g-b2-3-q2",
        type: "true-false",
        prompt: "sein + zu + Infinitiv can express necessity.",
        answer: true,
        explanation: "Die Miete ist monatlich zu zahlen.",
      },
    ],
    revision: [
      "man + Aktiv, sich lassen + Infinitiv, sein + zu + Infinitiv, -bar/-lich adjectives.",
      "All four replace a modal passive.",
      "Register: sein + zu = official, sich lassen = neutral/spoken.",
    ],
    cheatSheet: [
      { label: "man", value: "Man macht das so." },
      { label: "sich lassen", value: "Das lässt sich machen." },
      { label: "sein + zu", value: "Das ist zu machen." },
      { label: "-bar", value: "Das ist machbar." },
    ],
    related: ["passiv", "nominalisierung"],
  },
  {
    slug: "subjektive-modalverben",
    level: "B2",
    category: "Verbs",
    title: "Subjective use of modal verbs",
    titleDe: "Modalverben in subjektiver Bedeutung",
    minutes: 25,
    simple:
      "Modal verbs can express the speaker's certainty rather than ability or obligation: Er muss krank sein (I'm sure he's ill). Sie soll sehr reich sein (people say she is).",
    detailed: [
      "Objective meaning describes reality (Er muss arbeiten = obligation). Subjective meaning describes how sure the speaker is (Er muss zu Hause sein = I'm convinced). The structure is identical, so context and intonation decide.",
      "Scale of certainty: müssen (almost certain) > dürfte (probable, careful) > können/könnte (possible) > mag (concessive, may well) . For hearsay use sollen (people say) and for someone's claim use wollen (he claims).",
      "In the past, subjective modals combine with the perfect infinitive: Er muss den Zug verpasst haben. Sie soll im Ausland studiert haben.",
    ],
    tables: [
      {
        title: "Degrees of certainty",
        headers: ["Modal", "Certainty", "Example", "Paraphrase"],
        rows: [
          ["müssen", "≈ 95 %", "Er muss krank sein.", "Ich bin sicher, dass er krank ist."],
          ["dürfte", "≈ 75 %", "Das dürfte teuer sein.", "Wahrscheinlich ist es teuer."],
          ["können / könnte", "≈ 50 %", "Sie könnte im Büro sein.", "Möglicherweise ist sie im Büro."],
          ["mag", "concessive", "Das mag stimmen, aber …", "Es ist möglich, dass es stimmt."],
          ["kann nicht", "excluded", "Das kann nicht wahr sein.", "Es ist unmöglich."],
          ["sollen", "hearsay", "Er soll sehr streng sein.", "Man sagt, dass er streng ist."],
          ["wollen", "claim", "Er will nichts gewusst haben.", "Er behauptet, nichts gewusst zu haben."],
        ],
        highlightColumn: 1,
      },
    ],
    visuals: [
      {
        label: "Past form",
        pattern: "Modalverb + Partizip II + haben/sein",
        parts: ["Er", "muss", "den Zug verpasst", "haben."],
      },
    ],
    examples: [
      { de: "Das Paket dürfte morgen ankommen.", en: "The parcel should arrive tomorrow (probably)." },
      { de: "Die neue Kollegin soll aus Marokko kommen.", en: "The new colleague is said to be from Morocco." },
      { de: "Er will die E-Mail nie erhalten haben.", en: "He claims he never received the email." },
      { de: "Das kann nicht sein — ich habe alles überprüft.", en: "That can't be — I checked everything." },
    ],
    mistakes: [
      { wrong: "Er muss krank gewesen sein müssen.", right: "Er muss krank gewesen sein.", why: "Only one modal, plus the perfect infinitive." },
      { wrong: "Man sagt, er soll reich sein sollen.", right: "Er soll reich sein.", why: "sollen already means 'people say'." },
      { wrong: "Das dürfte teuer gewesen haben.", right: "Das dürfte teuer gewesen sein.", why: "sein takes sein in the perfect infinitive." },
    ],
    tips: [
      "In listening exams, sollen and wollen mark information the speaker does not vouch for.",
      "dürfte is the most elegant way to hedge in a discussion.",
      "Paraphrase practice (Er muss … = Ich bin sicher, dass …) is exactly what B2 tasks ask for.",
    ],
    practice: [
      {
        id: "g-b2-4-p1",
        type: "transform",
        prompt: "Express with a subjective modal.",
        input: "Ich bin sicher, dass sie zu Hause ist.",
        answers: ["Sie muss zu Hause sein."],
        explanation: "High certainty → müssen.",
      },
      {
        id: "g-b2-4-p2",
        type: "transform",
        prompt: "Express hearsay.",
        input: "Man sagt, dass das Restaurant sehr gut ist.",
        answers: ["Das Restaurant soll sehr gut sein."],
        explanation: "sollen = hearsay.",
      },
      {
        id: "g-b2-4-p3",
        type: "multiple-choice",
        prompt: "Er ___ den Bus verpasst haben — er ist noch nicht da.",
        options: ["will", "soll", "muss", "darf"],
        answerIndex: 2,
        explanation: "Strong inference → müssen.",
      },
    ],
    quiz: [
      {
        id: "g-b2-4-q1",
        type: "multiple-choice",
        prompt: "Der Zug ___ pünktlich sein, er hatte gestern auch keine Verspätung.",
        options: ["dürfte", "soll", "will", "kann nicht"],
        answerIndex: 0,
        explanation: "Probability → dürfte.",
      },
      {
        id: "g-b2-4-q2",
        type: "true-false",
        prompt: "wollen in subjective use reports someone's own claim.",
        answer: true,
        explanation: "Er will krank gewesen sein = he claims he was ill.",
      },
    ],
    revision: [
      "müssen > dürfte > können > mag; kann nicht = impossible.",
      "sollen = hearsay, wollen = the person's own claim.",
      "Past: Modalverb + Partizip II + haben/sein.",
    ],
    cheatSheet: [
      { label: "müssen", value: "I'm sure" },
      { label: "dürfte", value: "probably" },
      { label: "könnte", value: "possibly" },
      { label: "kann nicht", value: "impossible" },
      { label: "sollen", value: "people say" },
      { label: "wollen", value: "he claims" },
    ],
    related: ["konjunktiv-2", "futur-2"],
  },
  {
    slug: "nominalisierung",
    level: "B2",
    category: "Style",
    title: "Nominal vs. verbal style",
    titleDe: "Nominalstil und Verbalstil",
    minutes: 30,
    simple:
      "Formal German compresses clauses into noun phrases: Nach der Prüfung der Unterlagen … instead of Nachdem wir die Unterlagen geprüft haben, …",
    detailed: [
      "Nominalisation turns a verb into a noun (prüfen → die Prüfung, ankommen → die Ankunft, entscheiden → die Entscheidung) and replaces the conjunction with a preposition. Typical pairs: nachdem → nach, bevor → vor, weil → wegen/aufgrund, obwohl → trotz, wenn → bei/im Fall, damit → zu/zum Zweck, während → während.",
      "Nominal style is expected in reports, applications and academic texts; verbal style is clearer and preferred in speech. B2 exams test both directions, so practise transforming sentences each way.",
      "Common noun-forming suffixes: -ung (die Prüfung), -heit/-keit (die Möglichkeit), -tion (die Produktion), -nis (das Ergebnis), and the infinitive as a neuter noun (das Lernen).",
    ],
    tables: [
      {
        title: "Conjunction ↔ preposition",
        headers: ["Verbalstil", "Nominalstil"],
        rows: [
          ["Nachdem er angekommen war, …", "Nach seiner Ankunft …"],
          ["Bevor die Sitzung beginnt, …", "Vor Beginn der Sitzung …"],
          ["Weil das Wetter schlecht war, …", "Wegen des schlechten Wetters …"],
          ["Obwohl es Probleme gab, …", "Trotz der Probleme …"],
          ["Wenn Sie Fragen haben, …", "Bei Fragen …"],
          ["Damit die Kosten sinken, …", "Zur Senkung der Kosten …"],
          ["Während er studierte, …", "Während seines Studiums …"],
        ],
        highlightColumn: 1,
      },
      {
        title: "Verb → noun",
        headers: ["Verb", "Nomen", "Example"],
        rows: [
          ["prüfen", "die Prüfung", "nach der Prüfung der Dokumente"],
          ["ankommen", "die Ankunft", "bei der Ankunft am Flughafen"],
          ["entscheiden", "die Entscheidung", "vor der Entscheidung des Gerichts"],
          ["steigen", "der Anstieg", "wegen des Anstiegs der Preise"],
          ["einführen", "die Einführung", "seit der Einführung der Regel"],
          ["lernen", "das Lernen", "beim Lernen neuer Wörter"],
        ],
      },
    ],
    visuals: [
      {
        label: "Transformation",
        pattern: "Konjunktion + Satz → Präposition + Nominalphrase",
        parts: ["weil es regnete", "→", "wegen des Regens"],
      },
    ],
    examples: [
      { de: "Nach Abschluss der Ausbildung möchte ich in einem Krankenhaus arbeiten.", en: "After completing my training I'd like to work in a hospital." },
      { de: "Aufgrund der hohen Nachfrage wurden die Preise erhöht.", en: "Due to high demand, prices were increased." },
      { de: "Bei Rückfragen stehe ich Ihnen gern zur Verfügung.", en: "If you have any questions, I'll be happy to help." },
      { de: "Zur Verbesserung meiner Sprachkenntnisse besuche ich einen Abendkurs.", en: "To improve my language skills I attend an evening course." },
    ],
    mistakes: [
      { wrong: "Wegen es regnete, blieben wir zu Hause.", right: "Wegen des Regens blieben wir zu Hause.", why: "wegen needs a noun phrase in the genitive." },
      { wrong: "Nach ich angekommen bin, …", right: "Nach meiner Ankunft …", why: "nach is a preposition and cannot introduce a clause." },
      { wrong: "Trotz es war schwierig, …", right: "Trotz der Schwierigkeiten …", why: "Same rule for trotz." },
    ],
    tips: [
      "Use nominal style in the opening and closing lines of formal letters; keep the body readable.",
      "Learn the preposition–conjunction pairs as a table and practise both directions.",
      "In listening tasks, nominalised phrases often carry the key information.",
    ],
    practice: [
      {
        id: "g-b2-5-p1",
        type: "transform",
        prompt: "Nominalise.",
        input: "Nachdem ich die Prüfung bestanden habe, suche ich eine Stelle.",
        answers: ["Nach dem Bestehen der Prüfung suche ich eine Stelle."],
        explanation: "nachdem → nach + Nominalphrase.",
      },
      {
        id: "g-b2-5-p2",
        type: "transform",
        prompt: "Turn into verbal style.",
        input: "Wegen der Verspätung des Zuges kam ich zu spät.",
        answers: ["Weil der Zug Verspätung hatte, kam ich zu spät."],
        explanation: "wegen → weil.",
      },
      {
        id: "g-b2-5-p3",
        type: "multiple-choice",
        prompt: "___ Fragen wenden Sie sich bitte an das Sekretariat.",
        options: ["Wenn", "Bei", "Weil", "Trotz"],
        answerIndex: 1,
        explanation: "bei + Nomen = if/when.",
      },
    ],
    quiz: [
      {
        id: "g-b2-5-q1",
        type: "fill-blank",
        prompt: "Nominalise the verb.",
        sentence: "einführen → die ___ ; ankommen → die ___ ; entscheiden → die ___",
        answers: [["Einführung"], ["Ankunft"], ["Entscheidung"]],
        explanation: "Standard noun forms.",
      },
      {
        id: "g-b2-5-q2",
        type: "true-false",
        prompt: "Nominal style is preferred in everyday spoken German.",
        answer: false,
        explanation: "Speech prefers verbal style; nominal style belongs to formal writing.",
      },
    ],
    revision: [
      "nachdem→nach, bevor→vor, weil→wegen/aufgrund, obwohl→trotz, wenn→bei, damit→zu.",
      "Suffixes: -ung, -heit/-keit, -tion, -nis, infinitive as noun.",
      "Practise both directions for the exam.",
    ],
    cheatSheet: [
      { label: "weil", value: "wegen / aufgrund + Gen." },
      { label: "obwohl", value: "trotz + Gen." },
      { label: "nachdem", value: "nach + Dat." },
      { label: "bevor", value: "vor + Dat." },
      { label: "wenn", value: "bei + Dat." },
      { label: "damit", value: "zur / zum + Nomen" },
    ],
    related: ["genitiv", "partizipialattribute"],
  },
  {
    slug: "futur-2",
    level: "B2",
    category: "Tenses",
    title: "Futur I & II and expressing assumptions",
    titleDe: "Futur I und II, Vermutungen",
    minutes: 25,
    simple:
      "werden + Infinitiv talks about the future or an assumption; werden + Partizip II + haben/sein says something will have been finished.",
    detailed: [
      "Futur I (werden + Infinitiv) is used less for the future than English learners expect — a present tense with a time word is more common (Morgen fahre ich nach Bonn). Its main jobs are predictions, promises and assumptions: Das wird wohl richtig sein.",
      "Futur II (werden + Partizip II + haben/sein) describes something completed by a point in the future (Bis Freitag werde ich den Bericht fertiggestellt haben) or an assumption about the past (Er wird den Zug verpasst haben).",
      "Assumption markers combine with both: wohl, wahrscheinlich, vermutlich, sicher, bestimmt, vielleicht. Compare with the subjective modals: Er wird krank sein ≈ Er dürfte krank sein.",
    ],
    tables: [
      {
        title: "Forms and functions",
        headers: ["Tense", "Structure", "Function", "Example"],
        rows: [
          ["Präsens + Zeitangabe", "fahre morgen", "normal future", "Morgen fahre ich nach Köln."],
          ["Futur I", "werden + Infinitiv", "prediction / promise", "Ich werde dich anrufen."],
          ["Futur I + wohl", "werden + wohl + Inf.", "assumption (present)", "Sie wird wohl im Büro sein."],
          ["Futur II", "werden + Part. II + haben/sein", "completed in the future", "Bis Juni werde ich die Prüfung gemacht haben."],
          ["Futur II + wohl", "—", "assumption (past)", "Er wird wohl krank gewesen sein."],
        ],
        highlightColumn: 1,
      },
    ],
    visuals: [
      {
        label: "Futur II",
        pattern: "werden + Partizip II + haben/sein",
        parts: ["Bis 2027", "werde", "ich meine Ausbildung abgeschlossen", "haben."],
      },
    ],
    examples: [
      { de: "In zehn Jahren werden viele Berufe automatisiert sein.", en: "In ten years many jobs will be automated." },
      { de: "Ich werde mich morgen um den Termin kümmern.", en: "I'll take care of the appointment tomorrow." },
      { de: "Sie wird die E-Mail wohl noch nicht gelesen haben.", en: "She probably hasn't read the email yet." },
      { de: "Bis Ende des Jahres werden wir das Projekt abgeschlossen haben.", en: "By the end of the year we will have completed the project." },
    ],
    mistakes: [
      { wrong: "Ich werde morgen nach Berlin fahren werden.", right: "Ich werde morgen nach Berlin fahren.", why: "Only one werden." },
      { wrong: "Er wird den Zug verpasst gehabt.", right: "Er wird den Zug verpasst haben.", why: "Futur II = Partizip II + haben/sein in the infinitive." },
      { wrong: "Ich werde jeden Tag Deutsch lernen werde.", right: "Ich lerne jeden Tag Deutsch.", why: "Habitual actions use the present." },
    ],
    tips: [
      "Use Futur I for promises in emails: Ich werde Ihnen die Unterlagen zusenden.",
      "wohl is the standard marker of assumption; it does not mean 'well'.",
      "Futur II is rare in speech but appears in B2 reading and grammar tasks.",
    ],
    practice: [
      {
        id: "g-b2-6-p1",
        type: "transform",
        prompt: "Express the assumption with Futur I.",
        input: "Wahrscheinlich ist sie schon zu Hause.",
        answers: ["Sie wird wohl schon zu Hause sein."],
        explanation: "werden + wohl + Infinitiv.",
      },
      {
        id: "g-b2-6-p2",
        type: "transform",
        prompt: "Use Futur II.",
        input: "Bis Freitag schreibe ich den Bericht fertig.",
        answers: ["Bis Freitag werde ich den Bericht fertiggeschrieben haben."],
        explanation: "werden + Partizip II + haben.",
      },
      {
        id: "g-b2-6-p3",
        type: "multiple-choice",
        prompt: "Er ist nicht da. Er ___ wohl den Bus verpasst haben.",
        options: ["wird", "wurde", "würde", "ist"],
        answerIndex: 0,
        explanation: "Futur II for an assumption about the past.",
      },
    ],
    quiz: [
      {
        id: "g-b2-6-q1",
        type: "true-false",
        prompt: "German normally uses the present tense with a time expression to talk about the future.",
        answer: true,
        explanation: "Morgen habe ich einen Termin.",
      },
      {
        id: "g-b2-6-q2",
        type: "fill-blank",
        prompt: "Complete with Futur II.",
        sentence: "Bis nächstes Jahr ___ ich die B2-Prüfung ___ ___.",
        answers: [["werde"], ["bestanden"], ["haben"]],
        explanation: "werde … bestanden haben.",
      },
    ],
    revision: [
      "Futur I: werden + Infinitiv (prediction, promise, assumption).",
      "Futur II: werden + Partizip II + haben/sein.",
      "Assumption markers: wohl, wahrscheinlich, vermutlich.",
    ],
    cheatSheet: [
      { label: "Futur I", value: "wird kommen" },
      { label: "Futur II", value: "wird gekommen sein" },
      { label: "Assumption", value: "+ wohl / wahrscheinlich" },
      { label: "Everyday future", value: "Präsens + Zeitangabe" },
    ],
    related: ["subjektive-modalverben", "konjunktiv-2"],
  },
];
